% This file was generated by Isabelle (most likely Sledgehammer)

% Could-be-implicit typings (48)

tff(ty_n_t__fun_It__fun_It__Set__Oset_IT__n_J_Mt__HOL__Obool_J_Mt__fun_It__Set__Oset_IT__n_J_Mt__Set__Oset_IT__n_J_J_J, type,
    fun_fu420422081_set_n : $tType).

tff(ty_n_t__fun_It__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J_J, type,
    fun_fu50658420_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__n_J_Mt__fun_It__Set__Oset_IT__n_J_Mt__Set__Oset_IT__n_J_J_J, type,
    fun_se652460029_set_n : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J_J, type,
    fun_se1395821270_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__n_J_Mt__fun_It__Set__Oset_IT__n_J_Mt__HOL__Obool_J_J, type,
    fun_se317722439n_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J, type,
    fun_se1296151905a_bool : $tType).

tff(ty_n_t__fun_It__fun_IT__a_Mt__HOL__Obool_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_fun_a_bool_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J, type,
    fun_set_a_fun_a_bool : $tType).

tff(ty_n_t__fun_IT__e_Mt__fun_It__Set__Oset_IT__e_J_Mt__HOL__Obool_J_J, type,
    fun_e_fun_set_e_bool : $tType).

tff(ty_n_t__fun_IT__c_Mt__fun_It__Set__Oset_IT__c_J_Mt__HOL__Obool_J_J, type,
    fun_c_fun_set_c_bool : $tType).

tff(ty_n_t__fun_IT__b_Mt__fun_It__Set__Oset_IT__b_J_Mt__HOL__Obool_J_J, type,
    fun_b_fun_set_b_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J, type,
    fun_a_fun_set_a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__n_J_Mt__Set__Oset_IT__n_J_J, type,
    fun_set_n_set_n : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_set_a_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__n_J_Mt__HOL__Obool_J, type,
    fun_set_n_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__e_J_Mt__HOL__Obool_J, type,
    fun_set_e_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__c_J_Mt__HOL__Obool_J, type,
    fun_set_c_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__b_J_Mt__HOL__Obool_J, type,
    fun_set_b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    fun_set_a_bool : $tType).

tff(ty_n_t__fun_IT__b_Mt__fun_IT__a_Mt__HOL__Obool_J_J, type,
    fun_b_fun_a_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_IT__a_Mt__HOL__Obool_J_J, type,
    fun_a_fun_a_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_IT__a_MT__a_J_J, type,
    fun_a_fun_a_a : $tType).

tff(ty_n_t__fun_IT__e_Mt__HOL__Obool_J, type,
    fun_e_bool : $tType).

tff(ty_n_t__fun_IT__c_Mt__HOL__Obool_J, type,
    fun_c_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__HOL__Obool_J, type,
    fun_a_bool : $tType).

tff(ty_n_t__fun_IT__a__1_MT__a__2_J, type,
    fun_a_a : $tType).

tff(ty_n_t__Set__Oset_IT__a__1_J, type,
    set_a : $tType).

tff(ty_n_t__fun_IT__a_MT__b_J, type,
    fun_a_b : $tType).

tff(ty_n_t__fun_IT__a_MT__a_J, type,
    fun_a_a2 : $tType).

tff(ty_n_t__Set__Oset_IT__n_J, type,
    set_n : $tType).

tff(ty_n_t__Set__Oset_IT__e_J, type,
    set_e : $tType).

tff(ty_n_t__Set__Oset_IT__c_J, type,
    set_c : $tType).

tff(ty_n_t__Set__Oset_IT__b_J, type,
    set_b : $tType).

tff(ty_n_t__Set__Oset_IT__a_J, type,
    set_a2 : $tType).

tff(ty_n_t__HOL__Obool, type,
    bool : $tType).

tff(ty_n_T__a__2, type,
    a : $tType).

tff(ty_n_T__n, type,
    n : $tType).

tff(ty_n_T__e, type,
    e : $tType).

tff(ty_n_T__c, type,
    c : $tType).

tff(ty_n_T__b, type,
    b : $tType).

tff(ty_n_T__a, type,
    a2 : $tType).

tff(sy_cl_Topological__Spaces_Otopological__space, type,
    topolo503727757_space : !>[A : $tType]: $o).

tff(sy_cl_Boolean__Algebras_Oboolean__algebra, type,
    boolea436070733lgebra : !>[A : $tType]: $o).

tff(sy_cl_Real__Vector__Spaces_Oreal__vector, type,
    real_V1076094709vector : !>[A : $tType]: $o).

tff(sy_cl_Euclidean__Space_Oeuclidean__space, type,
    euclid925273238_space : !>[A : $tType]: $o).

tff(sy_cl_Lattices_Obounded__lattice__bot, type,
    bounded_lattice_bot : !>[A : $tType]: $o).

tff(sy_cl_Lattices_Obounded__lattice, type,
    bounded_lattice : !>[A : $tType]: $o).

tff(sy_cl_Orderings_Olinorder, type,
    linorder : !>[A : $tType]: $o).


% Explicit typings (60)

tff(sy_c_ATP_058Lamm__a, type,
    aTP_Lamm_a : fun_set_a_fun_a_bool).

tff(sy_c_Affine_Oaffine_001T__a, type,
    affine_a : fun_set_a_bool).

tff(sy_c_Affine_Oaffine_001T__n, type,
    affine_n : fun_set_n_bool).

tff(sy_c_Affine_Oaffine__dependent_001T__a, type,
    affine_dependent_a : fun_set_a_bool).

tff(sy_c_Affine_Oaffine__dependent_001T__n, type,
    affine_dependent_n : fun_set_n_bool).

tff(sy_c_Convex_Oconvex_001T__a, type,
    convex_a : fun_set_a_bool).

tff(sy_c_Convex_Oconvex_001T__n, type,
    convex_n : fun_set_n_bool).

tff(sy_c_Convex__Euclidean__Space_Orel__interior_001T__a, type,
    convex1609340813rior_a : fun_set_a_set_a).

tff(sy_c_Convex__Euclidean__Space_Orel__interior_001T__n, type,
    convex1609340826rior_n : fun_set_n_set_n).

tff(sy_c_Finite__Set_Ofinite_001T__a, type,
    finite_finite_a : fun_set_a_bool).

tff(sy_c_Finite__Set_Ofinite_001T__b, type,
    finite_finite_b : fun_set_b_bool).

tff(sy_c_Finite__Set_Ofinite_001T__n, type,
    finite_finite_n : fun_set_n_bool).

tff(sy_c_Hull_Ohull_001T__a, type,
    hull_a : fun_fu50658420_set_a).

tff(sy_c_Hull_Ohull_001T__n, type,
    hull_n : fun_fu420422081_set_n).

tff(sy_c_Lattices_Oinf__class_Oinf_001T__a, type,
    inf_inf_a : fun_a_fun_a_a).

tff(sy_c_Lattices_Oinf__class_Oinf_001t__Set__Oset_IT__a_J, type,
    inf_inf_set_a : fun_se1395821270_set_a).

tff(sy_c_Lattices_Oinf__class_Oinf_001t__Set__Oset_IT__n_J, type,
    inf_inf_set_n : fun_se652460029_set_n).

tff(sy_c_Orderings_Obot__class_Obot_001T__a, type,
    bot_bot_a : a2).

tff(sy_c_Orderings_Obot__class_Obot_001t__Set__Oset_IT__a_J, type,
    bot_bot_set_a : set_a2).

tff(sy_c_Orderings_Obot__class_Obot_001t__Set__Oset_IT__c_J, type,
    bot_bot_set_c : set_c).

tff(sy_c_Orderings_Obot__class_Obot_001t__Set__Oset_IT__e_J, type,
    bot_bot_set_e : set_e).

tff(sy_c_Orderings_Obot__class_Obot_001t__Set__Oset_IT__n_J, type,
    bot_bot_set_n : set_n).

tff(sy_c_Orderings_Oord__class_Oless__eq_001T__a, type,
    ord_less_eq_a : fun_a_fun_a_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001t__Set__Oset_IT__a_J, type,
    ord_less_eq_set_a : fun_se1296151905a_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001t__Set__Oset_IT__n_J, type,
    ord_less_eq_set_n : fun_se317722439n_bool).

tff(sy_c_Set_OCollect_001T__a, type,
    collect_a : fun_fun_a_bool_set_a).

tff(sy_c_aa_001T__a_001T__a, type,
    aa_a_a : (fun_a_a2 * a2) > a2).

tff(sy_c_aa_001T__a_001T__b, type,
    aa_a_b : (fun_a_b * a2) > b).

tff(sy_c_aa_001T__a_001t__HOL__Obool, type,
    aa_a_bool : (fun_a_bool * a2) > bool).

tff(sy_c_aa_001T__a_001t__fun_IT__a_MT__a_J, type,
    aa_a_fun_a_a : (fun_a_fun_a_a * a2) > fun_a_a2).

tff(sy_c_aa_001T__a_001t__fun_IT__a_Mt__HOL__Obool_J, type,
    aa_a_fun_a_bool : (fun_a_fun_a_bool * a2) > fun_a_bool).

tff(sy_c_aa_001T__a_001t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    aa_a_fun_set_a_bool : (fun_a_fun_set_a_bool * a2) > fun_set_a_bool).

tff(sy_c_aa_001T__b_001t__fun_IT__a_Mt__HOL__Obool_J, type,
    aa_b_fun_a_bool : (fun_b_fun_a_bool * b) > fun_a_bool).

tff(sy_c_aa_001T__b_001t__fun_It__Set__Oset_IT__b_J_Mt__HOL__Obool_J, type,
    aa_b_fun_set_b_bool : (fun_b_fun_set_b_bool * b) > fun_set_b_bool).

tff(sy_c_aa_001T__c_001t__HOL__Obool, type,
    aa_c_bool : (fun_c_bool * c) > bool).

tff(sy_c_aa_001T__c_001t__fun_It__Set__Oset_IT__c_J_Mt__HOL__Obool_J, type,
    aa_c_fun_set_c_bool : (fun_c_fun_set_c_bool * c) > fun_set_c_bool).

tff(sy_c_aa_001T__e_001t__HOL__Obool, type,
    aa_e_bool : (fun_e_bool * e) > bool).

tff(sy_c_aa_001T__e_001t__fun_It__Set__Oset_IT__e_J_Mt__HOL__Obool_J, type,
    aa_e_fun_set_e_bool : (fun_e_fun_set_e_bool * e) > fun_set_e_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__HOL__Obool, type,
    aa_set_a_bool : (fun_set_a_bool * set_a2) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__Set__Oset_IT__a_J, type,
    aa_set_a_set_a : (fun_set_a_set_a * set_a2) > set_a2).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_IT__a_Mt__HOL__Obool_J, type,
    aa_set_a_fun_a_bool : (fun_set_a_fun_a_bool * set_a2) > fun_a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    aa_set1122887114a_bool : (fun_se1296151905a_bool * set_a2) > fun_set_a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J, type,
    aa_set363163287_set_a : (fun_se1395821270_set_a * set_a2) > fun_set_a_set_a).

tff(sy_c_aa_001t__Set__Oset_IT__b_J_001t__HOL__Obool, type,
    aa_set_b_bool : (fun_set_b_bool * set_b) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__c_J_001t__HOL__Obool, type,
    aa_set_c_bool : (fun_set_c_bool * set_c) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__e_J_001t__HOL__Obool, type,
    aa_set_e_bool : (fun_set_e_bool * set_e) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__n_J_001t__HOL__Obool, type,
    aa_set_n_bool : (fun_set_n_bool * set_n) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__n_J_001t__Set__Oset_IT__n_J, type,
    aa_set_n_set_n : (fun_set_n_set_n * set_n) > set_n).

tff(sy_c_aa_001t__Set__Oset_IT__n_J_001t__fun_It__Set__Oset_IT__n_J_Mt__HOL__Obool_J, type,
    aa_set634251568n_bool : (fun_se317722439n_bool * set_n) > fun_set_n_bool).

tff(sy_c_aa_001t__Set__Oset_IT__n_J_001t__fun_It__Set__Oset_IT__n_J_Mt__Set__Oset_IT__n_J_J, type,
    aa_set1541951678_set_n : (fun_se652460029_set_n * set_n) > fun_set_n_set_n).

tff(sy_c_aa_001t__fun_IT__a_Mt__HOL__Obool_J_001t__Set__Oset_IT__a_J, type,
    aa_fun_a_bool_set_a : (fun_fun_a_bool_set_a * fun_a_bool) > set_a2).

tff(sy_c_aa_001t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_001t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J, type,
    aa_fun727137317_set_a : (fun_fu50658420_set_a * fun_set_a_bool) > fun_set_a_set_a).

tff(sy_c_aa_001t__fun_It__Set__Oset_IT__n_J_Mt__HOL__Obool_J_001t__fun_It__Set__Oset_IT__n_J_Mt__Set__Oset_IT__n_J_J, type,
    aa_fun871566962_set_n : (fun_fu420422081_set_n * fun_set_n_bool) > fun_set_n_set_n).

tff(sy_c_fFalse, type,
    fFalse : bool).

tff(sy_c_fTrue, type,
    fTrue : bool).

tff(sy_c_member_001T__a, type,
    member_a : fun_a_fun_set_a_bool).

tff(sy_c_member_001T__b, type,
    member_b : fun_b_fun_set_b_bool).

tff(sy_c_member_001T__c, type,
    member_c : fun_c_fun_set_c_bool).

tff(sy_c_member_001T__e, type,
    member_e : fun_e_fun_set_e_bool).

tff(sy_c_pp, type,
    pp : bool > $o).


% Relevant facts (65)

tff(fact_0_rel__interior__affine__hull, axiom,
    ((![N : $i]: (euclid925273238_space(n) => (![S : set_n]: (aa_set_n_set_n(convex1609340826rior_n, aa_set_n_set_n(aa_fun871566962_set_n(hull_n, affine_n), S)) = aa_set_n_set_n(aa_fun871566962_set_n(hull_n, affine_n), S))))))). % rel_interior_affine_hull

tff(fact_1_affine__hull__convex__hull, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => (![S : set_a2]: (aa_set_a_set_a(aa_fun727137317_set_a(hull_a, affine_a), aa_set_a_set_a(aa_fun727137317_set_a(hull_a, convex_a), S)) = aa_set_a_set_a(aa_fun727137317_set_a(hull_a, affine_a), S))))))). % affine_hull_convex_hull

tff(fact_2_affine__hull__empty, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => (aa_set_a_set_a(aa_fun727137317_set_a(hull_a, affine_a), bot_bot_set_a) = bot_bot_set_a))))). % affine_hull_empty

tff(fact_3_affine__hull__eq__empty, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => (![S : set_a2]: ((aa_set_a_set_a(aa_fun727137317_set_a(hull_a, affine_a), S) = bot_bot_set_a) <=> (S = bot_bot_set_a))))))). % affine_hull_eq_empty

tff(fact_4_empty__eq__affine__hull, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => (![S : set_a2]: ((bot_bot_set_a = aa_set_a_set_a(aa_fun727137317_set_a(hull_a, affine_a), S)) <=> (S = bot_bot_set_a))))))). % empty_eq_affine_hull

tff(fact_5_convex__hull__empty, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => (aa_set_a_set_a(aa_fun727137317_set_a(hull_a, convex_a), bot_bot_set_a) = bot_bot_set_a))))). % convex_hull_empty

tff(fact_6_convex__hull__eq__empty, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => (![S : set_a2]: ((aa_set_a_set_a(aa_fun727137317_set_a(hull_a, convex_a), S) = bot_bot_set_a) <=> (S = bot_bot_set_a))))))). % convex_hull_eq_empty

tff(fact_7_affine__independent__convex__affine__hull, axiom,
    ((![A : $i]: (euclid925273238_space(a2) => (![S : set_a2, T : set_a2]: ((~ (pp(aa_set_a_bool(affine_dependent_a, S)))) => (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, T), S)) => (aa_set_a_set_a(aa_fun727137317_set_a(hull_a, convex_a), T) = aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, aa_set_a_set_a(aa_fun727137317_set_a(hull_a, affine_a), T)), aa_set_a_set_a(aa_fun727137317_set_a(hull_a, convex_a), S)))))))))). % affine_independent_convex_affine_hull

tff(fact_8_disjoint__affine__hull, axiom,
    ((![N : $i]: (euclid925273238_space(n) => (![S : set_n, T : set_n, U : set_n]: ((~ (pp(aa_set_n_bool(affine_dependent_n, S)))) => (pp(aa_set_n_bool(aa_set634251568n_bool(ord_less_eq_set_n, T), S)) => (pp(aa_set_n_bool(aa_set634251568n_bool(ord_less_eq_set_n, U), S)) => ((aa_set_n_set_n(aa_set1541951678_set_n(inf_inf_set_n, T), U) = bot_bot_set_n) => (aa_set_n_set_n(aa_set1541951678_set_n(inf_inf_set_n, aa_set_n_set_n(aa_fun871566962_set_n(hull_n, affine_n), T)), aa_set_n_set_n(aa_fun871566962_set_n(hull_n, affine_n), U)) = bot_bot_set_n)))))))))). % disjoint_affine_hull

tff(fact_9_Radon, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => (![C : set_a2]: (pp(aa_set_a_bool(affine_dependent_a, C)) => (~ ((![M : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, M), C)) => (![P : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, P), C)) => ((aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, M), P) = bot_bot_set_a) => (aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, aa_set_a_set_a(aa_fun727137317_set_a(hull_a, convex_a), M)), aa_set_a_set_a(aa_fun727137317_set_a(hull_a, convex_a), P)) = bot_bot_set_a)))))))))))))). % Radon

tff(fact_10_affine__hull__eq, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => (![S2 : set_a2]: ((aa_set_a_set_a(aa_fun727137317_set_a(hull_a, affine_a), S2) = S2) <=> pp(aa_set_a_bool(affine_a, S2)))))))). % affine_hull_eq

tff(fact_11_extend__to__affine__basis__nonempty, axiom,
    ((![N : $i]: (real_V1076094709vector(n) => (![S : set_n, V : set_n]: ((~ (pp(aa_set_n_bool(affine_dependent_n, S)))) => (pp(aa_set_n_bool(aa_set634251568n_bool(ord_less_eq_set_n, S), V)) => ((S != bot_bot_set_n) => (?[T2 : set_n]: ((~ (pp(aa_set_n_bool(affine_dependent_n, T2)))) & (pp(aa_set_n_bool(aa_set634251568n_bool(ord_less_eq_set_n, S), T2)) & (pp(aa_set_n_bool(aa_set634251568n_bool(ord_less_eq_set_n, T2), V)) & (aa_set_n_set_n(aa_fun871566962_set_n(hull_n, affine_n), T2) = aa_set_n_set_n(aa_fun871566962_set_n(hull_n, affine_n), V)))))))))))))). % extend_to_affine_basis_nonempty

tff(fact_12_convex__empty, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => pp(aa_set_a_bool(convex_a, bot_bot_set_a)))))). % convex_empty

tff(fact_13_affine__empty, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => pp(aa_set_a_bool(affine_a, bot_bot_set_a)))))). % affine_empty

tff(fact_14_rel__interior__empty, axiom,
    ((![A : $i]: ((real_V1076094709vector(a2) & topolo503727757_space(a2)) => (aa_set_a_set_a(convex1609340813rior_a, bot_bot_set_a) = bot_bot_set_a))))). % rel_interior_empty

tff(fact_15_affine__Int, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => (![S : set_a2, T : set_a2]: (pp(aa_set_a_bool(affine_a, S)) => (pp(aa_set_a_bool(affine_a, T)) => pp(aa_set_a_bool(affine_a, aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, S), T)))))))))). % affine_Int

tff(fact_16_convex__convex__hull, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => (![S2 : set_a2]: pp(aa_set_a_bool(convex_a, aa_set_a_set_a(aa_fun727137317_set_a(hull_a, convex_a), S2)))))))). % convex_convex_hull

tff(fact_17_finite__indexed__bound, axiom,
    ((![B : $i, A : $i]: (linorder(a2) => (![A2 : set_b, P2 : fun_b_fun_a_bool]: (pp(aa_set_b_bool(finite_finite_b, A2)) => ((![X : b]: (pp(aa_set_b_bool(aa_b_fun_set_b_bool(member_b, X), A2)) => (?[X_1 : a2]: pp(aa_a_bool(aa_b_fun_a_bool(P2, X), X_1))))) => (?[M2 : a2]: (![X2 : b]: (pp(aa_set_b_bool(aa_b_fun_set_b_bool(member_b, X2), A2)) => (?[K : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, K), M2)) & pp(aa_a_bool(aa_b_fun_a_bool(P2, X2), K)))))))))))))). % finite_indexed_bound

tff(fact_18_convex__Int, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => (![S2 : set_a2, T3 : set_a2]: (pp(aa_set_a_bool(convex_a, S2)) => (pp(aa_set_a_bool(convex_a, T3)) => pp(aa_set_a_bool(convex_a, aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, S2), T3)))))))))). % convex_Int

tff(fact_19_rel__interior__subset, axiom,
    ((![A : $i]: ((real_V1076094709vector(a2) & topolo503727757_space(a2)) => (![S : set_a2]: pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, aa_set_a_set_a(convex1609340813rior_a, S)), S))))))). % rel_interior_subset

tff(fact_20_convex__hull__eq, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => (![S2 : set_a2]: ((aa_set_a_set_a(aa_fun727137317_set_a(hull_a, convex_a), S2) = S2) <=> pp(aa_set_a_bool(convex_a, S2)))))))). % convex_hull_eq

tff(fact_21_affine__imp__convex, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => (![S2 : set_a2]: (pp(aa_set_a_bool(affine_a, S2)) => pp(aa_set_a_bool(convex_a, S2)))))))). % affine_imp_convex

tff(fact_22_affine__affine__hull, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => (![S : set_a2]: pp(aa_set_a_bool(affine_a, aa_set_a_set_a(aa_fun727137317_set_a(hull_a, affine_a), S)))))))). % affine_affine_hull

tff(fact_23_rel__interior__rel__interior, axiom,
    ((![N : $i]: (euclid925273238_space(n) => (![S : set_n]: (pp(aa_set_n_bool(convex_n, S)) => (aa_set_n_set_n(convex1609340826rior_n, aa_set_n_set_n(convex1609340826rior_n, S)) = aa_set_n_set_n(convex1609340826rior_n, S)))))))). % rel_interior_rel_interior

tff(fact_24_convex__rel__interior, axiom,
    ((![N : $i]: (euclid925273238_space(n) => (![S : set_n]: (pp(aa_set_n_bool(convex_n, S)) => pp(aa_set_n_bool(convex_n, aa_set_n_set_n(convex1609340826rior_n, S))))))))). % convex_rel_interior

tff(fact_25_affine__independent__0, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => (~ (pp(aa_set_a_bool(affine_dependent_a, bot_bot_set_a)))))))). % affine_independent_0

tff(fact_26_affine__independent__subset, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => (![T : set_a2, S : set_a2]: ((~ (pp(aa_set_a_bool(affine_dependent_a, T)))) => (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, S), T)) => (~ (pp(aa_set_a_bool(affine_dependent_a, S))))))))))). % affine_independent_subset

tff(fact_27_affine__dependent__subset, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => (![S : set_a2, T : set_a2]: (pp(aa_set_a_bool(affine_dependent_a, S)) => (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, S), T)) => pp(aa_set_a_bool(affine_dependent_a, T))))))))). % affine_dependent_subset

tff(fact_28_aff__independent__finite, axiom,
    ((![N : $i]: (euclid925273238_space(n) => (![B2 : set_n]: ((~ (pp(aa_set_n_bool(affine_dependent_n, B2)))) => pp(aa_set_n_bool(finite_finite_n, B2)))))))). % aff_independent_finite

tff(fact_29_rel__interior__affine, axiom,
    ((![N : $i]: (euclid925273238_space(n) => (![S : set_n]: (pp(aa_set_n_bool(affine_n, S)) => (aa_set_n_set_n(convex1609340826rior_n, S) = S))))))). % rel_interior_affine

tff(fact_30_convex__hull__subset, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => (![S2 : set_a2, T3 : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, S2), aa_set_a_set_a(aa_fun727137317_set_a(hull_a, convex_a), T3))) => pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, aa_set_a_set_a(aa_fun727137317_set_a(hull_a, convex_a), S2)), aa_set_a_set_a(aa_fun727137317_set_a(hull_a, convex_a), T3))))))))). % convex_hull_subset

tff(fact_31_rel__interior__eq__empty, axiom,
    ((![N : $i]: (euclid925273238_space(n) => (![S : set_n]: (pp(aa_set_n_bool(convex_n, S)) => ((aa_set_n_set_n(convex1609340826rior_n, S) = bot_bot_set_n) <=> (S = bot_bot_set_n)))))))). % rel_interior_eq_empty

tff(fact_32_convex__affine__hull, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => (![S : set_a2]: pp(aa_set_a_bool(convex_a, aa_set_a_set_a(aa_fun727137317_set_a(hull_a, affine_a), S)))))))). % convex_affine_hull

tff(fact_33_convex__rel__interior__inter__two, axiom,
    ((![N : $i]: (euclid925273238_space(n) => (![S : set_n, T : set_n]: (pp(aa_set_n_bool(convex_n, S)) => (pp(aa_set_n_bool(convex_n, T)) => ((aa_set_n_set_n(aa_set1541951678_set_n(inf_inf_set_n, aa_set_n_set_n(convex1609340826rior_n, S)), aa_set_n_set_n(convex1609340826rior_n, T)) != bot_bot_set_n) => (aa_set_n_set_n(convex1609340826rior_n, aa_set_n_set_n(aa_set1541951678_set_n(inf_inf_set_n, S), T)) = aa_set_n_set_n(aa_set1541951678_set_n(inf_inf_set_n, aa_set_n_set_n(convex1609340826rior_n, S)), aa_set_n_set_n(convex1609340826rior_n, T))))))))))). % convex_rel_interior_inter_two

tff(fact_34_convex__hull__subset__affine__hull, axiom,
    ((![A : $i]: (real_V1076094709vector(a2) => (![S2 : set_a2]: pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, aa_set_a_set_a(aa_fun727137317_set_a(hull_a, convex_a), S2)), aa_set_a_set_a(aa_fun727137317_set_a(hull_a, affine_a), S2)))))))). % convex_hull_subset_affine_hull

tff(fact_35_subset__rel__interior, axiom,
    ((![N : $i]: (euclid925273238_space(n) => (![S : set_n, T : set_n]: (pp(aa_set_n_bool(aa_set634251568n_bool(ord_less_eq_set_n, S), T)) => ((aa_set_n_set_n(aa_fun871566962_set_n(hull_n, affine_n), S) = aa_set_n_set_n(aa_fun871566962_set_n(hull_n, affine_n), T)) => pp(aa_set_n_bool(aa_set634251568n_bool(ord_less_eq_set_n, aa_set_n_set_n(convex1609340826rior_n, S)), aa_set_n_set_n(convex1609340826rior_n, T)))))))))). % subset_rel_interior

tff(fact_36_rel__interior__mono, axiom,
    ((![A : $i]: ((real_V1076094709vector(a2) & topolo503727757_space(a2)) => (![S : set_a2, T : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, S), T)) => ((aa_set_a_set_a(aa_fun727137317_set_a(hull_a, affine_a), S) = aa_set_a_set_a(aa_fun727137317_set_a(hull_a, affine_a), T)) => pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, aa_set_a_set_a(convex1609340813rior_a, S)), aa_set_a_set_a(convex1609340813rior_a, T)))))))))). % rel_interior_mono

tff(fact_37_rel__interior__same__affine__hull, axiom,
    ((![N : $i]: (euclid925273238_space(n) => (![S : set_n]: (pp(aa_set_n_bool(convex_n, S)) => (aa_set_n_set_n(aa_fun871566962_set_n(hull_n, affine_n), aa_set_n_set_n(convex1609340826rior_n, S)) = aa_set_n_set_n(aa_fun871566962_set_n(hull_n, affine_n), S)))))))). % rel_interior_same_affine_hull

tff(fact_38_extend__to__affine__basis, axiom,
    ((![N : $i]: (real_V1076094709vector(n) => (![S : set_n, V : set_n]: ((~ (pp(aa_set_n_bool(affine_dependent_n, S)))) => (pp(aa_set_n_bool(aa_set634251568n_bool(ord_less_eq_set_n, S), V)) => (~ ((![T2 : set_n]: ((~ (pp(aa_set_n_bool(affine_dependent_n, T2)))) => (pp(aa_set_n_bool(aa_set634251568n_bool(ord_less_eq_set_n, S), T2)) => (pp(aa_set_n_bool(aa_set634251568n_bool(ord_less_eq_set_n, T2), V)) => (aa_set_n_set_n(aa_fun871566962_set_n(hull_n, affine_n), T2) != aa_set_n_set_n(aa_fun871566962_set_n(hull_n, affine_n), V))))))))))))))). % extend_to_affine_basis

tff(fact_39_affine__basis__exists, axiom,
    ((![N : $i]: (real_V1076094709vector(n) => (![V : set_n]: (?[B3 : set_n]: (pp(aa_set_n_bool(aa_set634251568n_bool(ord_less_eq_set_n, B3), V)) & ((~ (pp(aa_set_n_bool(affine_dependent_n, B3)))) & (aa_set_n_set_n(aa_fun871566962_set_n(hull_n, affine_n), V) = aa_set_n_set_n(aa_fun871566962_set_n(hull_n, affine_n), B3)))))))))). % affine_basis_exists

tff(fact_40_convex__affine__rel__interior__Int, axiom,
    ((![N : $i]: (euclid925273238_space(n) => (![S : set_n, T : set_n]: (pp(aa_set_n_bool(convex_n, S)) => (pp(aa_set_n_bool(affine_n, T)) => ((aa_set_n_set_n(aa_set1541951678_set_n(inf_inf_set_n, aa_set_n_set_n(convex1609340826rior_n, S)), T) != bot_bot_set_n) => (aa_set_n_set_n(convex1609340826rior_n, aa_set_n_set_n(aa_set1541951678_set_n(inf_inf_set_n, S), T)) = aa_set_n_set_n(aa_set1541951678_set_n(inf_inf_set_n, aa_set_n_set_n(convex1609340826rior_n, S)), T)))))))))). % convex_affine_rel_interior_Int

tff(fact_41_hull__subset, axiom,
    ((![A : $i, S2 : set_a2, S : fun_set_a_bool]: pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, S2), aa_set_a_set_a(aa_fun727137317_set_a(hull_a, S), S2)))))). % hull_subset

tff(fact_42_finite__Int, axiom,
    ((![A : $i, F : set_a2, G : set_a2]: ((pp(aa_set_a_bool(finite_finite_a, F)) | pp(aa_set_a_bool(finite_finite_a, G))) => pp(aa_set_a_bool(finite_finite_a, aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, F), G))))))). % finite_Int

tff(fact_43_boolean__algebra_Oconj__zero__right, axiom,
    ((![A : $i]: (boolea436070733lgebra(a2) => (![X3 : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, X3), bot_bot_a) = bot_bot_a)))))). % boolean_algebra.conj_zero_right

tff(fact_44_boolean__algebra_Oconj__zero__left, axiom,
    ((![A : $i]: (boolea436070733lgebra(a2) => (![X3 : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, bot_bot_a), X3) = bot_bot_a)))))). % boolean_algebra.conj_zero_left

tff(fact_45_mem__Collect__eq, axiom,
    ((![A : $i, A3 : a2, P2 : fun_a_bool]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, A3), aa_fun_a_bool_set_a(collect_a, P2))) <=> pp(aa_a_bool(P2, A3)))))). % mem_Collect_eq

tff(fact_46_Collect__mem__eq, axiom,
    ((![A : $i, A2 : set_a2]: (aa_fun_a_bool_set_a(collect_a, aa_set_a_fun_a_bool(aTP_Lamm_a, A2)) = A2)))). % Collect_mem_eq

tff(fact_47_Collect__cong, axiom,
    ((![A : $i, P2 : fun_a_bool, Q : fun_a_bool]: ((![X : a2]: (pp(aa_a_bool(P2, X)) <=> pp(aa_a_bool(Q, X)))) => (aa_fun_a_bool_set_a(collect_a, P2) = aa_fun_a_bool_set_a(collect_a, Q)))))). % Collect_cong

tff(fact_48_ext, axiom,
    ((![B : $i, A : $i, F2 : fun_a_b, G2 : fun_a_b]: ((![X : a2]: (aa_a_b(F2, X) = aa_a_b(G2, X))) => (F2 = G2))))). % ext

tff(fact_49_mem__simps_I7_J, axiom,
    ((![A : $i, A3 : a2, P2 : fun_a_bool]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, A3), aa_fun_a_bool_set_a(collect_a, P2))) <=> pp(aa_a_bool(P2, A3)))))). % mem_simps(7)

tff(fact_50_array__rules_I1_J, axiom,
    ((![B : $i, A : $i, F2 : fun_a_b, G2 : fun_a_b]: ((![X : a2]: (aa_a_b(F2, X) = aa_a_b(G2, X))) => (F2 = G2))))). % array_rules(1)

tff(fact_51_inf__bot__right, axiom,
    ((![A : $i]: (bounded_lattice_bot(a2) => (![X3 : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, X3), bot_bot_a) = bot_bot_a)))))). % inf_bot_right

tff(fact_52_inf__bot__left, axiom,
    ((![A : $i]: (bounded_lattice_bot(a2) => (![X3 : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, bot_bot_a), X3) = bot_bot_a)))))). % inf_bot_left

tff(fact_53_empty__subsetI, axiom,
    ((![A : $i, A2 : set_a2]: pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, bot_bot_set_a), A2))))). % empty_subsetI

tff(fact_54_subset__empty, axiom,
    ((![A : $i, A2 : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), bot_bot_set_a)) <=> (A2 = bot_bot_set_a))))). % subset_empty

tff(fact_55_bex__simps_I3_J, axiom,
    ((![C2 : $i, P2 : fun_c_bool]: (~ ((?[X2 : c]: (pp(aa_set_c_bool(aa_c_fun_set_c_bool(member_c, X2), bot_bot_set_c)) & pp(aa_c_bool(P2, X2))))))))). % bex_simps(3)

tff(fact_56_ball__simps_I5_J, axiom,
    ((![E : $i, P2 : fun_e_bool, X2 : e]: (pp(aa_set_e_bool(aa_e_fun_set_e_bool(member_e, X2), bot_bot_set_e)) => pp(aa_e_bool(P2, X2)))))). % ball_simps(5)

tff(fact_57_empty__iff, axiom,
    ((![A : $i, C : a2]: (~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), bot_bot_set_a))))))). % empty_iff

tff(fact_58_all__not__in__conv, axiom,
    ((![A : $i, A2 : set_a2]: ((![X4 : a2]: (~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X4), A2))))) <=> (A2 = bot_bot_set_a))))). % all_not_in_conv

tff(fact_59_Collect__empty__eq, axiom,
    ((![A : $i, P2 : fun_a_bool]: ((aa_fun_a_bool_set_a(collect_a, P2) = bot_bot_set_a) <=> (![X4 : a2]: (~ (pp(aa_a_bool(P2, X4))))))))). % Collect_empty_eq

tff(fact_60_empty__Collect__eq, axiom,
    ((![A : $i, P2 : fun_a_bool]: ((bot_bot_set_a = aa_fun_a_bool_set_a(collect_a, P2)) <=> (![X4 : a2]: (~ (pp(aa_a_bool(P2, X4))))))))). % empty_Collect_eq

tff(fact_61_subsetI, axiom,
    ((![A : $i, A2 : set_a2, B2 : set_a2]: ((![X : a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X), A2)) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X), B2)))) => pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B2)))))). % subsetI

tff(fact_62_equalityI, axiom,
    ((![A : $i, A2 : set_a2, B2 : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B2)) => (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, B2), A2)) => (A2 = B2)))))). % equalityI

tff(fact_63_subset__antisym, axiom,
    ((![A : $i, A2 : set_a2, B2 : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B2)) => (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, B2), A2)) => (A2 = B2)))))). % subset_antisym

tff(fact_64_ATP_Olambda__1, axiom,
    ((![A : $i, Uu : set_a2, Uua : a2]: (pp(aa_a_bool(aa_set_a_fun_a_bool(aTP_Lamm_a, Uu), Uua)) <=> pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, Uua), Uu)))))). % ATP.lambda_1


% Type constructors (12)

tff(tcon_HOL_Obool___Lattices_Obounded__lattice, axiom,
    (bounded_lattice(bool))).

tff(tcon_Set_Oset___Lattices_Obounded__lattice_1, axiom,
    ((![A4 : $i]: bounded_lattice(set_a)))).

tff(tcon_fun___Lattices_Obounded__lattice_2, axiom,
    ((![A4 : $i, A5 : $i]: (bounded_lattice(a) => bounded_lattice(fun_a_a))))).

tff(tcon_fun___Topological__Spaces_Otopological__space, axiom,
    ((![A4 : $i, A5 : $i]: (topolo503727757_space(a) => topolo503727757_space(fun_a_a))))).

tff(tcon_fun___Boolean__Algebras_Oboolean__algebra, axiom,
    ((![A4 : $i, A5 : $i]: (boolea436070733lgebra(a) => boolea436070733lgebra(fun_a_a))))).

tff(tcon_fun___Lattices_Obounded__lattice__bot, axiom,
    ((![A4 : $i, A5 : $i]: (bounded_lattice(a) => bounded_lattice_bot(fun_a_a))))).

tff(tcon_Set_Oset___Boolean__Algebras_Oboolean__algebra_3, axiom,
    ((![A4 : $i]: boolea436070733lgebra(set_a)))).

tff(tcon_Set_Oset___Lattices_Obounded__lattice__bot_4, axiom,
    ((![A4 : $i]: bounded_lattice_bot(set_a)))).

tff(tcon_HOL_Obool___Topological__Spaces_Otopological__space_5, axiom,
    (topolo503727757_space(bool))).

tff(tcon_HOL_Obool___Boolean__Algebras_Oboolean__algebra_6, axiom,
    (boolea436070733lgebra(bool))).

tff(tcon_HOL_Obool___Lattices_Obounded__lattice__bot_7, axiom,
    (bounded_lattice_bot(bool))).

tff(tcon_HOL_Obool___Orderings_Olinorder, axiom,
    (linorder(bool))).


% Helper facts (2)

tff(help_pp_2_1_U, axiom,
    (pp(fTrue))).

tff(help_pp_1_1_U, axiom,
    ((~ (pp(fFalse))))).


% Conjectures (1)

tff(conj_0, conjecture,
    ((![A : $i]: (euclid925273238_space(a2) => (![V : set_a2, W : set_a2]: (pp(aa_set_a_bool(finite_finite_a, V)) => ((~ (pp(aa_set_a_bool(affine_dependent_a, V)))) => (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, W), V)) => ((W != bot_bot_set_a) => ((W != V) => (aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, aa_set_a_set_a(aa_fun727137317_set_a(hull_a, affine_a), W)), aa_set_a_set_a(convex1609340813rior_a, aa_set_a_set_a(aa_fun727137317_set_a(hull_a, convex_a), V))) = bot_bot_set_a))))))))))).

