% This file was generated by Isabelle (most likely Sledgehammer)
2026-06-02 21:31:03.008

% Could-be-implicit typings (61)

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__b_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__Set__Oset_It__Set__Oset_IT__b_J_J_J_J_J_J, type,
    fun_se1068919980_set_b : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__b_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__Set__Oset_It__Set__Oset_IT__b_J_J_J_J_J, type,
    fun_se788599995_set_b : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J_J_J, type,
    fun_se1904574643_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J_J, type,
    fun_se471244048a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J_J, type,
    fun_se122506306_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J_J, type,
    fun_se823945538_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__b_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__Set__Oset_It__Set__Oset_IT__b_J_J_J_J, type,
    fun_se1154964884_set_b : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J, type,
    fun_se858012459a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__HOL__Obool_J_J, type,
    fun_se874411177b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J_J, type,
    fun_se590241323a_bool : $tType).

tff(ty_n_t__fun_It__fun_IT__a_MT__b_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_MT__b_J_J_J, type,
    fun_fu391738216un_a_b : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J, type,
    fun_se490019921_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J_J, type,
    fun_se1395821270_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_IT__a_Mt__fun_IT__a_Mt__Set__Oset_IT__a_J_J_J_J, type,
    fun_se178901211_set_a : $tType).

tff(ty_n_t__fun_It__fun_IT__a_MT__b_J_Mt__Set__Oset_It__Set__Oset_IT__b_J_J_J, type,
    fun_fu1506792354_set_b : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_IT__a_Mt__Set__Oset_IT__a_J_J_J, type,
    fun_se1248119584_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J, type,
    fun_set_a_set_set_a : $tType).

tff(ty_n_t__fun_It__fun_IT__a_Mt__HOL__Obool_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_fun_a_bool_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__HOL__Obool_J, type,
    fun_set_set_b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J, type,
    fun_set_set_a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J, type,
    fun_set_a_fun_a_bool : $tType).

tff(ty_n_t__fun_IT__e_Mt__fun_It__Set__Oset_IT__e_J_Mt__HOL__Obool_J_J, type,
    fun_e_fun_set_e_bool : $tType).

tff(ty_n_t__fun_IT__c_Mt__fun_It__Set__Oset_IT__c_J_Mt__HOL__Obool_J_J, type,
    fun_c_fun_set_c_bool : $tType).

tff(ty_n_t__fun_IT__b_Mt__fun_It__Set__Oset_IT__b_J_Mt__HOL__Obool_J_J, type,
    fun_b_fun_set_b_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J, type,
    fun_a_fun_set_a_bool : $tType).

tff(ty_n_t__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_MT__b_J_J, type,
    fun_fun_a_b_fun_a_b : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_set_a_set_a : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_IT__a_Mt__Set__Oset_IT__a_J_J_J, type,
    fun_a_fun_a_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__e_J_Mt__HOL__Obool_J, type,
    fun_set_e_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__c_J_Mt__HOL__Obool_J, type,
    fun_set_c_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__b_J_Mt__HOL__Obool_J, type,
    fun_set_b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    fun_set_a_bool : $tType).

tff(ty_n_t__fun_IT__b_Mt__fun_IT__b_MT__b_J_J, type,
    fun_b_fun_b_b : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_IT__a_MT__a_J_J, type,
    fun_a_fun_a_a : $tType).

tff(ty_n_t__fun_IT__a_Mt__Set__Oset_IT__a_J_J, type,
    fun_a_set_a : $tType).

tff(ty_n_t__Set__Oset_It__Set__Oset_IT__b_J_J, type,
    set_set_b : $tType).

tff(ty_n_t__Set__Oset_It__Set__Oset_IT__a_J_J, type,
    set_set_a : $tType).

tff(ty_n_t__fun_IT__e_Mt__HOL__Obool_J, type,
    fun_e_bool : $tType).

tff(ty_n_t__fun_IT__c_Mt__HOL__Obool_J, type,
    fun_c_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__HOL__Obool_J, type,
    fun_a_bool : $tType).

tff(ty_n_t__fun_IT__a__1_MT__a__2_J, type,
    fun_a_a : $tType).

tff(ty_n_t__Set__Oset_IT__a__1_J, type,
    set_a : $tType).

tff(ty_n_t__fun_IT__b_MT__b_J, type,
    fun_b_b : $tType).

tff(ty_n_t__fun_IT__a_MT__b_J, type,
    fun_a_b : $tType).

tff(ty_n_t__fun_IT__a_MT__a_J, type,
    fun_a_a2 : $tType).

tff(ty_n_t__Set__Oset_IT__e_J, type,
    set_e : $tType).

tff(ty_n_t__Set__Oset_IT__c_J, type,
    set_c : $tType).

tff(ty_n_t__Set__Oset_IT__b_J, type,
    set_b : $tType).

tff(ty_n_t__Set__Oset_IT__a_J, type,
    set_a2 : $tType).

tff(ty_n_t__HOL__Obool, type,
    bool : $tType).

tff(ty_n_T__a__2, type,
    a : $tType).

tff(ty_n_T__e, type,
    e : $tType).

tff(ty_n_T__c, type,
    c : $tType).

tff(ty_n_T__b, type,
    b : $tType).

tff(ty_n_T__a, type,
    a2 : $tType).

tff(sy_cl_Boolean__Algebras_Oboolean__algebra, type,
    boolea436070733lgebra : !>[A : $tType]: $o).

tff(sy_cl_Lattices_Obounded__lattice__bot, type,
    bounded_lattice_bot : !>[A : $tType]: $o).

tff(sy_cl_Lattices_Osemilattice__inf, type,
    semilattice_inf : !>[A : $tType]: $o).

tff(sy_cl_Lattices_Obounded__lattice, type,
    bounded_lattice : !>[A : $tType]: $o).

tff(sy_cl_Orderings_Olinorder, type,
    linorder : !>[A : $tType]: $o).

tff(sy_cl_Lattices_Olattice, type,
    lattice : !>[A : $tType]: $o).


% Explicit typings (70)

tff(sy_c_ATP_058Lamm__a, type,
    aTP_Lamm_a : fun_set_a_fun_a_bool).

tff(sy_c_Lattices_Oinf__class_Oinf_001T__a, type,
    inf_inf_a : fun_a_fun_a_a).

tff(sy_c_Lattices_Oinf__class_Oinf_001T__b, type,
    inf_inf_b : fun_b_fun_b_b).

tff(sy_c_Lattices_Oinf__class_Oinf_001t__Set__Oset_IT__a_J, type,
    inf_inf_set_a : fun_se1395821270_set_a).

tff(sy_c_Lattices_Oinf__class_Oinf_001t__fun_IT__a_MT__b_J, type,
    inf_inf_fun_a_b : fun_fu391738216un_a_b).

tff(sy_c_Orderings_Obot__class_Obot_001T__a, type,
    bot_bot_a : a2).

tff(sy_c_Orderings_Obot__class_Obot_001t__Set__Oset_IT__a_J, type,
    bot_bot_set_a : set_a2).

tff(sy_c_Orderings_Obot__class_Obot_001t__Set__Oset_IT__c_J, type,
    bot_bot_set_c : set_c).

tff(sy_c_Orderings_Obot__class_Obot_001t__Set__Oset_IT__e_J, type,
    bot_bot_set_e : set_e).

tff(sy_c_Set_OCollect_001T__a, type,
    collect_a : fun_fun_a_bool_set_a).

tff(sy_c_Top1__Ch2_Oclosedin__on_001T__a, type,
    top1_closedin_on_a : fun_se471244048a_bool).

tff(sy_c_Top1__Ch2_Ois__subbasis__on_001T__a, type,
    top1_i176603307s_on_a : fun_se590241323a_bool).

tff(sy_c_Top1__Ch2_Ois__topology__on_001T__a, type,
    top1_i235996828y_on_a : fun_se590241323a_bool).

tff(sy_c_Top1__Ch2_Ois__topology__on_001T__b, type,
    top1_i235996829y_on_b : fun_se874411177b_bool).

tff(sy_c_Top1__Ch2_Oopen__interval_001T__a, type,
    top1_open_interval_a : fun_a_fun_a_set_a).

tff(sy_c_Top1__Ch2_Oopen__interval__on_001T__a, type,
    top1_o1988065554l_on_a : fun_se178901211_set_a).

tff(sy_c_Top1__Ch2_Oopen__ray__lt_001T__a, type,
    top1_open_ray_lt_a : fun_a_set_a).

tff(sy_c_Top1__Ch2_Oopen__ray__lt__on_001T__a, type,
    top1_o38763521t_on_a : fun_se1248119584_set_a).

tff(sy_c_Top1__Ch2_Osubspace__topology_001T__a, type,
    top1_s1397583065logy_a : fun_se1904574643_set_a).

tff(sy_c_Top1__Ch2_Otop1__quotient__topology__by__map__on_001T__a_001T__b, type,
    top1_t1494391080on_a_b : fun_se1068919980_set_b).

tff(sy_c_Top1__Ch2_Otopology__generated__by__subbasis_001T__a, type,
    top1_t1717497711asis_a : fun_se823945538_set_a).

tff(sy_c_aa_001T__a_001T__a, type,
    aa_a_a : (fun_a_a2 * a2) > a2).

tff(sy_c_aa_001T__a_001T__b, type,
    aa_a_b : (fun_a_b * a2) > b).

tff(sy_c_aa_001T__a_001t__HOL__Obool, type,
    aa_a_bool : (fun_a_bool * a2) > bool).

tff(sy_c_aa_001T__a_001t__Set__Oset_IT__a_J, type,
    aa_a_set_a : (fun_a_set_a * a2) > set_a2).

tff(sy_c_aa_001T__a_001t__fun_IT__a_MT__a_J, type,
    aa_a_fun_a_a : (fun_a_fun_a_a * a2) > fun_a_a2).

tff(sy_c_aa_001T__a_001t__fun_IT__a_Mt__Set__Oset_IT__a_J_J, type,
    aa_a_fun_a_set_a : (fun_a_fun_a_set_a * a2) > fun_a_set_a).

tff(sy_c_aa_001T__a_001t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    aa_a_fun_set_a_bool : (fun_a_fun_set_a_bool * a2) > fun_set_a_bool).

tff(sy_c_aa_001T__b_001T__b, type,
    aa_b_b : (fun_b_b * b) > b).

tff(sy_c_aa_001T__b_001t__fun_IT__b_MT__b_J, type,
    aa_b_fun_b_b : (fun_b_fun_b_b * b) > fun_b_b).

tff(sy_c_aa_001T__b_001t__fun_It__Set__Oset_IT__b_J_Mt__HOL__Obool_J, type,
    aa_b_fun_set_b_bool : (fun_b_fun_set_b_bool * b) > fun_set_b_bool).

tff(sy_c_aa_001T__c_001t__HOL__Obool, type,
    aa_c_bool : (fun_c_bool * c) > bool).

tff(sy_c_aa_001T__c_001t__fun_It__Set__Oset_IT__c_J_Mt__HOL__Obool_J, type,
    aa_c_fun_set_c_bool : (fun_c_fun_set_c_bool * c) > fun_set_c_bool).

tff(sy_c_aa_001T__e_001t__HOL__Obool, type,
    aa_e_bool : (fun_e_bool * e) > bool).

tff(sy_c_aa_001T__e_001t__fun_It__Set__Oset_IT__e_J_Mt__HOL__Obool_J, type,
    aa_e_fun_set_e_bool : (fun_e_fun_set_e_bool * e) > fun_set_e_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__HOL__Obool, type,
    aa_set_a_bool : (fun_set_a_bool * set_a2) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__Set__Oset_IT__a_J, type,
    aa_set_a_set_a : (fun_set_a_set_a * set_a2) > set_a2).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__Set__Oset_It__Set__Oset_IT__a_J_J, type,
    aa_set_a_set_set_a : (fun_set_a_set_set_a * set_a2) > set_set_a).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_IT__a_Mt__HOL__Obool_J, type,
    aa_set_a_fun_a_bool : (fun_set_a_fun_a_bool * set_a2) > fun_a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_IT__a_Mt__Set__Oset_IT__a_J_J, type,
    aa_set_a_fun_a_set_a : (fun_se1248119584_set_a * set_a2) > fun_a_set_a).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_IT__a_Mt__fun_IT__a_Mt__Set__Oset_IT__a_J_J_J, type,
    aa_set851093276_set_a : (fun_se178901211_set_a * set_a2) > fun_a_fun_a_set_a).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J, type,
    aa_set363163287_set_a : (fun_se1395821270_set_a * set_a2) > fun_set_a_set_a).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J, type,
    aa_set1454015380a_bool : (fun_se590241323a_bool * set_a2) > fun_set_set_a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J, type,
    aa_set1227842307_set_a : (fun_se823945538_set_a * set_a2) > fun_se490019921_set_a).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J, type,
    aa_set18515193a_bool : (fun_se471244048a_bool * set_a2) > fun_se858012459a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J_J, type,
    aa_set392168180_set_a : (fun_se1904574643_set_a * set_a2) > fun_se122506306_set_a).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__b_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__Set__Oset_It__Set__Oset_IT__b_J_J_J_J_J, type,
    aa_set1873558381_set_b : (fun_se1068919980_set_b * set_a2) > fun_se788599995_set_b).

tff(sy_c_aa_001t__Set__Oset_IT__b_J_001t__HOL__Obool, type,
    aa_set_b_bool : (fun_set_b_bool * set_b) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__b_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__HOL__Obool_J, type,
    aa_set2083998098b_bool : (fun_se874411177b_bool * set_b) > fun_set_set_b_bool).

tff(sy_c_aa_001t__Set__Oset_IT__b_J_001t__fun_It__fun_IT__a_MT__b_J_Mt__Set__Oset_It__Set__Oset_IT__b_J_J_J, type,
    aa_set1416404949_set_b : (fun_se1154964884_set_b * set_b) > fun_fu1506792354_set_b).

tff(sy_c_aa_001t__Set__Oset_IT__c_J_001t__HOL__Obool, type,
    aa_set_c_bool : (fun_set_c_bool * set_c) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__e_J_001t__HOL__Obool, type,
    aa_set_e_bool : (fun_set_e_bool * set_e) > bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__HOL__Obool, type,
    aa_set_set_a_bool : (fun_set_set_a_bool * set_set_a) > bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__Set__Oset_It__Set__Oset_IT__a_J_J, type,
    aa_set1102275218_set_a : (fun_se490019921_set_a * set_set_a) > set_set_a).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    aa_set2012777364a_bool : (fun_se858012459a_bool * set_set_a) > fun_set_a_bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J, type,
    aa_set1645173507_set_a : (fun_se122506306_set_a * set_set_a) > fun_set_a_set_set_a).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__fun_It__Set__Oset_IT__b_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__Set__Oset_It__Set__Oset_IT__b_J_J_J_J, type,
    aa_set1660727292_set_b : (fun_se788599995_set_b * set_set_a) > fun_se1154964884_set_b).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__b_J_J_001t__HOL__Obool, type,
    aa_set_set_b_bool : (fun_set_set_b_bool * set_set_b) > bool).

tff(sy_c_aa_001t__fun_IT__a_MT__b_J_001t__Set__Oset_It__Set__Oset_IT__b_J_J, type,
    aa_fun_a_b_set_set_b : (fun_fu1506792354_set_b * fun_a_b) > set_set_b).

tff(sy_c_aa_001t__fun_IT__a_MT__b_J_001t__fun_IT__a_MT__b_J, type,
    aa_fun_a_b_fun_a_b : (fun_fun_a_b_fun_a_b * fun_a_b) > fun_a_b).

tff(sy_c_aa_001t__fun_IT__a_MT__b_J_001t__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_MT__b_J_J, type,
    aa_fun911777065un_a_b : (fun_fu391738216un_a_b * fun_a_b) > fun_fun_a_b_fun_a_b).

tff(sy_c_aa_001t__fun_IT__a_Mt__HOL__Obool_J_001t__Set__Oset_IT__a_J, type,
    aa_fun_a_bool_set_a : (fun_fun_a_bool_set_a * fun_a_bool) > set_a2).

tff(sy_c_fFalse, type,
    fFalse : bool).

tff(sy_c_fTrue, type,
    fTrue : bool).

tff(sy_c_member_001T__a, type,
    member_a : fun_a_fun_set_a_bool).

tff(sy_c_member_001T__b, type,
    member_b : fun_b_fun_set_b_bool).

tff(sy_c_member_001T__c, type,
    member_c : fun_c_fun_set_c_bool).

tff(sy_c_member_001T__e, type,
    member_e : fun_e_fun_set_e_bool).

tff(sy_c_member_001t__Set__Oset_IT__a_J, type,
    member_set_a : fun_se590241323a_bool).

tff(sy_c_pp, type,
    pp : bool > $o).


% Relevant facts (65)

tff(fact_0_mem__simps_I4_J, axiom,
    ((![A : $i, C : a2, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), B))) <=> (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A2)) & pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B))))))). % mem_simps(4)

tff(fact_1_IntI, axiom,
    ((![A : $i, C : a2, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A2)) => (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B)) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), B)))))))). % IntI

tff(fact_2_Int__iff, axiom,
    ((![A : $i, C : a2, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), B))) <=> (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A2)) & pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B))))))). % Int_iff

tff(fact_3_inf__aci_I4_J, axiom,
    ((![A : $i]: (semilattice_inf(a2) => (![X : a2, Y : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, X), aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y)) = aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y))))))). % inf_aci(4)

tff(fact_4_inf_Oidem, axiom,
    ((![A : $i]: (semilattice_inf(a2) => (![A3 : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, A3), A3) = A3)))))). % inf.idem

tff(fact_5_inf__idem, axiom,
    ((![A : $i]: (semilattice_inf(a2) => (![X : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, X), X) = X)))))). % inf_idem

tff(fact_6_inf_Oleft__idem, axiom,
    ((![A : $i]: (semilattice_inf(a2) => (![A3 : a2, B2 : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, A3), aa_a_a(aa_a_fun_a_a(inf_inf_a, A3), B2)) = aa_a_a(aa_a_fun_a_a(inf_inf_a, A3), B2))))))). % inf.left_idem

tff(fact_7_inf__left__idem, axiom,
    ((![A : $i]: (semilattice_inf(a2) => (![X : a2, Y : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, X), aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y)) = aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y))))))). % inf_left_idem

tff(fact_8_inf_Oright__idem, axiom,
    ((![A : $i]: (semilattice_inf(a2) => (![A3 : a2, B2 : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, aa_a_a(aa_a_fun_a_a(inf_inf_a, A3), B2)), B2) = aa_a_a(aa_a_fun_a_a(inf_inf_a, A3), B2))))))). % inf.right_idem

tff(fact_9_inf__right__idem, axiom,
    ((![A : $i]: (semilattice_inf(a2) => (![X : a2, Y : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y)), Y) = aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y))))))). % inf_right_idem

tff(fact_10_inf__apply, axiom,
    ((![B3 : $i, A : $i]: (semilattice_inf(b) => (![F : fun_a_b, G : fun_a_b, X : a2]: (aa_a_b(aa_fun_a_b_fun_a_b(aa_fun911777065un_a_b(inf_inf_fun_a_b, F), G), X) = aa_b_b(aa_b_fun_b_b(inf_inf_b, aa_a_b(F, X)), aa_a_b(G, X)))))))). % inf_apply

tff(fact_11_closedin__carrier, axiom,
    ((![A : $i, X2 : set_a2, T : set_set_a]: (pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_i235996828y_on_a, X2), T)) => pp(aa_set_a_bool(aa_set2012777364a_bool(aa_set18515193a_bool(top1_closedin_on_a, X2), T), X2)))))). % closedin_carrier

tff(fact_12_inf__fun__def, axiom,
    ((![B3 : $i, A : $i]: (semilattice_inf(b) => (![F : fun_a_b, G : fun_a_b, X3 : a2]: (aa_a_b(aa_fun_a_b_fun_a_b(aa_fun911777065un_a_b(inf_inf_fun_a_b, F), G), X3) = aa_b_b(aa_b_fun_b_b(inf_inf_b, aa_a_b(F, X3)), aa_a_b(G, X3)))))))). % inf_fun_def

tff(fact_13_inf__left__commute, axiom,
    ((![A : $i]: (semilattice_inf(a2) => (![X : a2, Y : a2, Z : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, X), aa_a_a(aa_a_fun_a_a(inf_inf_a, Y), Z)) = aa_a_a(aa_a_fun_a_a(inf_inf_a, Y), aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Z)))))))). % inf_left_commute

tff(fact_14_inf_Oleft__commute, axiom,
    ((![A : $i]: (semilattice_inf(a2) => (![B2 : a2, A3 : a2, C : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, B2), aa_a_a(aa_a_fun_a_a(inf_inf_a, A3), C)) = aa_a_a(aa_a_fun_a_a(inf_inf_a, A3), aa_a_a(aa_a_fun_a_a(inf_inf_a, B2), C)))))))). % inf.left_commute

tff(fact_15_inf__commute, axiom,
    ((![A : $i]: (semilattice_inf(a2) => (![X : a2, Y : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y) = aa_a_a(aa_a_fun_a_a(inf_inf_a, Y), X))))))). % inf_commute

tff(fact_16_inf_Ocommute, axiom,
    ((![A : $i]: (semilattice_inf(a2) => (![A3 : a2, B2 : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, A3), B2) = aa_a_a(aa_a_fun_a_a(inf_inf_a, B2), A3))))))). % inf.commute

tff(fact_17_inf__assoc, axiom,
    ((![A : $i]: (semilattice_inf(a2) => (![X : a2, Y : a2, Z : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y)), Z) = aa_a_a(aa_a_fun_a_a(inf_inf_a, X), aa_a_a(aa_a_fun_a_a(inf_inf_a, Y), Z)))))))). % inf_assoc

tff(fact_18_inf_Oassoc, axiom,
    ((![A : $i]: (semilattice_inf(a2) => (![A3 : a2, B2 : a2, C : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, aa_a_a(aa_a_fun_a_a(inf_inf_a, A3), B2)), C) = aa_a_a(aa_a_fun_a_a(inf_inf_a, A3), aa_a_a(aa_a_fun_a_a(inf_inf_a, B2), C)))))))). % inf.assoc

tff(fact_19_inf__aci_I1_J, axiom,
    ((![A : $i]: (semilattice_inf(a2) => (![X : a2, Y : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y) = aa_a_a(aa_a_fun_a_a(inf_inf_a, Y), X))))))). % inf_aci(1)

tff(fact_20_inf__aci_I2_J, axiom,
    ((![A : $i]: (semilattice_inf(a2) => (![X : a2, Y : a2, Z : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y)), Z) = aa_a_a(aa_a_fun_a_a(inf_inf_a, X), aa_a_a(aa_a_fun_a_a(inf_inf_a, Y), Z)))))))). % inf_aci(2)

tff(fact_21_inf__aci_I3_J, axiom,
    ((![A : $i]: (semilattice_inf(a2) => (![X : a2, Y : a2, Z : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, X), aa_a_a(aa_a_fun_a_a(inf_inf_a, Y), Z)) = aa_a_a(aa_a_fun_a_a(inf_inf_a, Y), aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Z)))))))). % inf_aci(3)

tff(fact_22_inf__sup__aci_I1_J, axiom,
    ((![A : $i]: (lattice(a2) => (![X : a2, Y : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y) = aa_a_a(aa_a_fun_a_a(inf_inf_a, Y), X))))))). % inf_sup_aci(1)

tff(fact_23_inf__sup__aci_I2_J, axiom,
    ((![A : $i]: (lattice(a2) => (![X : a2, Y : a2, Z : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y)), Z) = aa_a_a(aa_a_fun_a_a(inf_inf_a, X), aa_a_a(aa_a_fun_a_a(inf_inf_a, Y), Z)))))))). % inf_sup_aci(2)

tff(fact_24_inf__sup__aci_I3_J, axiom,
    ((![A : $i]: (lattice(a2) => (![X : a2, Y : a2, Z : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, X), aa_a_a(aa_a_fun_a_a(inf_inf_a, Y), Z)) = aa_a_a(aa_a_fun_a_a(inf_inf_a, Y), aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Z)))))))). % inf_sup_aci(3)

tff(fact_25_inf__sup__aci_I4_J, axiom,
    ((![A : $i]: (lattice(a2) => (![X : a2, Y : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, X), aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y)) = aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y))))))). % inf_sup_aci(4)

tff(fact_26_Int__left__commute, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2, C2 : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, B), C2)) = aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, B), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), C2)))))). % Int_left_commute

tff(fact_27_Int__left__absorb, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), B)) = aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), B))))). % Int_left_absorb

tff(fact_28_Int__commute, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), B) = aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, B), A2))))). % Int_commute

tff(fact_29_Int__absorb, axiom,
    ((![A : $i, A2 : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), A2) = A2)))). % Int_absorb

tff(fact_30_Int__assoc, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2, C2 : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), B)), C2) = aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, B), C2)))))). % Int_assoc

tff(fact_31_IntD2, axiom,
    ((![A : $i, C : a2, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), B))) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B)))))). % IntD2

tff(fact_32_IntD1, axiom,
    ((![A : $i, C : a2, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), B))) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A2)))))). % IntD1

tff(fact_33_IntE, axiom,
    ((![A : $i, C : a2, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), B))) => (~ ((pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A2)) => (~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B))))))))))). % IntE

tff(fact_34_Int__ac_I1_J, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2, C2 : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), B)), C2) = aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, B), C2)))))). % Int_ac(1)

tff(fact_35_Int__ac_I2_J, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), B)) = aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), B))))). % Int_ac(2)

tff(fact_36_Int__ac_I3_J, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), B) = aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, B), A2))))). % Int_ac(3)

tff(fact_37_Int__ac_I4_J, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2, C2 : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, B), C2)) = aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, B), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), C2)))))). % Int_ac(4)

tff(fact_38_topology__inter2, axiom,
    ((![A : $i, X2 : set_a2, T : set_set_a, U : set_a2, V : set_a2]: (pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_i235996828y_on_a, X2), T)) => (pp(aa_set_set_a_bool(aa_set1454015380a_bool(member_set_a, U), T)) => (pp(aa_set_set_a_bool(aa_set1454015380a_bool(member_set_a, V), T)) => pp(aa_set_set_a_bool(aa_set1454015380a_bool(member_set_a, aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, U), V)), T)))))))). % topology_inter2

tff(fact_39_top1__quotient__topology__by__map__on__is__topology__on, axiom,
    ((![B3 : $i, A : $i, X2 : set_a2, TX : set_set_a, P : fun_a_b, Y2 : set_b]: (pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_i235996828y_on_a, X2), TX)) => ((![X4 : a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X4), X2)) => pp(aa_set_b_bool(aa_b_fun_set_b_bool(member_b, aa_a_b(P, X4)), Y2)))) => pp(aa_set_set_b_bool(aa_set2083998098b_bool(top1_i235996829y_on_b, Y2), aa_fun_a_b_set_set_b(aa_set1416404949_set_b(aa_set1660727292_set_b(aa_set1873558381_set_b(top1_t1494391080on_a_b, X2), TX), Y2), P)))))))). % top1_quotient_topology_by_map_on_is_topology_on

tff(fact_40_boolean__algebra__cancel_Oinf2, axiom,
    ((![A : $i]: (semilattice_inf(a2) => (![B : a2, K : a2, B2 : a2, A3 : a2]: ((B = aa_a_a(aa_a_fun_a_a(inf_inf_a, K), B2)) => (aa_a_a(aa_a_fun_a_a(inf_inf_a, A3), B) = aa_a_a(aa_a_fun_a_a(inf_inf_a, K), aa_a_a(aa_a_fun_a_a(inf_inf_a, A3), B2))))))))). % boolean_algebra_cancel.inf2

tff(fact_41_boolean__algebra__cancel_Oinf1, axiom,
    ((![A : $i]: (semilattice_inf(a2) => (![A2 : a2, K : a2, A3 : a2, B2 : a2]: ((A2 = aa_a_a(aa_a_fun_a_a(inf_inf_a, K), A3)) => (aa_a_a(aa_a_fun_a_a(inf_inf_a, A2), B2) = aa_a_a(aa_a_fun_a_a(inf_inf_a, K), aa_a_a(aa_a_fun_a_a(inf_inf_a, A3), B2))))))))). % boolean_algebra_cancel.inf1

tff(fact_42_closedin__empty, axiom,
    ((![A : $i, X2 : set_a2, T : set_set_a]: (pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_i235996828y_on_a, X2), T)) => pp(aa_set_a_bool(aa_set2012777364a_bool(aa_set18515193a_bool(top1_closedin_on_a, X2), T), bot_bot_set_a)))))). % closedin_empty

tff(fact_43_Theorem__17__3, axiom,
    ((![A : $i, X2 : set_a2, T : set_set_a, Y2 : set_a2, A2 : set_a2]: (pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_i235996828y_on_a, X2), T)) => (pp(aa_set_a_bool(aa_set2012777364a_bool(aa_set18515193a_bool(top1_closedin_on_a, X2), T), Y2)) => (pp(aa_set_a_bool(aa_set2012777364a_bool(aa_set18515193a_bool(top1_closedin_on_a, Y2), aa_set_a_set_set_a(aa_set1645173507_set_a(aa_set392168180_set_a(top1_s1397583065logy_a, X2), T), Y2)), A2)) => pp(aa_set_a_bool(aa_set2012777364a_bool(aa_set18515193a_bool(top1_closedin_on_a, X2), T), A2)))))))). % Theorem_17_3

tff(fact_44_topology__generated__by__subbasis__is__topology__on, axiom,
    ((![A : $i, X2 : set_a2, S : set_set_a]: (pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_i176603307s_on_a, X2), S)) => pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_i235996828y_on_a, X2), aa_set1102275218_set_a(aa_set1227842307_set_a(top1_t1717497711asis_a, X2), S))))))). % topology_generated_by_subbasis_is_topology_on

tff(fact_45_mem__Collect__eq, axiom,
    ((![A : $i, A3 : a2, P2 : fun_a_bool]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, A3), aa_fun_a_bool_set_a(collect_a, P2))) <=> pp(aa_a_bool(P2, A3)))))). % mem_Collect_eq

tff(fact_46_Collect__mem__eq, axiom,
    ((![A : $i, A2 : set_a2]: (aa_fun_a_bool_set_a(collect_a, aa_set_a_fun_a_bool(aTP_Lamm_a, A2)) = A2)))). % Collect_mem_eq

tff(fact_47_Collect__cong, axiom,
    ((![A : $i, P2 : fun_a_bool, Q : fun_a_bool]: ((![X4 : a2]: (pp(aa_a_bool(P2, X4)) <=> pp(aa_a_bool(Q, X4)))) => (aa_fun_a_bool_set_a(collect_a, P2) = aa_fun_a_bool_set_a(collect_a, Q)))))). % Collect_cong

tff(fact_48_ext, axiom,
    ((![B3 : $i, A : $i, F : fun_a_b, G : fun_a_b]: ((![X4 : a2]: (aa_a_b(F, X4) = aa_a_b(G, X4))) => (F = G))))). % ext

tff(fact_49_mem__simps_I7_J, axiom,
    ((![A : $i, A3 : a2, P2 : fun_a_bool]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, A3), aa_fun_a_bool_set_a(collect_a, P2))) <=> pp(aa_a_bool(P2, A3)))))). % mem_simps(7)

tff(fact_50_array__rules_I1_J, axiom,
    ((![B3 : $i, A : $i, F : fun_a_b, G : fun_a_b]: ((![X4 : a2]: (aa_a_b(F, X4) = aa_a_b(G, X4))) => (F = G))))). % array_rules(1)

tff(fact_51_open__interval__on__def, axiom,
    ((![A : $i]: (linorder(a2) => (![X2 : set_a2, A3 : a2, B2 : a2]: (aa_a_set_a(aa_a_fun_a_set_a(aa_set851093276_set_a(top1_o1988065554l_on_a, X2), A3), B2) = aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, X2), aa_a_set_a(aa_a_fun_a_set_a(top1_open_interval_a, A3), B2)))))))). % open_interval_on_def

tff(fact_52_open__ray__lt__on__def, axiom,
    ((![A : $i]: (linorder(a2) => (![X2 : set_a2, A3 : a2]: (aa_a_set_a(aa_set_a_fun_a_set_a(top1_o38763521t_on_a, X2), A3) = aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, X2), aa_a_set_a(top1_open_ray_lt_a, A3)))))))). % open_ray_lt_on_def

tff(fact_53_bex__simps_I3_J, axiom,
    ((![C3 : $i, P2 : fun_c_bool]: (~ ((?[X3 : c]: (pp(aa_set_c_bool(aa_c_fun_set_c_bool(member_c, X3), bot_bot_set_c)) & pp(aa_c_bool(P2, X3))))))))). % bex_simps(3)

tff(fact_54_ball__simps_I5_J, axiom,
    ((![E : $i, P2 : fun_e_bool, X3 : e]: (pp(aa_set_e_bool(aa_e_fun_set_e_bool(member_e, X3), bot_bot_set_e)) => pp(aa_e_bool(P2, X3)))))). % ball_simps(5)

tff(fact_55_mem__simps_I2_J, axiom,
    ((![A : $i, C : a2]: (~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), bot_bot_set_a))))))). % mem_simps(2)

tff(fact_56_empty__iff, axiom,
    ((![A : $i, C : a2]: (~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), bot_bot_set_a))))))). % empty_iff

tff(fact_57_all__not__in__conv, axiom,
    ((![A : $i, A2 : set_a2]: ((![X5 : a2]: (~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X5), A2))))) <=> (A2 = bot_bot_set_a))))). % all_not_in_conv

tff(fact_58_Collect__empty__eq, axiom,
    ((![A : $i, P2 : fun_a_bool]: ((aa_fun_a_bool_set_a(collect_a, P2) = bot_bot_set_a) <=> (![X5 : a2]: (~ (pp(aa_a_bool(P2, X5))))))))). % Collect_empty_eq

tff(fact_59_empty__Collect__eq, axiom,
    ((![A : $i, P2 : fun_a_bool]: ((bot_bot_set_a = aa_fun_a_bool_set_a(collect_a, P2)) <=> (![X5 : a2]: (~ (pp(aa_a_bool(P2, X5))))))))). % empty_Collect_eq

tff(fact_60_boolean__algebra_Oconj__zero__right, axiom,
    ((![A : $i]: (boolea436070733lgebra(a2) => (![X : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, X), bot_bot_a) = bot_bot_a)))))). % boolean_algebra.conj_zero_right

tff(fact_61_boolean__algebra_Oconj__zero__left, axiom,
    ((![A : $i]: (boolea436070733lgebra(a2) => (![X : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, bot_bot_a), X) = bot_bot_a)))))). % boolean_algebra.conj_zero_left

tff(fact_62_inf__bot__left, axiom,
    ((![A : $i]: (bounded_lattice_bot(a2) => (![X : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, bot_bot_a), X) = bot_bot_a)))))). % inf_bot_left

tff(fact_63_inf__bot__right, axiom,
    ((![A : $i]: (bounded_lattice_bot(a2) => (![X : a2]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, X), bot_bot_a) = bot_bot_a)))))). % inf_bot_right

tff(fact_64_ATP_Olambda__1, axiom,
    ((![A : $i, Uu : set_a2, Uua : a2]: (pp(aa_a_bool(aa_set_a_fun_a_bool(aTP_Lamm_a, Uu), Uua)) <=> pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, Uua), Uu)))))). % ATP.lambda_1


% Type constructors (16)

tff(tcon_HOL_Obool___Lattices_Obounded__lattice, axiom,
    (bounded_lattice(bool))).

tff(tcon_Set_Oset___Lattices_Obounded__lattice_1, axiom,
    ((![A4 : $i]: bounded_lattice(set_a)))).

tff(tcon_fun___Lattices_Obounded__lattice_2, axiom,
    ((![A4 : $i, A5 : $i]: (bounded_lattice(a) => bounded_lattice(fun_a_a))))).

tff(tcon_fun___Boolean__Algebras_Oboolean__algebra, axiom,
    ((![A4 : $i, A5 : $i]: (boolea436070733lgebra(a) => boolea436070733lgebra(fun_a_a))))).

tff(tcon_fun___Lattices_Obounded__lattice__bot, axiom,
    ((![A4 : $i, A5 : $i]: (bounded_lattice(a) => bounded_lattice_bot(fun_a_a))))).

tff(tcon_fun___Lattices_Osemilattice__inf, axiom,
    ((![A4 : $i, A5 : $i]: (semilattice_inf(a) => semilattice_inf(fun_a_a))))).

tff(tcon_fun___Lattices_Olattice, axiom,
    ((![A4 : $i, A5 : $i]: (lattice(a) => lattice(fun_a_a))))).

tff(tcon_Set_Oset___Boolean__Algebras_Oboolean__algebra_3, axiom,
    ((![A4 : $i]: boolea436070733lgebra(set_a)))).

tff(tcon_Set_Oset___Lattices_Obounded__lattice__bot_4, axiom,
    ((![A4 : $i]: bounded_lattice_bot(set_a)))).

tff(tcon_Set_Oset___Lattices_Osemilattice__inf_5, axiom,
    ((![A4 : $i]: semilattice_inf(set_a)))).

tff(tcon_Set_Oset___Lattices_Olattice_6, axiom,
    ((![A4 : $i]: lattice(set_a)))).

tff(tcon_HOL_Obool___Boolean__Algebras_Oboolean__algebra_7, axiom,
    (boolea436070733lgebra(bool))).

tff(tcon_HOL_Obool___Lattices_Obounded__lattice__bot_8, axiom,
    (bounded_lattice_bot(bool))).

tff(tcon_HOL_Obool___Lattices_Osemilattice__inf_9, axiom,
    (semilattice_inf(bool))).

tff(tcon_HOL_Obool___Orderings_Olinorder, axiom,
    (linorder(bool))).

tff(tcon_HOL_Obool___Lattices_Olattice_10, axiom,
    (lattice(bool))).


% Helper facts (2)

tff(help_pp_2_1_U, axiom,
    (pp(fTrue))).

tff(help_pp_1_1_U, axiom,
    ((~ (pp(fFalse))))).


% Conjectures (4)

tff(conj_0, hypothesis,
    ((![A : $i, X2 : set_a2, T : set_set_a]: pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_i235996828y_on_a, X2), T))))).

tff(conj_1, hypothesis,
    ((![A : $i, X2 : set_a2, T : set_set_a, A2 : set_a2]: pp(aa_set_a_bool(aa_set2012777364a_bool(aa_set18515193a_bool(top1_closedin_on_a, X2), T), A2))))).

tff(conj_2, hypothesis,
    ((![A : $i, X2 : set_a2, T : set_set_a, B : set_a2]: pp(aa_set_a_bool(aa_set2012777364a_bool(aa_set18515193a_bool(top1_closedin_on_a, X2), T), B))))).

tff(conj_3, conjecture,
    ((![A : $i, X2 : set_a2, T : set_set_a, A2 : set_a2, B : set_a2]: pp(aa_set_a_bool(aa_set2012777364a_bool(aa_set18515193a_bool(top1_closedin_on_a, X2), T), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), B)))))).

