% This file was generated by Isabelle (most likely Sledgehammer)
2026-06-02 21:31:07.203

% Could-be-implicit typings (81)

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__b_J_Mt__fun_It__fun_IT__b_Mt__fun_IT__b_Mt__Real__Oreal_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J_J_J_J_J, type,
    fun_se1694933502a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J_J_J_J_J, type,
    fun_se857368887a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__HOL__Obool_J_J_J_J_J, type,
    fun_se133803932b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__b_J_Mt__fun_It__fun_IT__b_Mt__fun_IT__b_Mt__Real__Oreal_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J_J_J_J, type,
    fun_se2005891097a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J_J_J_J, type,
    fun_se141744850a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__HOL__Obool_J_J_J_J, type,
    fun_se1552047031b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__b_J_Mt__fun_It__fun_IT__b_Mt__fun_IT__b_Mt__Real__Oreal_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J_J_J, type,
    fun_se1490760170a_bool : $tType).

tff(ty_n_t__fun_It__fun_It__Nat__Onat_MT__b_J_Mt__fun_IT__b_Mt__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__HOL__Obool_J_J_J_J, type,
    fun_fu874162768b_bool : $tType).

tff(ty_n_t__fun_It__fun_It__Nat__Onat_MT__a_J_Mt__fun_IT__a_Mt__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J_J_J_J, type,
    fun_fu1827961940a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J_J_J, type,
    fun_se1351161635a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__b_J_Mt__fun_It__fun_IT__b_Mt__fun_IT__b_Mt__Real__Oreal_J_J_Mt__Set__Oset_It__Set__Oset_IT__b_J_J_J_J, type,
    fun_se920280766_set_b : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__fun_IT__a_Mt__fun_IT__a_Mt__Real__Oreal_J_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J_J, type,
    fun_se801188922_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__HOL__Obool_J_J_J, type,
    fun_se2143152776b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J_J, type,
    fun_se471244048a_bool : $tType).

tff(ty_n_t__fun_It__fun_IT__b_Mt__fun_IT__b_Mt__Real__Oreal_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J_J, type,
    fun_fu2038073158a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J_J, type,
    fun_se1655151231a_bool : $tType).

tff(ty_n_t__fun_IT__b_Mt__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__HOL__Obool_J_J_J, type,
    fun_b_1705634051b_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J_J_J, type,
    fun_a_1515919686a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__b_J_Mt__fun_It__fun_IT__b_Mt__fun_IT__b_Mt__Real__Oreal_J_J_Mt__HOL__Obool_J_J, type,
    fun_se585393008l_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__fun_IT__a_Mt__fun_IT__a_Mt__Real__Oreal_J_J_Mt__HOL__Obool_J_J, type,
    fun_se422218035l_bool : $tType).

tff(ty_n_t__fun_It__fun_It__Nat__Onat_Mt__fun_IT__a_MT__b_J_J_Mt__fun_IT__a_Mt__fun_It__Nat__Onat_MT__b_J_J_J, type,
    fun_fu920988683_nat_b : $tType).

tff(ty_n_t__fun_It__fun_IT__a_MT__b_J_Mt__fun_It__fun_It__Nat__Onat_MT__a_J_Mt__fun_It__Nat__Onat_MT__b_J_J_J, type,
    fun_fu9004939_nat_b : $tType).

tff(ty_n_t__fun_It__fun_IT__a_Mt__HOL__Obool_J_Mt__fun_It__fun_IT__a_Mt__HOL__Obool_J_Mt__HOL__Obool_J_J, type,
    fun_fu647214445l_bool : $tType).

tff(ty_n_t__fun_It__fun_IT__b_Mt__fun_IT__b_Mt__Real__Oreal_J_J_Mt__Set__Oset_It__Set__Oset_IT__b_J_J_J, type,
    fun_fu150939468_set_b : $tType).

tff(ty_n_t__fun_It__fun_IT__a_Mt__fun_IT__a_Mt__Real__Oreal_J_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J, type,
    fun_fu1297279561_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__HOL__Obool_J_J, type,
    fun_se1751821412b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J, type,
    fun_se858012459a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__HOL__Obool_J_J, type,
    fun_se874411177b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J_J, type,
    fun_se590241323a_bool : $tType).

tff(ty_n_t__fun_It__fun_IT__a_MT__b_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__HOL__Obool_J_J, type,
    fun_fu370395733b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J, type,
    fun_se1296151905a_bool : $tType).

tff(ty_n_t__fun_It__fun_IT__b_Mt__fun_IT__b_Mt__Real__Oreal_J_J_Mt__HOL__Obool_J, type,
    fun_fu419852236l_bool : $tType).

tff(ty_n_t__fun_It__fun_IT__a_Mt__fun_IT__a_Mt__Real__Oreal_J_J_Mt__HOL__Obool_J, type,
    fun_fu2111547854l_bool : $tType).

tff(ty_n_t__fun_It__fun_It__Nat__Onat_MT__a_J_Mt__fun_It__Nat__Onat_MT__b_J_J, type,
    fun_fu447973268_nat_b : $tType).

tff(ty_n_t__fun_It__Real__Oreal_Mt__fun_It__Real__Oreal_Mt__HOL__Obool_J_J, type,
    fun_re589487345l_bool : $tType).

tff(ty_n_t__fun_It__fun_IT__a_Mt__HOL__Obool_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_fun_a_bool_set_a : $tType).

tff(ty_n_t__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J, type,
    fun_fu798682257a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__HOL__Obool_J, type,
    fun_set_set_b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J, type,
    fun_set_set_a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J, type,
    fun_set_a_fun_a_bool : $tType).

tff(ty_n_t__fun_IT__b_Mt__fun_It__Set__Oset_IT__b_J_Mt__HOL__Obool_J_J, type,
    fun_b_fun_set_b_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J, type,
    fun_a_fun_set_a_bool : $tType).

tff(ty_n_t__fun_It__fun_IT__a_Mt__HOL__Obool_J_Mt__HOL__Obool_J, type,
    fun_fun_a_bool_bool : $tType).

tff(ty_n_t__fun_IT__b_Mt__fun_IT__b_Mt__Real__Oreal_J_J, type,
    fun_b_fun_b_real : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_IT__a_Mt__Real__Oreal_J_J, type,
    fun_a_fun_a_real : $tType).

tff(ty_n_t__fun_It__fun_IT__a_MT__b_J_Mt__HOL__Obool_J, type,
    fun_fun_a_b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__b_J_Mt__HOL__Obool_J, type,
    fun_set_b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    fun_set_a_bool : $tType).

tff(ty_n_t__fun_IT__c_Mt__fun_IT__c_Mt__HOL__Obool_J_J, type,
    fun_c_fun_c_bool : $tType).

tff(ty_n_t__fun_IT__b_Mt__fun_IT__b_Mt__HOL__Obool_J_J, type,
    fun_b_fun_b_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_IT__a_Mt__HOL__Obool_J_J, type,
    fun_a_fun_a_bool : $tType).

tff(ty_n_t__fun_It__Nat__Onat_Mt__fun_IT__a_MT__b_J_J, type,
    fun_nat_fun_a_b : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_It__Nat__Onat_MT__b_J_J, type,
    fun_a_fun_nat_b : $tType).

tff(ty_n_t__fun_It__Real__Oreal_Mt__HOL__Obool_J, type,
    fun_real_bool : $tType).

tff(ty_n_t__fun_IT__b_Mt__fun_IT__a_MT__b_J_J, type,
    fun_b_fun_a_b : $tType).

tff(ty_n_t__Set__Oset_It__Set__Oset_IT__b_J_J, type,
    set_set_b : $tType).

tff(ty_n_t__Set__Oset_It__Set__Oset_IT__a_J_J, type,
    set_set_a : $tType).

tff(ty_n_t__fun_IT__a_Mt__Real__Oreal_J, type,
    fun_a_real : $tType).

tff(ty_n_t__fun_IT__c_Mt__HOL__Obool_J, type,
    fun_c_bool : $tType).

tff(ty_n_t__fun_IT__b_Mt__HOL__Obool_J, type,
    fun_b_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__HOL__Obool_J, type,
    fun_a_bool : $tType).

tff(ty_n_t__fun_It__Nat__Onat_MT__b_J, type,
    fun_nat_b : $tType).

tff(ty_n_t__fun_It__Nat__Onat_MT__a_J, type,
    fun_nat_a : $tType).

tff(ty_n_t__fun_IT__a__1_MT__a__2_J, type,
    fun_a_a : $tType).

tff(ty_n_t__Set__Oset_IT__a__1_J, type,
    set_a : $tType).

tff(ty_n_t__fun_IT__b_MT__a_J, type,
    fun_b_a : $tType).

tff(ty_n_t__fun_IT__a_MT__c_J, type,
    fun_a_c : $tType).

tff(ty_n_t__fun_IT__a_MT__b_J, type,
    fun_a_b : $tType).

tff(ty_n_t__Set__Oset_IT__b_J, type,
    set_b : $tType).

tff(ty_n_t__Set__Oset_IT__a_J, type,
    set_a2 : $tType).

tff(ty_n_t__Real__Oreal, type,
    real : $tType).

tff(ty_n_t__HOL__Obool, type,
    bool : $tType).

tff(ty_n_t__Nat__Onat, type,
    nat : $tType).

tff(ty_n_T__a__2, type,
    a : $tType).

tff(ty_n_T__c, type,
    c : $tType).

tff(ty_n_T__b, type,
    b : $tType).

tff(ty_n_T__a, type,
    a2 : $tType).

tff(sy_cl_Orderings_Opreorder, type,
    preorder : !>[A : $tType]: $o).

tff(sy_cl_Orderings_Olinorder, type,
    linorder : !>[A : $tType]: $o).

tff(sy_cl_Orderings_Oorder, type,
    order : !>[A : $tType]: $o).

tff(sy_cl_Orderings_Oord, type,
    ord : !>[A : $tType]: $o).


% Explicit typings (94)

tff(sy_c_ATP_058Lamm__a, type,
    aTP_Lamm_a : fun_fu920988683_nat_b).

tff(sy_c_ATP_058Lamm__aa, type,
    aTP_Lamm_aa : fun_se1694933502a_bool).

tff(sy_c_ATP_058Lamm__ab, type,
    aTP_Lamm_ab : fun_fu9004939_nat_b).

tff(sy_c_ATP_058Lamm__ac, type,
    aTP_Lamm_ac : fun_b_fun_a_b).

tff(sy_c_ATP_058Lamm__ad, type,
    aTP_Lamm_ad : fun_set_a_fun_a_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001T__a, type,
    ord_less_eq_a : fun_a_fun_a_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001T__b, type,
    ord_less_eq_b : fun_b_fun_b_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001T__c, type,
    ord_less_eq_c : fun_c_fun_c_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001t__Real__Oreal, type,
    ord_less_eq_real : fun_re589487345l_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001t__Set__Oset_IT__a_J, type,
    ord_less_eq_set_a : fun_se1296151905a_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001t__fun_IT__a_MT__b_J, type,
    ord_less_eq_fun_a_b : fun_fu370395733b_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001t__fun_IT__a_Mt__HOL__Obool_J, type,
    ord_le801610962a_bool : fun_fu647214445l_bool).

tff(sy_c_Set_OCollect_001T__a, type,
    collect_a : fun_fun_a_bool_set_a).

tff(sy_c_Top1__Ch2_Ois__topology__on_001T__a, type,
    top1_i235996828y_on_a : fun_se590241323a_bool).

tff(sy_c_Top1__Ch2_Ois__topology__on_001T__b, type,
    top1_i235996829y_on_b : fun_se874411177b_bool).

tff(sy_c_Top1__Ch2_Oseq__converges__to__on_001T__a, type,
    top1_s1653822099o_on_a : fun_fu1827961940a_bool).

tff(sy_c_Top1__Ch2_Oseq__converges__to__on_001T__b, type,
    top1_s1653822100o_on_b : fun_fu874162768b_bool).

tff(sy_c_Top1__Ch2_Otop1__continuous__at__on_001T__a_001T__b, type,
    top1_t331991105on_a_b : fun_se857368887a_bool).

tff(sy_c_Top1__Ch2_Otop1__continuous__map__on_001T__a_001T__b, type,
    top1_t1121318858on_a_b : fun_se133803932b_bool).

tff(sy_c_Top1__Ch2_Otop1__metric__on_001T__a, type,
    top1_t1666180655c_on_a : fun_se422218035l_bool).

tff(sy_c_Top1__Ch2_Otop1__metric__on_001T__b, type,
    top1_t1666180656c_on_b : fun_se585393008l_bool).

tff(sy_c_Top1__Ch2_Otop1__metric__topology__on_001T__a, type,
    top1_t1018579774y_on_a : fun_se801188922_set_a).

tff(sy_c_Top1__Ch2_Otop1__metric__topology__on_001T__b, type,
    top1_t1018579775y_on_b : fun_se920280766_set_b).

tff(sy_c_Top1__Ch5__8_Otop1__baire__on_001T__a, type,
    top1_C1278066831e_on_a : fun_se590241323a_bool).

tff(sy_c_Top1__Ch5__8_Otop1__densein__on_001T__a, type,
    top1_C1617914646n_on_a : fun_se471244048a_bool).

tff(sy_c_aa_001T__a_001T__b, type,
    aa_a_b : (fun_a_b * a2) > b).

tff(sy_c_aa_001T__a_001T__c, type,
    aa_a_c : (fun_a_c * a2) > c).

tff(sy_c_aa_001T__a_001t__HOL__Obool, type,
    aa_a_bool : (fun_a_bool * a2) > bool).

tff(sy_c_aa_001T__a_001t__Real__Oreal, type,
    aa_a_real : (fun_a_real * a2) > real).

tff(sy_c_aa_001T__a_001t__fun_IT__a_Mt__HOL__Obool_J, type,
    aa_a_fun_a_bool : (fun_a_fun_a_bool * a2) > fun_a_bool).

tff(sy_c_aa_001T__a_001t__fun_IT__a_Mt__Real__Oreal_J, type,
    aa_a_fun_a_real : (fun_a_fun_a_real * a2) > fun_a_real).

tff(sy_c_aa_001T__a_001t__fun_It__Nat__Onat_MT__b_J, type,
    aa_a_fun_nat_b : (fun_a_fun_nat_b * a2) > fun_nat_b).

tff(sy_c_aa_001T__a_001t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    aa_a_fun_set_a_bool : (fun_a_fun_set_a_bool * a2) > fun_set_a_bool).

tff(sy_c_aa_001T__a_001t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J_J, type,
    aa_a_f2048418095a_bool : (fun_a_1515919686a_bool * a2) > fun_se590241323a_bool).

tff(sy_c_aa_001T__b_001T__a, type,
    aa_b_a : (fun_b_a * b) > a2).

tff(sy_c_aa_001T__b_001t__HOL__Obool, type,
    aa_b_bool : (fun_b_bool * b) > bool).

tff(sy_c_aa_001T__b_001t__fun_IT__a_MT__b_J, type,
    aa_b_fun_a_b : (fun_b_fun_a_b * b) > fun_a_b).

tff(sy_c_aa_001T__b_001t__fun_IT__b_Mt__HOL__Obool_J, type,
    aa_b_fun_b_bool : (fun_b_fun_b_bool * b) > fun_b_bool).

tff(sy_c_aa_001T__b_001t__fun_It__Set__Oset_IT__b_J_Mt__HOL__Obool_J, type,
    aa_b_fun_set_b_bool : (fun_b_fun_set_b_bool * b) > fun_set_b_bool).

tff(sy_c_aa_001T__b_001t__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__HOL__Obool_J_J, type,
    aa_b_f1778814956b_bool : (fun_b_1705634051b_bool * b) > fun_se874411177b_bool).

tff(sy_c_aa_001T__c_001t__HOL__Obool, type,
    aa_c_bool : (fun_c_bool * c) > bool).

tff(sy_c_aa_001T__c_001t__fun_IT__c_Mt__HOL__Obool_J, type,
    aa_c_fun_c_bool : (fun_c_fun_c_bool * c) > fun_c_bool).

tff(sy_c_aa_001t__Nat__Onat_001T__a, type,
    aa_nat_a : (fun_nat_a * nat) > a2).

tff(sy_c_aa_001t__Nat__Onat_001T__b, type,
    aa_nat_b : (fun_nat_b * nat) > b).

tff(sy_c_aa_001t__Nat__Onat_001t__fun_IT__a_MT__b_J, type,
    aa_nat_fun_a_b : (fun_nat_fun_a_b * nat) > fun_a_b).

tff(sy_c_aa_001t__Real__Oreal_001t__HOL__Obool, type,
    aa_real_bool : (fun_real_bool * real) > bool).

tff(sy_c_aa_001t__Real__Oreal_001t__fun_It__Real__Oreal_Mt__HOL__Obool_J, type,
    aa_rea628360026l_bool : (fun_re589487345l_bool * real) > fun_real_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__HOL__Obool, type,
    aa_set_a_bool : (fun_set_a_bool * set_a2) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_IT__a_Mt__HOL__Obool_J, type,
    aa_set_a_fun_a_bool : (fun_set_a_fun_a_bool * set_a2) > fun_a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    aa_set1122887114a_bool : (fun_se1296151905a_bool * set_a2) > fun_set_a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J, type,
    aa_set1454015380a_bool : (fun_se590241323a_bool * set_a2) > fun_set_set_a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J, type,
    aa_set18515193a_bool : (fun_se471244048a_bool * set_a2) > fun_se858012459a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__HOL__Obool_J_J_J_J, type,
    aa_set406949253b_bool : (fun_se133803932b_bool * set_a2) > fun_se1552047031b_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J_J_J_J, type,
    aa_set630445216a_bool : (fun_se857368887a_bool * set_a2) > fun_se141744850a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__b_J_Mt__fun_It__fun_IT__b_Mt__fun_IT__b_Mt__Real__Oreal_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J_J_J_J, type,
    aa_set1938247399a_bool : (fun_se1694933502a_bool * set_a2) > fun_se2005891097a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__fun_IT__a_Mt__fun_IT__a_Mt__Real__Oreal_J_J_Mt__HOL__Obool_J, type,
    aa_set115687580l_bool : (fun_se422218035l_bool * set_a2) > fun_fu2111547854l_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__fun_IT__a_Mt__fun_IT__a_Mt__Real__Oreal_J_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J, type,
    aa_set1186796539_set_a : (fun_se801188922_set_a * set_a2) > fun_fu1297279561_set_a).

tff(sy_c_aa_001t__Set__Oset_IT__b_J_001t__HOL__Obool, type,
    aa_set_b_bool : (fun_set_b_bool * set_b) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__b_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__HOL__Obool_J, type,
    aa_set2083998098b_bool : (fun_se874411177b_bool * set_b) > fun_set_set_b_bool).

tff(sy_c_aa_001t__Set__Oset_IT__b_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__HOL__Obool_J_J, type,
    aa_set1725488881b_bool : (fun_se2143152776b_bool * set_b) > fun_se1751821412b_bool).

tff(sy_c_aa_001t__Set__Oset_IT__b_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J_J, type,
    aa_set551360780a_bool : (fun_se1351161635a_bool * set_b) > fun_se1655151231a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__b_J_001t__fun_It__fun_IT__b_Mt__fun_IT__b_Mt__Real__Oreal_J_J_Mt__HOL__Obool_J, type,
    aa_set111032793l_bool : (fun_se585393008l_bool * set_b) > fun_fu419852236l_bool).

tff(sy_c_aa_001t__Set__Oset_IT__b_J_001t__fun_It__fun_IT__b_Mt__fun_IT__b_Mt__Real__Oreal_J_J_Mt__Set__Oset_It__Set__Oset_IT__b_J_J_J, type,
    aa_set1487575039_set_b : (fun_se920280766_set_b * set_b) > fun_fu150939468_set_b).

tff(sy_c_aa_001t__Set__Oset_IT__b_J_001t__fun_It__fun_IT__b_Mt__fun_IT__b_Mt__Real__Oreal_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J_J, type,
    aa_set2055091539a_bool : (fun_se1490760170a_bool * set_b) > fun_fu2038073158a_bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__HOL__Obool, type,
    aa_set_set_a_bool : (fun_set_set_a_bool * set_set_a) > bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    aa_set2012777364a_bool : (fun_se858012459a_bool * set_set_a) > fun_set_a_bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__HOL__Obool_J_J_J, type,
    aa_set124101152b_bool : (fun_se1552047031b_bool * set_set_a) > fun_se2143152776b_bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J_J_J, type,
    aa_set1858498235a_bool : (fun_se141744850a_bool * set_set_a) > fun_se1351161635a_bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__fun_It__Set__Oset_IT__b_J_Mt__fun_It__fun_IT__b_Mt__fun_IT__b_Mt__Real__Oreal_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J_J_J, type,
    aa_set1193872770a_bool : (fun_se2005891097a_bool * set_set_a) > fun_se1490760170a_bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__b_J_J_001t__HOL__Obool, type,
    aa_set_set_b_bool : (fun_set_set_b_bool * set_set_b) > bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__b_J_J_001t__fun_It__fun_IT__a_MT__b_J_Mt__HOL__Obool_J, type,
    aa_set1716771277b_bool : (fun_se1751821412b_bool * set_set_b) > fun_fun_a_b_bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__b_J_J_001t__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J, type,
    aa_set608605544a_bool : (fun_se1655151231a_bool * set_set_b) > fun_fu798682257a_bool).

tff(sy_c_aa_001t__fun_IT__a_MT__b_J_001t__HOL__Obool, type,
    aa_fun_a_b_bool : (fun_fun_a_b_bool * fun_a_b) > bool).

tff(sy_c_aa_001t__fun_IT__a_MT__b_J_001t__fun_IT__a_Mt__HOL__Obool_J, type,
    aa_fun1262135290a_bool : (fun_fu798682257a_bool * fun_a_b) > fun_a_bool).

tff(sy_c_aa_001t__fun_IT__a_MT__b_J_001t__fun_It__fun_IT__a_MT__b_J_Mt__HOL__Obool_J, type,
    aa_fun1154799550b_bool : (fun_fu370395733b_bool * fun_a_b) > fun_fun_a_b_bool).

tff(sy_c_aa_001t__fun_IT__a_MT__b_J_001t__fun_It__fun_It__Nat__Onat_MT__a_J_Mt__fun_It__Nat__Onat_MT__b_J_J, type,
    aa_fun899515084_nat_b : (fun_fu9004939_nat_b * fun_a_b) > fun_fu447973268_nat_b).

tff(sy_c_aa_001t__fun_IT__a_Mt__HOL__Obool_J_001t__HOL__Obool, type,
    aa_fun_a_bool_bool : (fun_fun_a_bool_bool * fun_a_bool) > bool).

tff(sy_c_aa_001t__fun_IT__a_Mt__HOL__Obool_J_001t__Set__Oset_IT__a_J, type,
    aa_fun_a_bool_set_a : (fun_fun_a_bool_set_a * fun_a_bool) > set_a2).

tff(sy_c_aa_001t__fun_IT__a_Mt__HOL__Obool_J_001t__fun_It__fun_IT__a_Mt__HOL__Obool_J_Mt__HOL__Obool_J, type,
    aa_fun1584535710l_bool : (fun_fu647214445l_bool * fun_a_bool) > fun_fun_a_bool_bool).

tff(sy_c_aa_001t__fun_IT__a_Mt__fun_IT__a_Mt__Real__Oreal_J_J_001t__HOL__Obool, type,
    aa_fun2145848247l_bool : (fun_fu2111547854l_bool * fun_a_fun_a_real) > bool).

tff(sy_c_aa_001t__fun_IT__a_Mt__fun_IT__a_Mt__Real__Oreal_J_J_001t__Set__Oset_It__Set__Oset_IT__a_J_J, type,
    aa_fun1779178634_set_a : (fun_fu1297279561_set_a * fun_a_fun_a_real) > set_set_a).

tff(sy_c_aa_001t__fun_IT__b_Mt__fun_IT__b_Mt__Real__Oreal_J_J_001t__HOL__Obool, type,
    aa_fun454152629l_bool : (fun_fu419852236l_bool * fun_b_fun_b_real) > bool).

tff(sy_c_aa_001t__fun_IT__b_Mt__fun_IT__b_Mt__Real__Oreal_J_J_001t__Set__Oset_It__Set__Oset_IT__b_J_J, type,
    aa_fun326748685_set_b : (fun_fu150939468_set_b * fun_b_fun_b_real) > set_set_b).

tff(sy_c_aa_001t__fun_IT__b_Mt__fun_IT__b_Mt__Real__Oreal_J_J_001t__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J, type,
    aa_fun908170799a_bool : (fun_fu2038073158a_bool * fun_b_fun_b_real) > fun_fu798682257a_bool).

tff(sy_c_aa_001t__fun_It__Nat__Onat_MT__a_J_001t__fun_IT__a_Mt__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J_J_J, type,
    aa_fun1439531453a_bool : (fun_fu1827961940a_bool * fun_nat_a) > fun_a_1515919686a_bool).

tff(sy_c_aa_001t__fun_It__Nat__Onat_MT__a_J_001t__fun_It__Nat__Onat_MT__b_J, type,
    aa_fun890308309_nat_b : (fun_fu447973268_nat_b * fun_nat_a) > fun_nat_b).

tff(sy_c_aa_001t__fun_It__Nat__Onat_MT__b_J_001t__fun_IT__b_Mt__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__HOL__Obool_J_J_J, type,
    aa_fun408534585b_bool : (fun_fu874162768b_bool * fun_nat_b) > fun_b_1705634051b_bool).

tff(sy_c_aa_001t__fun_It__Nat__Onat_Mt__fun_IT__a_MT__b_J_J_001t__fun_IT__a_Mt__fun_It__Nat__Onat_MT__b_J_J, type,
    aa_fun1860798668_nat_b : (fun_fu920988683_nat_b * fun_nat_fun_a_b) > fun_a_fun_nat_b).

tff(sy_c_fFalse, type,
    fFalse : bool).

tff(sy_c_fTrue, type,
    fTrue : bool).

tff(sy_c_member_001T__a, type,
    member_a : fun_a_fun_set_a_bool).

tff(sy_c_member_001T__b, type,
    member_b : fun_b_fun_set_b_bool).

tff(sy_c_member_001t__Set__Oset_IT__a_J, type,
    member_set_a : fun_se590241323a_bool).

tff(sy_c_pp, type,
    pp : bool > $o).


% Relevant facts (69)

tff(fact_0_Theorem__21__3__converse__metric, axiom,
    ((![B : $i, A : $i, X : set_a2, D : fun_a_fun_a_real, Y : set_b, TY : set_set_b, F : fun_a_b]: (pp(aa_fun2145848247l_bool(aa_set115687580l_bool(top1_t1666180655c_on_a, X), D)) => (pp(aa_set_set_b_bool(aa_set2083998098b_bool(top1_i235996829y_on_b, Y), TY)) => ((![X2 : a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X2), X)) => pp(aa_set_b_bool(aa_b_fun_set_b_bool(member_b, aa_a_b(F, X2)), Y)))) => ((![S : fun_nat_a, X2 : a2]: (pp(aa_set_set_a_bool(aa_set1454015380a_bool(aa_a_f2048418095a_bool(aa_fun1439531453a_bool(top1_s1653822099o_on_a, S), X2), X), aa_fun1779178634_set_a(aa_set1186796539_set_a(top1_t1018579774y_on_a, X), D))) => pp(aa_set_set_b_bool(aa_set2083998098b_bool(aa_b_f1778814956b_bool(aa_fun408534585b_bool(top1_s1653822100o_on_b, aa_fun890308309_nat_b(aa_fun899515084_nat_b(aTP_Lamm_ab, F), S)), aa_a_b(F, X2)), Y), TY)))) => pp(aa_fun_a_b_bool(aa_set1716771277b_bool(aa_set1725488881b_bool(aa_set124101152b_bool(aa_set406949253b_bool(top1_t1121318858on_a_b, X), aa_fun1779178634_set_a(aa_set1186796539_set_a(top1_t1018579774y_on_a, X), D)), Y), TY), F))))))))). % Theorem_21_3_converse_metric

tff(fact_1_Theorem__21__3_I1_J, axiom,
    ((![A : $i, B : $i, X : set_a2, TX : set_set_a, Y : set_b, TY : set_set_b, F : fun_a_b]: (pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_i235996828y_on_a, X), TX)) => (pp(aa_set_set_b_bool(aa_set2083998098b_bool(top1_i235996829y_on_b, Y), TY)) => ((![X2 : a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X2), X)) => pp(aa_set_b_bool(aa_b_fun_set_b_bool(member_b, aa_a_b(F, X2)), Y)))) => (pp(aa_fun_a_b_bool(aa_set1716771277b_bool(aa_set1725488881b_bool(aa_set124101152b_bool(aa_set406949253b_bool(top1_t1121318858on_a_b, X), TX), Y), TY), F)) => (![S2 : fun_nat_a, X3 : a2]: (pp(aa_set_set_a_bool(aa_set1454015380a_bool(aa_a_f2048418095a_bool(aa_fun1439531453a_bool(top1_s1653822099o_on_a, S2), X3), X), TX)) => pp(aa_set_set_b_bool(aa_set2083998098b_bool(aa_b_f1778814956b_bool(aa_fun408534585b_bool(top1_s1653822100o_on_b, aa_fun890308309_nat_b(aa_fun899515084_nat_b(aTP_Lamm_ab, F), S2)), aa_a_b(F, X3)), Y), TY))))))))))). % Theorem_21_3(1)

tff(fact_2_Theorem__21__3__forward, axiom,
    ((![A : $i, B : $i, X : set_a2, TX : set_set_a, Y : set_b, TY : set_set_b, F : fun_a_b, S3 : fun_nat_a, X4 : a2]: (pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_i235996828y_on_a, X), TX)) => (pp(aa_set_set_b_bool(aa_set2083998098b_bool(top1_i235996829y_on_b, Y), TY)) => (pp(aa_fun_a_b_bool(aa_set1716771277b_bool(aa_set1725488881b_bool(aa_set124101152b_bool(aa_set406949253b_bool(top1_t1121318858on_a_b, X), TX), Y), TY), F)) => (pp(aa_set_set_a_bool(aa_set1454015380a_bool(aa_a_f2048418095a_bool(aa_fun1439531453a_bool(top1_s1653822099o_on_a, S3), X4), X), TX)) => pp(aa_set_set_b_bool(aa_set2083998098b_bool(aa_b_f1778814956b_bool(aa_fun408534585b_bool(top1_s1653822100o_on_b, aa_fun890308309_nat_b(aa_fun899515084_nat_b(aTP_Lamm_ab, F), S3)), aa_a_b(F, X4)), Y), TY))))))))). % Theorem_21_3_forward

tff(fact_3_top1__metric__topology__on__is__topology__on, axiom,
    ((![A : $i, X : set_a2, D : fun_a_fun_a_real]: (pp(aa_fun2145848247l_bool(aa_set115687580l_bool(top1_t1666180655c_on_a, X), D)) => pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_i235996828y_on_a, X), aa_fun1779178634_set_a(aa_set1186796539_set_a(top1_t1018579774y_on_a, X), D))))))). % top1_metric_topology_on_is_topology_on

tff(fact_4_metric__topology__open__sub, axiom,
    ((![A : $i, X : set_a2, D : fun_a_fun_a_real, U : set_a2]: (pp(aa_fun2145848247l_bool(aa_set115687580l_bool(top1_t1666180655c_on_a, X), D)) => (pp(aa_set_set_a_bool(aa_set1454015380a_bool(member_set_a, U), aa_fun1779178634_set_a(aa_set1186796539_set_a(top1_t1018579774y_on_a, X), D))) => pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, U), X))))))). % metric_topology_open_sub

tff(fact_5_Theorem__18__2_I1_J, axiom,
    ((![A : $i, B : $i, X : set_a2, TX : set_set_a, Y : set_b, TY : set_set_b, Z : set_b, TZ : set_set_b]: (pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_i235996828y_on_a, X), TX)) => (pp(aa_set_set_b_bool(aa_set2083998098b_bool(top1_i235996829y_on_b, Y), TY)) => (pp(aa_set_set_b_bool(aa_set2083998098b_bool(top1_i235996829y_on_b, Z), TZ)) => (![X3 : b]: (pp(aa_set_b_bool(aa_b_fun_set_b_bool(member_b, X3), Y)) => pp(aa_fun_a_b_bool(aa_set1716771277b_bool(aa_set1725488881b_bool(aa_set124101152b_bool(aa_set406949253b_bool(top1_t1121318858on_a_b, X), TX), Y), TY), aa_b_fun_a_b(aTP_Lamm_ac, X3))))))))))). % Theorem_18_2(1)

tff(fact_6_const__fun, axiom,
    ((![A : $i, B : $i, X : set_a2, TX : set_set_a, Y : set_b, TY : set_set_b, Z : set_b, TZ : set_set_b]: (pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_i235996828y_on_a, X), TX)) => (pp(aa_set_set_b_bool(aa_set2083998098b_bool(top1_i235996829y_on_b, Y), TY)) => (pp(aa_set_set_b_bool(aa_set2083998098b_bool(top1_i235996829y_on_b, Z), TZ)) => (![X3 : b]: (pp(aa_set_b_bool(aa_b_fun_set_b_bool(member_b, X3), Y)) => pp(aa_fun_a_b_bool(aa_set1716771277b_bool(aa_set1725488881b_bool(aa_set124101152b_bool(aa_set406949253b_bool(top1_t1121318858on_a_b, X), TX), Y), TY), aa_b_fun_a_b(aTP_Lamm_ac, X3))))))))))). % const_fun

tff(fact_7_top1__continuous__map__on__const, axiom,
    ((![A : $i, B : $i, A2 : set_a2, TA : set_set_a, X : set_b, TX : set_set_b, X0 : b]: (pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_i235996828y_on_a, A2), TA)) => (pp(aa_set_set_b_bool(aa_set2083998098b_bool(top1_i235996829y_on_b, X), TX)) => (pp(aa_set_b_bool(aa_b_fun_set_b_bool(member_b, X0), X)) => pp(aa_fun_a_b_bool(aa_set1716771277b_bool(aa_set1725488881b_bool(aa_set124101152b_bool(aa_set406949253b_bool(top1_t1121318858on_a_b, A2), TA), X), TX), aa_b_fun_a_b(aTP_Lamm_ac, X0))))))))). % top1_continuous_map_on_const

tff(fact_8_subsetI, axiom,
    ((![A : $i, A2 : set_a2, B2 : set_a2]: ((![X2 : a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X2), A2)) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X2), B2)))) => pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B2)))))). % subsetI

tff(fact_9_equalityI, axiom,
    ((![A : $i, A2 : set_a2, B2 : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B2)) => (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, B2), A2)) => (A2 = B2)))))). % equalityI

tff(fact_10_subset__antisym, axiom,
    ((![A : $i, A2 : set_a2, B2 : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B2)) => (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, B2), A2)) => (A2 = B2)))))). % subset_antisym

tff(fact_11_order_Orefl, axiom,
    ((![A : $i]: (preorder(a2) => (![A3 : a2]: pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), A3))))))). % order.refl

tff(fact_12_dual__order_Orefl, axiom,
    ((![A : $i]: (preorder(a2) => (![A3 : a2]: pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), A3))))))). % dual_order.refl

tff(fact_13_order__refl, axiom,
    ((![A : $i]: (preorder(a2) => (![X4 : a2]: pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X4), X4))))))). % order_refl

tff(fact_14_less__eq__set__def, axiom,
    ((![A : $i, A2 : set_a2, B2 : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B2)) <=> pp(aa_fun_a_bool_bool(aa_fun1584535710l_bool(ord_le801610962a_bool, aa_set_a_fun_a_bool(aTP_Lamm_ad, A2)), aa_set_a_fun_a_bool(aTP_Lamm_ad, B2))))))). % less_eq_set_def

tff(fact_15_metric__limit__preserves__le, axiom,
    ((![A : $i, X : set_a2, D : fun_a_fun_a_real, S3 : fun_nat_a, X4 : a2, T : fun_nat_a, Y2 : a2, C : real]: (pp(aa_fun2145848247l_bool(aa_set115687580l_bool(top1_t1666180655c_on_a, X), D)) => (pp(aa_set_set_a_bool(aa_set1454015380a_bool(aa_a_f2048418095a_bool(aa_fun1439531453a_bool(top1_s1653822099o_on_a, S3), X4), X), aa_fun1779178634_set_a(aa_set1186796539_set_a(top1_t1018579774y_on_a, X), D))) => (pp(aa_set_set_a_bool(aa_set1454015380a_bool(aa_a_f2048418095a_bool(aa_fun1439531453a_bool(top1_s1653822099o_on_a, T), Y2), X), aa_fun1779178634_set_a(aa_set1186796539_set_a(top1_t1018579774y_on_a, X), D))) => ((![N : nat]: pp(aa_real_bool(aa_rea628360026l_bool(ord_less_eq_real, C), aa_a_real(aa_a_fun_a_real(D, aa_nat_a(S3, N)), aa_nat_a(T, N))))) => pp(aa_real_bool(aa_rea628360026l_bool(ord_less_eq_real, C), aa_a_real(aa_a_fun_a_real(D, X4), Y2)))))))))). % metric_limit_preserves_le

tff(fact_16_order__antisym__conv, axiom,
    ((![A : $i]: (order(a2) => (![Y2 : a2, X4 : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Y2), X4)) => (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X4), Y2)) <=> (X4 = Y2)))))))). % order_antisym_conv

tff(fact_17_linorder__le__cases, axiom,
    ((![A : $i]: (linorder(a2) => (![X4 : a2, Y2 : a2]: ((~ (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X4), Y2)))) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Y2), X4)))))))). % linorder_le_cases

tff(fact_18_ord__le__eq__subst, axiom,
    ((![A : $i, B : $i]: ((ord(b) & ord(a2)) => (![A3 : a2, B3 : a2, F : fun_a_b, C : b]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3)) => ((aa_a_b(F, B3) = C) => ((![X2 : a2, Y3 : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X2), Y3)) => pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, aa_a_b(F, X2)), aa_a_b(F, Y3))))) => pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, aa_a_b(F, A3)), C)))))))))). % ord_le_eq_subst

tff(fact_19_ord__eq__le__subst, axiom,
    ((![A : $i, B : $i]: ((ord(b) & ord(a2)) => (![A3 : a2, F : fun_b_a, B3 : b, C : b]: ((A3 = aa_b_a(F, B3)) => (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, B3), C)) => ((![X2 : b, Y3 : b]: (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, X2), Y3)) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, aa_b_a(F, X2)), aa_b_a(F, Y3))))) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), aa_b_a(F, C))))))))))). % ord_eq_le_subst

tff(fact_20_linorder__linear, axiom,
    ((![A : $i]: (linorder(a2) => (![X4 : a2, Y2 : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X4), Y2)) | pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Y2), X4)))))))). % linorder_linear

tff(fact_21_order__eq__refl, axiom,
    ((![A : $i]: (preorder(a2) => (![X4 : a2, Y2 : a2]: ((X4 = Y2) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X4), Y2)))))))). % order_eq_refl

tff(fact_22_order__subst2, axiom,
    ((![A : $i, C2 : $i]: ((order(c) & order(a2)) => (![A3 : a2, B3 : a2, F : fun_a_c, C : c]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3)) => (pp(aa_c_bool(aa_c_fun_c_bool(ord_less_eq_c, aa_a_c(F, B3)), C)) => ((![X2 : a2, Y3 : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X2), Y3)) => pp(aa_c_bool(aa_c_fun_c_bool(ord_less_eq_c, aa_a_c(F, X2)), aa_a_c(F, Y3))))) => pp(aa_c_bool(aa_c_fun_c_bool(ord_less_eq_c, aa_a_c(F, A3)), C)))))))))). % order_subst2

tff(fact_23_order__subst1, axiom,
    ((![A : $i, B : $i]: ((order(b) & order(a2)) => (![A3 : a2, F : fun_b_a, B3 : b, C : b]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), aa_b_a(F, B3))) => (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, B3), C)) => ((![X2 : b, Y3 : b]: (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, X2), Y3)) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, aa_b_a(F, X2)), aa_b_a(F, Y3))))) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), aa_b_a(F, C))))))))))). % order_subst1

tff(fact_24_Orderings_Oorder__eq__iff, axiom,
    ((![A : $i]: (order(a2) => (![A3 : a2, B3 : a2]: ((A3 = B3) <=> (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3)) & pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, B3), A3))))))))). % Orderings.order_eq_iff

tff(fact_25_le__fun__def, axiom,
    ((![B : $i, A : $i]: (ord(b) => (![F : fun_a_b, G : fun_a_b]: (pp(aa_fun_a_b_bool(aa_fun1154799550b_bool(ord_less_eq_fun_a_b, F), G)) <=> (![X5 : a2]: pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, aa_a_b(F, X5)), aa_a_b(G, X5)))))))))). % le_fun_def

tff(fact_26_le__funI, axiom,
    ((![B : $i, A : $i]: (ord(b) => (![F : fun_a_b, G : fun_a_b]: ((![X2 : a2]: pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, aa_a_b(F, X2)), aa_a_b(G, X2)))) => pp(aa_fun_a_b_bool(aa_fun1154799550b_bool(ord_less_eq_fun_a_b, F), G)))))))). % le_funI

tff(fact_27_le__funE, axiom,
    ((![B : $i, A : $i]: (ord(b) => (![F : fun_a_b, G : fun_a_b, X4 : a2]: (pp(aa_fun_a_b_bool(aa_fun1154799550b_bool(ord_less_eq_fun_a_b, F), G)) => pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, aa_a_b(F, X4)), aa_a_b(G, X4))))))))). % le_funE

tff(fact_28_le__funD, axiom,
    ((![B : $i, A : $i]: (ord(b) => (![F : fun_a_b, G : fun_a_b, X4 : a2]: (pp(aa_fun_a_b_bool(aa_fun1154799550b_bool(ord_less_eq_fun_a_b, F), G)) => pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, aa_a_b(F, X4)), aa_a_b(G, X4))))))))). % le_funD

tff(fact_29_antisym, axiom,
    ((![A : $i]: (order(a2) => (![A3 : a2, B3 : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3)) => (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, B3), A3)) => (A3 = B3)))))))). % antisym

tff(fact_30_eq__iff, axiom,
    ((![A : $i]: (order(a2) => (![A3 : a2, B3 : a2]: ((A3 = B3) <=> (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3)) & pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, B3), A3))))))))). % eq_iff

tff(fact_31_xt3, axiom,
    ((![B : $i, A : $i]: ((order(a2) & order(b)) => (![B3 : a2, A3 : a2, C : b, F : fun_a_b]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, B3), A3)) => (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, C), aa_a_b(F, B3))) => ((![X2 : a2, Y3 : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Y3), X2)) => pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, aa_a_b(F, Y3)), aa_a_b(F, X2))))) => pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, C), aa_a_b(F, A3))))))))))). % xt3

tff(fact_32_xt2, axiom,
    ((![B : $i, A : $i]: ((order(a2) & ord(b)) => (![F : fun_b_a, B3 : b, A3 : a2, C : b]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, aa_b_a(F, B3)), A3)) => (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, C), B3)) => ((![X2 : b, Y3 : b]: (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, Y3), X2)) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, aa_b_a(F, Y3)), aa_b_a(F, X2))))) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, aa_b_a(F, C)), A3)))))))))). % xt2

tff(fact_33_dual__order_Otrans, axiom,
    ((![A : $i]: (preorder(a2) => (![B3 : a2, A3 : a2, C : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, B3), A3)) => (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, C), B3)) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, C), A3))))))))). % dual_order.trans

tff(fact_34_dual__order_Oantisym, axiom,
    ((![A : $i]: (order(a2) => (![B3 : a2, A3 : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, B3), A3)) => (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3)) => (A3 = B3)))))))). % dual_order.antisym

tff(fact_35_dual__order_Oeq__iff, axiom,
    ((![A : $i]: (order(a2) => (![A3 : a2, B3 : a2]: ((A3 = B3) <=> (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, B3), A3)) & pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3))))))))). % dual_order.eq_iff

tff(fact_36_linorder__wlog, axiom,
    ((![A : $i]: (linorder(a2) => (![P : fun_a_fun_a_bool, A3 : a2, B3 : a2]: ((![A4 : a2, B4 : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A4), B4)) => pp(aa_a_bool(aa_a_fun_a_bool(P, A4), B4)))) => ((![A4 : a2, B4 : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(P, B4), A4)) => pp(aa_a_bool(aa_a_fun_a_bool(P, A4), B4)))) => pp(aa_a_bool(aa_a_fun_a_bool(P, A3), B3))))))))). % linorder_wlog

tff(fact_37_order__trans, axiom,
    ((![A : $i]: (preorder(a2) => (![X4 : a2, Y2 : a2, Z2 : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X4), Y2)) => (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Y2), Z2)) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X4), Z2))))))))). % order_trans

tff(fact_38_order_Otrans, axiom,
    ((![A : $i]: (preorder(a2) => (![A3 : a2, B3 : a2, C : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3)) => (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, B3), C)) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), C))))))))). % order.trans

tff(fact_39_order__antisym, axiom,
    ((![A : $i]: (order(a2) => (![X4 : a2, Y2 : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X4), Y2)) => (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Y2), X4)) => (X4 = Y2)))))))). % order_antisym

tff(fact_40_order_Oantisym, axiom,
    ((![A : $i]: (order(a2) => (![A3 : a2, B3 : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3)) => (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, B3), A3)) => (A3 = B3)))))))). % order.antisym

tff(fact_41_ord__le__eq__trans, axiom,
    ((![A : $i]: (ord(a2) => (![A3 : a2, B3 : a2, C : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3)) => ((B3 = C) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), C))))))))). % ord_le_eq_trans

tff(fact_42_ord__eq__le__trans, axiom,
    ((![A : $i]: (ord(a2) => (![A3 : a2, B3 : a2, C : a2]: ((A3 = B3) => (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, B3), C)) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), C))))))))). % ord_eq_le_trans

tff(fact_43_order__class_Oorder__eq__iff, axiom,
    ((![A : $i]: (order(a2) => (![X4 : a2, Y2 : a2]: ((X4 = Y2) <=> (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X4), Y2)) & pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Y2), X4))))))))). % order_class.order_eq_iff

tff(fact_44_order_Oeq__iff, axiom,
    ((![A : $i]: (order(a2) => (![A3 : a2, B3 : a2]: ((A3 = B3) <=> (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3)) & pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, B3), A3))))))))). % order.eq_iff

tff(fact_45_mem__Collect__eq, axiom,
    ((![A : $i, A3 : a2, P : fun_a_bool]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, A3), aa_fun_a_bool_set_a(collect_a, P))) <=> pp(aa_a_bool(P, A3)))))). % mem_Collect_eq

tff(fact_46_Collect__mem__eq, axiom,
    ((![A : $i, A2 : set_a2]: (aa_fun_a_bool_set_a(collect_a, aa_set_a_fun_a_bool(aTP_Lamm_ad, A2)) = A2)))). % Collect_mem_eq

tff(fact_47_Collect__cong, axiom,
    ((![A : $i, P : fun_a_bool, Q : fun_a_bool]: ((![X2 : a2]: (pp(aa_a_bool(P, X2)) <=> pp(aa_a_bool(Q, X2)))) => (aa_fun_a_bool_set_a(collect_a, P) = aa_fun_a_bool_set_a(collect_a, Q)))))). % Collect_cong

tff(fact_48_mem__simps_I7_J, axiom,
    ((![A : $i, A3 : a2, P : fun_a_bool]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, A3), aa_fun_a_bool_set_a(collect_a, P))) <=> pp(aa_a_bool(P, A3)))))). % mem_simps(7)

tff(fact_49_antisym__conv, axiom,
    ((![A : $i]: (order(a2) => (![Y2 : a2, X4 : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Y2), X4)) => (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X4), Y2)) <=> (X4 = Y2)))))))). % antisym_conv

tff(fact_50_le__cases3, axiom,
    ((![A : $i]: (linorder(a2) => (![X4 : a2, Y2 : a2, Z2 : a2]: ((pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X4), Y2)) => (~ (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Y2), Z2))))) => ((pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Y2), X4)) => (~ (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X4), Z2))))) => ((pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X4), Z2)) => (~ (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Z2), Y2))))) => ((pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Z2), Y2)) => (~ (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Y2), X4))))) => ((pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Y2), Z2)) => (~ (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Z2), X4))))) => (~ ((pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Z2), X4)) => (~ (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X4), Y2))))))))))))))))). % le_cases3

tff(fact_51_le__cases, axiom,
    ((![A : $i]: (linorder(a2) => (![X4 : a2, Y2 : a2]: ((~ (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X4), Y2)))) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Y2), X4)))))))). % le_cases

tff(fact_52_eq__refl, axiom,
    ((![A : $i]: (preorder(a2) => (![X4 : a2, Y2 : a2]: ((X4 = Y2) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X4), Y2)))))))). % eq_refl

tff(fact_53_nle__le, axiom,
    ((![A : $i]: (linorder(a2) => (![A3 : a2, B3 : a2]: ((~ (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3)))) <=> (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, B3), A3)) & (B3 != A3)))))))). % nle_le

tff(fact_54_linear, axiom,
    ((![A : $i]: (linorder(a2) => (![X4 : a2, Y2 : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X4), Y2)) | pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Y2), X4)))))))). % linear

tff(fact_55_order__trans__rules_I7_J, axiom,
    ((![A : $i, C2 : $i]: ((order(c) & order(a2)) => (![A3 : a2, B3 : a2, F : fun_a_c, C : c]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3)) => (pp(aa_c_bool(aa_c_fun_c_bool(ord_less_eq_c, aa_a_c(F, B3)), C)) => ((![X2 : a2, Y3 : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X2), Y3)) => pp(aa_c_bool(aa_c_fun_c_bool(ord_less_eq_c, aa_a_c(F, X2)), aa_a_c(F, Y3))))) => pp(aa_c_bool(aa_c_fun_c_bool(ord_less_eq_c, aa_a_c(F, A3)), C)))))))))). % order_trans_rules(7)

tff(fact_56_order__trans__rules_I8_J, axiom,
    ((![A : $i, B : $i]: ((order(b) & order(a2)) => (![A3 : a2, F : fun_b_a, B3 : b, C : b]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), aa_b_a(F, B3))) => (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, B3), C)) => ((![X2 : b, Y3 : b]: (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, X2), Y3)) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, aa_b_a(F, X2)), aa_b_a(F, Y3))))) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), aa_b_a(F, C))))))))))). % order_trans_rules(8)

tff(fact_57_order__trans__rules_I9_J, axiom,
    ((![A : $i, B : $i]: ((ord(b) & ord(a2)) => (![A3 : a2, B3 : a2, F : fun_a_b, C : b]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3)) => ((aa_a_b(F, B3) = C) => ((![X2 : a2, Y3 : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X2), Y3)) => pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, aa_a_b(F, X2)), aa_a_b(F, Y3))))) => pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, aa_a_b(F, A3)), C)))))))))). % order_trans_rules(9)

tff(fact_58_order__trans__rules_I10_J, axiom,
    ((![A : $i, B : $i]: ((ord(b) & ord(a2)) => (![A3 : a2, F : fun_b_a, B3 : b, C : b]: ((A3 = aa_b_a(F, B3)) => (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, B3), C)) => ((![X2 : b, Y3 : b]: (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, X2), Y3)) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, aa_b_a(F, X2)), aa_b_a(F, Y3))))) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), aa_b_a(F, C))))))))))). % order_trans_rules(10)

tff(fact_59_order__trans__rules_I23_J, axiom,
    ((![A : $i]: (preorder(a2) => (![X4 : a2, Y2 : a2, Z2 : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X4), Y2)) => (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Y2), Z2)) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X4), Z2))))))))). % order_trans_rules(23)

tff(fact_60_order__trans__rules_I24_J, axiom,
    ((![A : $i]: (order(a2) => (![A3 : a2, B3 : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3)) => (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, B3), A3)) => (A3 = B3)))))))). % order_trans_rules(24)

tff(fact_61_order__trans__rules_I25_J, axiom,
    ((![A : $i]: (ord(a2) => (![A3 : a2, B3 : a2, C : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3)) => ((B3 = C) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), C))))))))). % order_trans_rules(25)

tff(fact_62_order__trans__rules_I26_J, axiom,
    ((![A : $i]: (ord(a2) => (![A3 : a2, B3 : a2, C : a2]: ((A3 = B3) => (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, B3), C)) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), C))))))))). % order_trans_rules(26)

tff(fact_63_basic__trans__rules_I7_J, axiom,
    ((![A : $i, C2 : $i]: ((order(c) & order(a2)) => (![A3 : a2, B3 : a2, F : fun_a_c, C : c]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3)) => (pp(aa_c_bool(aa_c_fun_c_bool(ord_less_eq_c, aa_a_c(F, B3)), C)) => ((![X2 : a2, Y3 : a2]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X2), Y3)) => pp(aa_c_bool(aa_c_fun_c_bool(ord_less_eq_c, aa_a_c(F, X2)), aa_a_c(F, Y3))))) => pp(aa_c_bool(aa_c_fun_c_bool(ord_less_eq_c, aa_a_c(F, A3)), C)))))))))). % basic_trans_rules(7)

tff(fact_64_ATP_Olambda__1, axiom,
    ((![A : $i, Uu : set_a2, Uua : a2]: (pp(aa_a_bool(aa_set_a_fun_a_bool(aTP_Lamm_ad, Uu), Uua)) <=> pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, Uua), Uu)))))). % ATP.lambda_1

tff(fact_65_ATP_Olambda__2, axiom,
    ((![B : $i, A : $i, Uu : fun_nat_fun_a_b, Uua : a2, Uub : nat]: (aa_nat_b(aa_a_fun_nat_b(aa_fun1860798668_nat_b(aTP_Lamm_a, Uu), Uua), Uub) = aa_a_b(aa_nat_fun_a_b(Uu, Uub), Uua))))). % ATP.lambda_2

tff(fact_66_ATP_Olambda__3, axiom,
    ((![B : $i, A : $i, Uu : fun_a_b, Uua : fun_nat_a, Uub : nat]: (aa_nat_b(aa_fun890308309_nat_b(aa_fun899515084_nat_b(aTP_Lamm_ab, Uu), Uua), Uub) = aa_a_b(Uu, aa_nat_a(Uua, Uub)))))). % ATP.lambda_3

tff(fact_67_ATP_Olambda__4, axiom,
    ((![B : $i, A : $i, Uu : set_a2, Uua : set_set_a, Uub : set_b, Uuc : fun_b_fun_b_real, Uud : fun_a_b, Uue : a2]: (pp(aa_a_bool(aa_fun1262135290a_bool(aa_fun908170799a_bool(aa_set2055091539a_bool(aa_set1193872770a_bool(aa_set1938247399a_bool(aTP_Lamm_aa, Uu), Uua), Uub), Uuc), Uud), Uue)) <=> (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, Uue), Uu)) & pp(aa_a_bool(aa_fun1262135290a_bool(aa_set608605544a_bool(aa_set551360780a_bool(aa_set1858498235a_bool(aa_set630445216a_bool(top1_t331991105on_a_b, Uu), Uua), Uub), aa_fun326748685_set_b(aa_set1487575039_set_b(top1_t1018579775y_on_b, Uub), Uuc)), Uud), Uue))))))). % ATP.lambda_4

tff(fact_68_ATP_Olambda__5, axiom,
    ((![A : $i, B : $i, Uu : b, Uua : a2]: (aa_a_b(aa_b_fun_a_b(aTP_Lamm_ac, Uu), Uua) = Uu)))). % ATP.lambda_5


% Type constructors (18)

tff(tcon_fun___Orderings_Opreorder, axiom,
    ((![A5 : $i, A6 : $i]: (preorder(a) => preorder(fun_a_a))))).

tff(tcon_fun___Orderings_Oorder, axiom,
    ((![A5 : $i, A6 : $i]: (order(a) => order(fun_a_a))))).

tff(tcon_fun___Orderings_Oord, axiom,
    ((![A5 : $i, A6 : $i]: (ord(a) => ord(fun_a_a))))).

tff(tcon_Nat_Onat___Orderings_Opreorder_1, axiom,
    (preorder(nat))).

tff(tcon_Nat_Onat___Orderings_Olinorder, axiom,
    (linorder(nat))).

tff(tcon_Nat_Onat___Orderings_Oorder_2, axiom,
    (order(nat))).

tff(tcon_Nat_Onat___Orderings_Oord_3, axiom,
    (ord(nat))).

tff(tcon_Set_Oset___Orderings_Opreorder_4, axiom,
    ((![A5 : $i]: preorder(set_a)))).

tff(tcon_Set_Oset___Orderings_Oorder_5, axiom,
    ((![A5 : $i]: order(set_a)))).

tff(tcon_Set_Oset___Orderings_Oord_6, axiom,
    ((![A5 : $i]: ord(set_a)))).

tff(tcon_HOL_Obool___Orderings_Opreorder_7, axiom,
    (preorder(bool))).

tff(tcon_HOL_Obool___Orderings_Olinorder_8, axiom,
    (linorder(bool))).

tff(tcon_HOL_Obool___Orderings_Oorder_9, axiom,
    (order(bool))).

tff(tcon_HOL_Obool___Orderings_Oord_10, axiom,
    (ord(bool))).

tff(tcon_Real_Oreal___Orderings_Opreorder_11, axiom,
    (preorder(real))).

tff(tcon_Real_Oreal___Orderings_Olinorder_12, axiom,
    (linorder(real))).

tff(tcon_Real_Oreal___Orderings_Oorder_13, axiom,
    (order(real))).

tff(tcon_Real_Oreal___Orderings_Oord_14, axiom,
    (ord(real))).


% Helper facts (2)

tff(help_pp_2_1_U, axiom,
    (pp(fTrue))).

tff(help_pp_1_1_U, axiom,
    ((~ (pp(fFalse))))).


% Conjectures (7)

tff(conj_0, hypothesis,
    ((![A : $i, X : set_a2, TX : set_set_a]: pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_i235996828y_on_a, X), TX))))).

tff(conj_1, hypothesis,
    ((![A : $i, TX : set_set_a, X : set_a2, X3 : set_a2]: (pp(aa_set_set_a_bool(aa_set1454015380a_bool(member_set_a, X3), TX)) => pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, X3), X)))))).

tff(conj_2, hypothesis,
    ((![A : $i, X : set_a2, TX : set_set_a]: pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_C1278066831e_on_a, X), TX))))).

tff(conj_3, hypothesis,
    ((![B : $i, Y : set_b, D : fun_b_fun_b_real]: pp(aa_fun454152629l_bool(aa_set111032793l_bool(top1_t1666180656c_on_b, Y), D))))).

tff(conj_4, hypothesis,
    ((![A : $i, B : $i, X : set_a2, TX : set_set_a, Y : set_b, D : fun_b_fun_b_real, F : fun_nat_fun_a_b, N2 : nat]: pp(aa_fun_a_b_bool(aa_set1716771277b_bool(aa_set1725488881b_bool(aa_set124101152b_bool(aa_set406949253b_bool(top1_t1121318858on_a_b, X), TX), Y), aa_fun326748685_set_b(aa_set1487575039_set_b(top1_t1018579775y_on_b, Y), D)), aa_nat_fun_a_b(F, N2)))))).

tff(conj_5, hypothesis,
    ((![A : $i, B : $i, X : set_a2, F : fun_nat_fun_a_b, G : fun_a_b, Y : set_b, D : fun_b_fun_b_real, X3 : a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X3), X)) => pp(aa_set_set_b_bool(aa_set2083998098b_bool(aa_b_f1778814956b_bool(aa_fun408534585b_bool(top1_s1653822100o_on_b, aa_a_fun_nat_b(aa_fun1860798668_nat_b(aTP_Lamm_a, F), X3)), aa_a_b(G, X3)), Y), aa_fun326748685_set_b(aa_set1487575039_set_b(top1_t1018579775y_on_b, Y), D))))))).

tff(conj_6, conjecture,
    ((![B : $i, A : $i, X : set_a2, TX : set_set_a, Y : set_b, D : fun_b_fun_b_real, G : fun_a_b]: pp(aa_set_a_bool(aa_set2012777364a_bool(aa_set18515193a_bool(top1_C1617914646n_on_a, X), TX), aa_fun_a_bool_set_a(collect_a, aa_fun1262135290a_bool(aa_fun908170799a_bool(aa_set2055091539a_bool(aa_set1193872770a_bool(aa_set1938247399a_bool(aTP_Lamm_aa, X), TX), Y), D), G))))))).

