% This file was generated by Isabelle (most likely Sledgehammer)
2026-06-02 21:57:21.019

% Could-be-implicit typings (103)

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J_J_J, type,
    fun_se1904574643_set_a : $tType).

tff(ty_n_t__fun_It__Real__Oreal_Mt__fun_It__Real__Oreal_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__Real__Oreal_MT__a_J_J_J_J, type,
    fun_re465290269real_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J_J, type,
    fun_se122506306_set_a : $tType).

tff(ty_n_t__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__Set__Oset_It__Real__Oreal_J_Mt__Set__Oset_IT__a_J_J_J, type,
    fun_fu2039545399_set_a : $tType).

tff(ty_n_t__fun_It__Real__Oreal_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__Real__Oreal_MT__a_J_J_J, type,
    fun_re1692559348real_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J_J, type,
    fun_se590241323a_bool : $tType).

tff(ty_n_t__fun_It__fun_IT__b_MT__a_J_Mt__fun_It__Set__Oset_IT__b_J_Mt__Set__Oset_IT__a_J_J_J, type,
    fun_fu1241503453_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J_J, type,
    fun_se1395821270_set_a : $tType).

tff(ty_n_t__fun_It__Real__Oreal_Mt__fun_It__Real__Oreal_Mt__Set__Oset_It__Real__Oreal_J_J_J, type,
    fun_re1392512436t_real : $tType).

tff(ty_n_t__fun_It__Real__Oreal_Mt__fun_It__Set__Oset_It__Real__Oreal_J_Mt__HOL__Obool_J_J, type,
    fun_re596238651l_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J, type,
    fun_se1296151905a_bool : $tType).

tff(ty_n_t__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__Real__Oreal_MT__a_J_J, type,
    fun_fu1277785163real_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_set_set_a_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J, type,
    fun_set_a_set_set_a : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J_J, type,
    fun_a_1385981984_set_a : $tType).

tff(ty_n_t__fun_It__Real__Oreal_Mt__fun_It__Real__Oreal_Mt__Real__Oreal_J_J, type,
    fun_re785795966l_real : $tType).

tff(ty_n_t__fun_It__Real__Oreal_Mt__fun_It__Real__Oreal_Mt__HOL__Obool_J_J, type,
    fun_re589487345l_bool : $tType).

tff(ty_n_t__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_fun_real_a_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Real__Oreal_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_set_real_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J, type,
    fun_set_set_a_bool : $tType).

tff(ty_n_t__fun_It__Num__Onum_Mt__fun_It__Num__Onum_Mt__HOL__Obool_J_J, type,
    fun_num_fun_num_bool : $tType).

tff(ty_n_t__fun_IT__b_Mt__fun_It__Set__Oset_IT__b_J_Mt__HOL__Obool_J_J, type,
    fun_b_fun_set_b_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J, type,
    fun_a_fun_set_a_bool : $tType).

tff(ty_n_t__fun_It__Real__Oreal_Mt__Set__Oset_It__Real__Oreal_J_J, type,
    fun_real_set_real : $tType).

tff(ty_n_t__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J, type,
    fun_fun_real_a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Real__Oreal_J_Mt__HOL__Obool_J, type,
    fun_set_real_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__b_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_set_b_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_set_a_set_a : $tType).

tff(ty_n_t__fun_It__Num__Onum_Mt__fun_It__Num__Onum_MT__a_J_J, type,
    fun_num_fun_num_a : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_IT__a_Mt__Set__Oset_IT__a_J_J_J, type,
    fun_a_fun_a_set_a : $tType).

tff(ty_n_t__fun_It__fun_It__Real__Oreal_MT__a_J_MT__a_J, type,
    fun_fun_real_a_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__b_J_Mt__HOL__Obool_J, type,
    fun_set_b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    fun_set_a_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_IT__a_Mt__HOL__Obool_J_J, type,
    fun_a_fun_a_bool : $tType).

tff(ty_n_t__Extended____Nonnegative____Real__Oennreal, type,
    extend1728876344nnreal : $tType).

tff(ty_n_t__fun_It__Real__Oreal_Mt__Real__Oreal_J, type,
    fun_real_real : $tType).

tff(ty_n_t__fun_It__Real__Oreal_Mt__HOL__Obool_J, type,
    fun_real_bool : $tType).

tff(ty_n_t__fun_It__Num__Onum_Mt__HOL__Obool_J, type,
    fun_num_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_IT__a_MT__a_J_J, type,
    fun_a_fun_a_a : $tType).

tff(ty_n_t__fun_IT__a_Mt__Set__Oset_IT__a_J_J, type,
    fun_a_set_a : $tType).

tff(ty_n_t__Set__Oset_It__Set__Oset_IT__a_J_J, type,
    set_set_a : $tType).

tff(ty_n_t__fun_It__Real__Oreal_MT__a_J, type,
    fun_real_a : $tType).

tff(ty_n_t__Set__Oset_It__Real__Oreal_J, type,
    set_real : $tType).

tff(ty_n_t__fun_IT__a_Mt__HOL__Obool_J, type,
    fun_a_bool : $tType).

tff(ty_n_t__fun_It__Num__Onum_MT__a_J, type,
    fun_num_a : $tType).

tff(ty_n_t__Code____Numeral__Onatural, type,
    code_natural : $tType).

tff(ty_n_t__Code____Numeral__Ointeger, type,
    code_integer : $tType).

tff(ty_n_t__fun_IT__a__1_MT__a__2_J, type,
    fun_a_a : $tType).

tff(ty_n_t__Set__Oset_IT__a__1_J, type,
    set_a : $tType).

tff(ty_n_t__fun_IT__b_MT__a_J, type,
    fun_b_a : $tType).

tff(ty_n_t__fun_IT__a_MT__a_J, type,
    fun_a_a2 : $tType).

tff(ty_n_t__Set__Oset_IT__b_J, type,
    set_b : $tType).

tff(ty_n_t__Set__Oset_IT__a_J, type,
    set_a2 : $tType).

tff(ty_n_t__Complex__Ocomplex, type,
    complex : $tType).

tff(ty_n_t__Real__Oreal, type,
    real : $tType).

tff(ty_n_t__HOL__Obool, type,
    bool : $tType).

tff(ty_n_t__Num__Onum, type,
    num : $tType).

tff(ty_n_T__a__2, type,
    a : $tType).

tff(ty_n_T__a__1, type,
    a2 : $tType).

tff(ty_n_T__b, type,
    b : $tType).

tff(ty_n_T__a, type,
    a3 : $tType).

tff(sy_cl_Groups_Oordered__cancel__ab__semigroup__add, type,
    ordere223160158up_add : !>[A : $tType]: $o).

tff(sy_cl_Real__Vector__Spaces_Oreal__normed__vector, type,
    real_V55928688vector : !>[A : $tType]: $o).

tff(sy_cl_Groups_Ocanonically__ordered__monoid__add, type,
    canoni770627133id_add : !>[A : $tType]: $o).

tff(sy_cl_Topological__Spaces_Otopological__space, type,
    topolo503727757_space : !>[A : $tType]: $o).

tff(sy_cl_Topological__Spaces_Oopen__uniformity, type,
    topolo254921306ormity : !>[A : $tType]: $o).

tff(sy_cl_Complete__Lattices_Ocomplete__lattice, type,
    comple187826305attice : !>[A : $tType]: $o).

tff(sy_cl_Rings_Olinordered__nonzero__semiring, type,
    linord1659791738miring : !>[A : $tType]: $o).

tff(sy_cl_Groups_Oordered__ab__semigroup__add, type,
    ordere779506340up_add : !>[A : $tType]: $o).

tff(sy_cl_Real__Vector__Spaces_Oreal__vector, type,
    real_V1076094709vector : !>[A : $tType]: $o).

tff(sy_cl_Euclidean__Space_Oeuclidean__space, type,
    euclid925273238_space : !>[A : $tType]: $o).

tff(sy_cl_Groups_Ocancel__comm__monoid__add, type,
    cancel1352612707id_add : !>[A : $tType]: $o).

tff(sy_cl_Rings_Olinordered__ring__strict, type,
    linord581940658strict : !>[A : $tType]: $o).

tff(sy_cl_Groups_Oordered__ab__group__add, type,
    ordered_ab_group_add : !>[A : $tType]: $o).

tff(sy_cl_Inner__Product_Oreal__inner, type,
    inner_real_inner : !>[A : $tType]: $o).

tff(sy_cl_Rings_Osemiring__1__cancel, type,
    semiring_1_cancel : !>[A : $tType]: $o).

tff(sy_cl_Rings_Osemiring__0__cancel, type,
    semiring_0_cancel : !>[A : $tType]: $o).

tff(sy_cl_Rings_Olinordered__semidom, type,
    linordered_semidom : !>[A : $tType]: $o).

tff(sy_cl_Lattices_Osemilattice__inf, type,
    semilattice_inf : !>[A : $tType]: $o).

tff(sy_cl_Groups_Ocomm__monoid__mult, type,
    comm_monoid_mult : !>[A : $tType]: $o).

tff(sy_cl_Groups_Oab__semigroup__add, type,
    ab_semigroup_add : !>[A : $tType]: $o).

tff(sy_cl_Groups_Ocomm__monoid__add, type,
    comm_monoid_add : !>[A : $tType]: $o).

tff(sy_cl_Rings_Ocomm__semiring__1, type,
    comm_semiring_1 : !>[A : $tType]: $o).

tff(sy_cl_Rings_Olinordered__ring, type,
    linordered_ring : !>[A : $tType]: $o).

tff(sy_cl_Rings_Olinordered__idom, type,
    linordered_idom : !>[A : $tType]: $o).

tff(sy_cl_Rings_Ozero__less__one, type,
    zero_less_one : !>[A : $tType]: $o).

tff(sy_cl_Num_Osemiring__numeral, type,
    semiring_numeral : !>[A : $tType]: $o).

tff(sy_cl_Groups_Oab__group__add, type,
    ab_group_add : !>[A : $tType]: $o).

tff(sy_cl_Orderings_Oorder__bot, type,
    order_bot : !>[A : $tType]: $o).

tff(sy_cl_Rings_Oordered__ring, type,
    ordered_ring : !>[A : $tType]: $o).

tff(sy_cl_Rings_Ocomm__ring__1, type,
    comm_ring_1 : !>[A : $tType]: $o).

tff(sy_cl_Groups_Omonoid__mult, type,
    monoid_mult : !>[A : $tType]: $o).

tff(sy_cl_Orderings_Opreorder, type,
    preorder : !>[A : $tType]: $o).

tff(sy_cl_Orderings_Olinorder, type,
    linorder : !>[A : $tType]: $o).

tff(sy_cl_Groups_Omonoid__add, type,
    monoid_add : !>[A : $tType]: $o).

tff(sy_cl_Rings_Osemiring__1, type,
    semiring_1 : !>[A : $tType]: $o).

tff(sy_cl_Rings_Omult__zero, type,
    mult_zero : !>[A : $tType]: $o).

tff(sy_cl_Rings_Ocomm__ring, type,
    comm_ring : !>[A : $tType]: $o).

tff(sy_cl_Num_Oneg__numeral, type,
    neg_numeral : !>[A : $tType]: $o).

tff(sy_cl_Rings_Oring__1, type,
    ring_1 : !>[A : $tType]: $o).

tff(sy_cl_Orderings_Oord, type,
    ord : !>[A : $tType]: $o).

tff(sy_cl_Num_Onumeral, type,
    numeral : !>[A : $tType]: $o).

tff(sy_cl_Rings_Oring, type,
    ring : !>[A : $tType]: $o).


% Explicit typings (97)

tff(sy_c_GeoTopBase0_Ogeotop__euclidean__topology_001T__a, type,
    geotop883275193logy_a : set_set_a).

tff(sy_c_GeoTopBase0_Ogeotop__is__complex_001T__a, type,
    geotop_is_complex_a : fun_set_set_a_bool).

tff(sy_c_GeoTopBase0_Ogeotop__polyhedron_001T__a, type,
    geotop_polyhedron_a : fun_set_set_a_set_a).

tff(sy_c_GeoTopBase_Ogeotop__complex__is__1dim_001T__a, type,
    geotop7726258031dim_a : fun_set_set_a_bool).

tff(sy_c_GeoTopBase_Ogeotop__is__arc_001T__a, type,
    geotop_is_arc_a : fun_se590241323a_bool).

tff(sy_c_GeoTopBase_Ogeotop__is__broken__line_001T__a, type,
    geotop1661465655line_a : fun_set_a_bool).

tff(sy_c_Groups_Ominus__class_Ominus_001T__a, type,
    minus_minus_a : fun_a_fun_a_a).

tff(sy_c_Groups_Ominus__class_Ominus_001t__Real__Oreal, type,
    minus_minus_real : fun_re785795966l_real).

tff(sy_c_Groups_Oone__class_Oone_001T__a, type,
    one_one_a : a3).

tff(sy_c_Groups_Oone__class_Oone_001t__Real__Oreal, type,
    one_one_real : real).

tff(sy_c_Groups_Oplus__class_Oplus_001T__a, type,
    plus_plus_a : fun_a_fun_a_a).

tff(sy_c_Groups_Oplus__class_Oplus_001t__Real__Oreal, type,
    plus_plus_real : fun_re785795966l_real).

tff(sy_c_Groups_Otimes__class_Otimes_001T__a, type,
    times_times_a : fun_a_fun_a_a).

tff(sy_c_Groups_Otimes__class_Otimes_001t__Real__Oreal, type,
    times_times_real : fun_re785795966l_real).

tff(sy_c_Groups_Ozero__class_Ozero_001T__a, type,
    zero_zero_a : a3).

tff(sy_c_Groups_Ozero__class_Ozero_001t__Real__Oreal, type,
    zero_zero_real : real).

tff(sy_c_Lattices_Oinf__class_Oinf_001T__a, type,
    inf_inf_a : fun_a_fun_a_a).

tff(sy_c_Lattices_Oinf__class_Oinf_001t__Set__Oset_IT__a_J, type,
    inf_inf_set_a : fun_se1395821270_set_a).

tff(sy_c_Lattices_Osup__class_Osup_001t__Set__Oset_IT__a_J, type,
    sup_sup_set_a : fun_se1395821270_set_a).

tff(sy_c_Line__Segment_Oclosed__segment_001T__a, type,
    line_c924316307ment_a : fun_a_fun_a_set_a).

tff(sy_c_Line__Segment_Oclosed__segment_001t__Real__Oreal, type,
    line_c714736385t_real : fun_re1392512436t_real).

tff(sy_c_Num_Oneg__numeral__class_Osub_001T__a, type,
    neg_numeral_sub_a : fun_num_fun_num_a).

tff(sy_c_Num_Onum_OOne, type,
    one : num).

tff(sy_c_Num_Onumeral__class_Onumeral_001T__a, type,
    numeral_numeral_a : fun_num_a).

tff(sy_c_Orderings_Obot__class_Obot_001T__a, type,
    bot_bot_a : a3).

tff(sy_c_Orderings_Obot__class_Obot_001t__Set__Oset_IT__a_J, type,
    bot_bot_set_a : set_a2).

tff(sy_c_Orderings_Oord__class_Oless_001T__a, type,
    ord_less_a : fun_a_fun_a_bool).

tff(sy_c_Orderings_Oord__class_Oless_001t__Num__Onum, type,
    ord_less_num : fun_num_fun_num_bool).

tff(sy_c_Orderings_Oord__class_Oless_001t__Real__Oreal, type,
    ord_less_real : fun_re589487345l_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001T__a, type,
    ord_less_eq_a : fun_a_fun_a_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001t__Real__Oreal, type,
    ord_less_eq_real : fun_re589487345l_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001t__Set__Oset_IT__a_J, type,
    ord_less_eq_set_a : fun_se1296151905a_bool).

tff(sy_c_Orderings_Otop__class_Otop_001t__Set__Oset_IT__a_J, type,
    top_top_set_a : set_a2).

tff(sy_c_Path__Connected_Oarc_001T__a, type,
    path_arc_a : fun_fun_real_a_bool).

tff(sy_c_Path__Connected_Opath__image_001T__a, type,
    path_path_image_a : fun_fun_real_a_set_a).

tff(sy_c_Path__Connected_Opathfinish_001T__a, type,
    path_pathfinish_a : fun_fun_real_a_a).

tff(sy_c_Path__Connected_Opathstart_001T__a, type,
    path_pathstart_a : fun_fun_real_a_a).

tff(sy_c_Path__Connected_Osubpath_001T__a, type,
    path_subpath_a : fun_re465290269real_a).

tff(sy_c_Set_Oimage_001T__b_001T__a, type,
    image_b_a : fun_fu1241503453_set_a).

tff(sy_c_Set_Oimage_001t__Real__Oreal_001T__a, type,
    image_real_a : fun_fu2039545399_set_a).

tff(sy_c_Set_Oinsert_001T__a, type,
    insert_a : fun_a_1385981984_set_a).

tff(sy_c_Set__Interval_Oord__class_OatLeastAtMost_001T__a, type,
    set_or1784915657Most_a : fun_a_fun_a_set_a).

tff(sy_c_Set__Interval_Oord__class_OatLeastAtMost_001t__Real__Oreal, type,
    set_or656347191t_real : fun_re1392512436t_real).

tff(sy_c_Set__Interval_Oord__class_OatLeastLessThan_001T__a, type,
    set_or2043508205Than_a : fun_a_fun_a_set_a).

tff(sy_c_Set__Interval_Oord__class_OatLeastLessThan_001t__Real__Oreal, type,
    set_or2075149659n_real : fun_re1392512436t_real).

tff(sy_c_Top1__Ch2_Osubspace__topology_001T__a, type,
    top1_s1397583065logy_a : fun_se1904574643_set_a).

tff(sy_c_Topological__Spaces_Otopological__space__class_Oclosed_001T__a, type,
    topolo1189434316osed_a : fun_set_a_bool).

tff(sy_c_aa_001T__a_001T__a, type,
    aa_a_a : (fun_a_a2 * a3) > a3).

tff(sy_c_aa_001T__a_001t__HOL__Obool, type,
    aa_a_bool : (fun_a_bool * a3) > bool).

tff(sy_c_aa_001T__a_001t__Set__Oset_IT__a_J, type,
    aa_a_set_a : (fun_a_set_a * a3) > set_a2).

tff(sy_c_aa_001T__a_001t__fun_IT__a_MT__a_J, type,
    aa_a_fun_a_a : (fun_a_fun_a_a * a3) > fun_a_a2).

tff(sy_c_aa_001T__a_001t__fun_IT__a_Mt__HOL__Obool_J, type,
    aa_a_fun_a_bool : (fun_a_fun_a_bool * a3) > fun_a_bool).

tff(sy_c_aa_001T__a_001t__fun_IT__a_Mt__Set__Oset_IT__a_J_J, type,
    aa_a_fun_a_set_a : (fun_a_fun_a_set_a * a3) > fun_a_set_a).

tff(sy_c_aa_001T__a_001t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    aa_a_fun_set_a_bool : (fun_a_fun_set_a_bool * a3) > fun_set_a_bool).

tff(sy_c_aa_001T__a_001t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J, type,
    aa_a_fun_set_a_set_a : (fun_a_1385981984_set_a * a3) > fun_set_a_set_a).

tff(sy_c_aa_001T__b_001T__a, type,
    aa_b_a : (fun_b_a * b) > a3).

tff(sy_c_aa_001T__b_001t__fun_It__Set__Oset_IT__b_J_Mt__HOL__Obool_J, type,
    aa_b_fun_set_b_bool : (fun_b_fun_set_b_bool * b) > fun_set_b_bool).

tff(sy_c_aa_001t__Num__Onum_001T__a, type,
    aa_num_a : (fun_num_a * num) > a3).

tff(sy_c_aa_001t__Num__Onum_001t__HOL__Obool, type,
    aa_num_bool : (fun_num_bool * num) > bool).

tff(sy_c_aa_001t__Num__Onum_001t__fun_It__Num__Onum_MT__a_J, type,
    aa_num_fun_num_a : (fun_num_fun_num_a * num) > fun_num_a).

tff(sy_c_aa_001t__Num__Onum_001t__fun_It__Num__Onum_Mt__HOL__Obool_J, type,
    aa_num_fun_num_bool : (fun_num_fun_num_bool * num) > fun_num_bool).

tff(sy_c_aa_001t__Real__Oreal_001T__a, type,
    aa_real_a : (fun_real_a * real) > a3).

tff(sy_c_aa_001t__Real__Oreal_001t__HOL__Obool, type,
    aa_real_bool : (fun_real_bool * real) > bool).

tff(sy_c_aa_001t__Real__Oreal_001t__Real__Oreal, type,
    aa_real_real : (fun_real_real * real) > real).

tff(sy_c_aa_001t__Real__Oreal_001t__Set__Oset_It__Real__Oreal_J, type,
    aa_real_set_real : (fun_real_set_real * real) > set_real).

tff(sy_c_aa_001t__Real__Oreal_001t__fun_It__Real__Oreal_Mt__HOL__Obool_J, type,
    aa_rea628360026l_bool : (fun_re589487345l_bool * real) > fun_real_bool).

tff(sy_c_aa_001t__Real__Oreal_001t__fun_It__Real__Oreal_Mt__Real__Oreal_J, type,
    aa_rea846001983l_real : (fun_re785795966l_real * real) > fun_real_real).

tff(sy_c_aa_001t__Real__Oreal_001t__fun_It__Real__Oreal_Mt__Set__Oset_It__Real__Oreal_J_J, type,
    aa_rea1747993717t_real : (fun_re1392512436t_real * real) > fun_real_set_real).

tff(sy_c_aa_001t__Real__Oreal_001t__fun_It__Real__Oreal_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__Real__Oreal_MT__a_J_J_J, type,
    aa_rea608203102real_a : (fun_re465290269real_a * real) > fun_re1692559348real_a).

tff(sy_c_aa_001t__Real__Oreal_001t__fun_It__Set__Oset_It__Real__Oreal_J_Mt__HOL__Obool_J, type,
    aa_rea558415012l_bool : (fun_re596238651l_bool * real) > fun_set_real_bool).

tff(sy_c_aa_001t__Real__Oreal_001t__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__Real__Oreal_MT__a_J_J, type,
    aa_rea1156452021real_a : (fun_re1692559348real_a * real) > fun_fu1277785163real_a).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__HOL__Obool, type,
    aa_set_a_bool : (fun_set_a_bool * set_a2) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__Set__Oset_IT__a_J, type,
    aa_set_a_set_a : (fun_set_a_set_a * set_a2) > set_a2).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__Set__Oset_It__Set__Oset_IT__a_J_J, type,
    aa_set_a_set_set_a : (fun_set_a_set_set_a * set_a2) > set_set_a).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    aa_set1122887114a_bool : (fun_se1296151905a_bool * set_a2) > fun_set_a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J, type,
    aa_set363163287_set_a : (fun_se1395821270_set_a * set_a2) > fun_set_a_set_a).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J, type,
    aa_set1454015380a_bool : (fun_se590241323a_bool * set_a2) > fun_set_set_a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J_J, type,
    aa_set392168180_set_a : (fun_se1904574643_set_a * set_a2) > fun_se122506306_set_a).

tff(sy_c_aa_001t__Set__Oset_IT__b_J_001t__HOL__Obool, type,
    aa_set_b_bool : (fun_set_b_bool * set_b) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__b_J_001t__Set__Oset_IT__a_J, type,
    aa_set_b_set_a : (fun_set_b_set_a * set_b) > set_a2).

tff(sy_c_aa_001t__Set__Oset_It__Real__Oreal_J_001t__HOL__Obool, type,
    aa_set_real_bool : (fun_set_real_bool * set_real) > bool).

tff(sy_c_aa_001t__Set__Oset_It__Real__Oreal_J_001t__Set__Oset_IT__a_J, type,
    aa_set_real_set_a : (fun_set_real_set_a * set_real) > set_a2).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__HOL__Obool, type,
    aa_set_set_a_bool : (fun_set_set_a_bool * set_set_a) > bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__Set__Oset_IT__a_J, type,
    aa_set_set_a_set_a : (fun_set_set_a_set_a * set_set_a) > set_a2).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J, type,
    aa_set1645173507_set_a : (fun_se122506306_set_a * set_set_a) > fun_set_a_set_set_a).

tff(sy_c_aa_001t__fun_IT__b_MT__a_J_001t__fun_It__Set__Oset_IT__b_J_Mt__Set__Oset_IT__a_J_J, type,
    aa_fun662792990_set_a : (fun_fu1241503453_set_a * fun_b_a) > fun_set_b_set_a).

tff(sy_c_aa_001t__fun_It__Real__Oreal_MT__a_J_001T__a, type,
    aa_fun_real_a_a : (fun_fun_real_a_a * fun_real_a) > a3).

tff(sy_c_aa_001t__fun_It__Real__Oreal_MT__a_J_001t__HOL__Obool, type,
    aa_fun_real_a_bool : (fun_fun_real_a_bool * fun_real_a) > bool).

tff(sy_c_aa_001t__fun_It__Real__Oreal_MT__a_J_001t__Set__Oset_IT__a_J, type,
    aa_fun_real_a_set_a : (fun_fun_real_a_set_a * fun_real_a) > set_a2).

tff(sy_c_aa_001t__fun_It__Real__Oreal_MT__a_J_001t__fun_It__Real__Oreal_MT__a_J, type,
    aa_fun964359948real_a : (fun_fu1277785163real_a * fun_real_a) > fun_real_a).

tff(sy_c_aa_001t__fun_It__Real__Oreal_MT__a_J_001t__fun_It__Set__Oset_It__Real__Oreal_J_Mt__Set__Oset_IT__a_J_J, type,
    aa_fun1448892152_set_a : (fun_fu2039545399_set_a * fun_real_a) > fun_set_real_set_a).

tff(sy_c_fFalse, type,
    fFalse : bool).

tff(sy_c_fTrue, type,
    fTrue : bool).

tff(sy_c_member_001T__a, type,
    member_a : fun_a_fun_set_a_bool).

tff(sy_c_member_001T__b, type,
    member_b : fun_b_fun_set_b_bool).

tff(sy_c_member_001t__Real__Oreal, type,
    member_real : fun_re596238651l_bool).

tff(sy_c_pp, type,
    pp : bool > $o).


% Relevant facts (81)

tff(fact_0_GeoTopBase_Ogeotop__HOL__arc__imp__geotop__is__arc, axiom,
    ((![A : $i]: (euclid925273238_space(a3) => (![Gamma : fun_real_a]: (pp(aa_fun_real_a_bool(path_arc_a, Gamma)) => pp(aa_set_set_a_bool(aa_set1454015380a_bool(geotop_is_arc_a, aa_fun_real_a_set_a(path_path_image_a, Gamma)), aa_set_a_set_set_a(aa_set1645173507_set_a(aa_set392168180_set_a(top1_s1397583065logy_a, top_top_set_a), geotop883275193logy_a), aa_fun_real_a_set_a(path_path_image_a, Gamma)))))))))). % GeoTopBase.geotop_HOL_arc_imp_geotop_is_arc

tff(fact_1_GeoTopBase_Ogeotop__arc__first__intersection, axiom,
    ((![A : $i]: (euclid925273238_space(a3) => (![Gamma : fun_real_a, T : set_a2]: (pp(aa_fun_real_a_bool(path_arc_a, Gamma)) => (pp(aa_set_a_bool(topolo1189434316osed_a, T)) => (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, aa_real_a(Gamma, one_one_real)), T)) => (~ ((![Sstar : real]: (pp(aa_set_real_bool(aa_rea558415012l_bool(member_real, Sstar), aa_real_set_real(aa_rea1747993717t_real(set_or656347191t_real, zero_zero_real), one_one_real))) => (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, aa_real_a(Gamma, Sstar)), T)) => (~ ((![X : real]: (pp(aa_set_real_bool(aa_rea558415012l_bool(member_real, X), aa_real_set_real(aa_rea1747993717t_real(set_or2075149659n_real, zero_zero_real), Sstar))) => (~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, aa_real_a(Gamma, X)), T))))))))))))))))))))). % GeoTopBase.geotop_arc_first_intersection

tff(fact_2_GeoTopBase_Ogeotop__broken__line__closed, axiom,
    ((![A : $i]: (euclid925273238_space(a3) => (![B : set_a2]: (pp(aa_set_a_bool(geotop1661465655line_a, B)) => pp(aa_set_a_bool(topolo1189434316osed_a, B)))))))). % GeoTopBase.geotop_broken_line_closed

tff(fact_3_GeoTopBase_Ogeotop__broken__line__subarc, axiom,
    ((![A : $i]: (euclid925273238_space(a3) => (![B : set_a2, X2 : a3, Y : a3]: (pp(aa_set_a_bool(geotop1661465655line_a, B)) => (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X2), B)) => (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, Y), B)) => (?[B2 : set_a2]: (pp(aa_set_a_bool(geotop1661465655line_a, B2)) & (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, B2), B)) & (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X2), B2)) & (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, Y), B2)) & ((X2 = Y) | (?[Gamma2 : fun_real_a]: (pp(aa_fun_real_a_bool(path_arc_a, Gamma2)) & ((aa_fun_real_a_set_a(path_path_image_a, Gamma2) = B2) & ((aa_fun_real_a_a(path_pathstart_a, Gamma2) = X2) & (aa_fun_real_a_a(path_pathfinish_a, Gamma2) = Y))))))))))))))))))). % GeoTopBase.geotop_broken_line_subarc

tff(fact_4_GeoTopBase_Ogeotop__broken__lines__glue__disjoint__endpoints, axiom,
    ((![A : $i]: (euclid925273238_space(a3) => (![B_1 : set_a2, B_2 : set_a2, R : a3]: (pp(aa_set_a_bool(geotop1661465655line_a, B_1)) => (pp(aa_set_a_bool(geotop1661465655line_a, B_2)) => ((?[Gamma_1 : fun_real_a]: (pp(aa_fun_real_a_bool(path_arc_a, Gamma_1)) & ((aa_fun_real_a_set_a(path_path_image_a, Gamma_1) = B_1) & (aa_fun_real_a_a(path_pathfinish_a, Gamma_1) = R)))) => ((?[Gamma_2 : fun_real_a]: (pp(aa_fun_real_a_bool(path_arc_a, Gamma_2)) & ((aa_fun_real_a_set_a(path_path_image_a, Gamma_2) = B_2) & (aa_fun_real_a_a(path_pathstart_a, Gamma_2) = R)))) => ((aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, B_1), B_2) = aa_set_a_set_a(aa_a_fun_set_a_set_a(insert_a, R), bot_bot_set_a)) => pp(aa_set_a_bool(geotop1661465655line_a, aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, B_1), B_2))))))))))))). % GeoTopBase.geotop_broken_lines_glue_disjoint_endpoints

tff(fact_5_GeoTopBase_Ogeotop__is__broken__line__def, axiom,
    ((![A : $i]: (real_V55928688vector(a3) => (![B : set_a2]: (pp(aa_set_a_bool(geotop1661465655line_a, B)) <=> (?[K : set_set_a]: (pp(aa_set_set_a_bool(geotop_is_complex_a, K)) & ((aa_set_set_a_set_a(geotop_polyhedron_a, K) = B) & (pp(aa_set_set_a_bool(geotop7726258031dim_a, K)) & pp(aa_set_set_a_bool(aa_set1454015380a_bool(geotop_is_arc_a, B), aa_set_a_set_set_a(aa_set1645173507_set_a(aa_set392168180_set_a(top1_s1397583065logy_a, top_top_set_a), geotop883275193logy_a), B))))))))))))). % GeoTopBase.geotop_is_broken_line_def

tff(fact_6_GeoTopBase_Ogeotop__subarc__polyhedron, axiom,
    ((![A : $i]: (euclid925273238_space(a3) => (![B : set_a2, Gamma : fun_real_a, S_lo : real, S_hi : real]: (pp(aa_set_a_bool(geotop1661465655line_a, B)) => (pp(aa_fun_real_a_bool(path_arc_a, Gamma)) => ((aa_fun_real_a_set_a(path_path_image_a, Gamma) = B) => (pp(aa_set_real_bool(aa_rea558415012l_bool(member_real, S_lo), aa_real_set_real(aa_rea1747993717t_real(set_or656347191t_real, zero_zero_real), one_one_real))) => (pp(aa_set_real_bool(aa_rea558415012l_bool(member_real, S_hi), aa_real_set_real(aa_rea1747993717t_real(set_or656347191t_real, zero_zero_real), one_one_real))) => (pp(aa_real_bool(aa_rea628360026l_bool(ord_less_real, S_lo), S_hi)) => (?[K2 : set_set_a]: (pp(aa_set_set_a_bool(geotop_is_complex_a, K2)) & ((aa_set_set_a_set_a(geotop_polyhedron_a, K2) = aa_set_real_set_a(aa_fun1448892152_set_a(image_real_a, Gamma), aa_real_set_real(aa_rea1747993717t_real(line_c714736385t_real, S_lo), S_hi))) & pp(aa_set_set_a_bool(geotop7726258031dim_a, K2)))))))))))))))). % GeoTopBase.geotop_subarc_polyhedron

tff(fact_7_Groups_Oab__semigroup__add__class_Oadd_Ocommute, axiom,
    ((![A : $i]: (ab_semigroup_add(a3) => (![A2 : a3, B3 : a3]: (aa_a_a(aa_a_fun_a_a(plus_plus_a, A2), B3) = aa_a_a(aa_a_fun_a_a(plus_plus_a, B3), A2))))))). % Groups.ab_semigroup_add_class.add.commute

tff(fact_8_Groups_Oadd__mono__thms__linordered__field__1, axiom,
    ((![A : $i]: (ordere223160158up_add(a3) => (![I : a3, J : a3, K3 : a3, L : a3]: ((pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, I), J)) & (K3 = L)) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, aa_a_a(aa_a_fun_a_a(plus_plus_a, I), K3)), aa_a_a(aa_a_fun_a_a(plus_plus_a, J), L))))))))). % Groups.add_mono_thms_linordered_field_1

tff(fact_9_Groups_Oadd__mono__thms__linordered__field__3, axiom,
    ((![A : $i]: (ordere223160158up_add(a3) => (![I : a3, J : a3, K3 : a3, L : a3]: ((pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, I), J)) & pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, K3), L))) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, aa_a_a(aa_a_fun_a_a(plus_plus_a, I), K3)), aa_a_a(aa_a_fun_a_a(plus_plus_a, J), L))))))))). % Groups.add_mono_thms_linordered_field_3

tff(fact_10_Groups_Oadd__mono__thms__linordered__field__4, axiom,
    ((![A : $i]: (ordere223160158up_add(a3) => (![I : a3, J : a3, K3 : a3, L : a3]: ((pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, I), J)) & pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, K3), L))) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, aa_a_a(aa_a_fun_a_a(plus_plus_a, I), K3)), aa_a_a(aa_a_fun_a_a(plus_plus_a, J), L))))))))). % Groups.add_mono_thms_linordered_field_4

tff(fact_11_Groups_Oadd__mono__thms__linordered__field__5, axiom,
    ((![A : $i]: (ordere223160158up_add(a3) => (![I : a3, J : a3, K3 : a3, L : a3]: ((pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, I), J)) & pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, K3), L))) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, aa_a_a(aa_a_fun_a_a(plus_plus_a, I), K3)), aa_a_a(aa_a_fun_a_a(plus_plus_a, J), L))))))))). % Groups.add_mono_thms_linordered_field_5

tff(fact_12_Groups_Oadd__mono__thms__linordered__semiring__1, axiom,
    ((![A : $i]: (ordere779506340up_add(a3) => (![I : a3, J : a3, K3 : a3, L : a3]: ((pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, I), J)) & pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, K3), L))) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, aa_a_a(aa_a_fun_a_a(plus_plus_a, I), K3)), aa_a_a(aa_a_fun_a_a(plus_plus_a, J), L))))))))). % Groups.add_mono_thms_linordered_semiring_1

tff(fact_13_Groups_Ocancel__comm__monoid__add__class_Odiff__zero, axiom,
    ((![A : $i]: (cancel1352612707id_add(a3) => (![A2 : a3]: (aa_a_a(aa_a_fun_a_a(minus_minus_a, A2), zero_zero_a) = A2)))))). % Groups.cancel_comm_monoid_add_class.diff_zero

tff(fact_14_Groups_Omonoid__add__class_Oadd_Oleft__neutral, axiom,
    ((![A : $i]: (monoid_add(a3) => (![A2 : a3]: (aa_a_a(aa_a_fun_a_a(plus_plus_a, zero_zero_a), A2) = A2)))))). % Groups.monoid_add_class.add.left_neutral

tff(fact_15_Groups_Omonoid__add__class_Oadd_Oright__neutral, axiom,
    ((![A : $i]: (monoid_add(a3) => (![A2 : a3]: (aa_a_a(aa_a_fun_a_a(plus_plus_a, A2), zero_zero_a) = A2)))))). % Groups.monoid_add_class.add.right_neutral

tff(fact_16_Groups_Omonoid__add__class_Oadd__0__left, axiom,
    ((![A : $i]: (monoid_add(a3) => (![A2 : a3]: (aa_a_a(aa_a_fun_a_a(plus_plus_a, zero_zero_a), A2) = A2)))))). % Groups.monoid_add_class.add_0_left

tff(fact_17_Groups_Omonoid__add__class_Oadd__0__right, axiom,
    ((![A : $i]: (monoid_add(a3) => (![A2 : a3]: (aa_a_a(aa_a_fun_a_a(plus_plus_a, A2), zero_zero_a) = A2)))))). % Groups.monoid_add_class.add_0_right

tff(fact_18_Groups_Omonoid__mult__class_Omult_Oright__neutral, axiom,
    ((![A : $i]: (monoid_mult(a3) => (![A2 : a3]: (aa_a_a(aa_a_fun_a_a(times_times_a, A2), one_one_a) = A2)))))). % Groups.monoid_mult_class.mult.right_neutral

tff(fact_19_HOL_OallE, axiom,
    ((![A : $i, P : fun_a_bool, X3 : a3]: ((![X_1 : a3]: pp(aa_a_bool(P, X_1))) => pp(aa_a_bool(P, X3)))))). % HOL.allE

tff(fact_20_HOL_OconjE, axiom,
    ((![P : bool, Q : bool]: ((pp(P) & pp(Q)) => (~ ((pp(P) => (~ (pp(Q)))))))))). % HOL.conjE

tff(fact_21_HOL_OconjI, axiom,
    ((![P : bool, Q : bool]: (pp(P) => (pp(Q) => (pp(P) & pp(Q))))))). % HOL.conjI

tff(fact_22_HOL_OdisjCI, axiom,
    ((![Q : bool, P : bool]: (((~ (pp(Q))) => pp(P)) => (pp(P) | pp(Q)))))). % HOL.disjCI

tff(fact_23_HOL_OdisjE, axiom,
    ((![P : bool, Q : bool]: ((pp(P) | pp(Q)) => ((~ (pp(P))) => pp(Q)))))). % HOL.disjE

tff(fact_24_HOL_Oeq__reflection, axiom,
    ((![A : $i, X3 : a3, Y2 : a3]: ((X3 = Y2) => (X3 = Y2))))). % HOL.eq_reflection

tff(fact_25_HOL_OexE, axiom,
    ((![A : $i, P : fun_a_bool]: ((?[X_12 : a3]: pp(aa_a_bool(P, X_12))) => (~ ((![X4 : a3]: (~ (pp(aa_a_bool(P, X4))))))))))). % HOL.exE

tff(fact_26_HOL_OexI, axiom,
    ((![A : $i, P : fun_a_bool, X3 : a3]: (pp(aa_a_bool(P, X3)) => (?[X_1 : a3]: pp(aa_a_bool(P, X_1))))))). % HOL.exI

tff(fact_27_HOL_Oif__weak__cong, axiom,
    ((![A : $i, B3 : bool, C : bool, Y2 : a3, X3 : a3]: ((pp(B3) <=> pp(C)) => ((pp(C) => ((~ (pp(B3))) => (Y2 = X3))) & ((~ (pp(C))) => (pp(B3) => (X3 = Y2)))))))). % HOL.if_weak_cong

tff(fact_28_HOL_OimpI, axiom,
    ((![P : bool, Q : bool]: ((pp(P) => pp(Q)) => (pp(P) => pp(Q)))))). % HOL.impI

tff(fact_29_HOL_Ometa__eq__to__obj__eq, axiom,
    ((![A : $i, A3 : a3, B : a3]: ((A3 = B) => (A3 = B))))). % HOL.meta_eq_to_obj_eq

tff(fact_30_HOL_Onot__sym, axiom,
    ((![A : $i, T2 : a3, S : a3]: ((T2 != S) => (S != T2))))). % HOL.not_sym

tff(fact_31_HOL_Orefl, axiom,
    ((![A : $i, T2 : a3]: (T2 = T2)))). % HOL.refl

tff(fact_32_HOL_Osimp__thms__25, axiom,
    ((![P : bool]: ((pp(P) & pp(P)) <=> pp(P))))). % HOL.simp_thms_25

tff(fact_33_HOL_Osubst, axiom,
    ((![A : $i, S : a3, T2 : a3, P : fun_a_bool]: ((S = T2) => (pp(aa_a_bool(P, S)) => pp(aa_a_bool(P, T2))))))). % HOL.subst

tff(fact_34_HOL_Osym, axiom,
    ((![A : $i, S : a3, T2 : a3]: ((S = T2) => (T2 = S))))). % HOL.sym

tff(fact_35_HOL_Otrans, axiom,
    ((![A : $i, R2 : a3, S : a3, T2 : a3]: ((R2 = S) => ((S = T2) => (R2 = T2)))))). % HOL.trans

tff(fact_36_Lattices_Osemilattice__inf__class_Oinf_Obounded__iff, axiom,
    ((![A : $i]: (semilattice_inf(a3) => (![A2 : a3, B3 : a3, C : a3]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A2), aa_a_a(aa_a_fun_a_a(inf_inf_a, B3), C))) <=> (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A2), B3)) & pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A2), C))))))))). % Lattices.semilattice_inf_class.inf.bounded_iff

tff(fact_37_Line__Segment_Oclosed__segment__eq__real__ivl, axiom,
    ((![A2 : real, B3 : real]: ((pp(aa_real_bool(aa_rea628360026l_bool(ord_less_eq_real, A2), B3)) => (aa_real_set_real(aa_rea1747993717t_real(line_c714736385t_real, A2), B3) = aa_real_set_real(aa_rea1747993717t_real(set_or656347191t_real, A2), B3))) & ((~ (pp(aa_real_bool(aa_rea628360026l_bool(ord_less_eq_real, A2), B3)))) => (aa_real_set_real(aa_rea1747993717t_real(line_c714736385t_real, A2), B3) = aa_real_set_real(aa_rea1747993717t_real(set_or656347191t_real, B3), A2))))))). % Line_Segment.closed_segment_eq_real_ivl

tff(fact_38_Line__Segment_Oends__in__segment__2, axiom,
    ((![A : $i]: (real_V1076094709vector(a3) => (![B3 : a3, A2 : a3]: pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, B3), aa_a_set_a(aa_a_fun_a_set_a(line_c924316307ment_a, A2), B3)))))))). % Line_Segment.ends_in_segment_2

tff(fact_39_Num_Oarith__simps__16, axiom,
    ((![A : $i]: (neg_numeral(a3) => (aa_num_a(aa_num_fun_num_a(neg_numeral_sub_a, one), one) = zero_zero_a))))). % Num.arith_simps_16

tff(fact_40_Num_Oarith__simps__49, axiom,
    ((![A : $i]: (monoid_add(a3) => (![A2 : a3]: (aa_a_a(aa_a_fun_a_a(plus_plus_a, zero_zero_a), A2) = A2)))))). % Num.arith_simps_49

tff(fact_41_Num_Oarith__simps__50, axiom,
    ((![A : $i]: (monoid_add(a3) => (![A2 : a3]: (aa_a_a(aa_a_fun_a_a(plus_plus_a, A2), zero_zero_a) = A2)))))). % Num.arith_simps_50

tff(fact_42_Num_Oarith__simps__52, axiom,
    ((![A : $i]: (neg_numeral(a3) => (![M : num, N : num]: (aa_a_a(aa_a_fun_a_a(minus_minus_a, aa_num_a(numeral_numeral_a, M)), aa_num_a(numeral_numeral_a, N)) = aa_num_a(aa_num_fun_num_a(neg_numeral_sub_a, M), N))))))). % Num.arith_simps_52

tff(fact_43_Num_Oarith__simps__62, axiom,
    ((![A : $i]: (mult_zero(a3) => (![A2 : a3]: (aa_a_a(aa_a_fun_a_a(times_times_a, zero_zero_a), A2) = zero_zero_a)))))). % Num.arith_simps_62

tff(fact_44_Num_Omult__1s__1, axiom,
    ((![A : $i]: (semiring_numeral(a3) => (![A2 : a3]: (aa_a_a(aa_a_fun_a_a(times_times_a, aa_num_a(numeral_numeral_a, one)), A2) = A2)))))). % Num.mult_1s_1

tff(fact_45_Num_Onumeral__class_Onumeral_Onumeral__One, axiom,
    ((![A : $i]: (numeral(a3) => (aa_num_a(numeral_numeral_a, one) = one_one_a))))). % Num.numeral_class.numeral.numeral_One

tff(fact_46_Num_Orel__simps__8, axiom,
    ((![M : num]: (~ (pp(aa_num_bool(aa_num_fun_num_bool(ord_less_num, M), one))))))). % Num.rel_simps_8

tff(fact_47_Num_Orel__simps__48, axiom,
    ((![A : $i]: (linord1659791738miring(a3) => (![M : num, N : num]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, aa_num_a(numeral_numeral_a, M)), aa_num_a(numeral_numeral_a, N))) <=> pp(aa_num_bool(aa_num_fun_num_bool(ord_less_num, M), N)))))))). % Num.rel_simps_48

tff(fact_48_Orderings_Olinorder__not__le, axiom,
    ((![A : $i]: (linorder(a3) => (![X3 : a3, Y2 : a3]: ((~ (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X3), Y2)))) <=> pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, Y2), X3)))))))). % Orderings.linorder_not_le

tff(fact_49_Orderings_Olinorder__not__less, axiom,
    ((![A : $i]: (linorder(a3) => (![X3 : a3, Y2 : a3]: ((~ (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, X3), Y2)))) <=> pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Y2), X3)))))))). % Orderings.linorder_not_less

tff(fact_50_Orderings_Oorder__bot__class_Obot_Oextremum, axiom,
    ((![A : $i]: (order_bot(a3) => (![A2 : a3]: pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, bot_bot_a), A2))))))). % Orderings.order_bot_class.bot.extremum

tff(fact_51_Orderings_Oorder__less__irrefl, axiom,
    ((![A : $i]: (preorder(a3) => (![X3 : a3]: (~ (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, X3), X3))))))))). % Orderings.order_less_irrefl

tff(fact_52_Orderings_Opreorder__class_Oorder__refl, axiom,
    ((![A : $i]: (preorder(a3) => (![X3 : a3]: pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X3), X3))))))). % Orderings.preorder_class.order_refl

tff(fact_53_Path__Connected_Oarc__subpath__arc, axiom,
    ((![A : $i]: (real_V55928688vector(a3) => (![G : fun_real_a, U : real, V : real]: (pp(aa_fun_real_a_bool(path_arc_a, G)) => (pp(aa_set_real_bool(aa_rea558415012l_bool(member_real, U), aa_real_set_real(aa_rea1747993717t_real(set_or656347191t_real, zero_zero_real), one_one_real))) => (pp(aa_set_real_bool(aa_rea558415012l_bool(member_real, V), aa_real_set_real(aa_rea1747993717t_real(set_or656347191t_real, zero_zero_real), one_one_real))) => ((U != V) => pp(aa_fun_real_a_bool(path_arc_a, aa_fun964359948real_a(aa_rea1156452021real_a(aa_rea608203102real_a(path_subpath_a, U), V), G)))))))))))). % Path_Connected.arc_subpath_arc

tff(fact_54_Path__Connected_Opath__image__def, axiom,
    ((![A : $i]: (topolo503727757_space(a3) => (![G : fun_real_a]: (aa_fun_real_a_set_a(path_path_image_a, G) = aa_set_real_set_a(aa_fun1448892152_set_a(image_real_a, G), aa_real_set_real(aa_rea1747993717t_real(set_or656347191t_real, zero_zero_real), one_one_real)))))))). % Path_Connected.path_image_def

tff(fact_55_Path__Connected_Opath__image__subpath__gen, axiom,
    ((![A : $i]: (real_V55928688vector(a3) => (![U : real, V : real, G : fun_real_a]: (aa_fun_real_a_set_a(path_path_image_a, aa_fun964359948real_a(aa_rea1156452021real_a(aa_rea608203102real_a(path_subpath_a, U), V), G)) = aa_set_real_set_a(aa_fun1448892152_set_a(image_real_a, G), aa_real_set_real(aa_rea1747993717t_real(line_c714736385t_real, U), V)))))))). % Path_Connected.path_image_subpath_gen

tff(fact_56_Path__Connected_Opathfinish__def, axiom,
    ((![A : $i]: (topolo503727757_space(a3) => (![G : fun_real_a]: (aa_fun_real_a_a(path_pathfinish_a, G) = aa_real_a(G, one_one_real))))))). % Path_Connected.pathfinish_def

tff(fact_57_Path__Connected_Opathstart__def, axiom,
    ((![A : $i]: (topolo503727757_space(a3) => (![G : fun_real_a]: (aa_fun_real_a_a(path_pathstart_a, G) = aa_real_a(G, zero_zero_real))))))). % Path_Connected.pathstart_def

tff(fact_58_Path__Connected_Osubpath__def, axiom,
    ((![A : $i]: (real_V55928688vector(a3) => (![A2 : real, B3 : real, G : fun_real_a, X : real]: (aa_real_a(aa_fun964359948real_a(aa_rea1156452021real_a(aa_rea608203102real_a(path_subpath_a, A2), B3), G), X) = aa_real_a(G, aa_real_real(aa_rea846001983l_real(plus_plus_real, aa_real_real(aa_rea846001983l_real(times_times_real, aa_real_real(aa_rea846001983l_real(minus_minus_real, B3), A2)), X)), A2)))))))). % Path_Connected.subpath_def

tff(fact_59_Rings_Olinordered__idom__class_Olinorder__neqE__linordered__idom, axiom,
    ((![A : $i]: (linordered_idom(a3) => (![X3 : a3, Y2 : a3]: ((X3 != Y2) => ((~ (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, X3), Y2)))) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, Y2), X3))))))))). % Rings.linordered_idom_class.linorder_neqE_linordered_idom

tff(fact_60_Rings_Omult__zero__class_Omult__zero__left, axiom,
    ((![A : $i]: (mult_zero(a3) => (![A2 : a3]: (aa_a_a(aa_a_fun_a_a(times_times_a, zero_zero_a), A2) = zero_zero_a)))))). % Rings.mult_zero_class.mult_zero_left

tff(fact_61_Rings_Omult__zero__class_Omult__zero__right, axiom,
    ((![A : $i]: (mult_zero(a3) => (![A2 : a3]: (aa_a_a(aa_a_fun_a_a(times_times_a, A2), zero_zero_a) = zero_zero_a)))))). % Rings.mult_zero_class.mult_zero_right

tff(fact_62_Rings_Oordered__ring__class_Ole__add__iff1, axiom,
    ((![A : $i]: (ordered_ring(a3) => (![A2 : a3, E : a3, C : a3, B3 : a3, D : a3]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, aa_a_a(aa_a_fun_a_a(plus_plus_a, aa_a_a(aa_a_fun_a_a(times_times_a, A2), E)), C)), aa_a_a(aa_a_fun_a_a(plus_plus_a, aa_a_a(aa_a_fun_a_a(times_times_a, B3), E)), D))) <=> pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, aa_a_a(aa_a_fun_a_a(plus_plus_a, aa_a_a(aa_a_fun_a_a(times_times_a, aa_a_a(aa_a_fun_a_a(minus_minus_a, A2), B3)), E)), C)), D)))))))). % Rings.ordered_ring_class.le_add_iff1

tff(fact_63_Rings_Oordered__ring__class_Oless__add__iff1, axiom,
    ((![A : $i]: (ordered_ring(a3) => (![A2 : a3, E : a3, C : a3, B3 : a3, D : a3]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, aa_a_a(aa_a_fun_a_a(plus_plus_a, aa_a_a(aa_a_fun_a_a(times_times_a, A2), E)), C)), aa_a_a(aa_a_fun_a_a(plus_plus_a, aa_a_a(aa_a_fun_a_a(times_times_a, B3), E)), D))) <=> pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, aa_a_a(aa_a_fun_a_a(plus_plus_a, aa_a_a(aa_a_fun_a_a(times_times_a, aa_a_a(aa_a_fun_a_a(minus_minus_a, A2), B3)), E)), C)), D)))))))). % Rings.ordered_ring_class.less_add_iff1

tff(fact_64_Rings_Ozero__less__one__class_Ozero__le__one, axiom,
    ((![A : $i]: (zero_less_one(a3) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, zero_zero_a), one_one_a)))))). % Rings.zero_less_one_class.zero_le_one

tff(fact_65_Set_OIntE, axiom,
    ((![A : $i, C : a3, A3 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A3), B))) => (~ ((pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A3)) => (~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B))))))))))). % Set.IntE

tff(fact_66_Set_OUnCI, axiom,
    ((![A : $i, C : a3, B : set_a2, A3 : set_a2]: (((~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B)))) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A3))) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A3), B))))))). % Set.UnCI

tff(fact_67_Set_OUnE, axiom,
    ((![A : $i, C : a3, A3 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A3), B))) => ((~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A3)))) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B))))))). % Set.UnE

tff(fact_68_Set_OUn__iff, axiom,
    ((![A : $i, C : a3, A3 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A3), B))) <=> (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A3)) | pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B))))))). % Set.Un_iff

tff(fact_69_Set_OballE, axiom,
    ((![A : $i, A3 : set_a2, P : fun_a_bool, X3 : a3]: ((![X4 : a3]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X4), A3)) => pp(aa_a_bool(P, X4)))) => ((~ (pp(aa_a_bool(P, X3)))) => (~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X3), A3))))))))). % Set.ballE

tff(fact_70_Set_Oempty__iff, axiom,
    ((![A : $i, C : a3]: (~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), bot_bot_set_a))))))). % Set.empty_iff

tff(fact_71_Set_OequalityCE, axiom,
    ((![A : $i, A3 : set_a2, B : set_a2, C : a3]: ((A3 = B) => ((pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A3)) => (~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B))))) => (~ (((~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A3)))) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B)))))))))). % Set.equalityCE

tff(fact_72_Set_OimageE, axiom,
    ((![A : $i, B4 : $i, B3 : a3, F : fun_b_a, A3 : set_b]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, B3), aa_set_b_set_a(aa_fun662792990_set_a(image_b_a, F), A3))) => (~ ((![X4 : b]: ((B3 = aa_b_a(F, X4)) => (~ (pp(aa_set_b_bool(aa_b_fun_set_b_bool(member_b, X4), A3)))))))))))). % Set.imageE

tff(fact_73_Set_Oimage__eqI, axiom,
    ((![A : $i, B4 : $i, B3 : a3, F : fun_b_a, X3 : b, A3 : set_b]: ((B3 = aa_b_a(F, X3)) => (pp(aa_set_b_bool(aa_b_fun_set_b_bool(member_b, X3), A3)) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, B3), aa_set_b_set_a(aa_fun662792990_set_a(image_b_a, F), A3)))))))). % Set.image_eqI

tff(fact_74_Set_Oinsert__iff, axiom,
    ((![A : $i, A2 : a3, B3 : a3, A3 : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, A2), aa_set_a_set_a(aa_a_fun_set_a_set_a(insert_a, B3), A3))) <=> ((A2 = B3) | pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, A2), A3))))))). % Set.insert_iff

tff(fact_75_Set_Oinsert__subset, axiom,
    ((![A : $i, X3 : a3, A3 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, aa_set_a_set_a(aa_a_fun_set_a_set_a(insert_a, X3), A3)), B)) <=> (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X3), B)) & pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A3), B))))))). % Set.insert_subset

tff(fact_76_Set_OsubsetCE, axiom,
    ((![A : $i, A3 : set_a2, B : set_a2, C : a3]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A3), B)) => (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A3)) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B))))))). % Set.subsetCE

tff(fact_77_Set_OsubsetI, axiom,
    ((![A : $i, A3 : set_a2, B : set_a2]: ((![X4 : a3]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X4), A3)) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X4), B)))) => pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A3), B)))))). % Set.subsetI

tff(fact_78_Set_Osubset__antisym, axiom,
    ((![A : $i, A3 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A3), B)) => (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, B), A3)) => (A3 = B)))))). % Set.subset_antisym

tff(fact_79_Set__Interval_Oord__class_OatLeastAtMost__iff, axiom,
    ((![A : $i]: (ord(a3) => (![I : a3, L : a3, U : a3]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, I), aa_a_set_a(aa_a_fun_a_set_a(set_or1784915657Most_a, L), U))) <=> (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, L), I)) & pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, I), U))))))))). % Set_Interval.ord_class.atLeastAtMost_iff

tff(fact_80_Set__Interval_Oord__class_OatLeastLessThan__iff, axiom,
    ((![A : $i]: (ord(a3) => (![I : a3, L : a3, U : a3]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, I), aa_a_set_a(aa_a_fun_a_set_a(set_or2043508205Than_a, L), U))) <=> (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, L), I)) & pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, I), U))))))))). % Set_Interval.ord_class.atLeastLessThan_iff


% Type constructors (170)

tff(tcon_fun___Topological__Spaces_Otopological__space, axiom,
    ((![A4 : $i, A5 : $i]: (topolo503727757_space(a) => topolo503727757_space(fun_a_a))))).

tff(tcon_fun___Complete__Lattices_Ocomplete__lattice, axiom,
    ((![A4 : $i, A5 : $i]: (comple187826305attice(a) => comple187826305attice(fun_a_a))))).

tff(tcon_fun___Lattices_Osemilattice__inf, axiom,
    ((![A4 : $i, A5 : $i]: (semilattice_inf(a) => semilattice_inf(fun_a_a))))).

tff(tcon_fun___Orderings_Oorder__bot, axiom,
    ((![A4 : $i, A5 : $i]: (order_bot(a) => order_bot(fun_a_a))))).

tff(tcon_fun___Orderings_Opreorder, axiom,
    ((![A4 : $i, A5 : $i]: (preorder(a) => preorder(fun_a_a))))).

tff(tcon_fun___Orderings_Oord, axiom,
    ((![A4 : $i, A5 : $i]: (ord(a) => ord(fun_a_a))))).

tff(tcon_Num_Onum___Orderings_Opreorder_1, axiom,
    (preorder(num))).

tff(tcon_Num_Onum___Orderings_Olinorder, axiom,
    (linorder(num))).

tff(tcon_Num_Onum___Orderings_Oord_2, axiom,
    (ord(num))).

tff(tcon_Set_Oset___Complete__Lattices_Ocomplete__lattice_3, axiom,
    ((![A4 : $i]: comple187826305attice(set_a)))).

tff(tcon_Set_Oset___Lattices_Osemilattice__inf_4, axiom,
    ((![A4 : $i]: semilattice_inf(set_a)))).

tff(tcon_Set_Oset___Groups_Ocomm__monoid__mult, axiom,
    ((![A4 : $i]: (comm_monoid_mult(a2) => comm_monoid_mult(set_a))))).

tff(tcon_Set_Oset___Groups_Oab__semigroup__add, axiom,
    ((![A4 : $i]: (ab_semigroup_add(a2) => ab_semigroup_add(set_a))))).

tff(tcon_Set_Oset___Groups_Ocomm__monoid__add, axiom,
    ((![A4 : $i]: (comm_monoid_add(a2) => comm_monoid_add(set_a))))).

tff(tcon_Set_Oset___Orderings_Oorder__bot_5, axiom,
    ((![A4 : $i]: order_bot(set_a)))).

tff(tcon_Set_Oset___Orderings_Opreorder_6, axiom,
    ((![A4 : $i]: preorder(set_a)))).

tff(tcon_Set_Oset___Groups_Omonoid__mult, axiom,
    ((![A4 : $i]: (monoid_mult(a2) => monoid_mult(set_a))))).

tff(tcon_Set_Oset___Groups_Omonoid__add, axiom,
    ((![A4 : $i]: (monoid_add(a2) => monoid_add(set_a))))).

tff(tcon_Set_Oset___Orderings_Oord_7, axiom,
    ((![A4 : $i]: ord(set_a)))).

tff(tcon_HOL_Obool___Topological__Spaces_Otopological__space_8, axiom,
    (topolo503727757_space(bool))).

tff(tcon_HOL_Obool___Complete__Lattices_Ocomplete__lattice_9, axiom,
    (comple187826305attice(bool))).

tff(tcon_HOL_Obool___Lattices_Osemilattice__inf_10, axiom,
    (semilattice_inf(bool))).

tff(tcon_HOL_Obool___Orderings_Oorder__bot_11, axiom,
    (order_bot(bool))).

tff(tcon_HOL_Obool___Orderings_Opreorder_12, axiom,
    (preorder(bool))).

tff(tcon_HOL_Obool___Orderings_Olinorder_13, axiom,
    (linorder(bool))).

tff(tcon_HOL_Obool___Orderings_Oord_14, axiom,
    (ord(bool))).

tff(tcon_Real_Oreal___Groups_Oordered__cancel__ab__semigroup__add, axiom,
    (ordere223160158up_add(real))).

tff(tcon_Real_Oreal___Real__Vector__Spaces_Oreal__normed__vector, axiom,
    (real_V55928688vector(real))).

tff(tcon_Real_Oreal___Topological__Spaces_Otopological__space_15, axiom,
    (topolo503727757_space(real))).

tff(tcon_Real_Oreal___Topological__Spaces_Oopen__uniformity, axiom,
    (topolo254921306ormity(real))).

tff(tcon_Real_Oreal___Rings_Olinordered__nonzero__semiring, axiom,
    (linord1659791738miring(real))).

tff(tcon_Real_Oreal___Groups_Oordered__ab__semigroup__add, axiom,
    (ordere779506340up_add(real))).

tff(tcon_Real_Oreal___Euclidean__Space_Oeuclidean__space, axiom,
    (euclid925273238_space(real))).

tff(tcon_Real_Oreal___Real__Vector__Spaces_Oreal__vector, axiom,
    (real_V1076094709vector(real))).

tff(tcon_Real_Oreal___Groups_Ocancel__comm__monoid__add, axiom,
    (cancel1352612707id_add(real))).

tff(tcon_Real_Oreal___Rings_Olinordered__ring__strict, axiom,
    (linord581940658strict(real))).

tff(tcon_Real_Oreal___Groups_Oordered__ab__group__add, axiom,
    (ordered_ab_group_add(real))).

tff(tcon_Real_Oreal___Rings_Olinordered__semidom, axiom,
    (linordered_semidom(real))).

tff(tcon_Real_Oreal___Lattices_Osemilattice__inf_16, axiom,
    (semilattice_inf(real))).

tff(tcon_Real_Oreal___Inner__Product_Oreal__inner, axiom,
    (inner_real_inner(real))).

tff(tcon_Real_Oreal___Rings_Osemiring__1__cancel, axiom,
    (semiring_1_cancel(real))).

tff(tcon_Real_Oreal___Rings_Osemiring__0__cancel, axiom,
    (semiring_0_cancel(real))).

tff(tcon_Real_Oreal___Groups_Ocomm__monoid__mult_17, axiom,
    (comm_monoid_mult(real))).

tff(tcon_Real_Oreal___Groups_Oab__semigroup__add_18, axiom,
    (ab_semigroup_add(real))).

tff(tcon_Real_Oreal___Groups_Ocomm__monoid__add_19, axiom,
    (comm_monoid_add(real))).

tff(tcon_Real_Oreal___Rings_Olinordered__ring, axiom,
    (linordered_ring(real))).

tff(tcon_Real_Oreal___Rings_Olinordered__idom, axiom,
    (linordered_idom(real))).

tff(tcon_Real_Oreal___Rings_Ocomm__semiring__1, axiom,
    (comm_semiring_1(real))).

tff(tcon_Real_Oreal___Num_Osemiring__numeral, axiom,
    (semiring_numeral(real))).

tff(tcon_Real_Oreal___Rings_Ozero__less__one, axiom,
    (zero_less_one(real))).

tff(tcon_Real_Oreal___Groups_Oab__group__add, axiom,
    (ab_group_add(real))).

tff(tcon_Real_Oreal___Rings_Oordered__ring, axiom,
    (ordered_ring(real))).

tff(tcon_Real_Oreal___Orderings_Opreorder_20, axiom,
    (preorder(real))).

tff(tcon_Real_Oreal___Orderings_Olinorder_21, axiom,
    (linorder(real))).

tff(tcon_Real_Oreal___Groups_Omonoid__mult_22, axiom,
    (monoid_mult(real))).

tff(tcon_Real_Oreal___Rings_Ocomm__ring__1, axiom,
    (comm_ring_1(real))).

tff(tcon_Real_Oreal___Groups_Omonoid__add_23, axiom,
    (monoid_add(real))).

tff(tcon_Real_Oreal___Rings_Osemiring__1, axiom,
    (semiring_1(real))).

tff(tcon_Real_Oreal___Rings_Omult__zero, axiom,
    (mult_zero(real))).

tff(tcon_Real_Oreal___Rings_Ocomm__ring, axiom,
    (comm_ring(real))).

tff(tcon_Real_Oreal___Num_Oneg__numeral, axiom,
    (neg_numeral(real))).

tff(tcon_Real_Oreal___Orderings_Oord_24, axiom,
    (ord(real))).

tff(tcon_Real_Oreal___Rings_Oring__1, axiom,
    (ring_1(real))).

tff(tcon_Real_Oreal___Num_Onumeral, axiom,
    (numeral(real))).

tff(tcon_Real_Oreal___Rings_Oring, axiom,
    (ring(real))).

tff(tcon_Complex_Ocomplex___Groups_Oordered__cancel__ab__semigroup__add_25, axiom,
    (ordere223160158up_add(complex))).

tff(tcon_Complex_Ocomplex___Real__Vector__Spaces_Oreal__normed__vector_26, axiom,
    (real_V55928688vector(complex))).

tff(tcon_Complex_Ocomplex___Topological__Spaces_Otopological__space_27, axiom,
    (topolo503727757_space(complex))).

tff(tcon_Complex_Ocomplex___Topological__Spaces_Oopen__uniformity_28, axiom,
    (topolo254921306ormity(complex))).

tff(tcon_Complex_Ocomplex___Groups_Oordered__ab__semigroup__add_29, axiom,
    (ordere779506340up_add(complex))).

tff(tcon_Complex_Ocomplex___Euclidean__Space_Oeuclidean__space_30, axiom,
    (euclid925273238_space(complex))).

tff(tcon_Complex_Ocomplex___Real__Vector__Spaces_Oreal__vector_31, axiom,
    (real_V1076094709vector(complex))).

tff(tcon_Complex_Ocomplex___Groups_Ocancel__comm__monoid__add_32, axiom,
    (cancel1352612707id_add(complex))).

tff(tcon_Complex_Ocomplex___Groups_Oordered__ab__group__add_33, axiom,
    (ordered_ab_group_add(complex))).

tff(tcon_Complex_Ocomplex___Inner__Product_Oreal__inner_34, axiom,
    (inner_real_inner(complex))).

tff(tcon_Complex_Ocomplex___Rings_Osemiring__1__cancel_35, axiom,
    (semiring_1_cancel(complex))).

tff(tcon_Complex_Ocomplex___Rings_Osemiring__0__cancel_36, axiom,
    (semiring_0_cancel(complex))).

tff(tcon_Complex_Ocomplex___Groups_Ocomm__monoid__mult_37, axiom,
    (comm_monoid_mult(complex))).

tff(tcon_Complex_Ocomplex___Groups_Oab__semigroup__add_38, axiom,
    (ab_semigroup_add(complex))).

tff(tcon_Complex_Ocomplex___Groups_Ocomm__monoid__add_39, axiom,
    (comm_monoid_add(complex))).

tff(tcon_Complex_Ocomplex___Rings_Ocomm__semiring__1_40, axiom,
    (comm_semiring_1(complex))).

tff(tcon_Complex_Ocomplex___Num_Osemiring__numeral_41, axiom,
    (semiring_numeral(complex))).

tff(tcon_Complex_Ocomplex___Groups_Oab__group__add_42, axiom,
    (ab_group_add(complex))).

tff(tcon_Complex_Ocomplex___Rings_Oordered__ring_43, axiom,
    (ordered_ring(complex))).

tff(tcon_Complex_Ocomplex___Orderings_Opreorder_44, axiom,
    (preorder(complex))).

tff(tcon_Complex_Ocomplex___Groups_Omonoid__mult_45, axiom,
    (monoid_mult(complex))).

tff(tcon_Complex_Ocomplex___Rings_Ocomm__ring__1_46, axiom,
    (comm_ring_1(complex))).

tff(tcon_Complex_Ocomplex___Groups_Omonoid__add_47, axiom,
    (monoid_add(complex))).

tff(tcon_Complex_Ocomplex___Rings_Osemiring__1_48, axiom,
    (semiring_1(complex))).

tff(tcon_Complex_Ocomplex___Rings_Omult__zero_49, axiom,
    (mult_zero(complex))).

tff(tcon_Complex_Ocomplex___Rings_Ocomm__ring_50, axiom,
    (comm_ring(complex))).

tff(tcon_Complex_Ocomplex___Num_Oneg__numeral_51, axiom,
    (neg_numeral(complex))).

tff(tcon_Complex_Ocomplex___Orderings_Oord_52, axiom,
    (ord(complex))).

tff(tcon_Complex_Ocomplex___Rings_Oring__1_53, axiom,
    (ring_1(complex))).

tff(tcon_Complex_Ocomplex___Num_Onumeral_54, axiom,
    (numeral(complex))).

tff(tcon_Complex_Ocomplex___Rings_Oring_55, axiom,
    (ring(complex))).

tff(tcon_Code__Numeral_Ointeger___Groups_Oordered__cancel__ab__semigroup__add_56, axiom,
    (ordere223160158up_add(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Rings_Olinordered__nonzero__semiring_57, axiom,
    (linord1659791738miring(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Groups_Oordered__ab__semigroup__add_58, axiom,
    (ordere779506340up_add(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Groups_Ocancel__comm__monoid__add_59, axiom,
    (cancel1352612707id_add(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Rings_Olinordered__ring__strict_60, axiom,
    (linord581940658strict(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Groups_Oordered__ab__group__add_61, axiom,
    (ordered_ab_group_add(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Rings_Olinordered__semidom_62, axiom,
    (linordered_semidom(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Rings_Osemiring__1__cancel_63, axiom,
    (semiring_1_cancel(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Rings_Osemiring__0__cancel_64, axiom,
    (semiring_0_cancel(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Groups_Ocomm__monoid__mult_65, axiom,
    (comm_monoid_mult(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Groups_Oab__semigroup__add_66, axiom,
    (ab_semigroup_add(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Groups_Ocomm__monoid__add_67, axiom,
    (comm_monoid_add(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Rings_Olinordered__ring_68, axiom,
    (linordered_ring(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Rings_Olinordered__idom_69, axiom,
    (linordered_idom(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Rings_Ocomm__semiring__1_70, axiom,
    (comm_semiring_1(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Num_Osemiring__numeral_71, axiom,
    (semiring_numeral(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Rings_Ozero__less__one_72, axiom,
    (zero_less_one(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Groups_Oab__group__add_73, axiom,
    (ab_group_add(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Rings_Oordered__ring_74, axiom,
    (ordered_ring(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Orderings_Opreorder_75, axiom,
    (preorder(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Orderings_Olinorder_76, axiom,
    (linorder(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Groups_Omonoid__mult_77, axiom,
    (monoid_mult(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Rings_Ocomm__ring__1_78, axiom,
    (comm_ring_1(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Groups_Omonoid__add_79, axiom,
    (monoid_add(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Rings_Osemiring__1_80, axiom,
    (semiring_1(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Rings_Omult__zero_81, axiom,
    (mult_zero(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Rings_Ocomm__ring_82, axiom,
    (comm_ring(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Num_Oneg__numeral_83, axiom,
    (neg_numeral(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Orderings_Oord_84, axiom,
    (ord(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Rings_Oring__1_85, axiom,
    (ring_1(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Num_Onumeral_86, axiom,
    (numeral(code_integer))).

tff(tcon_Code__Numeral_Ointeger___Rings_Oring_87, axiom,
    (ring(code_integer))).

tff(tcon_Code__Numeral_Onatural___Groups_Oordered__cancel__ab__semigroup__add_88, axiom,
    (ordere223160158up_add(code_natural))).

tff(tcon_Code__Numeral_Onatural___Rings_Olinordered__nonzero__semiring_89, axiom,
    (linord1659791738miring(code_natural))).

tff(tcon_Code__Numeral_Onatural___Groups_Oordered__ab__semigroup__add_90, axiom,
    (ordere779506340up_add(code_natural))).

tff(tcon_Code__Numeral_Onatural___Groups_Ocancel__comm__monoid__add_91, axiom,
    (cancel1352612707id_add(code_natural))).

tff(tcon_Code__Numeral_Onatural___Rings_Olinordered__semidom_92, axiom,
    (linordered_semidom(code_natural))).

tff(tcon_Code__Numeral_Onatural___Rings_Osemiring__1__cancel_93, axiom,
    (semiring_1_cancel(code_natural))).

tff(tcon_Code__Numeral_Onatural___Rings_Osemiring__0__cancel_94, axiom,
    (semiring_0_cancel(code_natural))).

tff(tcon_Code__Numeral_Onatural___Groups_Ocomm__monoid__mult_95, axiom,
    (comm_monoid_mult(code_natural))).

tff(tcon_Code__Numeral_Onatural___Groups_Oab__semigroup__add_96, axiom,
    (ab_semigroup_add(code_natural))).

tff(tcon_Code__Numeral_Onatural___Groups_Ocomm__monoid__add_97, axiom,
    (comm_monoid_add(code_natural))).

tff(tcon_Code__Numeral_Onatural___Rings_Ocomm__semiring__1_98, axiom,
    (comm_semiring_1(code_natural))).

tff(tcon_Code__Numeral_Onatural___Num_Osemiring__numeral_99, axiom,
    (semiring_numeral(code_natural))).

tff(tcon_Code__Numeral_Onatural___Rings_Ozero__less__one_100, axiom,
    (zero_less_one(code_natural))).

tff(tcon_Code__Numeral_Onatural___Orderings_Opreorder_101, axiom,
    (preorder(code_natural))).

tff(tcon_Code__Numeral_Onatural___Orderings_Olinorder_102, axiom,
    (linorder(code_natural))).

tff(tcon_Code__Numeral_Onatural___Groups_Omonoid__mult_103, axiom,
    (monoid_mult(code_natural))).

tff(tcon_Code__Numeral_Onatural___Groups_Omonoid__add_104, axiom,
    (monoid_add(code_natural))).

tff(tcon_Code__Numeral_Onatural___Rings_Osemiring__1_105, axiom,
    (semiring_1(code_natural))).

tff(tcon_Code__Numeral_Onatural___Rings_Omult__zero_106, axiom,
    (mult_zero(code_natural))).

tff(tcon_Code__Numeral_Onatural___Orderings_Oord_107, axiom,
    (ord(code_natural))).

tff(tcon_Code__Numeral_Onatural___Num_Onumeral_108, axiom,
    (numeral(code_natural))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Groups_Ocanonically__ordered__monoid__add, axiom,
    (canoni770627133id_add(extend1728876344nnreal))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Topological__Spaces_Otopological__space_109, axiom,
    (topolo503727757_space(extend1728876344nnreal))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Complete__Lattices_Ocomplete__lattice_110, axiom,
    (comple187826305attice(extend1728876344nnreal))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Rings_Olinordered__nonzero__semiring_111, axiom,
    (linord1659791738miring(extend1728876344nnreal))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Groups_Oordered__ab__semigroup__add_112, axiom,
    (ordere779506340up_add(extend1728876344nnreal))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Lattices_Osemilattice__inf_113, axiom,
    (semilattice_inf(extend1728876344nnreal))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Groups_Ocomm__monoid__mult_114, axiom,
    (comm_monoid_mult(extend1728876344nnreal))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Groups_Oab__semigroup__add_115, axiom,
    (ab_semigroup_add(extend1728876344nnreal))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Groups_Ocomm__monoid__add_116, axiom,
    (comm_monoid_add(extend1728876344nnreal))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Rings_Ocomm__semiring__1_117, axiom,
    (comm_semiring_1(extend1728876344nnreal))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Num_Osemiring__numeral_118, axiom,
    (semiring_numeral(extend1728876344nnreal))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Rings_Ozero__less__one_119, axiom,
    (zero_less_one(extend1728876344nnreal))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Orderings_Oorder__bot_120, axiom,
    (order_bot(extend1728876344nnreal))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Orderings_Opreorder_121, axiom,
    (preorder(extend1728876344nnreal))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Orderings_Olinorder_122, axiom,
    (linorder(extend1728876344nnreal))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Groups_Omonoid__mult_123, axiom,
    (monoid_mult(extend1728876344nnreal))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Groups_Omonoid__add_124, axiom,
    (monoid_add(extend1728876344nnreal))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Rings_Osemiring__1_125, axiom,
    (semiring_1(extend1728876344nnreal))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Rings_Omult__zero_126, axiom,
    (mult_zero(extend1728876344nnreal))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Orderings_Oord_127, axiom,
    (ord(extend1728876344nnreal))).

tff(tcon_Extended__Nonnegative__Real_Oennreal___Num_Onumeral_128, axiom,
    (numeral(extend1728876344nnreal))).


% Helper facts (2)

tff(help_pp_2_1_U, axiom,
    (pp(fTrue))).

tff(help_pp_1_1_U, axiom,
    ((~ (pp(fFalse))))).


% Conjectures (7)

tff(conj_0, hypothesis,
    ((![A : $i]: (euclid925273238_space(a3) => (![B_1 : set_a2]: pp(aa_set_a_bool(geotop1661465655line_a, B_1))))))).

tff(conj_1, hypothesis,
    ((![A : $i]: (euclid925273238_space(a3) => (![B_2 : set_a2]: pp(aa_set_a_bool(geotop1661465655line_a, B_2))))))).

tff(conj_2, hypothesis,
    ((![A : $i]: (euclid925273238_space(a3) => (![P : a3, B_1 : set_a2]: pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, P), B_1))))))).

tff(conj_3, hypothesis,
    ((![A : $i]: (euclid925273238_space(a3) => (![Q_0 : a3, B_1 : set_a2]: pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, Q_0), B_1))))))).

tff(conj_4, hypothesis,
    ((![A : $i]: (euclid925273238_space(a3) => (![Q_0 : a3, B_2 : set_a2]: pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, Q_0), B_2))))))).

tff(conj_5, hypothesis,
    ((![A : $i]: (euclid925273238_space(a3) => (![Q : a3, B_2 : set_a2]: pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, Q), B_2))))))).

tff(conj_6, conjecture,
    ((![A : $i]: (euclid925273238_space(a3) => (![B_1 : set_a2, B_2 : set_a2, P : a3, Q : a3]: (?[B5 : set_a2]: (pp(aa_set_a_bool(geotop1661465655line_a, B5)) & (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, B5), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, B_1), B_2))) & (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, P), B5)) & pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, Q), B5))))))))))).

