% This file was generated by Isabelle (most likely Sledgehammer)

% Could-be-implicit typings (8)

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J, type,
    fun_set_set_a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    fun_set_a_bool : $tType).

tff(ty_n_t__Set__Oset_It__Set__Oset_IT__a_J_J, type,
    set_set_a : $tType).

tff(ty_n_t__fun_IT__a_Mt__HOL__Obool_J, type,
    fun_a_bool : $tType).

tff(ty_n_t__Set__Oset_IT__a_J, type,
    set_a : $tType).

tff(ty_n_t__HOL__Obool, type,
    bool : $tType).

tff(ty_n_T__a, type,
    a : $tType).

tff(sy_cl_Euclidean__Space_Oeuclidean__space, type,
    euclid925273238_space : !>[A : $tType]: $o).


% Explicit typings (19)

tff(sy_c_ATP_058Lamm__a, type,
    aTP_Lamm_a : set_a > fun_set_a_bool).

tff(sy_c_ATP_058Lamm__aa, type,
    aTP_Lamm_aa : set_a > fun_set_a_bool).

tff(sy_c_Finite__Set_Ofinite_001T__a, type,
    finite_finite_a : fun_set_a_bool).

tff(sy_c_Finite__Set_Ofinite_001t__Set__Oset_IT__a_J, type,
    finite_finite_set_a : fun_set_set_a_bool).

tff(sy_c_GeoTopBase0_Ogeotop__cell_001T__a, type,
    geotop_cell_a : fun_set_a_bool).

tff(sy_c_GeoTopBase0_Ogeotop__cell__face_001T__a, type,
    geotop_cell_face_a : set_a > fun_set_a_bool).

tff(sy_c_Orderings_Obot__class_Obot_001t__Set__Oset_IT__a_J, type,
    bot_bot_set_a : set_a).

tff(sy_c_Orderings_Oord__class_Oless__eq_001t__Set__Oset_IT__a_J, type,
    ord_less_eq_set_a : set_a > fun_set_a_bool).

tff(sy_c_Polytope_Oface__of_001T__a, type,
    face_of_a : set_a > fun_set_a_bool).

tff(sy_c_Polytope_Opolytope_001T__a, type,
    polytope_a : fun_set_a_bool).

tff(sy_c_Set_OCollect_001T__a, type,
    collect_a : fun_a_bool > set_a).

tff(sy_c_Set_OCollect_001t__Set__Oset_IT__a_J, type,
    collect_set_a : fun_set_a_bool > set_set_a).

tff(sy_c_aa_001T__a_001t__HOL__Obool, type,
    aa_a_bool : (fun_a_bool * a) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__HOL__Obool, type,
    aa_set_a_bool : (fun_set_a_bool * set_a) > bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__HOL__Obool, type,
    aa_set_set_a_bool : (fun_set_set_a_bool * set_set_a) > bool).

tff(sy_c_fFalse, type,
    fFalse : bool).

tff(sy_c_fTrue, type,
    fTrue : bool).

tff(sy_c_member_001T__a, type,
    member_a : a > fun_set_a_bool).

tff(sy_c_pp, type,
    pp : bool > $o).


% Relevant facts (13)

tff(fact_0_Finite__Set_Ofinite__subset, axiom,
    ((![A : $i, A2 : set_a, B : set_a]: (pp(aa_set_a_bool(ord_less_eq_set_a(A2), B)) => (pp(aa_set_a_bool(finite_finite_a, B)) => pp(aa_set_a_bool(finite_finite_a, A2))))))). % Finite_Set.finite_subset

tff(fact_1_GeoTopBase0_Ogeotop__cell__def, axiom,
    ((![A : $i]: (euclid925273238_space(a) => (![C : set_a]: (pp(aa_set_a_bool(geotop_cell_a, C)) <=> ((C != bot_bot_set_a) & pp(aa_set_a_bool(polytope_a, C))))))))). % GeoTopBase0.geotop_cell_def

tff(fact_2_GeoTopBase0_Ogeotop__cell__face__def, axiom,
    ((![A : $i]: (euclid925273238_space(a) => (![F : set_a, C : set_a]: (pp(aa_set_a_bool(geotop_cell_face_a(F), C)) <=> (pp(aa_set_a_bool(geotop_cell_a, C)) & ((F != bot_bot_set_a) & pp(aa_set_a_bool(face_of_a(F), C)))))))))). % GeoTopBase0.geotop_cell_face_def

tff(fact_3_HOL_OallE, axiom,
    ((![A : $i, P : fun_a_bool, X : a]: ((![X_1 : a]: pp(aa_a_bool(P, X_1))) => pp(aa_a_bool(P, X)))))). % HOL.allE

tff(fact_4_HOL_OconjE, axiom,
    ((![P : bool, Q : bool]: ((pp(P) & pp(Q)) => (~ ((pp(P) => (~ (pp(Q)))))))))). % HOL.conjE

tff(fact_5_Polytope_Ofinite__polytope__faces, axiom,
    ((![A : $i]: (euclid925273238_space(a) => (![S : set_a]: (pp(aa_set_a_bool(polytope_a, S)) => pp(aa_set_set_a_bool(finite_finite_set_a, collect_set_a(aTP_Lamm_aa(S)))))))))). % Polytope.finite_polytope_faces

tff(fact_6_Set_Oempty__subsetI, axiom,
    ((![A : $i, A2 : set_a]: pp(aa_set_a_bool(ord_less_eq_set_a(bot_bot_set_a), A2))))). % Set.empty_subsetI

tff(fact_7_Set_Omem__Collect__eq, axiom,
    ((![A : $i, A3 : a, P : fun_a_bool]: (pp(aa_set_a_bool(member_a(A3), collect_a(P))) <=> pp(aa_a_bool(P, A3)))))). % Set.mem_Collect_eq

tff(fact_8_Set_OsubsetCE, axiom,
    ((![A : $i, A2 : set_a, B : set_a, C2 : a]: (pp(aa_set_a_bool(ord_less_eq_set_a(A2), B)) => (pp(aa_set_a_bool(member_a(C2), A2)) => pp(aa_set_a_bool(member_a(C2), B))))))). % Set.subsetCE

tff(fact_9_Set_OsubsetI, axiom,
    ((![A : $i, A2 : set_a, B : set_a]: ((![X2 : a]: (pp(aa_set_a_bool(member_a(X2), A2)) => pp(aa_set_a_bool(member_a(X2), B)))) => pp(aa_set_a_bool(ord_less_eq_set_a(A2), B)))))). % Set.subsetI

tff(fact_10_Set_Osubset__antisym, axiom,
    ((![A : $i, A2 : set_a, B : set_a]: (pp(aa_set_a_bool(ord_less_eq_set_a(A2), B)) => (pp(aa_set_a_bool(ord_less_eq_set_a(B), A2)) => (A2 = B)))))). % Set.subset_antisym

tff(fact_11_ATP_Olambda__1, axiom,
    ((![A : $i]: (euclid925273238_space(a) => (![Uu : set_a, Uua : set_a]: (pp(aa_set_a_bool(aTP_Lamm_a(Uu), Uua)) <=> pp(aa_set_a_bool(geotop_cell_face_a(Uua), Uu)))))))). % ATP.lambda_1

tff(fact_12_ATP_Olambda__2, axiom,
    ((![A : $i]: (euclid925273238_space(a) => (![Uu : set_a, Uua : set_a]: (pp(aa_set_a_bool(aTP_Lamm_aa(Uu), Uua)) <=> pp(aa_set_a_bool(face_of_a(Uua), Uu)))))))). % ATP.lambda_2


% Helper facts (2)

tff(help_pp_2_1_U, axiom,
    (pp(fTrue))).

tff(help_pp_1_1_U, axiom,
    ((~ (pp(fFalse))))).


% Conjectures (1)

tff(conj_0, conjecture,
    ((![A : $i]: (euclid925273238_space(a) => (![C : set_a]: (pp(aa_set_a_bool(geotop_cell_a, C)) => pp(aa_set_set_a_bool(finite_finite_set_a, collect_set_a(aTP_Lamm_a(C)))))))))).

