% This file was generated by Isabelle (most likely Sledgehammer)
2026-06-02 20:25:07.950

% Could-be-implicit typings (55)

tff(ty_n_t__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__fun_It__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_Mt__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_J_J_J, type,
    fun_se1183457475l_real : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__fun_It__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_Mt__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_J_J, type,
    fun_se65565453l_real : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__fun_It__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_Mt__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__HOL__Obool_J_J_J, type,
    fun_se902853700l_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_Mt__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_J_J, type,
    fun_se967240206l_real : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_Mt__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_J, type,
    fun_se1563367768l_real : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_J, type,
    fun_se312934050l_real : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_Mt__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__HOL__Obool_J_J, type,
    fun_se1892890531l_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__fun_It__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_Mt__HOL__Obool_J_J, type,
    fun_se1637999779l_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_J, type,
    fun_se2059335971l_real : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J, type,
    fun_se1436921197l_real : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_Mt__HOL__Obool_J, type,
    fun_se470987138l_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__HOL__Obool_J, type,
    fun_se274450104l_bool : $tType).

tff(ty_n_t__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J, type,
    set_se911849070l_real : $tType).

tff(ty_n_t__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J, type,
    set_Pr1930119096l_real : $tType).

tff(ty_n_t__fun_It__fun_IT__a_MT__b_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_MT__b_J_J_J, type,
    fun_fu391738216un_a_b : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J_J, type,
    fun_se1395821270_set_a : $tType).

tff(ty_n_t__fun_It__fun_IT__a_Mt__HOL__Obool_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_fun_a_bool_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J, type,
    fun_set_a_fun_a_bool : $tType).

tff(ty_n_t__fun_IT__e_Mt__fun_It__Set__Oset_IT__e_J_Mt__HOL__Obool_J_J, type,
    fun_e_fun_set_e_bool : $tType).

tff(ty_n_t__fun_IT__c_Mt__fun_It__Set__Oset_IT__c_J_Mt__HOL__Obool_J_J, type,
    fun_c_fun_set_c_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J, type,
    fun_a_fun_set_a_bool : $tType).

tff(ty_n_t__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_MT__b_J_J, type,
    fun_fun_a_b_fun_a_b : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_set_a_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__e_J_Mt__HOL__Obool_J, type,
    fun_set_e_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__c_J_Mt__HOL__Obool_J, type,
    fun_set_c_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    fun_set_a_bool : $tType).

tff(ty_n_t__Product____Type__Oprod_IT__a__1_MT__a__2_J, type,
    product_prod_a_a : $tType).

tff(ty_n_t__fun_IT__b_Mt__fun_IT__b_MT__b_J_J, type,
    fun_b_fun_b_b : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_IT__a_MT__a_J_J, type,
    fun_a_fun_a_a : $tType).

tff(ty_n_t__fun_IT__e_Mt__HOL__Obool_J, type,
    fun_e_bool : $tType).

tff(ty_n_t__fun_IT__c_Mt__HOL__Obool_J, type,
    fun_c_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__HOL__Obool_J, type,
    fun_a_bool : $tType).

tff(ty_n_t__fun_IT__a__1_MT__a__2_J, type,
    fun_a_a : $tType).

tff(ty_n_t__Set__Oset_IT__a__1_J, type,
    set_a : $tType).

tff(ty_n_t__fun_IT__b_MT__b_J, type,
    fun_b_b : $tType).

tff(ty_n_t__fun_IT__a_MT__b_J, type,
    fun_a_b : $tType).

tff(ty_n_t__fun_IT__a_MT__a_J, type,
    fun_a_a2 : $tType).

tff(ty_n_t__Set__Oset_IT__e_J, type,
    set_e : $tType).

tff(ty_n_t__Set__Oset_IT__c_J, type,
    set_c : $tType).

tff(ty_n_t__Set__Oset_IT__a_J, type,
    set_a2 : $tType).

tff(ty_n_t__Real__Oreal, type,
    real : $tType).

tff(ty_n_t__HOL__Obool, type,
    bool : $tType).

tff(ty_n_T__a__2, type,
    a : $tType).

tff(ty_n_T__a__1, type,
    a2 : $tType).

tff(ty_n_T__e, type,
    e : $tType).

tff(ty_n_T__c, type,
    c : $tType).

tff(ty_n_T__b, type,
    b : $tType).

tff(ty_n_T__a, type,
    a3 : $tType).

tff(sy_cl_Lattices_Obounded__semilattice__sup__bot, type,
    bounde1808546759up_bot : !>[A : $tType]: $o).

tff(sy_cl_Lattices_Obounded__lattice__bot, type,
    bounded_lattice_bot : !>[A : $tType]: $o).

tff(sy_cl_Lattices_Osemilattice__sup, type,
    semilattice_sup : !>[A : $tType]: $o).

tff(sy_cl_Lattices_Osemilattice__inf, type,
    semilattice_inf : !>[A : $tType]: $o).

tff(sy_cl_Lattices_Obounded__lattice, type,
    bounded_lattice : !>[A : $tType]: $o).

tff(sy_cl_Lattices_Olattice, type,
    lattice : !>[A : $tType]: $o).

tff(sy_cl_Groups_Ominus, type,
    minus : !>[A : $tType]: $o).


% Explicit typings (66)

tff(sy_c_ATP_058Lamm__a, type,
    aTP_Lamm_a : fun_set_a_fun_a_bool).

tff(sy_c_AlgTop__JCT__Base_Otop1__S2, type,
    algTop_JCT_top1_S2 : set_Pr1930119096l_real).

tff(sy_c_AlgTop__JCT__Base_Otop1__S2__topology, type,
    algTop1528072561pology : set_se911849070l_real).

tff(sy_c_AlgTop__JCT__Base_Otop1__simple__closed__curve__on_001t__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J, type,
    algTop2095930224l_real : fun_se902853700l_bool).

tff(sy_c_Groups_Ominus__class_Ominus_001T__b, type,
    minus_minus_b : fun_b_fun_b_b).

tff(sy_c_Groups_Ominus__class_Ominus_001t__Set__Oset_IT__a_J, type,
    minus_minus_set_a : fun_se1395821270_set_a).

tff(sy_c_Groups_Ominus__class_Ominus_001t__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J, type,
    minus_1145959313l_real : fun_se312934050l_real).

tff(sy_c_Groups_Ominus__class_Ominus_001t__fun_IT__a_MT__b_J, type,
    minus_minus_fun_a_b : fun_fu391738216un_a_b).

tff(sy_c_Lattices_Oinf__class_Oinf_001T__a, type,
    inf_inf_a : fun_a_fun_a_a).

tff(sy_c_Lattices_Oinf__class_Oinf_001T__b, type,
    inf_inf_b : fun_b_fun_b_b).

tff(sy_c_Lattices_Oinf__class_Oinf_001t__Set__Oset_IT__a_J, type,
    inf_inf_set_a : fun_se1395821270_set_a).

tff(sy_c_Lattices_Oinf__class_Oinf_001t__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J, type,
    inf_in619654218l_real : fun_se312934050l_real).

tff(sy_c_Lattices_Oinf__class_Oinf_001t__fun_IT__a_MT__b_J, type,
    inf_inf_fun_a_b : fun_fu391738216un_a_b).

tff(sy_c_Lattices_Osup__class_Osup_001T__a, type,
    sup_sup_a : fun_a_fun_a_a).

tff(sy_c_Lattices_Osup__class_Osup_001T__b, type,
    sup_sup_b : fun_b_fun_b_b).

tff(sy_c_Lattices_Osup__class_Osup_001t__Set__Oset_IT__a_J, type,
    sup_sup_set_a : fun_se1395821270_set_a).

tff(sy_c_Lattices_Osup__class_Osup_001t__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J, type,
    sup_su69286116l_real : fun_se312934050l_real).

tff(sy_c_Lattices_Osup__class_Osup_001t__fun_IT__a_MT__b_J, type,
    sup_sup_fun_a_b : fun_fu391738216un_a_b).

tff(sy_c_Orderings_Obot__class_Obot_001T__a, type,
    bot_bot_a : a3).

tff(sy_c_Orderings_Obot__class_Obot_001t__Set__Oset_IT__a_J, type,
    bot_bot_set_a : set_a2).

tff(sy_c_Orderings_Obot__class_Obot_001t__Set__Oset_IT__c_J, type,
    bot_bot_set_c : set_c).

tff(sy_c_Orderings_Obot__class_Obot_001t__Set__Oset_IT__e_J, type,
    bot_bot_set_e : set_e).

tff(sy_c_Orderings_Obot__class_Obot_001t__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J, type,
    bot_bo307885644l_real : set_Pr1930119096l_real).

tff(sy_c_Set_OCollect_001T__a, type,
    collect_a : fun_fun_a_bool_set_a).

tff(sy_c_Top1__Ch2_Oclosure__on_001t__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J, type,
    top1_c223158040l_real : fun_se65565453l_real).

tff(sy_c_Top1__Ch2_Osubspace__topology_001t__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J, type,
    top1_s1666726429l_real : fun_se1183457475l_real).

tff(sy_c_Top1__Ch3_Otop1__connected__on_001t__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J, type,
    top1_t2008947945l_real : fun_se1637999779l_bool).

tff(sy_c_aa_001T__a_001T__a, type,
    aa_a_a : (fun_a_a2 * a3) > a3).

tff(sy_c_aa_001T__a_001T__b, type,
    aa_a_b : (fun_a_b * a3) > b).

tff(sy_c_aa_001T__a_001t__HOL__Obool, type,
    aa_a_bool : (fun_a_bool * a3) > bool).

tff(sy_c_aa_001T__a_001t__fun_IT__a_MT__a_J, type,
    aa_a_fun_a_a : (fun_a_fun_a_a * a3) > fun_a_a2).

tff(sy_c_aa_001T__a_001t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    aa_a_fun_set_a_bool : (fun_a_fun_set_a_bool * a3) > fun_set_a_bool).

tff(sy_c_aa_001T__b_001T__b, type,
    aa_b_b : (fun_b_b * b) > b).

tff(sy_c_aa_001T__b_001t__fun_IT__b_MT__b_J, type,
    aa_b_fun_b_b : (fun_b_fun_b_b * b) > fun_b_b).

tff(sy_c_aa_001T__c_001t__HOL__Obool, type,
    aa_c_bool : (fun_c_bool * c) > bool).

tff(sy_c_aa_001T__c_001t__fun_It__Set__Oset_IT__c_J_Mt__HOL__Obool_J, type,
    aa_c_fun_set_c_bool : (fun_c_fun_set_c_bool * c) > fun_set_c_bool).

tff(sy_c_aa_001T__e_001t__HOL__Obool, type,
    aa_e_bool : (fun_e_bool * e) > bool).

tff(sy_c_aa_001T__e_001t__fun_It__Set__Oset_IT__e_J_Mt__HOL__Obool_J, type,
    aa_e_fun_set_e_bool : (fun_e_fun_set_e_bool * e) > fun_set_e_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__HOL__Obool, type,
    aa_set_a_bool : (fun_set_a_bool * set_a2) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__Set__Oset_IT__a_J, type,
    aa_set_a_set_a : (fun_set_a_set_a * set_a2) > set_a2).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_IT__a_Mt__HOL__Obool_J, type,
    aa_set_a_fun_a_bool : (fun_set_a_fun_a_bool * set_a2) > fun_a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J, type,
    aa_set363163287_set_a : (fun_se1395821270_set_a * set_a2) > fun_set_a_set_a).

tff(sy_c_aa_001t__Set__Oset_IT__c_J_001t__HOL__Obool, type,
    aa_set_c_bool : (fun_set_c_bool * set_c) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__e_J_001t__HOL__Obool, type,
    aa_set_e_bool : (fun_set_e_bool * set_e) > bool).

tff(sy_c_aa_001t__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_001t__HOL__Obool, type,
    aa_set428719265l_bool : (fun_se274450104l_bool * set_Pr1930119096l_real) > bool).

tff(sy_c_aa_001t__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_001t__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J, type,
    aa_set1050760878l_real : (fun_se1436921197l_real * set_Pr1930119096l_real) > set_Pr1930119096l_real).

tff(sy_c_aa_001t__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_001t__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J, type,
    aa_set1376316772l_real : (fun_se2059335971l_real * set_Pr1930119096l_real) > set_se911849070l_real).

tff(sy_c_aa_001t__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_001t__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J, type,
    aa_set2073708131l_real : (fun_se312934050l_real * set_Pr1930119096l_real) > fun_se1436921197l_real).

tff(sy_c_aa_001t__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_001t__fun_It__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_Mt__HOL__Obool_J, type,
    aa_set1201437708l_bool : (fun_se1637999779l_bool * set_Pr1930119096l_real) > fun_se470987138l_bool).

tff(sy_c_aa_001t__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_001t__fun_It__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_Mt__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__HOL__Obool_J_J, type,
    aa_set612694061l_bool : (fun_se902853700l_bool * set_Pr1930119096l_real) > fun_se1892890531l_bool).

tff(sy_c_aa_001t__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_001t__fun_It__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_Mt__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_J, type,
    aa_set1262576718l_real : (fun_se65565453l_real * set_Pr1930119096l_real) > fun_se1563367768l_real).

tff(sy_c_aa_001t__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_001t__fun_It__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_Mt__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_J_J, type,
    aa_set149052676l_real : (fun_se1183457475l_real * set_Pr1930119096l_real) > fun_se967240206l_real).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_001t__HOL__Obool, type,
    aa_set374130539l_bool : (fun_se470987138l_bool * set_se911849070l_real) > bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_001t__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__HOL__Obool_J, type,
    aa_set914061836l_bool : (fun_se1892890531l_bool * set_se911849070l_real) > fun_se274450104l_bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_001t__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J, type,
    aa_set680673561l_real : (fun_se1563367768l_real * set_se911849070l_real) > fun_se1436921197l_real).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_001t__fun_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_Mt__Set__Oset_It__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J_J_J, type,
    aa_set858184911l_real : (fun_se967240206l_real * set_se911849070l_real) > fun_se2059335971l_real).

tff(sy_c_aa_001t__fun_IT__a_MT__b_J_001t__fun_IT__a_MT__b_J, type,
    aa_fun_a_b_fun_a_b : (fun_fun_a_b_fun_a_b * fun_a_b) > fun_a_b).

tff(sy_c_aa_001t__fun_IT__a_MT__b_J_001t__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_MT__b_J_J, type,
    aa_fun911777065un_a_b : (fun_fu391738216un_a_b * fun_a_b) > fun_fun_a_b_fun_a_b).

tff(sy_c_aa_001t__fun_IT__a_Mt__HOL__Obool_J_001t__Set__Oset_IT__a_J, type,
    aa_fun_a_bool_set_a : (fun_fun_a_bool_set_a * fun_a_bool) > set_a2).

tff(sy_c_fFalse, type,
    fFalse : bool).

tff(sy_c_fTrue, type,
    fTrue : bool).

tff(sy_c_member_001T__a, type,
    member_a : fun_a_fun_set_a_bool).

tff(sy_c_member_001T__c, type,
    member_c : fun_c_fun_set_c_bool).

tff(sy_c_member_001T__e, type,
    member_e : fun_e_fun_set_e_bool).

tff(sy_c_member_001t__Set__Oset_It__Product____Type__Oprod_It__Real__Oreal_Mt__Product____Type__Oprod_It__Real__Oreal_Mt__Real__Oreal_J_J_J, type,
    member1326644047l_real : fun_se1637999779l_bool).

tff(sy_c_pp, type,
    pp : bool > $o).


% Relevant facts (65)

tff(fact_0_Diff__disjoint, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), aa_set_a_set_a(aa_set363163287_set_a(minus_minus_set_a, B), A2)) = bot_bot_set_a)))). % Diff_disjoint

tff(fact_1_Un__Diff__cancel, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), aa_set_a_set_a(aa_set363163287_set_a(minus_minus_set_a, B), A2)) = aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B))))). % Un_Diff_cancel

tff(fact_2_Un__Diff__cancel2, axiom,
    ((![A : $i, B : set_a2, A2 : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, aa_set_a_set_a(aa_set363163287_set_a(minus_minus_set_a, B), A2)), A2) = aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, B), A2))))). % Un_Diff_cancel2

tff(fact_3_Int__Un__eq_I4_J, axiom,
    ((![A : $i, T : set_a2, S : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, T), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, S), T)) = T)))). % Int_Un_eq(4)

tff(fact_4_Int__Un__eq_I3_J, axiom,
    ((![A : $i, S : set_a2, T : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, S), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, S), T)) = S)))). % Int_Un_eq(3)

tff(fact_5_Int__Un__eq_I2_J, axiom,
    ((![A : $i, S : set_a2, T : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, S), T)), T) = T)))). % Int_Un_eq(2)

tff(fact_6_Int__Un__eq_I1_J, axiom,
    ((![A : $i, S : set_a2, T : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, S), T)), S) = S)))). % Int_Un_eq(1)

tff(fact_7_Un__Int__eq_I4_J, axiom,
    ((![A : $i, T : set_a2, S : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, T), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, S), T)) = T)))). % Un_Int_eq(4)

tff(fact_8_Un__Int__eq_I3_J, axiom,
    ((![A : $i, S : set_a2, T : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, S), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, S), T)) = S)))). % Un_Int_eq(3)

tff(fact_9_Un__Int__eq_I2_J, axiom,
    ((![A : $i, S : set_a2, T : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, S), T)), T) = T)))). % Un_Int_eq(2)

tff(fact_10_Un__Int__eq_I1_J, axiom,
    ((![A : $i, S : set_a2, T : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, S), T)), S) = S)))). % Un_Int_eq(1)

tff(fact_11_inf__sup__absorb, axiom,
    ((![A : $i]: (lattice(a3) => (![X : a3, Y : a3]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, X), aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Y)) = X)))))). % inf_sup_absorb

tff(fact_12_minus__apply, axiom,
    ((![B2 : $i, A : $i]: (minus(b) => (![A2 : fun_a_b, B : fun_a_b, X : a3]: (aa_a_b(aa_fun_a_b_fun_a_b(aa_fun911777065un_a_b(minus_minus_fun_a_b, A2), B), X) = aa_b_b(aa_b_fun_b_b(minus_minus_b, aa_a_b(A2, X)), aa_a_b(B, X)))))))). % minus_apply

tff(fact_13_empty__Collect__eq, axiom,
    ((![A : $i, P : fun_a_bool]: ((bot_bot_set_a = aa_fun_a_bool_set_a(collect_a, P)) <=> (![X2 : a3]: (~ (pp(aa_a_bool(P, X2))))))))). % empty_Collect_eq

tff(fact_14_Collect__empty__eq, axiom,
    ((![A : $i, P : fun_a_bool]: ((aa_fun_a_bool_set_a(collect_a, P) = bot_bot_set_a) <=> (![X2 : a3]: (~ (pp(aa_a_bool(P, X2))))))))). % Collect_empty_eq

tff(fact_15_all__not__in__conv, axiom,
    ((![A : $i, A2 : set_a2]: ((![X2 : a3]: (~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X2), A2))))) <=> (A2 = bot_bot_set_a))))). % all_not_in_conv

tff(fact_16_empty__iff, axiom,
    ((![A : $i, C : a3]: (~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), bot_bot_set_a))))))). % empty_iff

tff(fact_17_ball__simps_I5_J, axiom,
    ((![E : $i, P : fun_e_bool, X3 : e]: (pp(aa_set_e_bool(aa_e_fun_set_e_bool(member_e, X3), bot_bot_set_e)) => pp(aa_e_bool(P, X3)))))). % ball_simps(5)

tff(fact_18_bex__simps_I3_J, axiom,
    ((![C2 : $i, P : fun_c_bool]: (~ ((?[X3 : c]: (pp(aa_set_c_bool(aa_c_fun_set_c_bool(member_c, X3), bot_bot_set_c)) & pp(aa_c_bool(P, X3))))))))). % bex_simps(3)

tff(fact_19_inf__apply, axiom,
    ((![B2 : $i, A : $i]: (semilattice_inf(b) => (![F : fun_a_b, G : fun_a_b, X : a3]: (aa_a_b(aa_fun_a_b_fun_a_b(aa_fun911777065un_a_b(inf_inf_fun_a_b, F), G), X) = aa_b_b(aa_b_fun_b_b(inf_inf_b, aa_a_b(F, X)), aa_a_b(G, X)))))))). % inf_apply

tff(fact_20_inf__right__idem, axiom,
    ((![A : $i]: (semilattice_inf(a3) => (![X : a3, Y : a3]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y)), Y) = aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y))))))). % inf_right_idem

tff(fact_21_inf_Oright__idem, axiom,
    ((![A : $i]: (semilattice_inf(a3) => (![A3 : a3, B3 : a3]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, aa_a_a(aa_a_fun_a_a(inf_inf_a, A3), B3)), B3) = aa_a_a(aa_a_fun_a_a(inf_inf_a, A3), B3))))))). % inf.right_idem

tff(fact_22_inf__left__idem, axiom,
    ((![A : $i]: (semilattice_inf(a3) => (![X : a3, Y : a3]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, X), aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y)) = aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y))))))). % inf_left_idem

tff(fact_23_inf_Oleft__idem, axiom,
    ((![A : $i]: (semilattice_inf(a3) => (![A3 : a3, B3 : a3]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, A3), aa_a_a(aa_a_fun_a_a(inf_inf_a, A3), B3)) = aa_a_a(aa_a_fun_a_a(inf_inf_a, A3), B3))))))). % inf.left_idem

tff(fact_24_inf__idem, axiom,
    ((![A : $i]: (semilattice_inf(a3) => (![X : a3]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, X), X) = X)))))). % inf_idem

tff(fact_25_inf_Oidem, axiom,
    ((![A : $i]: (semilattice_inf(a3) => (![A3 : a3]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, A3), A3) = A3)))))). % inf.idem

tff(fact_26_inf__aci_I4_J, axiom,
    ((![A : $i]: (semilattice_inf(a3) => (![X : a3, Y : a3]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, X), aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y)) = aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y))))))). % inf_aci(4)

tff(fact_27_Int__iff, axiom,
    ((![A : $i, C : a3, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), B))) <=> (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A2)) & pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B))))))). % Int_iff

tff(fact_28_IntI, axiom,
    ((![A : $i, C : a3, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A2)) => (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B)) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, A2), B)))))))). % IntI

tff(fact_29_sup__apply, axiom,
    ((![B2 : $i, A : $i]: (semilattice_sup(b) => (![F : fun_a_b, G : fun_a_b, X : a3]: (aa_a_b(aa_fun_a_b_fun_a_b(aa_fun911777065un_a_b(sup_sup_fun_a_b, F), G), X) = aa_b_b(aa_b_fun_b_b(sup_sup_b, aa_a_b(F, X)), aa_a_b(G, X)))))))). % sup_apply

tff(fact_30_sup_Oright__idem, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![A3 : a3, B3 : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), B3)), B3) = aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), B3))))))). % sup.right_idem

tff(fact_31_sup__left__idem, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![X : a3, Y : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, X), aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Y)) = aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Y))))))). % sup_left_idem

tff(fact_32_sup_Oleft__idem, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![A3 : a3, B3 : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), B3)) = aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), B3))))))). % sup.left_idem

tff(fact_33_sup__idem, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![X : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, X), X) = X)))))). % sup_idem

tff(fact_34_sup_Oidem, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![A3 : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), A3) = A3)))))). % sup.idem

tff(fact_35_sup__aci_I4_J, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![X : a3, Y : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, X), aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Y)) = aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Y))))))). % sup_aci(4)

tff(fact_36_Diff__idemp, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(minus_minus_set_a, aa_set_a_set_a(aa_set363163287_set_a(minus_minus_set_a, A2), B)), B) = aa_set_a_set_a(aa_set363163287_set_a(minus_minus_set_a, A2), B))))). % Diff_idemp

tff(fact_37_Diff__iff, axiom,
    ((![A : $i, C : a3, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(minus_minus_set_a, A2), B))) <=> (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A2)) & (~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B))))))))). % Diff_iff

tff(fact_38_DiffI, axiom,
    ((![A : $i, C : a3, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A2)) => ((~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B)))) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(minus_minus_set_a, A2), B)))))))). % DiffI

tff(fact_39_Un__iff, axiom,
    ((![A : $i, C : a3, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B))) <=> (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A2)) | pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B))))))). % Un_iff

tff(fact_40_UnCI, axiom,
    ((![A : $i, C : a3, B : set_a2, A2 : set_a2]: (((~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B)))) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A2))) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B))))))). % UnCI

tff(fact_41_inf__bot__right, axiom,
    ((![A : $i]: (bounded_lattice_bot(a3) => (![X : a3]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, X), bot_bot_a) = bot_bot_a)))))). % inf_bot_right

tff(fact_42_inf__bot__left, axiom,
    ((![A : $i]: (bounded_lattice_bot(a3) => (![X : a3]: (aa_a_a(aa_a_fun_a_a(inf_inf_a, bot_bot_a), X) = bot_bot_a)))))). % inf_bot_left

tff(fact_43_sup__bot_Oright__neutral, axiom,
    ((![A : $i]: (bounde1808546759up_bot(a3) => (![A3 : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), bot_bot_a) = A3)))))). % sup_bot.right_neutral

tff(fact_44_sup__bot_Oneutr__eq__iff, axiom,
    ((![A : $i]: (bounde1808546759up_bot(a3) => (![A3 : a3, B3 : a3]: ((bot_bot_a = aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), B3)) <=> ((A3 = bot_bot_a) & (B3 = bot_bot_a)))))))). % sup_bot.neutr_eq_iff

tff(fact_45_mem__Collect__eq, axiom,
    ((![A : $i, A3 : a3, P : fun_a_bool]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, A3), aa_fun_a_bool_set_a(collect_a, P))) <=> pp(aa_a_bool(P, A3)))))). % mem_Collect_eq

tff(fact_46_Collect__mem__eq, axiom,
    ((![A : $i, A2 : set_a2]: (aa_fun_a_bool_set_a(collect_a, aa_set_a_fun_a_bool(aTP_Lamm_a, A2)) = A2)))). % Collect_mem_eq

tff(fact_47_Collect__cong, axiom,
    ((![A : $i, P : fun_a_bool, Q : fun_a_bool]: ((![X4 : a3]: (pp(aa_a_bool(P, X4)) <=> pp(aa_a_bool(Q, X4)))) => (aa_fun_a_bool_set_a(collect_a, P) = aa_fun_a_bool_set_a(collect_a, Q)))))). % Collect_cong

tff(fact_48_ext, axiom,
    ((![B2 : $i, A : $i, F : fun_a_b, G : fun_a_b]: ((![X4 : a3]: (aa_a_b(F, X4) = aa_a_b(G, X4))) => (F = G))))). % ext

tff(fact_49_mem__simps_I7_J, axiom,
    ((![A : $i, A3 : a3, P : fun_a_bool]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, A3), aa_fun_a_bool_set_a(collect_a, P))) <=> pp(aa_a_bool(P, A3)))))). % mem_simps(7)

tff(fact_50_array__rules_I1_J, axiom,
    ((![B2 : $i, A : $i, F : fun_a_b, G : fun_a_b]: ((![X4 : a3]: (aa_a_b(F, X4) = aa_a_b(G, X4))) => (F = G))))). % array_rules(1)

tff(fact_51_sup__bot_Oleft__neutral, axiom,
    ((![A : $i]: (bounde1808546759up_bot(a3) => (![A3 : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, bot_bot_a), A3) = A3)))))). % sup_bot.left_neutral

tff(fact_52_sup__bot_Oeq__neutr__iff, axiom,
    ((![A : $i]: (bounde1808546759up_bot(a3) => (![A3 : a3, B3 : a3]: ((aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), B3) = bot_bot_a) <=> ((A3 = bot_bot_a) & (B3 = bot_bot_a)))))))). % sup_bot.eq_neutr_iff

tff(fact_53_sup__bot_Ocomm__neutral, axiom,
    ((![A : $i]: (bounde1808546759up_bot(a3) => (![A3 : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), bot_bot_a) = A3)))))). % sup_bot.comm_neutral

tff(fact_54_sup__eq__bot__iff, axiom,
    ((![A : $i]: (bounde1808546759up_bot(a3) => (![X : a3, Y : a3]: ((aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Y) = bot_bot_a) <=> ((X = bot_bot_a) & (Y = bot_bot_a)))))))). % sup_eq_bot_iff

tff(fact_55_bot__eq__sup__iff, axiom,
    ((![A : $i]: (bounde1808546759up_bot(a3) => (![X : a3, Y : a3]: ((bot_bot_a = aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Y)) <=> ((X = bot_bot_a) & (Y = bot_bot_a)))))))). % bot_eq_sup_iff

tff(fact_56_sup__bot__right, axiom,
    ((![A : $i]: (bounde1808546759up_bot(a3) => (![X : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, X), bot_bot_a) = X)))))). % sup_bot_right

tff(fact_57_sup__bot__left, axiom,
    ((![A : $i]: (bounde1808546759up_bot(a3) => (![X : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, bot_bot_a), X) = X)))))). % sup_bot_left

tff(fact_58_Diff__cancel, axiom,
    ((![A : $i, A2 : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(minus_minus_set_a, A2), A2) = bot_bot_set_a)))). % Diff_cancel

tff(fact_59_empty__Diff, axiom,
    ((![A : $i, A2 : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(minus_minus_set_a, bot_bot_set_a), A2) = bot_bot_set_a)))). % empty_Diff

tff(fact_60_Diff__empty, axiom,
    ((![A : $i, A2 : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(minus_minus_set_a, A2), bot_bot_set_a) = A2)))). % Diff_empty

tff(fact_61_Un__empty, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: ((aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B) = bot_bot_set_a) <=> ((A2 = bot_bot_set_a) & (B = bot_bot_set_a)))))). % Un_empty

tff(fact_62_sup__inf__absorb, axiom,
    ((![A : $i]: (lattice(a3) => (![X : a3, Y : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, X), aa_a_a(aa_a_fun_a_a(inf_inf_a, X), Y)) = X)))))). % sup_inf_absorb

tff(fact_63_fun__diff__def, axiom,
    ((![B2 : $i, A : $i]: (minus(b) => (![A2 : fun_a_b, B : fun_a_b, X3 : a3]: (aa_a_b(aa_fun_a_b_fun_a_b(aa_fun911777065un_a_b(minus_minus_fun_a_b, A2), B), X3) = aa_b_b(aa_b_fun_b_b(minus_minus_b, aa_a_b(A2, X3)), aa_a_b(B, X3)))))))). % fun_diff_def

tff(fact_64_ATP_Olambda__1, axiom,
    ((![A : $i, Uu : set_a2, Uua : a3]: (pp(aa_a_bool(aa_set_a_fun_a_bool(aTP_Lamm_a, Uu), Uua)) <=> pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, Uua), Uu)))))). % ATP.lambda_1


% Type constructors (32)

tff(tcon_Product__Type_Oprod___Lattices_Obounded__lattice, axiom,
    ((![A4 : $i, A5 : $i]: ((bounded_lattice(a2) & bounded_lattice(a)) => bounded_lattice(product_prod_a_a))))).

tff(tcon_HOL_Obool___Lattices_Obounded__lattice_1, axiom,
    (bounded_lattice(bool))).

tff(tcon_Set_Oset___Lattices_Obounded__lattice_2, axiom,
    ((![A4 : $i]: bounded_lattice(set_a)))).

tff(tcon_fun___Lattices_Obounded__lattice_3, axiom,
    ((![A4 : $i, A5 : $i]: (bounded_lattice(a) => bounded_lattice(fun_a_a))))).

tff(tcon_fun___Lattices_Obounded__semilattice__sup__bot, axiom,
    ((![A4 : $i, A5 : $i]: (bounded_lattice(a) => bounde1808546759up_bot(fun_a_a))))).

tff(tcon_fun___Lattices_Obounded__lattice__bot, axiom,
    ((![A4 : $i, A5 : $i]: (bounded_lattice(a) => bounded_lattice_bot(fun_a_a))))).

tff(tcon_fun___Lattices_Osemilattice__sup, axiom,
    ((![A4 : $i, A5 : $i]: (semilattice_sup(a) => semilattice_sup(fun_a_a))))).

tff(tcon_fun___Lattices_Osemilattice__inf, axiom,
    ((![A4 : $i, A5 : $i]: (semilattice_inf(a) => semilattice_inf(fun_a_a))))).

tff(tcon_fun___Lattices_Olattice, axiom,
    ((![A4 : $i, A5 : $i]: (lattice(a) => lattice(fun_a_a))))).

tff(tcon_fun___Groups_Ominus, axiom,
    ((![A4 : $i, A5 : $i]: (minus(a) => minus(fun_a_a))))).

tff(tcon_Set_Oset___Lattices_Obounded__semilattice__sup__bot_4, axiom,
    ((![A4 : $i]: bounde1808546759up_bot(set_a)))).

tff(tcon_Set_Oset___Lattices_Obounded__lattice__bot_5, axiom,
    ((![A4 : $i]: bounded_lattice_bot(set_a)))).

tff(tcon_Set_Oset___Lattices_Osemilattice__sup_6, axiom,
    ((![A4 : $i]: semilattice_sup(set_a)))).

tff(tcon_Set_Oset___Lattices_Osemilattice__inf_7, axiom,
    ((![A4 : $i]: semilattice_inf(set_a)))).

tff(tcon_Set_Oset___Lattices_Olattice_8, axiom,
    ((![A4 : $i]: lattice(set_a)))).

tff(tcon_Set_Oset___Groups_Ominus_9, axiom,
    ((![A4 : $i]: minus(set_a)))).

tff(tcon_HOL_Obool___Lattices_Obounded__semilattice__sup__bot_10, axiom,
    (bounde1808546759up_bot(bool))).

tff(tcon_HOL_Obool___Lattices_Obounded__lattice__bot_11, axiom,
    (bounded_lattice_bot(bool))).

tff(tcon_HOL_Obool___Lattices_Osemilattice__sup_12, axiom,
    (semilattice_sup(bool))).

tff(tcon_HOL_Obool___Lattices_Osemilattice__inf_13, axiom,
    (semilattice_inf(bool))).

tff(tcon_HOL_Obool___Lattices_Olattice_14, axiom,
    (lattice(bool))).

tff(tcon_HOL_Obool___Groups_Ominus_15, axiom,
    (minus(bool))).

tff(tcon_Real_Oreal___Lattices_Osemilattice__sup_16, axiom,
    (semilattice_sup(real))).

tff(tcon_Real_Oreal___Lattices_Osemilattice__inf_17, axiom,
    (semilattice_inf(real))).

tff(tcon_Real_Oreal___Lattices_Olattice_18, axiom,
    (lattice(real))).

tff(tcon_Real_Oreal___Groups_Ominus_19, axiom,
    (minus(real))).

tff(tcon_Product__Type_Oprod___Lattices_Obounded__semilattice__sup__bot_20, axiom,
    ((![A4 : $i, A5 : $i]: ((bounded_lattice(a2) & bounded_lattice(a)) => bounde1808546759up_bot(product_prod_a_a))))).

tff(tcon_Product__Type_Oprod___Lattices_Obounded__lattice__bot_21, axiom,
    ((![A4 : $i, A5 : $i]: ((bounded_lattice(a2) & bounded_lattice(a)) => bounded_lattice_bot(product_prod_a_a))))).

tff(tcon_Product__Type_Oprod___Lattices_Osemilattice__sup_22, axiom,
    ((![A4 : $i, A5 : $i]: ((semilattice_sup(a2) & semilattice_sup(a)) => semilattice_sup(product_prod_a_a))))).

tff(tcon_Product__Type_Oprod___Lattices_Osemilattice__inf_23, axiom,
    ((![A4 : $i, A5 : $i]: ((semilattice_inf(a2) & semilattice_inf(a)) => semilattice_inf(product_prod_a_a))))).

tff(tcon_Product__Type_Oprod___Lattices_Olattice_24, axiom,
    ((![A4 : $i, A5 : $i]: ((lattice(a2) & lattice(a)) => lattice(product_prod_a_a))))).

tff(tcon_Product__Type_Oprod___Groups_Ominus_25, axiom,
    ((![A4 : $i, A5 : $i]: ((minus(a2) & minus(a)) => minus(product_prod_a_a))))).


% Helper facts (2)

tff(help_pp_2_1_U, axiom,
    (pp(fTrue))).

tff(help_pp_1_1_U, axiom,
    ((~ (pp(fFalse))))).


% Conjectures (10)

tff(conj_0, hypothesis,
    ((![SCC : set_Pr1930119096l_real]: pp(aa_set428719265l_bool(aa_set914061836l_bool(aa_set612694061l_bool(algTop2095930224l_real, algTop_JCT_top1_S2), algTop1528072561pology), SCC))))).

tff(conj_1, hypothesis,
    ((![Q : set_Pr1930119096l_real]: pp(aa_set374130539l_bool(aa_set1201437708l_bool(member1326644047l_real, Q), algTop1528072561pology))))).

tff(conj_2, hypothesis,
    ((![R : set_Pr1930119096l_real]: pp(aa_set374130539l_bool(aa_set1201437708l_bool(member1326644047l_real, R), algTop1528072561pology))))).

tff(conj_3, hypothesis,
    ((![Q : set_Pr1930119096l_real]: (Q != bot_bo307885644l_real)))).

tff(conj_4, hypothesis,
    ((![R : set_Pr1930119096l_real]: (R != bot_bo307885644l_real)))).

tff(conj_5, hypothesis,
    ((![Q : set_Pr1930119096l_real, R : set_Pr1930119096l_real]: (aa_set1050760878l_real(aa_set2073708131l_real(inf_in619654218l_real, Q), R) = bot_bo307885644l_real)))).

tff(conj_6, hypothesis,
    ((![Q : set_Pr1930119096l_real, R : set_Pr1930119096l_real, SCC : set_Pr1930119096l_real]: (aa_set1050760878l_real(aa_set2073708131l_real(sup_su69286116l_real, Q), R) = aa_set1050760878l_real(aa_set2073708131l_real(minus_1145959313l_real, algTop_JCT_top1_S2), SCC))))).

tff(conj_7, hypothesis,
    ((![Q : set_Pr1930119096l_real]: pp(aa_set374130539l_bool(aa_set1201437708l_bool(top1_t2008947945l_real, Q), aa_set1376316772l_real(aa_set858184911l_real(aa_set149052676l_real(top1_s1666726429l_real, algTop_JCT_top1_S2), algTop1528072561pology), Q)))))).

tff(conj_8, hypothesis,
    ((![R : set_Pr1930119096l_real]: pp(aa_set374130539l_bool(aa_set1201437708l_bool(top1_t2008947945l_real, R), aa_set1376316772l_real(aa_set858184911l_real(aa_set149052676l_real(top1_s1666726429l_real, algTop_JCT_top1_S2), algTop1528072561pology), R)))))).

tff(conj_9, conjecture,
    ((![Q : set_Pr1930119096l_real, SCC : set_Pr1930119096l_real]: (aa_set1050760878l_real(aa_set680673561l_real(aa_set1262576718l_real(top1_c223158040l_real, algTop_JCT_top1_S2), algTop1528072561pology), Q) = aa_set1050760878l_real(aa_set2073708131l_real(sup_su69286116l_real, Q), SCC))))).

