% This file was generated by Isabelle (most likely Sledgehammer)
2026-06-02 20:32:32.569

% Could-be-implicit typings (105)

tff(ty_n_t__fun_It__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J_Mt__fun_It__List__Olist_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J_J, type,
    fun_fu564408078a_bool : $tType).

tff(ty_n_t__fun_It__fun_It__Set__Oset_IT__a_J_MT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__Set__Oset_IT__a_J_J_J, type,
    fun_fu557047111_set_a : $tType).

tff(ty_n_t__fun_It__fun_IT__a_Mt__HOL__Obool_J_Mt__fun_It__fun_IT__a_Mt__HOL__Obool_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J_J, type,
    fun_fu958398344a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J_J, type,
    fun_se1447345141a_bool : $tType).

tff(ty_n_t__fun_It__Nat__Onat_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J_J, type,
    fun_na746762910_set_a : $tType).

tff(ty_n_t__fun_It__fun_IT__a_Mt__fun_IT__a_Mt__HOL__Obool_J_J_Mt__fun_It__List__Olist_IT__a_J_Mt__HOL__Obool_J_J, type,
    fun_fu1580049368a_bool : $tType).

tff(ty_n_t__fun_It__fun_It__Nat__Onat_MT__a_J_Mt__fun_It__Set__Oset_It__Nat__Onat_J_Mt__Set__Oset_IT__a_J_J_J, type,
    fun_fu2018723327_set_a : $tType).

tff(ty_n_t__fun_It__fun_It__List__Olist_IT__b_J_Mt__HOL__Obool_J_Mt__Set__Oset_It__List__Olist_IT__b_J_J_J, type,
    fun_fu1674834681list_b : $tType).

tff(ty_n_t__fun_It__fun_It__List__Olist_IT__a_J_Mt__HOL__Obool_J_Mt__Set__Oset_It__List__Olist_IT__a_J_J_J, type,
    fun_fu226907449list_a : $tType).

tff(ty_n_t__fun_It__fun_IT__a_Mt__HOL__Obool_J_Mt__fun_It__fun_IT__a_Mt__HOL__Obool_J_Mt__HOL__Obool_J_J, type,
    fun_fu647214445l_bool : $tType).

tff(ty_n_t__fun_It__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J, type,
    fun_fu1487319609_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J_J, type,
    fun_se590241323a_bool : $tType).

tff(ty_n_t__fun_It__List__Olist_It__Set__Oset_IT__a_J_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J, type,
    fun_li1246370091_set_a : $tType).

tff(ty_n_t__fun_It__fun_IT__i_MT__j_J_Mt__fun_It__Set__Oset_IT__i_J_Mt__Set__Oset_IT__j_J_J_J, type,
    fun_fu1656505853_set_j : $tType).

tff(ty_n_t__fun_It__fun_IT__g_MT__h_J_Mt__fun_It__Set__Oset_IT__g_J_Mt__Set__Oset_IT__h_J_J_J, type,
    fun_fu892916725_set_h : $tType).

tff(ty_n_t__fun_It__fun_IT__b_MT__a_J_Mt__fun_It__Set__Oset_IT__b_J_Mt__Set__Oset_IT__a_J_J_J, type,
    fun_fu1241503453_set_a : $tType).

tff(ty_n_t__fun_It__fun_IT__a_MT__b_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__b_J_J_J, type,
    fun_fu749632989_set_b : $tType).

tff(ty_n_t__fun_It__fun_IT__a_MT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J_J, type,
    fun_fu804670939_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J, type,
    fun_se490019921_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__b_J_Mt__fun_It__List__Olist_IT__b_J_Mt__HOL__Obool_J_J, type,
    fun_se317721989b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__List__Olist_IT__a_J_Mt__HOL__Obool_J_J, type,
    fun_se607730439a_bool : $tType).

tff(ty_n_t__fun_It__fun_It__Nat__Onat_Mt__HOL__Obool_J_Mt__Set__Oset_It__Nat__Onat_J_J, type,
    fun_fu874497849et_nat : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_IT__b_J_Mt__HOL__Obool_J_J, type,
    fun_se64550751b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J, type,
    fun_se1296151905a_bool : $tType).

tff(ty_n_t__fun_It__fun_IT__a_Mt__HOL__Obool_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J, type,
    fun_fu816707011a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_set_set_a_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__List__Olist_IT__b_J_J_Mt__HOL__Obool_J, type,
    fun_set_list_b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__List__Olist_IT__a_J_J_Mt__HOL__Obool_J, type,
    fun_set_list_a_bool : $tType).

tff(ty_n_t__fun_It__List__Olist_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J, type,
    fun_list_set_a_bool : $tType).

tff(ty_n_t__fun_It__fun_IT__a_Mt__HOL__Obool_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_fun_a_bool_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J, type,
    fun_set_set_a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J, type,
    fun_set_a_fun_a_bool : $tType).

tff(ty_n_t__fun_It__Nat__Onat_Mt__fun_It__Nat__Onat_Mt__HOL__Obool_J_J, type,
    fun_nat_fun_nat_bool : $tType).

tff(ty_n_t__fun_IT__j_Mt__fun_It__Set__Oset_IT__j_J_Mt__HOL__Obool_J_J, type,
    fun_j_fun_set_j_bool : $tType).

tff(ty_n_t__fun_IT__i_Mt__fun_It__Set__Oset_IT__i_J_Mt__HOL__Obool_J_J, type,
    fun_i_fun_set_i_bool : $tType).

tff(ty_n_t__fun_IT__h_Mt__fun_It__Set__Oset_IT__h_J_Mt__HOL__Obool_J_J, type,
    fun_h_fun_set_h_bool : $tType).

tff(ty_n_t__fun_IT__g_Mt__fun_It__Set__Oset_IT__g_J_Mt__HOL__Obool_J_J, type,
    fun_g_fun_set_g_bool : $tType).

tff(ty_n_t__fun_IT__b_Mt__fun_It__Set__Oset_IT__b_J_Mt__HOL__Obool_J_J, type,
    fun_b_fun_set_b_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J, type,
    fun_a_fun_set_a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Nat__Onat_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_set_nat_set_a : $tType).

tff(ty_n_t__fun_It__fun_IT__a_Mt__HOL__Obool_J_Mt__HOL__Obool_J, type,
    fun_fun_a_bool_bool : $tType).

tff(ty_n_t__fun_It__List__Olist_IT__b_J_Mt__Set__Oset_IT__b_J_J, type,
    fun_list_b_set_b : $tType).

tff(ty_n_t__fun_It__List__Olist_IT__a_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_list_a_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__i_J_Mt__Set__Oset_IT__j_J_J, type,
    fun_set_i_set_j : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__g_J_Mt__Set__Oset_IT__h_J_J, type,
    fun_set_g_set_h : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__b_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_set_b_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__b_J_J, type,
    fun_set_a_set_b : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_set_a_set_a : $tType).

tff(ty_n_t__fun_It__List__Olist_IT__b_J_Mt__HOL__Obool_J, type,
    fun_list_b_bool : $tType).

tff(ty_n_t__fun_It__List__Olist_IT__a_J_Mt__HOL__Obool_J, type,
    fun_list_a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__j_J_Mt__HOL__Obool_J, type,
    fun_set_j_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__i_J_Mt__HOL__Obool_J, type,
    fun_set_i_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__h_J_Mt__HOL__Obool_J, type,
    fun_set_h_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__g_J_Mt__HOL__Obool_J, type,
    fun_set_g_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__b_J_Mt__HOL__Obool_J, type,
    fun_set_b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    fun_set_a_bool : $tType).

tff(ty_n_t__fun_IT__c_Mt__fun_IT__c_Mt__HOL__Obool_J_J, type,
    fun_c_fun_c_bool : $tType).

tff(ty_n_t__fun_IT__b_Mt__fun_IT__b_Mt__HOL__Obool_J_J, type,
    fun_b_fun_b_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_IT__a_Mt__HOL__Obool_J_J, type,
    fun_a_fun_a_bool : $tType).

tff(ty_n_t__Set__Oset_It__List__Olist_IT__b_J_J, type,
    set_list_b : $tType).

tff(ty_n_t__Set__Oset_It__List__Olist_IT__a_J_J, type,
    set_list_a : $tType).

tff(ty_n_t__List__Olist_It__Set__Oset_IT__a_J_J, type,
    list_set_a : $tType).

tff(ty_n_t__fun_It__Nat__Onat_Mt__HOL__Obool_J, type,
    fun_nat_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_MT__a_J, type,
    fun_set_a_a : $tType).

tff(ty_n_t__Set__Oset_It__Set__Oset_IT__a_J_J, type,
    set_set_a : $tType).

tff(ty_n_t__fun_IT__j_Mt__HOL__Obool_J, type,
    fun_j_bool : $tType).

tff(ty_n_t__fun_IT__h_Mt__HOL__Obool_J, type,
    fun_h_bool : $tType).

tff(ty_n_t__fun_IT__c_Mt__HOL__Obool_J, type,
    fun_c_bool : $tType).

tff(ty_n_t__fun_IT__b_Mt__HOL__Obool_J, type,
    fun_b_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__HOL__Obool_J, type,
    fun_a_bool : $tType).

tff(ty_n_t__fun_It__Nat__Onat_MT__a_J, type,
    fun_nat_a : $tType).

tff(ty_n_t__Set__Oset_It__Nat__Onat_J, type,
    set_nat : $tType).

tff(ty_n_t__fun_IT__a__1_MT__a__2_J, type,
    fun_a_a : $tType).

tff(ty_n_t__Set__Oset_IT__a__1_J, type,
    set_a : $tType).

tff(ty_n_t__List__Olist_IT__b_J, type,
    list_b : $tType).

tff(ty_n_t__List__Olist_IT__a_J, type,
    list_a : $tType).

tff(ty_n_t__fun_IT__i_MT__j_J, type,
    fun_i_j : $tType).

tff(ty_n_t__fun_IT__g_MT__h_J, type,
    fun_g_h : $tType).

tff(ty_n_t__fun_IT__b_MT__a_J, type,
    fun_b_a : $tType).

tff(ty_n_t__fun_IT__a_MT__c_J, type,
    fun_a_c : $tType).

tff(ty_n_t__fun_IT__a_MT__b_J, type,
    fun_a_b : $tType).

tff(ty_n_t__fun_IT__a_MT__a_J, type,
    fun_a_a2 : $tType).

tff(ty_n_t__Set__Oset_IT__j_J, type,
    set_j : $tType).

tff(ty_n_t__Set__Oset_IT__i_J, type,
    set_i : $tType).

tff(ty_n_t__Set__Oset_IT__h_J, type,
    set_h : $tType).

tff(ty_n_t__Set__Oset_IT__g_J, type,
    set_g : $tType).

tff(ty_n_t__Set__Oset_IT__b_J, type,
    set_b : $tType).

tff(ty_n_t__Set__Oset_IT__a_J, type,
    set_a2 : $tType).

tff(ty_n_t__HOL__Obool, type,
    bool : $tType).

tff(ty_n_t__Nat__Onat, type,
    nat : $tType).

tff(ty_n_T__a__2, type,
    a : $tType).

tff(ty_n_T__a__1, type,
    a2 : $tType).

tff(ty_n_T__j, type,
    j : $tType).

tff(ty_n_T__i, type,
    i : $tType).

tff(ty_n_T__h, type,
    h : $tType).

tff(ty_n_T__g, type,
    g : $tType).

tff(ty_n_T__c, type,
    c : $tType).

tff(ty_n_T__b, type,
    b : $tType).

tff(ty_n_T__a, type,
    a3 : $tType).

tff(sy_cl_Euclidean__Space_Oeuclidean__space, type,
    euclid925273238_space : !>[A : $tType]: $o).

tff(sy_cl_Orderings_Opreorder, type,
    preorder : !>[A : $tType]: $o).

tff(sy_cl_Orderings_Olinorder, type,
    linorder : !>[A : $tType]: $o).

tff(sy_cl_Finite__Set_Ofinite, type,
    finite_finite : !>[A : $tType]: $o).

tff(sy_cl_Orderings_Oorder, type,
    order : !>[A : $tType]: $o).

tff(sy_cl_Orderings_Oord, type,
    ord : !>[A : $tType]: $o).


% Explicit typings (133)

tff(sy_c_ATP_058Lamm__a, type,
    aTP_Lamm_a : fun_se1296151905a_bool).

tff(sy_c_ATP_058Lamm__aa, type,
    aTP_Lamm_aa : fun_se607730439a_bool).

tff(sy_c_ATP_058Lamm__ab, type,
    aTP_Lamm_ab : fun_se317721989b_bool).

tff(sy_c_ATP_058Lamm__ac, type,
    aTP_Lamm_ac : fun_a_a2).

tff(sy_c_ATP_058Lamm__ad, type,
    aTP_Lamm_ad : fun_fu958398344a_bool).

tff(sy_c_ATP_058Lamm__ae, type,
    aTP_Lamm_ae : fun_fu958398344a_bool).

tff(sy_c_ATP_058Lamm__af, type,
    aTP_Lamm_af : fun_nat_fun_nat_bool).

tff(sy_c_ATP_058Lamm__ag, type,
    aTP_Lamm_ag : fun_set_a_fun_a_bool).

tff(sy_c_Finite__Set_Ofinite_001T__a, type,
    finite_finite_a : fun_set_a_bool).

tff(sy_c_Finite__Set_Ofinite_001T__b, type,
    finite_finite_b : fun_set_b_bool).

tff(sy_c_Finite__Set_Ofinite_001t__List__Olist_IT__a_J, type,
    finite_finite_list_a : fun_set_list_a_bool).

tff(sy_c_Finite__Set_Ofinite_001t__List__Olist_IT__b_J, type,
    finite_finite_list_b : fun_set_list_b_bool).

tff(sy_c_Finite__Set_Ofinite_001t__Set__Oset_IT__a_J, type,
    finite_finite_set_a : fun_set_set_a_bool).

tff(sy_c_GeoTopBase0_Ogeotop__barycenter_001T__a, type,
    geotop_barycenter_a : fun_set_a_a).

tff(sy_c_GeoTopBase0_Ogeotop__convex__hull_001T__a, type,
    geotop_convex_hull_a : fun_set_a_set_a).

tff(sy_c_GeoTopBase0_Ogeotop__is__complex_001T__a, type,
    geotop_is_complex_a : fun_set_set_a_bool).

tff(sy_c_GeoTopBase0_Ogeotop__iterated__Sd_001T__a, type,
    geotop_iterated_Sd_a : fun_na746762910_set_a).

tff(sy_c_Groups_Oone__class_Oone_001t__Nat__Onat, type,
    one_one_nat : nat).

tff(sy_c_List_Odistinct_001T__a, type,
    distinct_a : fun_list_a_bool).

tff(sy_c_List_Odistinct_001T__b, type,
    distinct_b : fun_list_b_bool).

tff(sy_c_List_Odistinct_001t__Set__Oset_IT__a_J, type,
    distinct_set_a : fun_list_set_a_bool).

tff(sy_c_List_Olist_ONil_001t__Set__Oset_IT__a_J, type,
    nil_set_a : list_set_a).

tff(sy_c_List_Olist_Oset_001T__a, type,
    set_a3 : fun_list_a_set_a).

tff(sy_c_List_Olist_Oset_001T__b, type,
    set_b2 : fun_list_b_set_b).

tff(sy_c_List_Olist_Oset_001t__Set__Oset_IT__a_J, type,
    set_set_a2 : fun_li1246370091_set_a).

tff(sy_c_List_Osorted__wrt_001T__a, type,
    sorted_wrt_a : fun_fu1580049368a_bool).

tff(sy_c_List_Osorted__wrt_001t__Set__Oset_IT__a_J, type,
    sorted_wrt_set_a : fun_fu564408078a_bool).

tff(sy_c_Orderings_Oord__class_Oless_001T__a, type,
    ord_less_a : fun_a_fun_a_bool).

tff(sy_c_Orderings_Oord__class_Oless_001T__b, type,
    ord_less_b : fun_b_fun_b_bool).

tff(sy_c_Orderings_Oord__class_Oless_001T__c, type,
    ord_less_c : fun_c_fun_c_bool).

tff(sy_c_Orderings_Oord__class_Oless_001t__Nat__Onat, type,
    ord_less_nat : fun_nat_fun_nat_bool).

tff(sy_c_Orderings_Oord__class_Oless_001t__Set__Oset_IT__a_J, type,
    ord_less_set_a : fun_se1296151905a_bool).

tff(sy_c_Orderings_Oord__class_Oless_001t__fun_IT__a_Mt__HOL__Obool_J, type,
    ord_less_fun_a_bool : fun_fu647214445l_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001T__a, type,
    ord_less_eq_a : fun_a_fun_a_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001T__b, type,
    ord_less_eq_b : fun_b_fun_b_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001T__c, type,
    ord_less_eq_c : fun_c_fun_c_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001t__Set__Oset_IT__a_J, type,
    ord_less_eq_set_a : fun_se1296151905a_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001t__Set__Oset_IT__b_J, type,
    ord_less_eq_set_b : fun_se64550751b_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001t__Set__Oset_It__Set__Oset_IT__a_J_J, type,
    ord_le1348423818_set_a : fun_se1447345141a_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001t__fun_IT__a_Mt__HOL__Obool_J, type,
    ord_le801610962a_bool : fun_fu647214445l_bool).

tff(sy_c_Set_OCollect_001T__a, type,
    collect_a : fun_fun_a_bool_set_a).

tff(sy_c_Set_OCollect_001t__List__Olist_IT__a_J, type,
    collect_list_a : fun_fu226907449list_a).

tff(sy_c_Set_OCollect_001t__List__Olist_IT__b_J, type,
    collect_list_b : fun_fu1674834681list_b).

tff(sy_c_Set_OCollect_001t__Nat__Onat, type,
    collect_nat : fun_fu874497849et_nat).

tff(sy_c_Set_OCollect_001t__Set__Oset_IT__a_J, type,
    collect_set_a : fun_fu1487319609_set_a).

tff(sy_c_Set_Oimage_001T__a_001T__a, type,
    image_a_a : fun_fu804670939_set_a).

tff(sy_c_Set_Oimage_001T__a_001T__b, type,
    image_a_b : fun_fu749632989_set_b).

tff(sy_c_Set_Oimage_001T__b_001T__a, type,
    image_b_a : fun_fu1241503453_set_a).

tff(sy_c_Set_Oimage_001T__g_001T__h, type,
    image_g_h : fun_fu892916725_set_h).

tff(sy_c_Set_Oimage_001T__i_001T__j, type,
    image_i_j : fun_fu1656505853_set_j).

tff(sy_c_Set_Oimage_001t__Nat__Onat_001T__a, type,
    image_nat_a : fun_fu2018723327_set_a).

tff(sy_c_Set_Oimage_001t__Set__Oset_IT__a_J_001T__a, type,
    image_set_a_a : fun_fu557047111_set_a).

tff(sy_c_aa_001T__a_001T__a, type,
    aa_a_a : (fun_a_a2 * a3) > a3).

tff(sy_c_aa_001T__a_001T__b, type,
    aa_a_b : (fun_a_b * a3) > b).

tff(sy_c_aa_001T__a_001T__c, type,
    aa_a_c : (fun_a_c * a3) > c).

tff(sy_c_aa_001T__a_001t__HOL__Obool, type,
    aa_a_bool : (fun_a_bool * a3) > bool).

tff(sy_c_aa_001T__a_001t__fun_IT__a_Mt__HOL__Obool_J, type,
    aa_a_fun_a_bool : (fun_a_fun_a_bool * a3) > fun_a_bool).

tff(sy_c_aa_001T__a_001t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    aa_a_fun_set_a_bool : (fun_a_fun_set_a_bool * a3) > fun_set_a_bool).

tff(sy_c_aa_001T__b_001T__a, type,
    aa_b_a : (fun_b_a * b) > a3).

tff(sy_c_aa_001T__b_001t__HOL__Obool, type,
    aa_b_bool : (fun_b_bool * b) > bool).

tff(sy_c_aa_001T__b_001t__fun_IT__b_Mt__HOL__Obool_J, type,
    aa_b_fun_b_bool : (fun_b_fun_b_bool * b) > fun_b_bool).

tff(sy_c_aa_001T__b_001t__fun_It__Set__Oset_IT__b_J_Mt__HOL__Obool_J, type,
    aa_b_fun_set_b_bool : (fun_b_fun_set_b_bool * b) > fun_set_b_bool).

tff(sy_c_aa_001T__c_001t__HOL__Obool, type,
    aa_c_bool : (fun_c_bool * c) > bool).

tff(sy_c_aa_001T__c_001t__fun_IT__c_Mt__HOL__Obool_J, type,
    aa_c_fun_c_bool : (fun_c_fun_c_bool * c) > fun_c_bool).

tff(sy_c_aa_001T__g_001T__h, type,
    aa_g_h : (fun_g_h * g) > h).

tff(sy_c_aa_001T__g_001t__fun_It__Set__Oset_IT__g_J_Mt__HOL__Obool_J, type,
    aa_g_fun_set_g_bool : (fun_g_fun_set_g_bool * g) > fun_set_g_bool).

tff(sy_c_aa_001T__h_001t__HOL__Obool, type,
    aa_h_bool : (fun_h_bool * h) > bool).

tff(sy_c_aa_001T__h_001t__fun_It__Set__Oset_IT__h_J_Mt__HOL__Obool_J, type,
    aa_h_fun_set_h_bool : (fun_h_fun_set_h_bool * h) > fun_set_h_bool).

tff(sy_c_aa_001T__i_001T__j, type,
    aa_i_j : (fun_i_j * i) > j).

tff(sy_c_aa_001T__i_001t__fun_It__Set__Oset_IT__i_J_Mt__HOL__Obool_J, type,
    aa_i_fun_set_i_bool : (fun_i_fun_set_i_bool * i) > fun_set_i_bool).

tff(sy_c_aa_001T__j_001t__HOL__Obool, type,
    aa_j_bool : (fun_j_bool * j) > bool).

tff(sy_c_aa_001T__j_001t__fun_It__Set__Oset_IT__j_J_Mt__HOL__Obool_J, type,
    aa_j_fun_set_j_bool : (fun_j_fun_set_j_bool * j) > fun_set_j_bool).

tff(sy_c_aa_001t__List__Olist_IT__a_J_001t__HOL__Obool, type,
    aa_list_a_bool : (fun_list_a_bool * list_a) > bool).

tff(sy_c_aa_001t__List__Olist_IT__a_J_001t__Set__Oset_IT__a_J, type,
    aa_list_a_set_a : (fun_list_a_set_a * list_a) > set_a2).

tff(sy_c_aa_001t__List__Olist_IT__b_J_001t__HOL__Obool, type,
    aa_list_b_bool : (fun_list_b_bool * list_b) > bool).

tff(sy_c_aa_001t__List__Olist_IT__b_J_001t__Set__Oset_IT__b_J, type,
    aa_list_b_set_b : (fun_list_b_set_b * list_b) > set_b).

tff(sy_c_aa_001t__List__Olist_It__Set__Oset_IT__a_J_J_001t__HOL__Obool, type,
    aa_list_set_a_bool : (fun_list_set_a_bool * list_set_a) > bool).

tff(sy_c_aa_001t__List__Olist_It__Set__Oset_IT__a_J_J_001t__Set__Oset_It__Set__Oset_IT__a_J_J, type,
    aa_lis126049132_set_a : (fun_li1246370091_set_a * list_set_a) > set_set_a).

tff(sy_c_aa_001t__Nat__Onat_001t__HOL__Obool, type,
    aa_nat_bool : (fun_nat_bool * nat) > bool).

tff(sy_c_aa_001t__Nat__Onat_001t__fun_It__Nat__Onat_Mt__HOL__Obool_J, type,
    aa_nat_fun_nat_bool : (fun_nat_fun_nat_bool * nat) > fun_nat_bool).

tff(sy_c_aa_001t__Nat__Onat_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J, type,
    aa_nat733854815_set_a : (fun_na746762910_set_a * nat) > fun_se490019921_set_a).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__HOL__Obool, type,
    aa_set_a_bool : (fun_set_a_bool * set_a2) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__Set__Oset_IT__a_J, type,
    aa_set_a_set_a : (fun_set_a_set_a * set_a2) > set_a2).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__Set__Oset_IT__b_J, type,
    aa_set_a_set_b : (fun_set_a_set_b * set_a2) > set_b).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_IT__a_Mt__HOL__Obool_J, type,
    aa_set_a_fun_a_bool : (fun_set_a_fun_a_bool * set_a2) > fun_a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__List__Olist_IT__a_J_Mt__HOL__Obool_J, type,
    aa_set1088820336a_bool : (fun_se607730439a_bool * set_a2) > fun_list_a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    aa_set1122887114a_bool : (fun_se1296151905a_bool * set_a2) > fun_set_a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J, type,
    aa_set1454015380a_bool : (fun_se590241323a_bool * set_a2) > fun_set_set_a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__b_J_001t__HOL__Obool, type,
    aa_set_b_bool : (fun_set_b_bool * set_b) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__b_J_001t__Set__Oset_IT__a_J, type,
    aa_set_b_set_a : (fun_set_b_set_a * set_b) > set_a2).

tff(sy_c_aa_001t__Set__Oset_IT__b_J_001t__fun_It__List__Olist_IT__b_J_Mt__HOL__Obool_J, type,
    aa_set175724142b_bool : (fun_se317721989b_bool * set_b) > fun_list_b_bool).

tff(sy_c_aa_001t__Set__Oset_IT__b_J_001t__fun_It__Set__Oset_IT__b_J_Mt__HOL__Obool_J, type,
    aa_set1415681864b_bool : (fun_se64550751b_bool * set_b) > fun_set_b_bool).

tff(sy_c_aa_001t__Set__Oset_IT__g_J_001t__HOL__Obool, type,
    aa_set_g_bool : (fun_set_g_bool * set_g) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__g_J_001t__Set__Oset_IT__h_J, type,
    aa_set_g_set_h : (fun_set_g_set_h * set_g) > set_h).

tff(sy_c_aa_001t__Set__Oset_IT__h_J_001t__HOL__Obool, type,
    aa_set_h_bool : (fun_set_h_bool * set_h) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__i_J_001t__HOL__Obool, type,
    aa_set_i_bool : (fun_set_i_bool * set_i) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__i_J_001t__Set__Oset_IT__j_J, type,
    aa_set_i_set_j : (fun_set_i_set_j * set_i) > set_j).

tff(sy_c_aa_001t__Set__Oset_IT__j_J_001t__HOL__Obool, type,
    aa_set_j_bool : (fun_set_j_bool * set_j) > bool).

tff(sy_c_aa_001t__Set__Oset_It__List__Olist_IT__a_J_J_001t__HOL__Obool, type,
    aa_set_list_a_bool : (fun_set_list_a_bool * set_list_a) > bool).

tff(sy_c_aa_001t__Set__Oset_It__List__Olist_IT__b_J_J_001t__HOL__Obool, type,
    aa_set_list_b_bool : (fun_set_list_b_bool * set_list_b) > bool).

tff(sy_c_aa_001t__Set__Oset_It__Nat__Onat_J_001t__Set__Oset_IT__a_J, type,
    aa_set_nat_set_a : (fun_set_nat_set_a * set_nat) > set_a2).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__HOL__Obool, type,
    aa_set_set_a_bool : (fun_set_set_a_bool * set_set_a) > bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__Set__Oset_IT__a_J, type,
    aa_set_set_a_set_a : (fun_set_set_a_set_a * set_set_a) > set_a2).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__Set__Oset_It__Set__Oset_IT__a_J_J, type,
    aa_set1102275218_set_a : (fun_se490019921_set_a * set_set_a) > set_set_a).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J, type,
    aa_set677970270a_bool : (fun_se1447345141a_bool * set_set_a) > fun_set_set_a_bool).

tff(sy_c_aa_001t__fun_IT__a_MT__a_J_001t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J, type,
    aa_fun1919496604_set_a : (fun_fu804670939_set_a * fun_a_a2) > fun_set_a_set_a).

tff(sy_c_aa_001t__fun_IT__a_MT__b_J_001t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__b_J_J, type,
    aa_fun1558368798_set_b : (fun_fu749632989_set_b * fun_a_b) > fun_set_a_set_b).

tff(sy_c_aa_001t__fun_IT__a_Mt__HOL__Obool_J_001t__HOL__Obool, type,
    aa_fun_a_bool_bool : (fun_fun_a_bool_bool * fun_a_bool) > bool).

tff(sy_c_aa_001t__fun_IT__a_Mt__HOL__Obool_J_001t__Set__Oset_IT__a_J, type,
    aa_fun_a_bool_set_a : (fun_fun_a_bool_set_a * fun_a_bool) > set_a2).

tff(sy_c_aa_001t__fun_IT__a_Mt__HOL__Obool_J_001t__fun_IT__a_Mt__HOL__Obool_J, type,
    aa_fun1510068540a_bool : (fun_fu816707011a_bool * fun_a_bool) > fun_a_bool).

tff(sy_c_aa_001t__fun_IT__a_Mt__HOL__Obool_J_001t__fun_It__fun_IT__a_Mt__HOL__Obool_J_Mt__HOL__Obool_J, type,
    aa_fun1584535710l_bool : (fun_fu647214445l_bool * fun_a_bool) > fun_fun_a_bool_bool).

tff(sy_c_aa_001t__fun_IT__a_Mt__HOL__Obool_J_001t__fun_It__fun_IT__a_Mt__HOL__Obool_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J, type,
    aa_fun1085870137a_bool : (fun_fu958398344a_bool * fun_a_bool) > fun_fu816707011a_bool).

tff(sy_c_aa_001t__fun_IT__a_Mt__fun_IT__a_Mt__HOL__Obool_J_J_001t__fun_It__List__Olist_IT__a_J_Mt__HOL__Obool_J, type,
    aa_fun480720209a_bool : (fun_fu1580049368a_bool * fun_a_fun_a_bool) > fun_list_a_bool).

tff(sy_c_aa_001t__fun_IT__b_MT__a_J_001t__fun_It__Set__Oset_IT__b_J_Mt__Set__Oset_IT__a_J_J, type,
    aa_fun662792990_set_a : (fun_fu1241503453_set_a * fun_b_a) > fun_set_b_set_a).

tff(sy_c_aa_001t__fun_IT__g_MT__h_J_001t__fun_It__Set__Oset_IT__g_J_Mt__Set__Oset_IT__h_J_J, type,
    aa_fun441314870_set_h : (fun_fu892916725_set_h * fun_g_h) > fun_set_g_set_h).

tff(sy_c_aa_001t__fun_IT__i_MT__j_J_001t__fun_It__Set__Oset_IT__i_J_Mt__Set__Oset_IT__j_J_J, type,
    aa_fun1500619326_set_j : (fun_fu1656505853_set_j * fun_i_j) > fun_set_i_set_j).

tff(sy_c_aa_001t__fun_It__List__Olist_IT__a_J_Mt__HOL__Obool_J_001t__Set__Oset_It__List__Olist_IT__a_J_J, type,
    aa_fun975174250list_a : (fun_fu226907449list_a * fun_list_a_bool) > set_list_a).

tff(sy_c_aa_001t__fun_It__List__Olist_IT__b_J_Mt__HOL__Obool_J_001t__Set__Oset_It__List__Olist_IT__b_J_J, type,
    aa_fun2117011626list_b : (fun_fu1674834681list_b * fun_list_b_bool) > set_list_b).

tff(sy_c_aa_001t__fun_It__Nat__Onat_MT__a_J_001t__fun_It__Set__Oset_It__Nat__Onat_J_Mt__Set__Oset_IT__a_J_J, type,
    aa_fun357214912_set_a : (fun_fu2018723327_set_a * fun_nat_a) > fun_set_nat_set_a).

tff(sy_c_aa_001t__fun_It__Nat__Onat_Mt__HOL__Obool_J_001t__Set__Oset_It__Nat__Onat_J, type,
    aa_fun778297194et_nat : (fun_fu874497849et_nat * fun_nat_bool) > set_nat).

tff(sy_c_aa_001t__fun_It__Set__Oset_IT__a_J_MT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__Set__Oset_IT__a_J_J, type,
    aa_fun1287875592_set_a : (fun_fu557047111_set_a * fun_set_a_a) > fun_set_set_a_set_a).

tff(sy_c_aa_001t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_001t__Set__Oset_It__Set__Oset_IT__a_J_J, type,
    aa_fun1146893418_set_a : (fun_fu1487319609_set_a * fun_set_a_bool) > set_set_a).

tff(sy_c_aa_001t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J_001t__fun_It__List__Olist_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J, type,
    aa_fun406926727a_bool : (fun_fu564408078a_bool * fun_se1296151905a_bool) > fun_list_set_a_bool).

tff(sy_c_fFalse, type,
    fFalse : bool).

tff(sy_c_fTrue, type,
    fTrue : bool).

tff(sy_c_member_001T__a, type,
    member_a : fun_a_fun_set_a_bool).

tff(sy_c_member_001T__b, type,
    member_b : fun_b_fun_set_b_bool).

tff(sy_c_member_001T__g, type,
    member_g : fun_g_fun_set_g_bool).

tff(sy_c_member_001T__h, type,
    member_h : fun_h_fun_set_h_bool).

tff(sy_c_member_001T__i, type,
    member_i : fun_i_fun_set_i_bool).

tff(sy_c_member_001T__j, type,
    member_j : fun_j_fun_set_j_bool).

tff(sy_c_member_001t__Set__Oset_IT__a_J, type,
    member_set_a : fun_se590241323a_bool).

tff(sy_c_pp, type,
    pp : bool > $o).


% Relevant facts (72)

tff(fact_0_finite__Collect__subsets, axiom,
    ((![A : $i, A2 : set_a2]: (pp(aa_set_a_bool(finite_finite_a, A2)) => pp(aa_set_set_a_bool(finite_finite_set_a, aa_fun1146893418_set_a(collect_set_a, aa_set1122887114a_bool(aTP_Lamm_a, A2)))))))). % finite_Collect_subsets

tff(fact_1_finite__sorted__distinct__unique, axiom,
    ((![A : $i]: (linorder(a3) => (![A2 : set_a2]: (pp(aa_set_a_bool(finite_finite_a, A2)) => (?[X : list_a]: (((aa_list_a_set_a(set_a3, X) = A2) & (pp(aa_list_a_bool(aa_fun480720209a_bool(sorted_wrt_a, ord_less_eq_a), X)) & pp(aa_list_a_bool(distinct_a, X)))) & (![Y : list_a]: (((aa_list_a_set_a(set_a3, Y) = A2) & (pp(aa_list_a_bool(aa_fun480720209a_bool(sorted_wrt_a, ord_less_eq_a), Y)) & pp(aa_list_a_bool(distinct_a, Y)))) => (Y = X))))))))))). % finite_sorted_distinct_unique

tff(fact_2_psubsetI, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B)) => ((A2 != B) => pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_set_a, A2), B))))))). % psubsetI

tff(fact_3_list_Oset__finite, axiom,
    ((![A : $i, X2 : list_a]: pp(aa_set_a_bool(finite_finite_a, aa_list_a_set_a(set_a3, X2)))))). % list.set_finite

tff(fact_4_List_Ofinite__set, axiom,
    ((![A : $i, Xs : list_a]: pp(aa_set_a_bool(finite_finite_a, aa_list_a_set_a(set_a3, Xs)))))). % List.finite_set

tff(fact_5_finite__imageI, axiom,
    ((![B2 : $i, A : $i, F : set_a2, H : fun_a_b]: (pp(aa_set_a_bool(finite_finite_a, F)) => pp(aa_set_b_bool(finite_finite_b, aa_set_a_set_b(aa_fun1558368798_set_b(image_a_b, H), F))))))). % finite_imageI

tff(fact_6_geotop__iterated__Sd__simplex__in__K__simplex, axiom,
    ((![A : $i]: (euclid925273238_space(a3) => (![K : set_set_a, Tau : set_a2, M : nat]: (pp(aa_set_set_a_bool(geotop_is_complex_a, K)) => (pp(aa_set_set_a_bool(finite_finite_set_a, K)) => (pp(aa_set_set_a_bool(aa_set1454015380a_bool(member_set_a, Tau), aa_set1102275218_set_a(aa_nat733854815_set_a(geotop_iterated_Sd_a, M), K))) => (?[X : set_a2]: (pp(aa_set_set_a_bool(aa_set1454015380a_bool(member_set_a, X), K)) & pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, Tau), X)))))))))))). % geotop_iterated_Sd_simplex_in_K_simplex

tff(fact_7_finite__subset__distinct, axiom,
    ((![A : $i, A2 : set_a2]: (pp(aa_set_a_bool(finite_finite_a, A2)) => pp(aa_set_list_a_bool(finite_finite_list_a, aa_fun975174250list_a(collect_list_a, aa_set1088820336a_bool(aTP_Lamm_aa, A2)))))))). % finite_subset_distinct

tff(fact_8_geotop__finite__distinct__lists__over__finite, axiom,
    ((![B2 : $i, S : set_b]: (pp(aa_set_b_bool(finite_finite_b, S)) => pp(aa_set_list_b_bool(finite_finite_list_b, aa_fun2117011626list_b(collect_list_b, aa_set175724142b_bool(aTP_Lamm_ab, S)))))))). % geotop_finite_distinct_lists_over_finite

tff(fact_9_geotop__chain__barycenters__in__top, axiom,
    ((![A : $i]: (euclid925273238_space(a3) => (![K : set_set_a, S : set_set_a, Sigma_p : set_a2]: (pp(aa_set_set_a_bool(geotop_is_complex_a, K)) => ((![X : set_a2]: (pp(aa_set_set_a_bool(aa_set1454015380a_bool(member_set_a, X), S)) => pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, X), Sigma_p)))) => ((![X : set_a2]: (pp(aa_set_set_a_bool(aa_set1454015380a_bool(member_set_a, X), S)) => pp(aa_set_set_a_bool(aa_set1454015380a_bool(member_set_a, X), K)))) => pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, aa_set_set_a_set_a(aa_fun1287875592_set_a(image_set_a_a, geotop_barycenter_a), S)), Sigma_p)))))))))). % geotop_chain_barycenters_in_top

tff(fact_10_sorted__distinct__set__unique, axiom,
    ((![A : $i]: (linorder(a3) => (![Xs : list_a, Ys : list_a]: (pp(aa_list_a_bool(aa_fun480720209a_bool(sorted_wrt_a, ord_less_eq_a), Xs)) => (pp(aa_list_a_bool(distinct_a, Xs)) => (pp(aa_list_a_bool(aa_fun480720209a_bool(sorted_wrt_a, ord_less_eq_a), Ys)) => (pp(aa_list_a_bool(distinct_a, Ys)) => ((aa_list_a_set_a(set_a3, Xs) = aa_list_a_set_a(set_a3, Ys)) => (Xs = Ys))))))))))). % sorted_distinct_set_unique

tff(fact_11_strict__sorted__iff, axiom,
    ((![A : $i]: (linorder(a3) => (![L : list_a]: (pp(aa_list_a_bool(aa_fun480720209a_bool(sorted_wrt_a, ord_less_a), L)) <=> (pp(aa_list_a_bool(aa_fun480720209a_bool(sorted_wrt_a, ord_less_eq_a), L)) & pp(aa_list_a_bool(distinct_a, L))))))))). % strict_sorted_iff

tff(fact_12_subset__antisym, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B)) => (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, B), A2)) => (A2 = B)))))). % subset_antisym

tff(fact_13_equalityI, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B)) => (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, B), A2)) => (A2 = B)))))). % equalityI

tff(fact_14_subsetI, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: ((![X : a3]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X), A2)) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X), B)))) => pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B)))))). % subsetI

tff(fact_15_image__eqI, axiom,
    ((![A : $i, B2 : $i, B3 : a3, F2 : fun_b_a, X2 : b, A2 : set_b]: ((B3 = aa_b_a(F2, X2)) => (pp(aa_set_b_bool(aa_b_fun_set_b_bool(member_b, X2), A2)) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, B3), aa_set_b_set_a(aa_fun662792990_set_a(image_b_a, F2), A2)))))))). % image_eqI

tff(fact_16_ex__image__cong__iff_I2_J, axiom,
    ((![A : $i, B2 : $i, F2 : fun_b_a, A2 : set_b, P : fun_a_bool]: ((?[X3 : a3]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X3), aa_set_b_set_a(aa_fun662792990_set_a(image_b_a, F2), A2))) & pp(aa_a_bool(P, X3)))) <=> (?[X3 : b]: (pp(aa_set_b_bool(aa_b_fun_set_b_bool(member_b, X3), A2)) & pp(aa_a_bool(P, aa_b_a(F2, X3))))))))). % ex_image_cong_iff(2)

tff(fact_17_ball__simps_I9_J, axiom,
    ((![J : $i, I : $i, F2 : fun_i_j, A2 : set_i, P : fun_j_bool]: ((![X3 : j]: (pp(aa_set_j_bool(aa_j_fun_set_j_bool(member_j, X3), aa_set_i_set_j(aa_fun1500619326_set_j(image_i_j, F2), A2))) => pp(aa_j_bool(P, X3)))) <=> (![X3 : i]: (pp(aa_set_i_bool(aa_i_fun_set_i_bool(member_i, X3), A2)) => pp(aa_j_bool(P, aa_i_j(F2, X3))))))))). % ball_simps(9)

tff(fact_18_bex__simps_I7_J, axiom,
    ((![H2 : $i, G : $i, F2 : fun_g_h, A2 : set_g, P : fun_h_bool]: ((?[X3 : h]: (pp(aa_set_h_bool(aa_h_fun_set_h_bool(member_h, X3), aa_set_g_set_h(aa_fun441314870_set_h(image_g_h, F2), A2))) & pp(aa_h_bool(P, X3)))) <=> (?[X3 : g]: (pp(aa_set_g_bool(aa_g_fun_set_g_bool(member_g, X3), A2)) & pp(aa_h_bool(P, aa_g_h(F2, X3))))))))). % bex_simps(7)

tff(fact_19_finite__code, axiom,
    ((![A : $i]: (finite_finite(a3) => (![A2 : set_a2]: pp(aa_set_a_bool(finite_finite_a, A2))))))). % finite_code

tff(fact_20_image__ident, axiom,
    ((![A : $i, Y2 : set_a2]: (aa_set_a_set_a(aa_fun1919496604_set_a(image_a_a, aTP_Lamm_ac), Y2) = Y2)))). % image_ident

tff(fact_21_finite__Collect__disjI, axiom,
    ((![A : $i, P : fun_a_bool, Q : fun_a_bool]: (pp(aa_set_a_bool(finite_finite_a, aa_fun_a_bool_set_a(collect_a, aa_fun1510068540a_bool(aa_fun1085870137a_bool(aTP_Lamm_ad, P), Q)))) <=> (pp(aa_set_a_bool(finite_finite_a, aa_fun_a_bool_set_a(collect_a, P))) & pp(aa_set_a_bool(finite_finite_a, aa_fun_a_bool_set_a(collect_a, Q)))))))). % finite_Collect_disjI

tff(fact_22_finite__Collect__conjI, axiom,
    ((![A : $i, P : fun_a_bool, Q : fun_a_bool]: ((pp(aa_set_a_bool(finite_finite_a, aa_fun_a_bool_set_a(collect_a, P))) | pp(aa_set_a_bool(finite_finite_a, aa_fun_a_bool_set_a(collect_a, Q)))) => pp(aa_set_a_bool(finite_finite_a, aa_fun_a_bool_set_a(collect_a, aa_fun1510068540a_bool(aa_fun1085870137a_bool(aTP_Lamm_ae, P), Q)))))))). % finite_Collect_conjI

tff(fact_23_finite__conv__nat__seg__image, axiom,
    ((![A : $i, A2 : set_a2]: (pp(aa_set_a_bool(finite_finite_a, A2)) <=> (?[N : nat, F3 : fun_nat_a]: (A2 = aa_set_nat_set_a(aa_fun357214912_set_a(image_nat_a, F3), aa_fun778297194et_nat(collect_nat, aa_nat_fun_nat_bool(aTP_Lamm_af, N))))))))). % finite_conv_nat_seg_image

tff(fact_24_nat__seg__image__imp__finite, axiom,
    ((![A : $i, A2 : set_a2, F2 : fun_nat_a, N2 : nat]: ((A2 = aa_set_nat_set_a(aa_fun357214912_set_a(image_nat_a, F2), aa_fun778297194et_nat(collect_nat, aa_nat_fun_nat_bool(aTP_Lamm_af, N2)))) => pp(aa_set_a_bool(finite_finite_a, A2)))))). % nat_seg_image_imp_finite

tff(fact_25_less__eq__set__def, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B)) <=> pp(aa_fun_a_bool_bool(aa_fun1584535710l_bool(ord_le801610962a_bool, aa_set_a_fun_a_bool(aTP_Lamm_ag, A2)), aa_set_a_fun_a_bool(aTP_Lamm_ag, B))))))). % less_eq_set_def

tff(fact_26_less__set__def, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_set_a, A2), B)) <=> pp(aa_fun_a_bool_bool(aa_fun1584535710l_bool(ord_less_fun_a_bool, aa_set_a_fun_a_bool(aTP_Lamm_ag, A2)), aa_set_a_fun_a_bool(aTP_Lamm_ag, B))))))). % less_set_def

tff(fact_27_basic__trans__rules_I7_J, axiom,
    ((![A : $i, C : $i]: ((order(c) & order(a3)) => (![A3 : a3, B3 : a3, F2 : fun_a_c, C2 : c]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3)) => (pp(aa_c_bool(aa_c_fun_c_bool(ord_less_eq_c, aa_a_c(F2, B3)), C2)) => ((![X : a3, Y3 : a3]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X), Y3)) => pp(aa_c_bool(aa_c_fun_c_bool(ord_less_eq_c, aa_a_c(F2, X)), aa_a_c(F2, Y3))))) => pp(aa_c_bool(aa_c_fun_c_bool(ord_less_eq_c, aa_a_c(F2, A3)), C2)))))))))). % basic_trans_rules(7)

tff(fact_28_basic__trans__rules_I8_J, axiom,
    ((![A : $i, B2 : $i]: ((order(b) & order(a3)) => (![A3 : a3, F2 : fun_b_a, B3 : b, C2 : b]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), aa_b_a(F2, B3))) => (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, B3), C2)) => ((![X : b, Y3 : b]: (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, X), Y3)) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, aa_b_a(F2, X)), aa_b_a(F2, Y3))))) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), aa_b_a(F2, C2))))))))))). % basic_trans_rules(8)

tff(fact_29_basic__trans__rules_I9_J, axiom,
    ((![A : $i, B2 : $i]: ((ord(b) & ord(a3)) => (![A3 : a3, B3 : a3, F2 : fun_a_b, C2 : b]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3)) => ((aa_a_b(F2, B3) = C2) => ((![X : a3, Y3 : a3]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X), Y3)) => pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, aa_a_b(F2, X)), aa_a_b(F2, Y3))))) => pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, aa_a_b(F2, A3)), C2)))))))))). % basic_trans_rules(9)

tff(fact_30_basic__trans__rules_I10_J, axiom,
    ((![A : $i, B2 : $i]: ((ord(b) & ord(a3)) => (![A3 : a3, F2 : fun_b_a, B3 : b, C2 : b]: ((A3 = aa_b_a(F2, B3)) => (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, B3), C2)) => ((![X : b, Y3 : b]: (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_eq_b, X), Y3)) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, aa_b_a(F2, X)), aa_b_a(F2, Y3))))) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), aa_b_a(F2, C2))))))))))). % basic_trans_rules(10)

tff(fact_31_basic__trans__rules_I23_J, axiom,
    ((![A : $i]: (preorder(a3) => (![X2 : a3, Y4 : a3, Z : a3]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X2), Y4)) => (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Y4), Z)) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X2), Z))))))))). % basic_trans_rules(23)

tff(fact_32_basic__trans__rules_I24_J, axiom,
    ((![A : $i]: (order(a3) => (![A3 : a3, B3 : a3]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3)) => (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, B3), A3)) => (A3 = B3)))))))). % basic_trans_rules(24)

tff(fact_33_basic__trans__rules_I25_J, axiom,
    ((![A : $i]: (ord(a3) => (![A3 : a3, B3 : a3, C2 : a3]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), B3)) => ((B3 = C2) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), C2))))))))). % basic_trans_rules(25)

tff(fact_34_basic__trans__rules_I26_J, axiom,
    ((![A : $i]: (ord(a3) => (![A3 : a3, B3 : a3, C2 : a3]: ((A3 = B3) => (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, B3), C2)) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A3), C2))))))))). % basic_trans_rules(26)

tff(fact_35_basic__trans__rules_I1_J, axiom,
    ((![A : $i, C : $i]: ((order(c) & order(a3)) => (![A3 : a3, B3 : a3, F2 : fun_a_c, C2 : c]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, A3), B3)) => (pp(aa_c_bool(aa_c_fun_c_bool(ord_less_c, aa_a_c(F2, B3)), C2)) => ((![X : a3, Y3 : a3]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, X), Y3)) => pp(aa_c_bool(aa_c_fun_c_bool(ord_less_c, aa_a_c(F2, X)), aa_a_c(F2, Y3))))) => pp(aa_c_bool(aa_c_fun_c_bool(ord_less_c, aa_a_c(F2, A3)), C2)))))))))). % basic_trans_rules(1)

tff(fact_36_basic__trans__rules_I2_J, axiom,
    ((![A : $i, B2 : $i]: ((order(b) & order(a3)) => (![A3 : a3, F2 : fun_b_a, B3 : b, C2 : b]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, A3), aa_b_a(F2, B3))) => (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_b, B3), C2)) => ((![X : b, Y3 : b]: (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_b, X), Y3)) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, aa_b_a(F2, X)), aa_b_a(F2, Y3))))) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, A3), aa_b_a(F2, C2))))))))))). % basic_trans_rules(2)

tff(fact_37_basic__trans__rules_I11_J, axiom,
    ((![A : $i, B2 : $i]: ((ord(b) & ord(a3)) => (![A3 : a3, B3 : a3, F2 : fun_a_b, C2 : b]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, A3), B3)) => ((aa_a_b(F2, B3) = C2) => ((![X : a3, Y3 : a3]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, X), Y3)) => pp(aa_b_bool(aa_b_fun_b_bool(ord_less_b, aa_a_b(F2, X)), aa_a_b(F2, Y3))))) => pp(aa_b_bool(aa_b_fun_b_bool(ord_less_b, aa_a_b(F2, A3)), C2)))))))))). % basic_trans_rules(11)

tff(fact_38_basic__trans__rules_I12_J, axiom,
    ((![A : $i, B2 : $i]: ((ord(b) & ord(a3)) => (![A3 : a3, F2 : fun_b_a, B3 : b, C2 : b]: ((A3 = aa_b_a(F2, B3)) => (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_b, B3), C2)) => ((![X : b, Y3 : b]: (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_b, X), Y3)) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, aa_b_a(F2, X)), aa_b_a(F2, Y3))))) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, A3), aa_b_a(F2, C2))))))))))). % basic_trans_rules(12)

tff(fact_39_basic__trans__rules_I19_J, axiom,
    ((![A : $i]: (preorder(a3) => (![X2 : a3, Y4 : a3, Z : a3]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, X2), Y4)) => (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, Y4), Z)) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, X2), Z))))))))). % basic_trans_rules(19)

tff(fact_40_basic__trans__rules_I20_J, axiom,
    ((![A : $i]: (preorder(a3) => (![A3 : a3, B3 : a3]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, A3), B3)) => (~ (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, B3), A3)))))))))). % basic_trans_rules(20)

tff(fact_41_basic__trans__rules_I27_J, axiom,
    ((![A : $i]: (ord(a3) => (![A3 : a3, B3 : a3, C2 : a3]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, A3), B3)) => ((B3 = C2) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, A3), C2))))))))). % basic_trans_rules(27)

tff(fact_42_basic__trans__rules_I28_J, axiom,
    ((![A : $i]: (ord(a3) => (![A3 : a3, B3 : a3, C2 : a3]: ((A3 = B3) => (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, B3), C2)) => pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, A3), C2))))))))). % basic_trans_rules(28)

tff(fact_43_Collect__mono__iff, axiom,
    ((![A : $i, P : fun_a_bool, Q : fun_a_bool]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, aa_fun_a_bool_set_a(collect_a, P)), aa_fun_a_bool_set_a(collect_a, Q))) <=> (![X3 : a3]: (pp(aa_a_bool(P, X3)) => pp(aa_a_bool(Q, X3)))))))). % Collect_mono_iff

tff(fact_44_contra__subsetD, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2, C2 : a3]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B)) => ((~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C2), B)))) => (~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C2), A2))))))))). % contra_subsetD

tff(fact_45_mem__Collect__eq, axiom,
    ((![A : $i, A3 : a3, P : fun_a_bool]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, A3), aa_fun_a_bool_set_a(collect_a, P))) <=> pp(aa_a_bool(P, A3)))))). % mem_Collect_eq

tff(fact_46_Collect__mem__eq, axiom,
    ((![A : $i, A2 : set_a2]: (aa_fun_a_bool_set_a(collect_a, aa_set_a_fun_a_bool(aTP_Lamm_ag, A2)) = A2)))). % Collect_mem_eq

tff(fact_47_Collect__cong, axiom,
    ((![A : $i, P : fun_a_bool, Q : fun_a_bool]: ((![X : a3]: (pp(aa_a_bool(P, X)) <=> pp(aa_a_bool(Q, X)))) => (aa_fun_a_bool_set_a(collect_a, P) = aa_fun_a_bool_set_a(collect_a, Q)))))). % Collect_cong

tff(fact_48_ext, axiom,
    ((![B2 : $i, A : $i, F2 : fun_a_b, G2 : fun_a_b]: ((![X : a3]: (aa_a_b(F2, X) = aa_a_b(G2, X))) => (F2 = G2))))). % ext

tff(fact_49_mem__simps_I7_J, axiom,
    ((![A : $i, A3 : a3, P : fun_a_bool]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, A3), aa_fun_a_bool_set_a(collect_a, P))) <=> pp(aa_a_bool(P, A3)))))). % mem_simps(7)

tff(fact_50_array__rules_I1_J, axiom,
    ((![B2 : $i, A : $i, F2 : fun_a_b, G2 : fun_a_b]: ((![X : a3]: (aa_a_b(F2, X) = aa_a_b(G2, X))) => (F2 = G2))))). % array_rules(1)

tff(fact_51_set__eq__subset, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: ((A2 = B) <=> (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B)) & pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, B), A2))))))). % set_eq_subset

tff(fact_52_subset__trans, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2, C3 : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B)) => (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, B), C3)) => pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), C3))))))). % subset_trans

tff(fact_53_Collect__mono, axiom,
    ((![A : $i, P : fun_a_bool, Q : fun_a_bool]: ((![X : a3]: (pp(aa_a_bool(P, X)) => pp(aa_a_bool(Q, X)))) => pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, aa_fun_a_bool_set_a(collect_a, P)), aa_fun_a_bool_set_a(collect_a, Q))))))). % Collect_mono

tff(fact_54_subset__refl, axiom,
    ((![A : $i, A2 : set_a2]: pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), A2))))). % subset_refl

tff(fact_55_rev__subsetD, axiom,
    ((![A : $i, C2 : a3, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C2), A2)) => (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B)) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C2), B))))))). % rev_subsetD

tff(fact_56_subset__iff, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B)) <=> (![T : a3]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, T), A2)) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, T), B)))))))). % subset_iff

tff(fact_57_set__rev__mp, axiom,
    ((![A : $i, C2 : a3, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C2), A2)) => (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B)) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C2), B))))))). % set_rev_mp

tff(fact_58_equalityD2, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: ((A2 = B) => pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, B), A2)))))). % equalityD2

tff(fact_59_equalityD1, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: ((A2 = B) => pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B)))))). % equalityD1

tff(fact_60_subset__eq, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B)) <=> (![X3 : a3]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X3), A2)) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X3), B)))))))). % subset_eq

tff(fact_61_equalityE, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: ((A2 = B) => (~ ((pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B)) => (~ (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, B), A2))))))))))). % equalityE

tff(fact_62_subsetCE, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2, C2 : a3]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B)) => (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C2), A2)) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C2), B))))))). % subsetCE

tff(fact_63_subsetD, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2, C2 : a3]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), B)) => (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C2), A2)) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C2), B))))))). % subsetD

tff(fact_64_ATP_Olambda__1, axiom,
    ((![B2 : $i, Uu : set_b, Uua : list_b]: (pp(aa_list_b_bool(aa_set175724142b_bool(aTP_Lamm_ab, Uu), Uua)) <=> (pp(aa_set_b_bool(aa_set1415681864b_bool(ord_less_eq_set_b, aa_list_b_set_b(set_b2, Uua)), Uu)) & pp(aa_list_b_bool(distinct_b, Uua))))))). % ATP.lambda_1

tff(fact_65_ATP_Olambda__2, axiom,
    ((![A : $i, Uu : set_a2, Uua : list_a]: (pp(aa_list_a_bool(aa_set1088820336a_bool(aTP_Lamm_aa, Uu), Uua)) <=> (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, aa_list_a_set_a(set_a3, Uua)), Uu)) & pp(aa_list_a_bool(distinct_a, Uua))))))). % ATP.lambda_2

tff(fact_66_ATP_Olambda__3, axiom,
    ((![A : $i, Uu : set_a2, Uua : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(aTP_Lamm_a, Uu), Uua)) <=> pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, Uua), Uu)))))). % ATP.lambda_3

tff(fact_67_ATP_Olambda__4, axiom,
    ((![Uu : nat, Uua : nat]: (pp(aa_nat_bool(aa_nat_fun_nat_bool(aTP_Lamm_af, Uu), Uua)) <=> pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, Uua), Uu)))))). % ATP.lambda_4

tff(fact_68_ATP_Olambda__5, axiom,
    ((![A : $i, Uu : set_a2, Uua : a3]: (pp(aa_a_bool(aa_set_a_fun_a_bool(aTP_Lamm_ag, Uu), Uua)) <=> pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, Uua), Uu)))))). % ATP.lambda_5

tff(fact_69_ATP_Olambda__6, axiom,
    ((![A : $i, Uu : fun_a_bool, Uua : fun_a_bool, Uub : a3]: (pp(aa_a_bool(aa_fun1510068540a_bool(aa_fun1085870137a_bool(aTP_Lamm_ad, Uu), Uua), Uub)) <=> (pp(aa_a_bool(Uu, Uub)) | pp(aa_a_bool(Uua, Uub))))))). % ATP.lambda_6

tff(fact_70_ATP_Olambda__7, axiom,
    ((![A : $i, Uu : fun_a_bool, Uua : fun_a_bool, Uub : a3]: (pp(aa_a_bool(aa_fun1510068540a_bool(aa_fun1085870137a_bool(aTP_Lamm_ae, Uu), Uua), Uub)) <=> (pp(aa_a_bool(Uu, Uub)) & pp(aa_a_bool(Uua, Uub))))))). % ATP.lambda_7

tff(fact_71_ATP_Olambda__8, axiom,
    ((![A : $i, Uu : a3]: (aa_a_a(aTP_Lamm_ac, Uu) = Uu)))). % ATP.lambda_8


% Type constructors (17)

tff(tcon_fun___Orderings_Opreorder, axiom,
    ((![A4 : $i, A5 : $i]: (preorder(a) => preorder(fun_a_a))))).

tff(tcon_fun___Finite__Set_Ofinite, axiom,
    ((![A4 : $i, A5 : $i]: ((finite_finite(a2) & finite_finite(a)) => finite_finite(fun_a_a))))).

tff(tcon_fun___Orderings_Oorder, axiom,
    ((![A4 : $i, A5 : $i]: (order(a) => order(fun_a_a))))).

tff(tcon_fun___Orderings_Oord, axiom,
    ((![A4 : $i, A5 : $i]: (ord(a) => ord(fun_a_a))))).

tff(tcon_Nat_Onat___Orderings_Opreorder_1, axiom,
    (preorder(nat))).

tff(tcon_Nat_Onat___Orderings_Olinorder, axiom,
    (linorder(nat))).

tff(tcon_Nat_Onat___Orderings_Oorder_2, axiom,
    (order(nat))).

tff(tcon_Nat_Onat___Orderings_Oord_3, axiom,
    (ord(nat))).

tff(tcon_Set_Oset___Orderings_Opreorder_4, axiom,
    ((![A4 : $i]: preorder(set_a)))).

tff(tcon_Set_Oset___Finite__Set_Ofinite_5, axiom,
    ((![A4 : $i]: (finite_finite(a2) => finite_finite(set_a))))).

tff(tcon_Set_Oset___Orderings_Oorder_6, axiom,
    ((![A4 : $i]: order(set_a)))).

tff(tcon_Set_Oset___Orderings_Oord_7, axiom,
    ((![A4 : $i]: ord(set_a)))).

tff(tcon_HOL_Obool___Orderings_Opreorder_8, axiom,
    (preorder(bool))).

tff(tcon_HOL_Obool___Orderings_Olinorder_9, axiom,
    (linorder(bool))).

tff(tcon_HOL_Obool___Finite__Set_Ofinite_10, axiom,
    (finite_finite(bool))).

tff(tcon_HOL_Obool___Orderings_Oorder_11, axiom,
    (order(bool))).

tff(tcon_HOL_Obool___Orderings_Oord_12, axiom,
    (ord(bool))).


% Helper facts (2)

tff(help_pp_2_1_U, axiom,
    (pp(fTrue))).

tff(help_pp_1_1_U, axiom,
    ((~ (pp(fFalse))))).


% Conjectures (4)

tff(conj_0, hypothesis,
    ((![A : $i]: (euclid925273238_space(a3) => (![K : set_set_a]: pp(aa_set_set_a_bool(geotop_is_complex_a, K))))))).

tff(conj_1, hypothesis,
    ((![A : $i]: (euclid925273238_space(a3) => (![K : set_set_a]: pp(aa_set_set_a_bool(finite_finite_set_a, K))))))).

tff(conj_2, hypothesis,
    ((![A : $i]: (euclid925273238_space(a3) => (![Tau : set_a2, K : set_set_a]: pp(aa_set_set_a_bool(aa_set1454015380a_bool(member_set_a, Tau), aa_set1102275218_set_a(aa_nat733854815_set_a(geotop_iterated_Sd_a, one_one_nat), K)))))))).

tff(conj_3, conjecture,
    ((![A : $i]: (euclid925273238_space(a3) => (![K : set_set_a, Tau : set_a2]: (?[C4 : list_set_a]: ((C4 != nil_set_a) & (pp(aa_set_set_a_bool(aa_set677970270a_bool(ord_le1348423818_set_a, aa_lis126049132_set_a(set_set_a2, C4)), K)) & (pp(aa_list_set_a_bool(aa_fun406926727a_bool(sorted_wrt_set_a, ord_less_set_a), C4)) & (pp(aa_list_set_a_bool(distinct_set_a, C4)) & (Tau = aa_set_a_set_a(geotop_convex_hull_a, aa_set_set_a_set_a(aa_fun1287875592_set_a(image_set_a_a, geotop_barycenter_a), aa_lis126049132_set_a(set_set_a2, C4)))))))))))))).

