% This file was generated by Isabelle (most likely Sledgehammer)
2026-06-02 20:31:48.191

% Could-be-implicit typings (57)

tff(ty_n_t__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__HOL__Obool_J_J_J_J_J, type,
    fun_se3566430091_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__HOL__Obool_J_J_J_J, type,
    fun_se10033951391_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__HOL__Obool_J_J_J, type,
    fun_se17996897711_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_J_J, type,
    fun_se1683296923l_num1 : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__HOL__Obool_J_J, type,
    fun_se8482916291_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_J, type,
    fun_se554467587l_num1 : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J_J_J_J, type,
    fun_se1454099088a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__HOL__Obool_J, type,
    fun_se660289491_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J_J_J, type,
    fun_se1125638315a_bool : $tType).

tff(ty_n_t__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J, type,
    set_Fi857430405l_num1 : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J_J, type,
    fun_se456803398a_bool : $tType).

tff(ty_n_t__fun_It__fun_IT__a_MT__b_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_MT__b_J_J_J, type,
    fun_fu391738216un_a_b : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J_J, type,
    fun_se1395821270_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J, type,
    fun_se1296151905a_bool : $tType).

tff(ty_n_t__fun_It__fun_IT__a_Mt__HOL__Obool_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_fun_a_bool_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J, type,
    fun_set_a_fun_a_bool : $tType).

tff(ty_n_t__fun_IT__e_Mt__fun_It__Set__Oset_IT__e_J_Mt__HOL__Obool_J_J, type,
    fun_e_fun_set_e_bool : $tType).

tff(ty_n_t__fun_IT__c_Mt__fun_It__Set__Oset_IT__c_J_Mt__HOL__Obool_J_J, type,
    fun_c_fun_set_c_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J, type,
    fun_a_fun_set_a_bool : $tType).

tff(ty_n_t__Finite____Cartesian____Product__Ovec_IT__a__1_MT__a__2_J, type,
    finite1731297606ec_a_a : $tType).

tff(ty_n_t__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_MT__b_J_J, type,
    fun_fun_a_b_fun_a_b : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_set_a_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__e_J_Mt__HOL__Obool_J, type,
    fun_set_e_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__c_J_Mt__HOL__Obool_J, type,
    fun_set_c_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    fun_set_a_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_IT__a_Mt__HOL__Obool_J_J, type,
    fun_a_fun_a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_MT__a_J, type,
    fun_set_a_a : $tType).

tff(ty_n_t__fun_IT__b_Mt__fun_IT__b_MT__b_J_J, type,
    fun_b_fun_b_b : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_IT__a_MT__a_J_J, type,
    fun_a_fun_a_a : $tType).

tff(ty_n_t__Numeral____Type__Obit0_IT__a__1_J, type,
    numeral_bit0_a : $tType).

tff(ty_n_t__fun_IT__e_Mt__HOL__Obool_J, type,
    fun_e_bool : $tType).

tff(ty_n_t__fun_IT__c_Mt__HOL__Obool_J, type,
    fun_c_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__HOL__Obool_J, type,
    fun_a_bool : $tType).

tff(ty_n_t__fun_IT__a__1_MT__a__2_J, type,
    fun_a_a : $tType).

tff(ty_n_t__Numeral____Type__Onum1, type,
    numeral_num1 : $tType).

tff(ty_n_t__Set__Oset_IT__a__1_J, type,
    set_a : $tType).

tff(ty_n_t__fun_IT__b_MT__b_J, type,
    fun_b_b : $tType).

tff(ty_n_t__fun_IT__a_MT__b_J, type,
    fun_a_b : $tType).

tff(ty_n_t__fun_IT__a_MT__a_J, type,
    fun_a_a2 : $tType).

tff(ty_n_t__Set__Oset_IT__e_J, type,
    set_e : $tType).

tff(ty_n_t__Set__Oset_IT__c_J, type,
    set_c : $tType).

tff(ty_n_t__Set__Oset_IT__a_J, type,
    set_a2 : $tType).

tff(ty_n_t__Real__Oreal, type,
    real : $tType).

tff(ty_n_t__HOL__Obool, type,
    bool : $tType).

tff(ty_n_T__a__2, type,
    a : $tType).

tff(ty_n_T__a__1, type,
    a2 : $tType).

tff(ty_n_T__e, type,
    e : $tType).

tff(ty_n_T__c, type,
    c : $tType).

tff(ty_n_T__b, type,
    b : $tType).

tff(ty_n_T__a, type,
    a3 : $tType).

tff(sy_cl_Ordered__Euclidean__Space_Oordered__euclidean__space, type,
    ordere890947078_space : !>[A : $tType]: $o).

tff(sy_cl_Real__Vector__Spaces_Oreal__normed__vector, type,
    real_V55928688vector : !>[A : $tType]: $o).

tff(sy_cl_Complete__Lattices_Ocomplete__lattice, type,
    comple187826305attice : !>[A : $tType]: $o).

tff(sy_cl_Lattices_Osemilattice__sup, type,
    semilattice_sup : !>[A : $tType]: $o).

tff(sy_cl_Finite__Set_Ofinite, type,
    finite_finite : !>[A : $tType]: $o).

tff(sy_cl_Lattices_Olattice, type,
    lattice : !>[A : $tType]: $o).

tff(sy_cl_Groups_Ominus, type,
    minus : !>[A : $tType]: $o).


% Explicit typings (59)

tff(sy_c_ATP_058Lamm__a, type,
    aTP_Lamm_a : fun_set_a_fun_a_bool).

tff(sy_c_Complete__Lattices_OSup__class_OSup_001T__a, type,
    complete_Sup_Sup_a : fun_set_a_a).

tff(sy_c_GeoTopBase_Ogeotop__arc__interior_001t__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J, type,
    geotop1440280007l_num1 : fun_se1683296923l_num1).

tff(sy_c_GeoTop__Prefix_Ogeotop__is__polyhedral__theta__graph_001T__a, type,
    geoTop1978091745raph_a : fun_se1454099088a_bool).

tff(sy_c_GeoTop__Prefix_Ogeotop__is__polyhedral__theta__graph_001t__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J, type,
    geoTop1152744770l_num1 : fun_se3566430091_bool).

tff(sy_c_GeoTop__Prefix_Ogeotop__is__theta__graph_001T__a, type,
    geoTop1089232703raph_a : fun_se1454099088a_bool).

tff(sy_c_Groups_Ominus__class_Ominus_001T__b, type,
    minus_minus_b : fun_b_fun_b_b).

tff(sy_c_Groups_Ominus__class_Ominus_001t__Set__Oset_IT__a_J, type,
    minus_minus_set_a : fun_se1395821270_set_a).

tff(sy_c_Groups_Ominus__class_Ominus_001t__fun_IT__a_MT__b_J, type,
    minus_minus_fun_a_b : fun_fu391738216un_a_b).

tff(sy_c_Lattices_Osup__class_Osup_001T__a, type,
    sup_sup_a : fun_a_fun_a_a).

tff(sy_c_Lattices_Osup__class_Osup_001T__b, type,
    sup_sup_b : fun_b_fun_b_b).

tff(sy_c_Lattices_Osup__class_Osup_001t__Set__Oset_IT__a_J, type,
    sup_sup_set_a : fun_se1395821270_set_a).

tff(sy_c_Lattices_Osup__class_Osup_001t__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J, type,
    sup_su2030898009l_num1 : fun_se1683296923l_num1).

tff(sy_c_Lattices_Osup__class_Osup_001t__fun_IT__a_MT__b_J, type,
    sup_sup_fun_a_b : fun_fu391738216un_a_b).

tff(sy_c_Orderings_Obot__class_Obot_001t__Set__Oset_IT__a_J, type,
    bot_bot_set_a : set_a2).

tff(sy_c_Orderings_Obot__class_Obot_001t__Set__Oset_IT__c_J, type,
    bot_bot_set_c : set_c).

tff(sy_c_Orderings_Obot__class_Obot_001t__Set__Oset_IT__e_J, type,
    bot_bot_set_e : set_e).

tff(sy_c_Orderings_Oord__class_Oless__eq_001T__a, type,
    ord_less_eq_a : fun_a_fun_a_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001t__Set__Oset_IT__a_J, type,
    ord_less_eq_set_a : fun_se1296151905a_bool).

tff(sy_c_Set_OCollect_001T__a, type,
    collect_a : fun_fun_a_bool_set_a).

tff(sy_c_aa_001T__a_001T__a, type,
    aa_a_a : (fun_a_a2 * a3) > a3).

tff(sy_c_aa_001T__a_001T__b, type,
    aa_a_b : (fun_a_b * a3) > b).

tff(sy_c_aa_001T__a_001t__HOL__Obool, type,
    aa_a_bool : (fun_a_bool * a3) > bool).

tff(sy_c_aa_001T__a_001t__fun_IT__a_MT__a_J, type,
    aa_a_fun_a_a : (fun_a_fun_a_a * a3) > fun_a_a2).

tff(sy_c_aa_001T__a_001t__fun_IT__a_Mt__HOL__Obool_J, type,
    aa_a_fun_a_bool : (fun_a_fun_a_bool * a3) > fun_a_bool).

tff(sy_c_aa_001T__a_001t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    aa_a_fun_set_a_bool : (fun_a_fun_set_a_bool * a3) > fun_set_a_bool).

tff(sy_c_aa_001T__b_001T__b, type,
    aa_b_b : (fun_b_b * b) > b).

tff(sy_c_aa_001T__b_001t__fun_IT__b_MT__b_J, type,
    aa_b_fun_b_b : (fun_b_fun_b_b * b) > fun_b_b).

tff(sy_c_aa_001T__c_001t__HOL__Obool, type,
    aa_c_bool : (fun_c_bool * c) > bool).

tff(sy_c_aa_001T__c_001t__fun_It__Set__Oset_IT__c_J_Mt__HOL__Obool_J, type,
    aa_c_fun_set_c_bool : (fun_c_fun_set_c_bool * c) > fun_set_c_bool).

tff(sy_c_aa_001T__e_001t__HOL__Obool, type,
    aa_e_bool : (fun_e_bool * e) > bool).

tff(sy_c_aa_001T__e_001t__fun_It__Set__Oset_IT__e_J_Mt__HOL__Obool_J, type,
    aa_e_fun_set_e_bool : (fun_e_fun_set_e_bool * e) > fun_set_e_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001T__a, type,
    aa_set_a_a : (fun_set_a_a * set_a2) > a3).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__HOL__Obool, type,
    aa_set_a_bool : (fun_set_a_bool * set_a2) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__Set__Oset_IT__a_J, type,
    aa_set_a_set_a : (fun_set_a_set_a * set_a2) > set_a2).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_IT__a_Mt__HOL__Obool_J, type,
    aa_set_a_fun_a_bool : (fun_set_a_fun_a_bool * set_a2) > fun_a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    aa_set1122887114a_bool : (fun_se1296151905a_bool * set_a2) > fun_set_a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J, type,
    aa_set363163287_set_a : (fun_se1395821270_set_a * set_a2) > fun_set_a_set_a).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J, type,
    aa_set924202799a_bool : (fun_se456803398a_bool * set_a2) > fun_se1296151905a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J_J, type,
    aa_set573724180a_bool : (fun_se1125638315a_bool * set_a2) > fun_se456803398a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J_J_J, type,
    aa_set984842873a_bool : (fun_se1454099088a_bool * set_a2) > fun_se1125638315a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__c_J_001t__HOL__Obool, type,
    aa_set_c_bool : (fun_set_c_bool * set_c) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__e_J_001t__HOL__Obool, type,
    aa_set_e_bool : (fun_set_e_bool * set_e) > bool).

tff(sy_c_aa_001t__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_001t__HOL__Obool, type,
    aa_set12678787981_bool : (fun_se660289491_bool * set_Fi857430405l_num1) > bool).

tff(sy_c_aa_001t__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_001t__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J, type,
    aa_set1402112508l_num1 : (fun_se554467587l_num1 * set_Fi857430405l_num1) > set_Fi857430405l_num1).

tff(sy_c_aa_001t__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_001t__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__HOL__Obool_J, type,
    aa_set8031428781_bool : (fun_se8482916291_bool * set_Fi857430405l_num1) > fun_se660289491_bool).

tff(sy_c_aa_001t__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_001t__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_J, type,
    aa_set1536463692l_num1 : (fun_se1683296923l_num1 * set_Fi857430405l_num1) > fun_se554467587l_num1).

tff(sy_c_aa_001t__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_001t__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__HOL__Obool_J_J, type,
    aa_set4730626921_bool : (fun_se17996897711_bool * set_Fi857430405l_num1) > fun_se8482916291_bool).

tff(sy_c_aa_001t__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_001t__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__HOL__Obool_J_J_J, type,
    aa_set14200184201_bool : (fun_se10033951391_bool * set_Fi857430405l_num1) > fun_se17996897711_bool).

tff(sy_c_aa_001t__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_001t__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__fun_It__Set__Oset_It__Finite____Cartesian____Product__Ovec_It__Real__Oreal_Mt__Numeral____Type__Obit0_It__Numeral____Type__Onum1_J_J_J_Mt__HOL__Obool_J_J_J_J, type,
    aa_set20268791621_bool : (fun_se3566430091_bool * set_Fi857430405l_num1) > fun_se10033951391_bool).

tff(sy_c_aa_001t__fun_IT__a_MT__b_J_001t__fun_IT__a_MT__b_J, type,
    aa_fun_a_b_fun_a_b : (fun_fun_a_b_fun_a_b * fun_a_b) > fun_a_b).

tff(sy_c_aa_001t__fun_IT__a_MT__b_J_001t__fun_It__fun_IT__a_MT__b_J_Mt__fun_IT__a_MT__b_J_J, type,
    aa_fun911777065un_a_b : (fun_fu391738216un_a_b * fun_a_b) > fun_fun_a_b_fun_a_b).

tff(sy_c_aa_001t__fun_IT__a_Mt__HOL__Obool_J_001t__Set__Oset_IT__a_J, type,
    aa_fun_a_bool_set_a : (fun_fun_a_bool_set_a * fun_a_bool) > set_a2).

tff(sy_c_fFalse, type,
    fFalse : bool).

tff(sy_c_fTrue, type,
    fTrue : bool).

tff(sy_c_member_001T__a, type,
    member_a : fun_a_fun_set_a_bool).

tff(sy_c_member_001T__c, type,
    member_c : fun_c_fun_set_c_bool).

tff(sy_c_member_001T__e, type,
    member_e : fun_e_fun_set_e_bool).

tff(sy_c_pp, type,
    pp : bool > $o).


% Relevant facts (65)

tff(fact_0_unfold__simps_I1_J, axiom,
    ((![A : $i, C : a3, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B))) <=> (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A2)) | pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B))))))). % unfold_simps(1)

tff(fact_1_mem__simps_I3_J, axiom,
    ((![A : $i, C : a3, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B))) <=> (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A2)) | pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B))))))). % mem_simps(3)

tff(fact_2_UnCI, axiom,
    ((![A : $i, C : a3, B : set_a2, A2 : set_a2]: (((~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B)))) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A2))) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B))))))). % UnCI

tff(fact_3_Un__iff, axiom,
    ((![A : $i, C : a3, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B))) <=> (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A2)) | pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B))))))). % Un_iff

tff(fact_4_sup__aci_I4_J, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![X : a3, Y : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, X), aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Y)) = aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Y))))))). % sup_aci(4)

tff(fact_5_sup_Oidem, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![A3 : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), A3) = A3)))))). % sup.idem

tff(fact_6_sup__idem, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![X : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, X), X) = X)))))). % sup_idem

tff(fact_7_sup_Oleft__idem, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![A3 : a3, B2 : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), B2)) = aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), B2))))))). % sup.left_idem

tff(fact_8_sup__left__idem, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![X : a3, Y : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, X), aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Y)) = aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Y))))))). % sup_left_idem

tff(fact_9_sup_Oright__idem, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![A3 : a3, B2 : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), B2)), B2) = aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), B2))))))). % sup.right_idem

tff(fact_10_sup__apply, axiom,
    ((![B3 : $i, A : $i]: (semilattice_sup(b) => (![F : fun_a_b, G : fun_a_b, X : a3]: (aa_a_b(aa_fun_a_b_fun_a_b(aa_fun911777065un_a_b(sup_sup_fun_a_b, F), G), X) = aa_b_b(aa_b_fun_b_b(sup_sup_b, aa_a_b(F, X)), aa_a_b(G, X)))))))). % sup_apply

tff(fact_11_Un__ac_I4_J, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2, C2 : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, B), C2)) = aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, B), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), C2)))))). % Un_ac(4)

tff(fact_12_sup__fun__def, axiom,
    ((![B3 : $i, A : $i]: (semilattice_sup(b) => (![F : fun_a_b, G : fun_a_b, X2 : a3]: (aa_a_b(aa_fun_a_b_fun_a_b(aa_fun911777065un_a_b(sup_sup_fun_a_b, F), G), X2) = aa_b_b(aa_b_fun_b_b(sup_sup_b, aa_a_b(F, X2)), aa_a_b(G, X2)))))))). % sup_fun_def

tff(fact_13_sup__left__commute, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![X : a3, Y : a3, Z : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, X), aa_a_a(aa_a_fun_a_a(sup_sup_a, Y), Z)) = aa_a_a(aa_a_fun_a_a(sup_sup_a, Y), aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Z)))))))). % sup_left_commute

tff(fact_14_sup_Oleft__commute, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![B2 : a3, A3 : a3, C : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, B2), aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), C)) = aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), aa_a_a(aa_a_fun_a_a(sup_sup_a, B2), C)))))))). % sup.left_commute

tff(fact_15_sup__commute, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![X : a3, Y : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Y) = aa_a_a(aa_a_fun_a_a(sup_sup_a, Y), X))))))). % sup_commute

tff(fact_16_sup_Ocommute, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![A3 : a3, B2 : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), B2) = aa_a_a(aa_a_fun_a_a(sup_sup_a, B2), A3))))))). % sup.commute

tff(fact_17_sup__assoc, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![X : a3, Y : a3, Z : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Y)), Z) = aa_a_a(aa_a_fun_a_a(sup_sup_a, X), aa_a_a(aa_a_fun_a_a(sup_sup_a, Y), Z)))))))). % sup_assoc

tff(fact_18_sup_Oassoc, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![A3 : a3, B2 : a3, C : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), B2)), C) = aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), aa_a_a(aa_a_fun_a_a(sup_sup_a, B2), C)))))))). % sup.assoc

tff(fact_19_sup__aci_I1_J, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![X : a3, Y : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Y) = aa_a_a(aa_a_fun_a_a(sup_sup_a, Y), X))))))). % sup_aci(1)

tff(fact_20_sup__aci_I2_J, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![X : a3, Y : a3, Z : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Y)), Z) = aa_a_a(aa_a_fun_a_a(sup_sup_a, X), aa_a_a(aa_a_fun_a_a(sup_sup_a, Y), Z)))))))). % sup_aci(2)

tff(fact_21_sup__aci_I3_J, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![X : a3, Y : a3, Z : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, X), aa_a_a(aa_a_fun_a_a(sup_sup_a, Y), Z)) = aa_a_a(aa_a_fun_a_a(sup_sup_a, Y), aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Z)))))))). % sup_aci(3)

tff(fact_22_inf__sup__aci_I5_J, axiom,
    ((![A : $i]: (lattice(a3) => (![X : a3, Y : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Y) = aa_a_a(aa_a_fun_a_a(sup_sup_a, Y), X))))))). % inf_sup_aci(5)

tff(fact_23_inf__sup__aci_I6_J, axiom,
    ((![A : $i]: (lattice(a3) => (![X : a3, Y : a3, Z : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Y)), Z) = aa_a_a(aa_a_fun_a_a(sup_sup_a, X), aa_a_a(aa_a_fun_a_a(sup_sup_a, Y), Z)))))))). % inf_sup_aci(6)

tff(fact_24_inf__sup__aci_I7_J, axiom,
    ((![A : $i]: (lattice(a3) => (![X : a3, Y : a3, Z : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, X), aa_a_a(aa_a_fun_a_a(sup_sup_a, Y), Z)) = aa_a_a(aa_a_fun_a_a(sup_sup_a, Y), aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Z)))))))). % inf_sup_aci(7)

tff(fact_25_inf__sup__aci_I8_J, axiom,
    ((![A : $i]: (lattice(a3) => (![X : a3, Y : a3]: (aa_a_a(aa_a_fun_a_a(sup_sup_a, X), aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Y)) = aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Y))))))). % inf_sup_aci(8)

tff(fact_26_Un__left__commute, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2, C2 : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, B), C2)) = aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, B), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), C2)))))). % Un_left_commute

tff(fact_27_Un__left__absorb, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B)) = aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B))))). % Un_left_absorb

tff(fact_28_Un__commute, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B) = aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, B), A2))))). % Un_commute

tff(fact_29_Un__absorb, axiom,
    ((![A : $i, A2 : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), A2) = A2)))). % Un_absorb

tff(fact_30_Un__assoc, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2, C2 : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B)), C2) = aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, B), C2)))))). % Un_assoc

tff(fact_31_ball__Un, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2, P : fun_a_bool]: ((![X3 : a3]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X3), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B))) => pp(aa_a_bool(P, X3)))) <=> ((![X3 : a3]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X3), A2)) => pp(aa_a_bool(P, X3)))) & (![X3 : a3]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X3), B)) => pp(aa_a_bool(P, X3))))))))). % ball_Un

tff(fact_32_bex__Un, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2, P : fun_a_bool]: ((?[X3 : a3]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X3), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B))) & pp(aa_a_bool(P, X3)))) <=> ((?[X3 : a3]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X3), A2)) & pp(aa_a_bool(P, X3)))) | (?[X3 : a3]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X3), B)) & pp(aa_a_bool(P, X3))))))))). % bex_Un

tff(fact_33_UnI2, axiom,
    ((![A : $i, C : a3, B : set_a2, A2 : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B)) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B))))))). % UnI2

tff(fact_34_UnI1, axiom,
    ((![A : $i, C : a3, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A2)) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B))))))). % UnI1

tff(fact_35_UnE, axiom,
    ((![A : $i, C : a3, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B))) => ((~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A2)))) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B))))))). % UnE

tff(fact_36_Un__ac_I1_J, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2, C2 : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B)), C2) = aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, B), C2)))))). % Un_ac(1)

tff(fact_37_Un__ac_I2_J, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B)) = aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B))))). % Un_ac(2)

tff(fact_38_Un__ac_I3_J, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B) = aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, B), A2))))). % Un_ac(3)

tff(fact_39_boolean__algebra__cancel_Osup2, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![B : a3, K : a3, B2 : a3, A3 : a3]: ((B = aa_a_a(aa_a_fun_a_a(sup_sup_a, K), B2)) => (aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), B) = aa_a_a(aa_a_fun_a_a(sup_sup_a, K), aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), B2))))))))). % boolean_algebra_cancel.sup2

tff(fact_40_boolean__algebra__cancel_Osup1, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![A2 : a3, K : a3, A3 : a3, B2 : a3]: ((A2 = aa_a_a(aa_a_fun_a_a(sup_sup_a, K), A3)) => (aa_a_a(aa_a_fun_a_a(sup_sup_a, A2), B2) = aa_a_a(aa_a_fun_a_a(sup_sup_a, K), aa_a_a(aa_a_fun_a_a(sup_sup_a, A3), B2))))))))). % boolean_algebra_cancel.sup1

tff(fact_41_Sup__union__distrib, axiom,
    ((![A : $i]: (comple187826305attice(a3) => (![A2 : set_a2, B : set_a2]: (aa_set_a_a(complete_Sup_Sup_a, aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B)) = aa_a_a(aa_a_fun_a_a(sup_sup_a, aa_set_a_a(complete_Sup_Sup_a, A2)), aa_set_a_a(complete_Sup_Sup_a, B)))))))). % Sup_union_distrib

tff(fact_42_polyhedral__theta__graph__imp__theta, axiom,
    ((![A : $i]: (real_V55928688vector(a3) => (![M : set_a2, B1 : set_a2, B22 : set_a2, B32 : set_a2, E : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(aa_set924202799a_bool(aa_set573724180a_bool(aa_set984842873a_bool(geoTop1978091745raph_a, M), B1), B22), B32), E)) => pp(aa_set_a_bool(aa_set1122887114a_bool(aa_set924202799a_bool(aa_set573724180a_bool(aa_set984842873a_bool(geoTop1089232703raph_a, M), B1), B22), B32), E)))))))). % polyhedral_theta_graph_imp_theta

tff(fact_43_Un__empty, axiom,
    ((![A : $i, A2 : set_a2, B : set_a2]: ((aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, A2), B) = bot_bot_set_a) <=> ((A2 = bot_bot_set_a) & (B = bot_bot_set_a)))))). % Un_empty

tff(fact_44_sup_Obounded__iff, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![B2 : a3, C : a3, A3 : a3]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, aa_a_a(aa_a_fun_a_a(sup_sup_a, B2), C)), A3)) <=> (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, B2), A3)) & pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, C), A3))))))))). % sup.bounded_iff

tff(fact_45_mem__Collect__eq, axiom,
    ((![A : $i, A3 : a3, P : fun_a_bool]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, A3), aa_fun_a_bool_set_a(collect_a, P))) <=> pp(aa_a_bool(P, A3)))))). % mem_Collect_eq

tff(fact_46_Collect__mem__eq, axiom,
    ((![A : $i, A2 : set_a2]: (aa_fun_a_bool_set_a(collect_a, aa_set_a_fun_a_bool(aTP_Lamm_a, A2)) = A2)))). % Collect_mem_eq

tff(fact_47_Collect__cong, axiom,
    ((![A : $i, P : fun_a_bool, Q : fun_a_bool]: ((![X4 : a3]: (pp(aa_a_bool(P, X4)) <=> pp(aa_a_bool(Q, X4)))) => (aa_fun_a_bool_set_a(collect_a, P) = aa_fun_a_bool_set_a(collect_a, Q)))))). % Collect_cong

tff(fact_48_ext, axiom,
    ((![B3 : $i, A : $i, F : fun_a_b, G : fun_a_b]: ((![X4 : a3]: (aa_a_b(F, X4) = aa_a_b(G, X4))) => (F = G))))). % ext

tff(fact_49_mem__simps_I7_J, axiom,
    ((![A : $i, A3 : a3, P : fun_a_bool]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, A3), aa_fun_a_bool_set_a(collect_a, P))) <=> pp(aa_a_bool(P, A3)))))). % mem_simps(7)

tff(fact_50_array__rules_I1_J, axiom,
    ((![B3 : $i, A : $i, F : fun_a_b, G : fun_a_b]: ((![X4 : a3]: (aa_a_b(F, X4) = aa_a_b(G, X4))) => (F = G))))). % array_rules(1)

tff(fact_51_le__sup__iff, axiom,
    ((![A : $i]: (semilattice_sup(a3) => (![X : a3, Y : a3, Z : a3]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, aa_a_a(aa_a_fun_a_a(sup_sup_a, X), Y)), Z)) <=> (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, X), Z)) & pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, Y), Z))))))))). % le_sup_iff

tff(fact_52_Un__Diff__cancel2, axiom,
    ((![A : $i, B : set_a2, A2 : set_a2]: (aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, aa_set_a_set_a(aa_set363163287_set_a(minus_minus_set_a, B), A2)), A2) = aa_set_a_set_a(aa_set363163287_set_a(sup_sup_set_a, B), A2))))). % Un_Diff_cancel2

tff(fact_53_minus__apply, axiom,
    ((![B3 : $i, A : $i]: (minus(b) => (![A2 : fun_a_b, B : fun_a_b, X : a3]: (aa_a_b(aa_fun_a_b_fun_a_b(aa_fun911777065un_a_b(minus_minus_fun_a_b, A2), B), X) = aa_b_b(aa_b_fun_b_b(minus_minus_b, aa_a_b(A2, X)), aa_a_b(B, X)))))))). % minus_apply

tff(fact_54_bex__simps_I3_J, axiom,
    ((![C3 : $i, P : fun_c_bool]: (~ ((?[X2 : c]: (pp(aa_set_c_bool(aa_c_fun_set_c_bool(member_c, X2), bot_bot_set_c)) & pp(aa_c_bool(P, X2))))))))). % bex_simps(3)

tff(fact_55_ball__simps_I5_J, axiom,
    ((![E2 : $i, P : fun_e_bool, X2 : e]: (pp(aa_set_e_bool(aa_e_fun_set_e_bool(member_e, X2), bot_bot_set_e)) => pp(aa_e_bool(P, X2)))))). % ball_simps(5)

tff(fact_56_mem__simps_I2_J, axiom,
    ((![A : $i, C : a3]: (~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), bot_bot_set_a))))))). % mem_simps(2)

tff(fact_57_empty__iff, axiom,
    ((![A : $i, C : a3]: (~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), bot_bot_set_a))))))). % empty_iff

tff(fact_58_subset__empty, axiom,
    ((![A : $i, A2 : set_a2]: (pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, A2), bot_bot_set_a)) <=> (A2 = bot_bot_set_a))))). % subset_empty

tff(fact_59_empty__subsetI, axiom,
    ((![A : $i, A2 : set_a2]: pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, bot_bot_set_a), A2))))). % empty_subsetI

tff(fact_60_all__not__in__conv, axiom,
    ((![A : $i, A2 : set_a2]: ((![X3 : a3]: (~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X3), A2))))) <=> (A2 = bot_bot_set_a))))). % all_not_in_conv

tff(fact_61_Collect__empty__eq, axiom,
    ((![A : $i, P : fun_a_bool]: ((aa_fun_a_bool_set_a(collect_a, P) = bot_bot_set_a) <=> (![X3 : a3]: (~ (pp(aa_a_bool(P, X3))))))))). % Collect_empty_eq

tff(fact_62_empty__Collect__eq, axiom,
    ((![A : $i, P : fun_a_bool]: ((bot_bot_set_a = aa_fun_a_bool_set_a(collect_a, P)) <=> (![X3 : a3]: (~ (pp(aa_a_bool(P, X3))))))))). % empty_Collect_eq

tff(fact_63_mem__simps_I6_J, axiom,
    ((![A : $i, C : a3, A2 : set_a2, B : set_a2]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), aa_set_a_set_a(aa_set363163287_set_a(minus_minus_set_a, A2), B))) <=> (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), A2)) & (~ (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, C), B))))))))). % mem_simps(6)

tff(fact_64_ATP_Olambda__1, axiom,
    ((![A : $i, Uu : set_a2, Uua : a3]: (pp(aa_a_bool(aa_set_a_fun_a_bool(aTP_Lamm_a, Uu), Uua)) <=> pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, Uua), Uu)))))). % ATP.lambda_1


% Type constructors (30)

tff(tcon_Finite__Cartesian__Product_Ovec___Finite__Set_Ofinite, axiom,
    ((![A4 : $i, A5 : $i]: ((finite_finite(a2) & finite_finite(a)) => finite_finite(finite1731297606ec_a_a))))).

tff(tcon_Finite__Cartesian__Product_Ovec___Ordered__Euclidean__Space_Oordered__euclidean__space, axiom,
    ((![A4 : $i, A5 : $i]: ((ordere890947078_space(a2) & finite_finite(a)) => ordere890947078_space(finite1731297606ec_a_a))))).

tff(tcon_Numeral__Type_Onum1___Finite__Set_Ofinite_1, axiom,
    (finite_finite(numeral_num1))).

tff(tcon_Numeral__Type_Obit0___Finite__Set_Ofinite_2, axiom,
    ((![A4 : $i]: (finite_finite(a2) => finite_finite(numeral_bit0_a))))).

tff(tcon_Real_Oreal___Ordered__Euclidean__Space_Oordered__euclidean__space_3, axiom,
    (ordere890947078_space(real))).

tff(tcon_HOL_Obool___Finite__Set_Ofinite_4, axiom,
    (finite_finite(bool))).

tff(tcon_Set_Oset___Finite__Set_Ofinite_5, axiom,
    ((![A4 : $i]: (finite_finite(a2) => finite_finite(set_a))))).

tff(tcon_fun___Finite__Set_Ofinite_6, axiom,
    ((![A4 : $i, A5 : $i]: ((finite_finite(a2) & finite_finite(a)) => finite_finite(fun_a_a))))).

tff(tcon_fun___Complete__Lattices_Ocomplete__lattice, axiom,
    ((![A4 : $i, A5 : $i]: (comple187826305attice(a) => comple187826305attice(fun_a_a))))).

tff(tcon_fun___Lattices_Osemilattice__sup, axiom,
    ((![A4 : $i, A5 : $i]: (semilattice_sup(a) => semilattice_sup(fun_a_a))))).

tff(tcon_fun___Lattices_Olattice, axiom,
    ((![A4 : $i, A5 : $i]: (lattice(a) => lattice(fun_a_a))))).

tff(tcon_fun___Groups_Ominus, axiom,
    ((![A4 : $i, A5 : $i]: (minus(a) => minus(fun_a_a))))).

tff(tcon_Set_Oset___Complete__Lattices_Ocomplete__lattice_7, axiom,
    ((![A4 : $i]: comple187826305attice(set_a)))).

tff(tcon_Set_Oset___Lattices_Osemilattice__sup_8, axiom,
    ((![A4 : $i]: semilattice_sup(set_a)))).

tff(tcon_Set_Oset___Lattices_Olattice_9, axiom,
    ((![A4 : $i]: lattice(set_a)))).

tff(tcon_Set_Oset___Groups_Ominus_10, axiom,
    ((![A4 : $i]: minus(set_a)))).

tff(tcon_HOL_Obool___Complete__Lattices_Ocomplete__lattice_11, axiom,
    (comple187826305attice(bool))).

tff(tcon_HOL_Obool___Lattices_Osemilattice__sup_12, axiom,
    (semilattice_sup(bool))).

tff(tcon_HOL_Obool___Lattices_Olattice_13, axiom,
    (lattice(bool))).

tff(tcon_HOL_Obool___Groups_Ominus_14, axiom,
    (minus(bool))).

tff(tcon_Real_Oreal___Real__Vector__Spaces_Oreal__normed__vector, axiom,
    (real_V55928688vector(real))).

tff(tcon_Real_Oreal___Lattices_Osemilattice__sup_15, axiom,
    (semilattice_sup(real))).

tff(tcon_Real_Oreal___Lattices_Olattice_16, axiom,
    (lattice(real))).

tff(tcon_Real_Oreal___Groups_Ominus_17, axiom,
    (minus(real))).

tff(tcon_Numeral__Type_Obit0___Groups_Ominus_18, axiom,
    ((![A4 : $i]: (finite_finite(a2) => minus(numeral_bit0_a))))).

tff(tcon_Numeral__Type_Onum1___Groups_Ominus_19, axiom,
    (minus(numeral_num1))).

tff(tcon_Finite__Cartesian__Product_Ovec___Real__Vector__Spaces_Oreal__normed__vector_20, axiom,
    ((![A4 : $i, A5 : $i]: ((real_V55928688vector(a2) & finite_finite(a)) => real_V55928688vector(finite1731297606ec_a_a))))).

tff(tcon_Finite__Cartesian__Product_Ovec___Lattices_Osemilattice__sup_21, axiom,
    ((![A4 : $i, A5 : $i]: ((ordere890947078_space(a2) & finite_finite(a)) => semilattice_sup(finite1731297606ec_a_a))))).

tff(tcon_Finite__Cartesian__Product_Ovec___Lattices_Olattice_22, axiom,
    ((![A4 : $i, A5 : $i]: ((ordere890947078_space(a2) & finite_finite(a)) => lattice(finite1731297606ec_a_a))))).

tff(tcon_Finite__Cartesian__Product_Ovec___Groups_Ominus_23, axiom,
    ((![A4 : $i, A5 : $i]: ((minus(a2) & finite_finite(a)) => minus(finite1731297606ec_a_a))))).


% Helper facts (2)

tff(help_pp_2_1_U, axiom,
    (pp(fTrue))).

tff(help_pp_1_1_U, axiom,
    ((~ (pp(fFalse))))).


% Conjectures (2)

tff(conj_0, hypothesis,
    ((![M : set_Fi857430405l_num1, B1 : set_Fi857430405l_num1, B22 : set_Fi857430405l_num1, B32 : set_Fi857430405l_num1, E : set_Fi857430405l_num1]: pp(aa_set12678787981_bool(aa_set8031428781_bool(aa_set4730626921_bool(aa_set14200184201_bool(aa_set20268791621_bool(geoTop1152744770l_num1, M), B1), B22), B32), E))))).

tff(conj_1, conjecture,
    ((![M : set_Fi857430405l_num1, B1 : set_Fi857430405l_num1, E : set_Fi857430405l_num1, B22 : set_Fi857430405l_num1, B32 : set_Fi857430405l_num1]: (M = aa_set1402112508l_num1(aa_set1536463692l_num1(sup_su2030898009l_num1, aa_set1402112508l_num1(aa_set1536463692l_num1(sup_su2030898009l_num1, aa_set1402112508l_num1(aa_set1536463692l_num1(sup_su2030898009l_num1, aa_set1402112508l_num1(aa_set1536463692l_num1(geotop1440280007l_num1, B1), E)), aa_set1402112508l_num1(aa_set1536463692l_num1(geotop1440280007l_num1, B22), E))), aa_set1402112508l_num1(aa_set1536463692l_num1(geotop1440280007l_num1, B32), E))), E))))).

