% This file was generated by Isabelle (most likely Sledgehammer)
2026-06-02 21:12:44.443

% Could-be-implicit typings (105)

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_Mt__fun_It__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_J_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_Mt__HOL__Obool_J_J_J_J, type,
    fun_se434555779a_bool : $tType).

tff(ty_n_t__fun_It__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_J_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_Mt__HOL__Obool_J_J_J, type,
    fun_fu1730399037a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Real__Oreal_J_Mt__fun_It__Set__Oset_It__Set__Oset_It__Real__Oreal_J_J_Mt__fun_It__Set__Oset_It__Real__Oreal_J_Mt__fun_It__Set__Oset_It__Set__Oset_It__Real__Oreal_J_J_Mt__fun_It__fun_It__Real__Oreal_Mt__Real__Oreal_J_Mt__HOL__Obool_J_J_J_J_J, type,
    fun_se375434315l_bool : $tType).

tff(ty_n_t__fun_It__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__Real__Oreal_MT__a_J_J_J_Mt__fun_It__List__Olist_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__Real__Oreal_MT__a_J_J_J_J, type,
    fun_fu1009460459real_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_IT__a_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_J_J_J_J, type,
    fun_se1074891428real_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Real__Oreal_J_Mt__fun_It__Set__Oset_It__Set__Oset_It__Real__Oreal_J_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_J_J_J_J, type,
    fun_se1175928469a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_IT__a_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_J_J_J, type,
    fun_se1117430707real_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_It__Real__Oreal_J_J_Mt__fun_It__Set__Oset_It__Real__Oreal_J_Mt__fun_It__Set__Oset_It__Set__Oset_It__Real__Oreal_J_J_Mt__fun_It__fun_It__Real__Oreal_Mt__Real__Oreal_J_Mt__HOL__Obool_J_J_J_J, type,
    fun_se687036244l_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__HOL__Obool_J_J_J_J_J, type,
    fun_se133803932b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_IT__a_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_J_J_J, type,
    fun_se380795402real_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_It__Real__Oreal_J_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_J_J_J, type,
    fun_se1058567326a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_IT__a_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_J_J_J_J, type,
    fun_se1074563370a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_Mt__HOL__Obool_J_J, type,
    fun_se111987445a_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_J_J, type,
    fun_a_1388812940real_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__HOL__Obool_J_J_J_J, type,
    fun_se1552047031b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_IT__a_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_J_J, type,
    fun_se201199385real_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Real__Oreal_J_Mt__fun_It__Set__Oset_It__Set__Oset_It__Real__Oreal_J_J_Mt__fun_It__fun_It__Real__Oreal_Mt__Real__Oreal_J_Mt__HOL__Obool_J_J_J, type,
    fun_se1955784595l_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_J, type,
    fun_se744323153real_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_IT__a_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_J_J_J, type,
    fun_se1442295365a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_IT__a_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_J_J_J, type,
    fun_se1783137784a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J_J_J, type,
    fun_se1904574643_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__Set__Oset_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_Mt__HOL__Obool_J_J, type,
    fun_se1021952345a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_IT__a_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_J_J, type,
    fun_se1572299504real_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_J_J, type,
    fun_se1831257309a_bool : $tType).

tff(ty_n_t__fun_It__List__Olist_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__Real__Oreal_MT__a_J_J_J, type,
    fun_li903581887real_a : $tType).

tff(ty_n_t__fun_It__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_Mt__HOL__Obool_J, type,
    fun_fu1326045817a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__HOL__Obool_J_J_J, type,
    fun_se2143152776b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_It__Real__Oreal_J_J_Mt__fun_It__fun_It__Real__Oreal_Mt__Real__Oreal_J_Mt__HOL__Obool_J_J, type,
    fun_se710986396l_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_J, type,
    fun_a_456397554real_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_IT__a_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_J_J, type,
    fun_se1592439059a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J_J, type,
    fun_se122506306_set_a : $tType).

tff(ty_n_t__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__Real__Oreal_MT__a_J_J_J, type,
    fun_fu1728579119real_a : $tType).

tff(ty_n_t__fun_It__List__Olist_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__Nat__Onat_Mt__fun_It__Real__Oreal_MT__a_J_J_J, type,
    fun_li323301544real_a : $tType).

tff(ty_n_t__fun_It__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J, type,
    fun_fu1021081849real_a : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_J_J, type,
    fun_a_618731542a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_IT__a_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_J, type,
    fun_se1158460415real_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J, type,
    fun_se678812599real_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_J, type,
    fun_se691104376a_bool : $tType).

tff(ty_n_t__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_J, type,
    fun_fu1191294203a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__HOL__Obool_J_J, type,
    fun_se1751821412b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J_J, type,
    fun_se590241323a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_Mt__HOL__Obool_J, type,
    fun_se170279005a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J_J, type,
    fun_se1395821270_set_a : $tType).

tff(ty_n_t__fun_It__Real__Oreal_Mt__fun_It__Set__Oset_It__Real__Oreal_J_Mt__HOL__Obool_J_J, type,
    fun_re596238651l_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J, type,
    fun_se1296151905a_bool : $tType).

tff(ty_n_t__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__Real__Oreal_MT__a_J_J, type,
    fun_fu1277785163real_a : $tType).

tff(ty_n_t__fun_It__List__Olist_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Nat__Onat_J, type,
    fun_li1559291076_a_nat : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_J, type,
    fun_a_897415140a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J, type,
    fun_set_a_set_set_a : $tType).

tff(ty_n_t__fun_It__Real__Oreal_Mt__fun_It__Real__Oreal_Mt__Real__Oreal_J_J, type,
    fun_re785795966l_real : $tType).

tff(ty_n_t__fun_It__fun_It__Real__Oreal_Mt__Real__Oreal_J_Mt__HOL__Obool_J, type,
    fun_fu49617115l_bool : $tType).

tff(ty_n_t__fun_It__Real__Oreal_Mt__fun_It__Real__Oreal_Mt__HOL__Obool_J_J, type,
    fun_re589487345l_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J, type,
    fun_a_set_fun_real_a : $tType).

tff(ty_n_t__Set__Oset_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J, type,
    set_set_fun_real_a : $tType).

tff(ty_n_t__fun_It__fun_IT__a_Mt__HOL__Obool_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_fun_a_bool_set_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J, type,
    fun_set_set_a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__fun_IT__a_Mt__HOL__Obool_J_J, type,
    fun_set_a_fun_a_bool : $tType).

tff(ty_n_t__fun_It__Nat__Onat_Mt__fun_It__Nat__Onat_Mt__HOL__Obool_J_J, type,
    fun_nat_fun_nat_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J_J, type,
    fun_a_fun_set_a_bool : $tType).

tff(ty_n_t__fun_It__Nat__Onat_Mt__fun_It__Nat__Onat_Mt__Nat__Onat_J_J, type,
    fun_nat_fun_nat_nat : $tType).

tff(ty_n_t__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J, type,
    fun_fun_real_a_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_It__Real__Oreal_J_Mt__HOL__Obool_J, type,
    fun_set_real_bool : $tType).

tff(ty_n_t__fun_It__Nat__Onat_Mt__fun_It__Real__Oreal_MT__a_J_J, type,
    fun_nat_fun_real_a : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J, type,
    fun_set_a_set_a : $tType).

tff(ty_n_t__List__Olist_It__fun_It__Real__Oreal_MT__a_J_J, type,
    list_fun_real_a : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_It__Real__Oreal_MT__a_J_J, type,
    fun_a_fun_real_a : $tType).

tff(ty_n_t__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J, type,
    set_fun_real_a : $tType).

tff(ty_n_t__Set__Oset_It__Set__Oset_It__Real__Oreal_J_J, type,
    set_set_real : $tType).

tff(ty_n_t__fun_It__fun_IT__a_MT__b_J_Mt__HOL__Obool_J, type,
    fun_fun_a_b_bool : $tType).

tff(ty_n_t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    fun_set_a_bool : $tType).

tff(ty_n_t__fun_IT__b_Mt__fun_IT__b_Mt__HOL__Obool_J_J, type,
    fun_b_fun_b_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_IT__a_Mt__HOL__Obool_J_J, type,
    fun_a_fun_a_bool : $tType).

tff(ty_n_t__fun_It__Real__Oreal_Mt__Real__Oreal_J, type,
    fun_real_real : $tType).

tff(ty_n_t__fun_It__Real__Oreal_Mt__HOL__Obool_J, type,
    fun_real_bool : $tType).

tff(ty_n_t__fun_It__Nat__Onat_Mt__HOL__Obool_J, type,
    fun_nat_bool : $tType).

tff(ty_n_t__fun_It__Nat__Onat_Mt__Nat__Onat_J, type,
    fun_nat_nat : $tType).

tff(ty_n_t__fun_IT__a_Mt__fun_IT__a_MT__a_J_J, type,
    fun_a_fun_a_a : $tType).

tff(ty_n_t__Set__Oset_It__Set__Oset_IT__b_J_J, type,
    set_set_b : $tType).

tff(ty_n_t__Set__Oset_It__Set__Oset_IT__a_J_J, type,
    set_set_a : $tType).

tff(ty_n_t__fun_It__Real__Oreal_MT__a_J, type,
    fun_real_a : $tType).

tff(ty_n_t__Set__Oset_It__Real__Oreal_J, type,
    set_real : $tType).

tff(ty_n_t__fun_IT__b_Mt__HOL__Obool_J, type,
    fun_b_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__HOL__Obool_J, type,
    fun_a_bool : $tType).

tff(ty_n_t__fun_IT__a_Mt__Nat__Onat_J, type,
    fun_a_nat : $tType).

tff(ty_n_t__List__Olist_IT__a__1_J, type,
    list_a : $tType).

tff(ty_n_t__fun_IT__a_MT__b_J, type,
    fun_a_b : $tType).

tff(ty_n_t__fun_IT__a_MT__a_J, type,
    fun_a_a : $tType).

tff(ty_n_t__Set__Oset_IT__b_J, type,
    set_b : $tType).

tff(ty_n_t__Set__Oset_IT__a_J, type,
    set_a : $tType).

tff(ty_n_t__Real__Oreal, type,
    real : $tType).

tff(ty_n_t__HOL__Obool, type,
    bool : $tType).

tff(ty_n_t__Nat__Onat, type,
    nat : $tType).

tff(ty_n_T__b, type,
    b : $tType).

tff(ty_n_T__a, type,
    a : $tType).

tff(sy_cl_Groups_Ocanonically__ordered__monoid__add, type,
    canoni770627133id_add : !>[A : $tType]: $o).

tff(sy_cl_Groups_Ocancel__ab__semigroup__add, type,
    cancel146912293up_add : !>[A : $tType]: $o).

tff(sy_cl_Groups_Ocancel__comm__monoid__add, type,
    cancel1352612707id_add : !>[A : $tType]: $o).

tff(sy_cl_Groups_Oordered__ab__group__add, type,
    ordered_ab_group_add : !>[A : $tType]: $o).

tff(sy_cl_Groups_Ocomm__monoid__diff, type,
    comm_monoid_diff : !>[A : $tType]: $o).

tff(sy_cl_Orderings_Owellorder, type,
    wellorder : !>[A : $tType]: $o).

tff(sy_cl_Groups_Ogroup__add, type,
    group_add : !>[A : $tType]: $o).

tff(sy_cl_Num_Oneg__numeral, type,
    neg_numeral : !>[A : $tType]: $o).

tff(sy_cl_Groups_Ozero, type,
    zero : !>[A : $tType]: $o).

tff(sy_cl_Groups_Oone, type,
    one : !>[A : $tType]: $o).

tff(sy_cl_Nat_Osize, type,
    size : !>[A : $tType]: $o).


% Explicit typings (122)

tff(sy_c_ATP_058Lamm__a, type,
    aTP_Lamm_a : fun_set_a_fun_a_bool).

tff(sy_c_Groups_Ominus__class_Ominus_001T__a, type,
    minus_minus_a : fun_a_fun_a_a).

tff(sy_c_Groups_Ominus__class_Ominus_001t__Nat__Onat, type,
    minus_minus_nat : fun_nat_fun_nat_nat).

tff(sy_c_Groups_Ominus__class_Ominus_001t__Real__Oreal, type,
    minus_minus_real : fun_re785795966l_real).

tff(sy_c_Groups_Oone__class_Oone_001T__a, type,
    one_one_a : a).

tff(sy_c_Groups_Oone__class_Oone_001t__Nat__Onat, type,
    one_one_nat : nat).

tff(sy_c_Groups_Oone__class_Oone_001t__Real__Oreal, type,
    one_one_real : real).

tff(sy_c_Groups_Ozero__class_Ozero_001T__a, type,
    zero_zero_a : a).

tff(sy_c_Groups_Ozero__class_Ozero_001t__Nat__Onat, type,
    zero_zero_nat : nat).

tff(sy_c_Groups_Ozero__class_Ozero_001t__Real__Oreal, type,
    zero_zero_real : real).

tff(sy_c_Lattices_Oinf__class_Oinf_001t__Set__Oset_IT__a_J, type,
    inf_inf_set_a : fun_se1395821270_set_a).

tff(sy_c_List_Ofoldr_001t__fun_It__Real__Oreal_MT__a_J_001t__fun_It__Real__Oreal_MT__a_J, type,
    foldr_149499255real_a : fun_fu1009460459real_a).

tff(sy_c_List_Onth_001t__fun_It__Real__Oreal_MT__a_J, type,
    nth_fun_real_a : fun_li323301544real_a).

tff(sy_c_Nat_Osize__class_Osize_001T__a, type,
    size_size_a : fun_a_nat).

tff(sy_c_Nat_Osize__class_Osize_001t__List__Olist_It__fun_It__Real__Oreal_MT__a_J_J, type,
    size_s408874891real_a : fun_li1559291076_a_nat).

tff(sy_c_Orderings_Oord__class_Oless_001T__a, type,
    ord_less_a : fun_a_fun_a_bool).

tff(sy_c_Orderings_Oord__class_Oless_001T__b, type,
    ord_less_b : fun_b_fun_b_bool).

tff(sy_c_Orderings_Oord__class_Oless_001t__Nat__Onat, type,
    ord_less_nat : fun_nat_fun_nat_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001T__a, type,
    ord_less_eq_a : fun_a_fun_a_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001t__Nat__Onat, type,
    ord_less_eq_nat : fun_nat_fun_nat_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001t__Real__Oreal, type,
    ord_less_eq_real : fun_re589487345l_bool).

tff(sy_c_Orderings_Oord__class_Oless__eq_001t__Set__Oset_IT__a_J, type,
    ord_less_eq_set_a : fun_se1296151905a_bool).

tff(sy_c_Set_OCollect_001T__a, type,
    collect_a : fun_fun_a_bool_set_a).

tff(sy_c_Set_OCollect_001t__fun_It__Real__Oreal_MT__a_J, type,
    collect_fun_real_a : fun_fu1021081849real_a).

tff(sy_c_Top1__Ch2_Ois__topology__on_001T__a, type,
    top1_i235996828y_on_a : fun_se590241323a_bool).

tff(sy_c_Top1__Ch2_Osubspace__topology_001T__a, type,
    top1_s1397583065logy_a : fun_se1904574643_set_a).

tff(sy_c_Top1__Ch2_Otop1__continuous__map__on_001T__a_001T__b, type,
    top1_t1121318858on_a_b : fun_se133803932b_bool).

tff(sy_c_Top1__Ch2_Otop1__continuous__map__on_001t__Real__Oreal_001T__a, type,
    top1_t193675959real_a : fun_se1175928469a_bool).

tff(sy_c_Top1__Ch2_Otop1__continuous__map__on_001t__Real__Oreal_001t__Real__Oreal, type,
    top1_t2101492005l_real : fun_se375434315l_bool).

tff(sy_c_Top1__Ch3_Otop1__path__connected__on_001T__a, type,
    top1_t1018604352d_on_a : fun_se590241323a_bool).

tff(sy_c_Top1__Ch3_Otop1__unit__interval, type,
    top1_t1808349867terval : set_real).

tff(sy_c_Top1__Ch3_Otop1__unit__interval__topology, type,
    top1_t1361226682pology : set_set_real).

tff(sy_c_Top1__Ch9__13_Otop1__constant__path_001T__a, type,
    top1_C339327026path_a : fun_a_fun_real_a).

tff(sy_c_Top1__Ch9__13_Otop1__fundamental__group__id_001T__a, type,
    top1_C1808544318p_id_a : fun_se1572299504real_a).

tff(sy_c_Top1__Ch9__13_Otop1__fundamental__group__invg_001T__a, type,
    top1_C362558777invg_a : fun_se380795402real_a).

tff(sy_c_Top1__Ch9__13_Otop1__fundamental__group__mul_001T__a, type,
    top1_C1676176095_mul_a : fun_se1074891428real_a).

tff(sy_c_Top1__Ch9__13_Otop1__is__group__on_001t__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J, type,
    top1_C194632552real_a : fun_se434555779a_bool).

tff(sy_c_Top1__Ch9__13_Otop1__is__loop__on_001T__a, type,
    top1_C243786134p_on_a : fun_se1783137784a_bool).

tff(sy_c_Top1__Ch9__13_Otop1__loop__equiv__on_001T__a, type,
    top1_C1365662694v_on_a : fun_se1074563370a_bool).

tff(sy_c_Top1__Ch9__13_Otop1__path__product_001T__a, type,
    top1_C2124551647duct_a : fun_fu1728579119real_a).

tff(sy_c_aa_001T__a_001T__a, type,
    aa_a_a : (fun_a_a * a) > a).

tff(sy_c_aa_001T__a_001T__b, type,
    aa_a_b : (fun_a_b * a) > b).

tff(sy_c_aa_001T__a_001t__HOL__Obool, type,
    aa_a_bool : (fun_a_bool * a) > bool).

tff(sy_c_aa_001T__a_001t__Nat__Onat, type,
    aa_a_nat : (fun_a_nat * a) > nat).

tff(sy_c_aa_001T__a_001t__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J, type,
    aa_a_set_fun_real_a : (fun_a_set_fun_real_a * a) > set_fun_real_a).

tff(sy_c_aa_001T__a_001t__fun_IT__a_MT__a_J, type,
    aa_a_fun_a_a : (fun_a_fun_a_a * a) > fun_a_a).

tff(sy_c_aa_001T__a_001t__fun_IT__a_Mt__HOL__Obool_J, type,
    aa_a_fun_a_bool : (fun_a_fun_a_bool * a) > fun_a_bool).

tff(sy_c_aa_001T__a_001t__fun_It__Real__Oreal_MT__a_J, type,
    aa_a_fun_real_a : (fun_a_fun_real_a * a) > fun_real_a).

tff(sy_c_aa_001T__a_001t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    aa_a_fun_set_a_bool : (fun_a_fun_set_a_bool * a) > fun_set_a_bool).

tff(sy_c_aa_001T__a_001t__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J, type,
    aa_a_f2083677107real_a : (fun_a_456397554real_a * a) > fun_se678812599real_a).

tff(sy_c_aa_001T__a_001t__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_J, type,
    aa_a_f179370573real_a : (fun_a_1388812940real_a * a) > fun_se744323153real_a).

tff(sy_c_aa_001T__a_001t__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J, type,
    aa_a_f869117133a_bool : (fun_a_897415140a_bool * a) > fun_fun_real_a_bool).

tff(sy_c_aa_001T__a_001t__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_J, type,
    aa_a_f1220162559a_bool : (fun_a_618731542a_bool * a) > fun_fu1191294203a_bool).

tff(sy_c_aa_001T__b_001t__HOL__Obool, type,
    aa_b_bool : (fun_b_bool * b) > bool).

tff(sy_c_aa_001T__b_001t__fun_IT__b_Mt__HOL__Obool_J, type,
    aa_b_fun_b_bool : (fun_b_fun_b_bool * b) > fun_b_bool).

tff(sy_c_aa_001t__List__Olist_It__fun_It__Real__Oreal_MT__a_J_J_001t__Nat__Onat, type,
    aa_lis1745948165_a_nat : (fun_li1559291076_a_nat * list_fun_real_a) > nat).

tff(sy_c_aa_001t__List__Olist_It__fun_It__Real__Oreal_MT__a_J_J_001t__fun_It__Nat__Onat_Mt__fun_It__Real__Oreal_MT__a_J_J, type,
    aa_lis794516969real_a : (fun_li323301544real_a * list_fun_real_a) > fun_nat_fun_real_a).

tff(sy_c_aa_001t__List__Olist_It__fun_It__Real__Oreal_MT__a_J_J_001t__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__Real__Oreal_MT__a_J_J, type,
    aa_lis1561326464real_a : (fun_li903581887real_a * list_fun_real_a) > fun_fu1277785163real_a).

tff(sy_c_aa_001t__Nat__Onat_001t__HOL__Obool, type,
    aa_nat_bool : (fun_nat_bool * nat) > bool).

tff(sy_c_aa_001t__Nat__Onat_001t__Nat__Onat, type,
    aa_nat_nat : (fun_nat_nat * nat) > nat).

tff(sy_c_aa_001t__Nat__Onat_001t__fun_It__Nat__Onat_Mt__HOL__Obool_J, type,
    aa_nat_fun_nat_bool : (fun_nat_fun_nat_bool * nat) > fun_nat_bool).

tff(sy_c_aa_001t__Nat__Onat_001t__fun_It__Nat__Onat_Mt__Nat__Onat_J, type,
    aa_nat_fun_nat_nat : (fun_nat_fun_nat_nat * nat) > fun_nat_nat).

tff(sy_c_aa_001t__Nat__Onat_001t__fun_It__Real__Oreal_MT__a_J, type,
    aa_nat_fun_real_a : (fun_nat_fun_real_a * nat) > fun_real_a).

tff(sy_c_aa_001t__Real__Oreal_001T__a, type,
    aa_real_a : (fun_real_a * real) > a).

tff(sy_c_aa_001t__Real__Oreal_001t__HOL__Obool, type,
    aa_real_bool : (fun_real_bool * real) > bool).

tff(sy_c_aa_001t__Real__Oreal_001t__fun_It__Real__Oreal_Mt__HOL__Obool_J, type,
    aa_rea628360026l_bool : (fun_re589487345l_bool * real) > fun_real_bool).

tff(sy_c_aa_001t__Real__Oreal_001t__fun_It__Real__Oreal_Mt__Real__Oreal_J, type,
    aa_rea846001983l_real : (fun_re785795966l_real * real) > fun_real_real).

tff(sy_c_aa_001t__Real__Oreal_001t__fun_It__Set__Oset_It__Real__Oreal_J_Mt__HOL__Obool_J, type,
    aa_rea558415012l_bool : (fun_re596238651l_bool * real) > fun_set_real_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__HOL__Obool, type,
    aa_set_a_bool : (fun_set_a_bool * set_a) > bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__Set__Oset_IT__a_J, type,
    aa_set_a_set_a : (fun_set_a_set_a * set_a) > set_a).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__Set__Oset_It__Set__Oset_IT__a_J_J, type,
    aa_set_a_set_set_a : (fun_set_a_set_set_a * set_a) > set_set_a).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_IT__a_Mt__HOL__Obool_J, type,
    aa_set_a_fun_a_bool : (fun_set_a_fun_a_bool * set_a) > fun_a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_IT__a_J_Mt__HOL__Obool_J, type,
    aa_set1122887114a_bool : (fun_se1296151905a_bool * set_a) > fun_set_a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_IT__a_J_J, type,
    aa_set363163287_set_a : (fun_se1395821270_set_a * set_a) > fun_set_a_set_a).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__HOL__Obool_J, type,
    aa_set1454015380a_bool : (fun_se590241323a_bool * set_a) > fun_set_set_a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_IT__a_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_J, type,
    aa_set233248177real_a : (fun_se1572299504real_a * set_a) > fun_se1158460415real_a).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_IT__a_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_J_J, type,
    aa_set1877048267real_a : (fun_se380795402real_a * set_a) > fun_se201199385real_a).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_IT__a_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_J_J_J, type,
    aa_set551000933real_a : (fun_se1074891428real_a * set_a) > fun_se1117430707real_a).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_IT__a_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_J_J, type,
    aa_set779984865a_bool : (fun_se1783137784a_bool * set_a) > fun_se1592439059a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_IT__a_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_J_J_J, type,
    aa_set1130400275a_bool : (fun_se1074563370a_bool * set_a) > fun_se1442295365a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J_J, type,
    aa_set392168180_set_a : (fun_se1904574643_set_a * set_a) > fun_se122506306_set_a).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__HOL__Obool_J_J_J_J, type,
    aa_set406949253b_bool : (fun_se133803932b_bool * set_a) > fun_se1552047031b_bool).

tff(sy_c_aa_001t__Set__Oset_IT__a_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_J, type,
    aa_set297177414a_bool : (fun_se1831257309a_bool * set_a) > fun_se691104376a_bool).

tff(sy_c_aa_001t__Set__Oset_IT__b_J_001t__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__HOL__Obool_J_J, type,
    aa_set1725488881b_bool : (fun_se2143152776b_bool * set_b) > fun_se1751821412b_bool).

tff(sy_c_aa_001t__Set__Oset_It__Real__Oreal_J_001t__HOL__Obool, type,
    aa_set_real_bool : (fun_set_real_bool * set_real) > bool).

tff(sy_c_aa_001t__Set__Oset_It__Real__Oreal_J_001t__fun_It__Set__Oset_It__Set__Oset_It__Real__Oreal_J_J_Mt__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_J_J_J, type,
    aa_set966414334a_bool : (fun_se1175928469a_bool * set_real) > fun_se1058567326a_bool).

tff(sy_c_aa_001t__Set__Oset_It__Real__Oreal_J_001t__fun_It__Set__Oset_It__Set__Oset_It__Real__Oreal_J_J_Mt__fun_It__Set__Oset_It__Real__Oreal_J_Mt__fun_It__Set__Oset_It__Set__Oset_It__Real__Oreal_J_J_Mt__fun_It__fun_It__Real__Oreal_Mt__Real__Oreal_J_Mt__HOL__Obool_J_J_J_J, type,
    aa_set1921639092l_bool : (fun_se375434315l_bool * set_real) > fun_se687036244l_bool).

tff(sy_c_aa_001t__Set__Oset_It__Real__Oreal_J_001t__fun_It__Set__Oset_It__Set__Oset_It__Real__Oreal_J_J_Mt__fun_It__fun_It__Real__Oreal_Mt__Real__Oreal_J_Mt__HOL__Obool_J_J, type,
    aa_set760198652l_bool : (fun_se1955784595l_bool * set_real) > fun_se710986396l_bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__HOL__Obool, type,
    aa_set_set_a_bool : (fun_set_set_a_bool * set_set_a) > bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__fun_IT__a_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J, type,
    aa_set1777218368real_a : (fun_se1158460415real_a * set_set_a) > fun_a_set_fun_real_a).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__fun_IT__a_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_J, type,
    aa_set1152408922real_a : (fun_se201199385real_a * set_set_a) > fun_a_456397554real_a).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__fun_IT__a_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_J_J, type,
    aa_set882213108real_a : (fun_se1117430707real_a * set_set_a) > fun_a_1388812940real_a).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__fun_IT__a_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_J, type,
    aa_set640627580a_bool : (fun_se1592439059a_bool * set_set_a) > fun_a_897415140a_bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__fun_IT__a_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_J_J, type,
    aa_set777295790a_bool : (fun_se1442295365a_bool * set_set_a) > fun_a_618731542a_bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__fun_It__Set__Oset_IT__a_J_Mt__Set__Oset_It__Set__Oset_IT__a_J_J_J, type,
    aa_set1645173507_set_a : (fun_se122506306_set_a * set_set_a) > fun_set_a_set_set_a).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__fun_It__Set__Oset_IT__b_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__b_J_J_Mt__fun_It__fun_IT__a_MT__b_J_Mt__HOL__Obool_J_J_J, type,
    aa_set124101152b_bool : (fun_se1552047031b_bool * set_set_a) > fun_se2143152776b_bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__a_J_J_001t__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J, type,
    aa_set565305185a_bool : (fun_se691104376a_bool * set_set_a) > fun_fun_real_a_bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_IT__b_J_J_001t__fun_It__fun_IT__a_MT__b_J_Mt__HOL__Obool_J, type,
    aa_set1716771277b_bool : (fun_se1751821412b_bool * set_set_b) > fun_fun_a_b_bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_It__Real__Oreal_J_J_001t__fun_It__Set__Oset_IT__a_J_Mt__fun_It__Set__Oset_It__Set__Oset_IT__a_J_J_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_J_J, type,
    aa_set735229831a_bool : (fun_se1058567326a_bool * set_set_real) > fun_se1831257309a_bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_It__Real__Oreal_J_J_001t__fun_It__Set__Oset_It__Real__Oreal_J_Mt__fun_It__Set__Oset_It__Set__Oset_It__Real__Oreal_J_J_Mt__fun_It__fun_It__Real__Oreal_Mt__Real__Oreal_J_Mt__HOL__Obool_J_J_J, type,
    aa_set532987709l_bool : (fun_se687036244l_bool * set_set_real) > fun_se1955784595l_bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_It__Real__Oreal_J_J_001t__fun_It__fun_It__Real__Oreal_Mt__Real__Oreal_J_Mt__HOL__Obool_J, type,
    aa_set1035389573l_bool : (fun_se710986396l_bool * set_set_real) > fun_fu49617115l_bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_001t__HOL__Obool, type,
    aa_set25805382a_bool : (fun_se170279005a_bool * set_set_fun_real_a) > bool).

tff(sy_c_aa_001t__Set__Oset_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_001t__fun_It__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_J_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_Mt__HOL__Obool_J_J_J, type,
    aa_set1001469036a_bool : (fun_se434555779a_bool * set_set_fun_real_a) > fun_fu1730399037a_bool).

tff(sy_c_aa_001t__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_001t__fun_It__Set__Oset_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_Mt__HOL__Obool_J, type,
    aa_set2046342210a_bool : (fun_se1021952345a_bool * set_fun_real_a) > fun_se170279005a_bool).

tff(sy_c_aa_001t__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_001t__fun_It__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_Mt__HOL__Obool_J, type,
    aa_set2075949534a_bool : (fun_se111987445a_bool * set_fun_real_a) > fun_fu1326045817a_bool).

tff(sy_c_aa_001t__fun_IT__a_MT__b_J_001t__HOL__Obool, type,
    aa_fun_a_b_bool : (fun_fun_a_b_bool * fun_a_b) > bool).

tff(sy_c_aa_001t__fun_IT__a_Mt__HOL__Obool_J_001t__Set__Oset_IT__a_J, type,
    aa_fun_a_bool_set_a : (fun_fun_a_bool_set_a * fun_a_bool) > set_a).

tff(sy_c_aa_001t__fun_It__Real__Oreal_MT__a_J_001t__HOL__Obool, type,
    aa_fun_real_a_bool : (fun_fun_real_a_bool * fun_real_a) > bool).

tff(sy_c_aa_001t__fun_It__Real__Oreal_MT__a_J_001t__fun_It__Real__Oreal_MT__a_J, type,
    aa_fun964359948real_a : (fun_fu1277785163real_a * fun_real_a) > fun_real_a).

tff(sy_c_aa_001t__fun_It__Real__Oreal_MT__a_J_001t__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J, type,
    aa_fun1449139684a_bool : (fun_fu1191294203a_bool * fun_real_a) > fun_fun_real_a_bool).

tff(sy_c_aa_001t__fun_It__Real__Oreal_MT__a_J_001t__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__Real__Oreal_MT__a_J_J, type,
    aa_fun110333168real_a : (fun_fu1728579119real_a * fun_real_a) > fun_fu1277785163real_a).

tff(sy_c_aa_001t__fun_It__Real__Oreal_Mt__Real__Oreal_J_001t__HOL__Obool, type,
    aa_fun2138992324l_bool : (fun_fu49617115l_bool * fun_real_real) > bool).

tff(sy_c_aa_001t__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_001t__HOL__Obool, type,
    aa_fun917745762a_bool : (fun_fu1326045817a_bool * fun_se678812599real_a) > bool).

tff(sy_c_aa_001t__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_J_001t__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__fun_It__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_Mt__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J_J_Mt__HOL__Obool_J_J, type,
    aa_fun1321926182a_bool : (fun_fu1730399037a_bool * fun_se744323153real_a) > fun_se111987445a_bool).

tff(sy_c_aa_001t__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__HOL__Obool_J_001t__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J, type,
    aa_fun2143400618real_a : (fun_fu1021081849real_a * fun_fun_real_a_bool) > set_fun_real_a).

tff(sy_c_aa_001t__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__Real__Oreal_MT__a_J_J_J_001t__fun_It__List__Olist_It__fun_It__Real__Oreal_MT__a_J_J_Mt__fun_It__fun_It__Real__Oreal_MT__a_J_Mt__fun_It__Real__Oreal_MT__a_J_J_J, type,
    aa_fun1222027692real_a : (fun_fu1009460459real_a * fun_fu1728579119real_a) > fun_li903581887real_a).

tff(sy_c_fFalse, type,
    fFalse : bool).

tff(sy_c_fTrue, type,
    fTrue : bool).

tff(sy_c_member_001T__a, type,
    member_a : fun_a_fun_set_a_bool).

tff(sy_c_member_001t__Real__Oreal, type,
    member_real : fun_re596238651l_bool).

tff(sy_c_member_001t__Set__Oset_It__fun_It__Real__Oreal_MT__a_J_J, type,
    member234694068real_a : fun_se1021952345a_bool).

tff(sy_c_pp, type,
    pp : bool > $o).


% Relevant facts (62)

tff(fact_0_top1__path__product__continuous, axiom,
    ((![A : $i, X : set_a, TX : set_set_a, F : fun_real_a, G : fun_real_a]: (pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_i235996828y_on_a, X), TX)) => (pp(aa_fun_real_a_bool(aa_set565305185a_bool(aa_set297177414a_bool(aa_set735229831a_bool(aa_set966414334a_bool(top1_t193675959real_a, top1_t1808349867terval), top1_t1361226682pology), X), TX), F)) => (pp(aa_fun_real_a_bool(aa_set565305185a_bool(aa_set297177414a_bool(aa_set735229831a_bool(aa_set966414334a_bool(top1_t193675959real_a, top1_t1808349867terval), top1_t1361226682pology), X), TX), G)) => ((aa_real_a(F, one_one_real) = aa_real_a(G, zero_zero_real)) => pp(aa_fun_real_a_bool(aa_set565305185a_bool(aa_set297177414a_bool(aa_set735229831a_bool(aa_set966414334a_bool(top1_t193675959real_a, top1_t1808349867terval), top1_t1361226682pology), X), TX), aa_fun964359948real_a(aa_fun110333168real_a(top1_C2124551647duct_a, F), G)))))))))). % top1_path_product_continuous

tff(fact_1_diff__is__0__eq, axiom,
    ((![M : nat, N : nat]: ((aa_nat_nat(aa_nat_fun_nat_nat(minus_minus_nat, M), N) = zero_zero_nat) <=> pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_eq_nat, M), N)))))). % diff_is_0_eq

tff(fact_2_diff__is__0__eq_H, axiom,
    ((![M : nat, N : nat]: (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_eq_nat, M), N)) => (aa_nat_nat(aa_nat_fun_nat_nat(minus_minus_nat, M), N) = zero_zero_nat))))). % diff_is_0_eq'

tff(fact_3_zero__less__diff, axiom,
    ((![N : nat, M : nat]: (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, zero_zero_nat), aa_nat_nat(aa_nat_fun_nat_nat(minus_minus_nat, N), M))) <=> pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, M), N)))))). % zero_less_diff

tff(fact_4_less__one, axiom,
    ((![N : nat]: (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, N), one_one_nat)) <=> (N = zero_zero_nat))))). % less_one

tff(fact_5_arith__special_I21_J, axiom,
    ((![A : $i]: (neg_numeral(a) => (aa_a_a(aa_a_fun_a_a(minus_minus_a, one_one_a), one_one_a) = zero_zero_a))))). % arith_special(21)

tff(fact_6_diff__numeral__special_I9_J, axiom,
    ((![A : $i]: (neg_numeral(a) => (aa_a_a(aa_a_fun_a_a(minus_minus_a, one_one_a), one_one_a) = zero_zero_a))))). % diff_numeral_special(9)

tff(fact_7_diff__gt__0__iff__gt, axiom,
    ((![A : $i]: (ordered_ab_group_add(a) => (![A2 : a, B : a]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, zero_zero_a), aa_a_a(aa_a_fun_a_a(minus_minus_a, A2), B))) <=> pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, B), A2)))))))). % diff_gt_0_iff_gt

tff(fact_8_diff__less__0__iff__less, axiom,
    ((![A : $i]: (ordered_ab_group_add(a) => (![A2 : a, B : a]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, aa_a_a(aa_a_fun_a_a(minus_minus_a, A2), B)), zero_zero_a)) <=> pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, A2), B)))))))). % diff_less_0_iff_less

tff(fact_9_foldr__path__product__pointwise__eq, axiom,
    ((![A : $i, Xs : list_fun_real_a, Ys : list_fun_real_a, Base : fun_real_a]: ((aa_lis1745948165_a_nat(size_s408874891real_a, Xs) = aa_lis1745948165_a_nat(size_s408874891real_a, Ys)) => ((![K : nat]: (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, K), aa_lis1745948165_a_nat(size_s408874891real_a, Xs))) => (![X2 : real]: (pp(aa_set_real_bool(aa_rea558415012l_bool(member_real, X2), top1_t1808349867terval)) => (aa_real_a(aa_nat_fun_real_a(aa_lis794516969real_a(nth_fun_real_a, Xs), K), X2) = aa_real_a(aa_nat_fun_real_a(aa_lis794516969real_a(nth_fun_real_a, Ys), K), X2)))))) => (![X3 : real]: (pp(aa_set_real_bool(aa_rea558415012l_bool(member_real, X3), top1_t1808349867terval)) => (aa_real_a(aa_fun964359948real_a(aa_lis1561326464real_a(aa_fun1222027692real_a(foldr_149499255real_a, top1_C2124551647duct_a), Xs), Base), X3) = aa_real_a(aa_fun964359948real_a(aa_lis1561326464real_a(aa_fun1222027692real_a(foldr_149499255real_a, top1_C2124551647duct_a), Ys), Base), X3))))))))). % foldr_path_product_pointwise_eq

tff(fact_10_diff__ge__0__iff__ge, axiom,
    ((![A : $i]: (ordered_ab_group_add(a) => (![A2 : a, B : a]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, zero_zero_a), aa_a_a(aa_a_fun_a_a(minus_minus_a, A2), B))) <=> pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, B), A2)))))))). % diff_ge_0_iff_ge

tff(fact_11_diff__le__0__iff__le, axiom,
    ((![A : $i]: (ordered_ab_group_add(a) => (![A2 : a, B : a]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, aa_a_a(aa_a_fun_a_a(minus_minus_a, A2), B)), zero_zero_a)) <=> pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, A2), B)))))))). % diff_le_0_iff_le

tff(fact_12_le__zero__eq, axiom,
    ((![A : $i]: (canoni770627133id_add(a) => (![N : a]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, N), zero_zero_a)) <=> (N = zero_zero_a))))))). % le_zero_eq

tff(fact_13_zero__order_I2_J, axiom,
    ((![A : $i]: (canoni770627133id_add(a) => (![N : a]: (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_eq_a, N), zero_zero_a)) <=> (N = zero_zero_a))))))). % zero_order(2)

tff(fact_14_not__gr__zero, axiom,
    ((![A : $i]: (canoni770627133id_add(a) => (![N : a]: ((~ (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, zero_zero_a), N)))) <=> (N = zero_zero_a))))))). % not_gr_zero

tff(fact_15_zero__order_I5_J, axiom,
    ((![A : $i]: (canoni770627133id_add(a) => (![N : a]: ((~ (pp(aa_a_bool(aa_a_fun_a_bool(ord_less_a, zero_zero_a), N)))) <=> (N = zero_zero_a))))))). % zero_order(5)

tff(fact_16_cancel__comm__monoid__add__class_Odiff__cancel, axiom,
    ((![A : $i]: (cancel1352612707id_add(a) => (![A2 : a]: (aa_a_a(aa_a_fun_a_a(minus_minus_a, A2), A2) = zero_zero_a)))))). % cancel_comm_monoid_add_class.diff_cancel

tff(fact_17_diff__zero, axiom,
    ((![A : $i]: (cancel1352612707id_add(a) => (![A2 : a]: (aa_a_a(aa_a_fun_a_a(minus_minus_a, A2), zero_zero_a) = A2)))))). % diff_zero

tff(fact_18_zero__diff, axiom,
    ((![A : $i]: (comm_monoid_diff(a) => (![A2 : a]: (aa_a_a(aa_a_fun_a_a(minus_minus_a, zero_zero_a), A2) = zero_zero_a)))))). % zero_diff

tff(fact_19_right__minus__eq, axiom,
    ((![A : $i]: (group_add(a) => (![A2 : a, B : a]: ((aa_a_a(aa_a_fun_a_a(minus_minus_a, A2), B) = zero_zero_a) <=> (A2 = B))))))). % right_minus_eq

tff(fact_20_diff__0__right, axiom,
    ((![A : $i]: (group_add(a) => (![A2 : a]: (aa_a_a(aa_a_fun_a_a(minus_minus_a, A2), zero_zero_a) = A2)))))). % diff_0_right

tff(fact_21_diff__self, axiom,
    ((![A : $i]: (group_add(a) => (![A2 : a]: (aa_a_a(aa_a_fun_a_a(minus_minus_a, A2), A2) = zero_zero_a)))))). % diff_self

tff(fact_22_arith__extra__simps_I13_J, axiom,
    ((![A : $i]: (group_add(a) => (![A2 : a]: (aa_a_a(aa_a_fun_a_a(minus_minus_a, A2), zero_zero_a) = A2)))))). % arith_extra_simps(13)

tff(fact_23_arith__simps_I57_J, axiom,
    ((![A : $i]: (group_add(a) => (![A2 : a]: (aa_a_a(aa_a_fun_a_a(minus_minus_a, A2), zero_zero_a) = A2)))))). % arith_simps(57)

tff(fact_24_less__nat__zero__code, axiom,
    ((![N : nat]: (~ (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, N), zero_zero_nat))))))). % less_nat_zero_code

tff(fact_25_neq0__conv, axiom,
    ((![N : nat]: ((N != zero_zero_nat) <=> pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, zero_zero_nat), N)))))). % neq0_conv

tff(fact_26_bot__nat__0_Onot__eq__extremum, axiom,
    ((![A2 : nat]: ((A2 != zero_zero_nat) <=> pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, zero_zero_nat), A2)))))). % bot_nat_0.not_eq_extremum

tff(fact_27_le0, axiom,
    ((![N : nat]: pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_eq_nat, zero_zero_nat), N))))). % le0

tff(fact_28_bot__nat__0_Oextremum, axiom,
    ((![A2 : nat]: pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_eq_nat, zero_zero_nat), A2))))). % bot_nat_0.extremum

tff(fact_29_diff__self__eq__0, axiom,
    ((![M : nat]: (aa_nat_nat(aa_nat_fun_nat_nat(minus_minus_nat, M), M) = zero_zero_nat)))). % diff_self_eq_0

tff(fact_30_diff__0__eq__0, axiom,
    ((![N : nat]: (aa_nat_nat(aa_nat_fun_nat_nat(minus_minus_nat, zero_zero_nat), N) = zero_zero_nat)))). % diff_0_eq_0

tff(fact_31_diff__diff__cancel, axiom,
    ((![I : nat, N : nat]: (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_eq_nat, I), N)) => (aa_nat_nat(aa_nat_fun_nat_nat(minus_minus_nat, N), aa_nat_nat(aa_nat_fun_nat_nat(minus_minus_nat, N), I)) = I))))). % diff_diff_cancel

tff(fact_32_op__minus__continuous__on__interval, axiom,
    (pp(aa_fun2138992324l_bool(aa_set1035389573l_bool(aa_set760198652l_bool(aa_set532987709l_bool(aa_set1921639092l_bool(top1_t2101492005l_real, top1_t1808349867terval), top1_t1361226682pology), top1_t1808349867terval), top1_t1361226682pology), aa_rea846001983l_real(minus_minus_real, one_one_real))))). % op_minus_continuous_on_interval

tff(fact_33_zero__reorient, axiom,
    ((![A : $i]: (zero(a) => (![X4 : a]: ((zero_zero_a = X4) <=> (X4 = zero_zero_a))))))). % zero_reorient

tff(fact_34_measure__induct__rule, axiom,
    ((![B2 : $i, A : $i]: (wellorder(b) => (![F : fun_a_b, P : fun_a_bool, A2 : a]: ((![X2 : a]: ((![Y : a]: (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_b, aa_a_b(F, Y)), aa_a_b(F, X2))) => pp(aa_a_bool(P, Y)))) => pp(aa_a_bool(P, X2)))) => pp(aa_a_bool(P, A2)))))))). % measure_induct_rule

tff(fact_35_measure__induct, axiom,
    ((![B2 : $i, A : $i]: (wellorder(b) => (![F : fun_a_b, P : fun_a_bool, A2 : a]: ((![X2 : a]: ((![Y : a]: (pp(aa_b_bool(aa_b_fun_b_bool(ord_less_b, aa_a_b(F, Y)), aa_a_b(F, X2))) => pp(aa_a_bool(P, Y)))) => pp(aa_a_bool(P, X2)))) => pp(aa_a_bool(P, A2)))))))). % measure_induct

tff(fact_36_one__reorient, axiom,
    ((![A : $i]: (one(a) => (![X4 : a]: ((one_one_a = X4) <=> (X4 = one_one_a))))))). % one_reorient

tff(fact_37_diff__right__commute, axiom,
    ((![A : $i]: (cancel146912293up_add(a) => (![A2 : a, C : a, B : a]: (aa_a_a(aa_a_fun_a_a(minus_minus_a, aa_a_a(aa_a_fun_a_a(minus_minus_a, A2), C)), B) = aa_a_a(aa_a_fun_a_a(minus_minus_a, aa_a_a(aa_a_fun_a_a(minus_minus_a, A2), B)), C))))))). % diff_right_commute

tff(fact_38_diff__eq__diff__eq, axiom,
    ((![A : $i]: (group_add(a) => (![A2 : a, B : a, C : a, D : a]: ((aa_a_a(aa_a_fun_a_a(minus_minus_a, A2), B) = aa_a_a(aa_a_fun_a_a(minus_minus_a, C), D)) => ((A2 = B) <=> (C = D)))))))). % diff_eq_diff_eq

tff(fact_39_infinite__descent__measure, axiom,
    ((![A : $i, P : fun_a_bool, V : fun_a_nat, X4 : a]: ((![X2 : a]: ((~ (pp(aa_a_bool(P, X2)))) => (?[Y : a]: (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, aa_a_nat(V, Y)), aa_a_nat(V, X2))) & (~ (pp(aa_a_bool(P, Y)))))))) => pp(aa_a_bool(P, X4)))))). % infinite_descent_measure

tff(fact_40_linorder__neqE__nat, axiom,
    ((![X4 : nat, Y2 : nat]: ((X4 != Y2) => ((~ (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, X4), Y2)))) => pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, Y2), X4))))))). % linorder_neqE_nat

tff(fact_41_infinite__descent, axiom,
    ((![P : fun_nat_bool, N : nat]: ((![N2 : nat]: ((~ (pp(aa_nat_bool(P, N2)))) => (?[M2 : nat]: (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, M2), N2)) & (~ (pp(aa_nat_bool(P, M2)))))))) => pp(aa_nat_bool(P, N)))))). % infinite_descent

tff(fact_42_mem__Collect__eq, axiom,
    ((![A : $i, A2 : a, P : fun_a_bool]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, A2), aa_fun_a_bool_set_a(collect_a, P))) <=> pp(aa_a_bool(P, A2)))))). % mem_Collect_eq

tff(fact_43_Collect__mem__eq, axiom,
    ((![A : $i, A3 : set_a]: (aa_fun_a_bool_set_a(collect_a, aa_set_a_fun_a_bool(aTP_Lamm_a, A3)) = A3)))). % Collect_mem_eq

tff(fact_44_Collect__cong, axiom,
    ((![A : $i, P : fun_a_bool, Q : fun_a_bool]: ((![X2 : a]: (pp(aa_a_bool(P, X2)) <=> pp(aa_a_bool(Q, X2)))) => (aa_fun_a_bool_set_a(collect_a, P) = aa_fun_a_bool_set_a(collect_a, Q)))))). % Collect_cong

tff(fact_45_mem__simps_I7_J, axiom,
    ((![A : $i, A2 : a, P : fun_a_bool]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, A2), aa_fun_a_bool_set_a(collect_a, P))) <=> pp(aa_a_bool(P, A2)))))). % mem_simps(7)

tff(fact_46_nat__less__induct, axiom,
    ((![P : fun_nat_bool, N : nat]: ((![N2 : nat]: ((![M2 : nat]: (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, M2), N2)) => pp(aa_nat_bool(P, M2)))) => pp(aa_nat_bool(P, N2)))) => pp(aa_nat_bool(P, N)))))). % nat_less_induct

tff(fact_47_less__irrefl__nat, axiom,
    ((![N : nat]: (~ (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, N), N))))))). % less_irrefl_nat

tff(fact_48_less__not__refl3, axiom,
    ((![S : nat, T : nat]: (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, S), T)) => (S != T))))). % less_not_refl3

tff(fact_49_less__not__refl2, axiom,
    ((![N : nat, M : nat]: (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, N), M)) => (M != N))))). % less_not_refl2

tff(fact_50_less__not__refl, axiom,
    ((![N : nat]: (~ (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, N), N))))))). % less_not_refl

tff(fact_51_nat__neq__iff, axiom,
    ((![M : nat, N : nat]: ((M != N) <=> (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, M), N)) | pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, N), M))))))). % nat_neq_iff

tff(fact_52_Nat_Oex__has__greatest__nat, axiom,
    ((![P : fun_nat_bool, K2 : nat, B : nat]: (pp(aa_nat_bool(P, K2)) => ((![Y3 : nat]: (pp(aa_nat_bool(P, Y3)) => pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_eq_nat, Y3), B)))) => (?[X2 : nat]: (pp(aa_nat_bool(P, X2)) & (![Y : nat]: (pp(aa_nat_bool(P, Y)) => pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_eq_nat, Y), X2))))))))))). % Nat.ex_has_greatest_nat

tff(fact_53_nat__le__linear, axiom,
    ((![M : nat, N : nat]: (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_eq_nat, M), N)) | pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_eq_nat, N), M)))))). % nat_le_linear

tff(fact_54_le__antisym, axiom,
    ((![M : nat, N : nat]: (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_eq_nat, M), N)) => (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_eq_nat, N), M)) => (M = N)))))). % le_antisym

tff(fact_55_eq__imp__le, axiom,
    ((![M : nat, N : nat]: ((M = N) => pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_eq_nat, M), N)))))). % eq_imp_le

tff(fact_56_le__trans, axiom,
    ((![I : nat, J : nat, K2 : nat]: (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_eq_nat, I), J)) => (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_eq_nat, J), K2)) => pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_eq_nat, I), K2))))))). % le_trans

tff(fact_57_le__refl, axiom,
    ((![N : nat]: pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_eq_nat, N), N))))). % le_refl

tff(fact_58_size__neq__size__imp__neq, axiom,
    ((![A : $i]: (size(a) => (![X4 : a, Y2 : a]: ((aa_a_nat(size_size_a, X4) != aa_a_nat(size_size_a, Y2)) => (X4 != Y2))))))). % size_neq_size_imp_neq

tff(fact_59_diff__commute, axiom,
    ((![I : nat, J : nat, K2 : nat]: (aa_nat_nat(aa_nat_fun_nat_nat(minus_minus_nat, aa_nat_nat(aa_nat_fun_nat_nat(minus_minus_nat, I), J)), K2) = aa_nat_nat(aa_nat_fun_nat_nat(minus_minus_nat, aa_nat_nat(aa_nat_fun_nat_nat(minus_minus_nat, I), K2)), J))))). % diff_commute

tff(fact_60_top1__continuous__map__on__agree_H, axiom,
    ((![B2 : $i, A : $i, S2 : set_a, TS : set_set_a, Y4 : set_b, TY : set_set_b, F : fun_a_b, G : fun_a_b]: (pp(aa_fun_a_b_bool(aa_set1716771277b_bool(aa_set1725488881b_bool(aa_set124101152b_bool(aa_set406949253b_bool(top1_t1121318858on_a_b, S2), TS), Y4), TY), F)) => ((![X2 : a]: (pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X2), S2)) => (aa_a_b(F, X2) = aa_a_b(G, X2)))) => pp(aa_fun_a_b_bool(aa_set1716771277b_bool(aa_set1725488881b_bool(aa_set124101152b_bool(aa_set406949253b_bool(top1_t1121318858on_a_b, S2), TS), Y4), TY), G))))))). % top1_continuous_map_on_agree'

tff(fact_61_ATP_Olambda__1, axiom,
    ((![A : $i, Uu : set_a, Uua : a]: (pp(aa_a_bool(aa_set_a_fun_a_bool(aTP_Lamm_a, Uu), Uua)) <=> pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, Uua), Uu)))))). % ATP.lambda_1


% Type constructors (16)

tff(tcon_Nat_Onat___Groups_Ocanonically__ordered__monoid__add, axiom,
    (canoni770627133id_add(nat))).

tff(tcon_Nat_Onat___Groups_Ocancel__ab__semigroup__add, axiom,
    (cancel146912293up_add(nat))).

tff(tcon_Nat_Onat___Groups_Ocancel__comm__monoid__add, axiom,
    (cancel1352612707id_add(nat))).

tff(tcon_Nat_Onat___Groups_Ocomm__monoid__diff, axiom,
    (comm_monoid_diff(nat))).

tff(tcon_Nat_Onat___Orderings_Owellorder, axiom,
    (wellorder(nat))).

tff(tcon_Nat_Onat___Groups_Ozero, axiom,
    (zero(nat))).

tff(tcon_Nat_Onat___Groups_Oone, axiom,
    (one(nat))).

tff(tcon_Nat_Onat___Nat_Osize, axiom,
    (size(nat))).

tff(tcon_List_Olist___Nat_Osize_1, axiom,
    ((![A4 : $i]: size(list_a)))).

tff(tcon_Real_Oreal___Groups_Ocancel__ab__semigroup__add_2, axiom,
    (cancel146912293up_add(real))).

tff(tcon_Real_Oreal___Groups_Ocancel__comm__monoid__add_3, axiom,
    (cancel1352612707id_add(real))).

tff(tcon_Real_Oreal___Groups_Oordered__ab__group__add, axiom,
    (ordered_ab_group_add(real))).

tff(tcon_Real_Oreal___Groups_Ogroup__add, axiom,
    (group_add(real))).

tff(tcon_Real_Oreal___Num_Oneg__numeral, axiom,
    (neg_numeral(real))).

tff(tcon_Real_Oreal___Groups_Ozero_4, axiom,
    (zero(real))).

tff(tcon_Real_Oreal___Groups_Oone_5, axiom,
    (one(real))).


% Helper facts (2)

tff(help_pp_2_1_U, axiom,
    (pp(fTrue))).

tff(help_pp_1_1_U, axiom,
    ((~ (pp(fFalse))))).


% Conjectures (17)

tff(conj_0, hypothesis,
    ((![A : $i, X : set_a, TX : set_set_a]: pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_i235996828y_on_a, X), TX))))).

tff(conj_1, hypothesis,
    ((![A : $i, U : set_a, X : set_a]: pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, U), X))))).

tff(conj_2, hypothesis,
    ((![A : $i, V : set_a, X : set_a]: pp(aa_set_a_bool(aa_set1122887114a_bool(ord_less_eq_set_a, V), X))))).

tff(conj_3, hypothesis,
    ((![A : $i, U : set_a, X : set_a, TX : set_set_a]: pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_t1018604352d_on_a, U), aa_set_a_set_set_a(aa_set1645173507_set_a(aa_set392168180_set_a(top1_s1397583065logy_a, X), TX), U)))))).

tff(conj_4, hypothesis,
    ((![A : $i, V : set_a, X : set_a, TX : set_set_a]: pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_t1018604352d_on_a, V), aa_set_a_set_set_a(aa_set1645173507_set_a(aa_set392168180_set_a(top1_s1397583065logy_a, X), TX), V)))))).

tff(conj_5, hypothesis,
    ((![A : $i, U : set_a, V : set_a, X : set_a, TX : set_set_a]: pp(aa_set_set_a_bool(aa_set1454015380a_bool(top1_t1018604352d_on_a, aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, U), V)), aa_set_a_set_set_a(aa_set1645173507_set_a(aa_set392168180_set_a(top1_s1397583065logy_a, X), TX), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, U), V))))))).

tff(conj_6, hypothesis,
    ((![A : $i, X0 : a, U : set_a, V : set_a]: pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, X0), aa_set_a_set_a(aa_set363163287_set_a(inf_inf_set_a, U), V)))))).

tff(conj_7, hypothesis,
    ((![A : $i, H : set_set_fun_real_a, X : set_a, TX : set_set_a, X0 : a]: pp(aa_fun917745762a_bool(aa_set2075949534a_bool(aa_fun1321926182a_bool(aa_set1001469036a_bool(top1_C194632552real_a, H), aa_a_f179370573real_a(aa_set882213108real_a(aa_set551000933real_a(top1_C1676176095_mul_a, X), TX), X0)), aa_a_set_fun_real_a(aa_set1777218368real_a(aa_set233248177real_a(top1_C1808544318p_id_a, X), TX), X0)), aa_a_f2083677107real_a(aa_set1152408922real_a(aa_set1877048267real_a(top1_C362558777invg_a, X), TX), X0)))))).

tff(conj_8, hypothesis,
    ((![A : $i, U : set_a, X : set_a, TX : set_set_a, X0 : a, H : set_set_fun_real_a, G2 : fun_real_a]: (pp(aa_fun_real_a_bool(aa_a_f869117133a_bool(aa_set640627580a_bool(aa_set779984865a_bool(top1_C243786134p_on_a, U), aa_set_a_set_set_a(aa_set1645173507_set_a(aa_set392168180_set_a(top1_s1397583065logy_a, X), TX), U)), X0), G2)) => pp(aa_set25805382a_bool(aa_set2046342210a_bool(member234694068real_a, aa_fun2143400618real_a(collect_fun_real_a, aa_fun1449139684a_bool(aa_a_f1220162559a_bool(aa_set777295790a_bool(aa_set1130400275a_bool(top1_C1365662694v_on_a, X), TX), X0), G2))), H)))))).

tff(conj_9, hypothesis,
    ((![A : $i, V : set_a, X : set_a, TX : set_set_a, X0 : a, H : set_set_fun_real_a, G2 : fun_real_a]: (pp(aa_fun_real_a_bool(aa_a_f869117133a_bool(aa_set640627580a_bool(aa_set779984865a_bool(top1_C243786134p_on_a, V), aa_set_a_set_set_a(aa_set1645173507_set_a(aa_set392168180_set_a(top1_s1397583065logy_a, X), TX), V)), X0), G2)) => pp(aa_set25805382a_bool(aa_set2046342210a_bool(member234694068real_a, aa_fun2143400618real_a(collect_fun_real_a, aa_fun1449139684a_bool(aa_a_f1220162559a_bool(aa_set777295790a_bool(aa_set1130400275a_bool(top1_C1365662694v_on_a, X), TX), X0), G2))), H)))))).

tff(conj_10, hypothesis,
    ((![K2 : nat]: pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_eq_nat, one_one_nat), K2))))).

tff(conj_11, hypothesis,
    ((![A : $i, Ps : list_fun_real_a, K2 : nat]: (aa_lis1745948165_a_nat(size_s408874891real_a, Ps) = K2)))).

tff(conj_12, hypothesis,
    ((![A : $i, K2 : nat, Ps : list_fun_real_a, U : set_a, V : set_a, I2 : nat]: (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, I2), K2)) => ((![T2 : real]: ((pp(aa_real_bool(aa_rea628360026l_bool(ord_less_eq_real, zero_zero_real), T2)) & pp(aa_real_bool(aa_rea628360026l_bool(ord_less_eq_real, T2), one_one_real))) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, aa_real_a(aa_nat_fun_real_a(aa_lis794516969real_a(nth_fun_real_a, Ps), I2), T2)), U)))) | (![T2 : real]: ((pp(aa_real_bool(aa_rea628360026l_bool(ord_less_eq_real, zero_zero_real), T2)) & pp(aa_real_bool(aa_rea628360026l_bool(ord_less_eq_real, T2), one_one_real))) => pp(aa_set_a_bool(aa_a_fun_set_a_bool(member_a, aa_real_a(aa_nat_fun_real_a(aa_lis794516969real_a(nth_fun_real_a, Ps), I2), T2)), V))))))))).

tff(conj_13, hypothesis,
    ((![A : $i, K2 : nat, X : set_a, TX : set_set_a, Ps : list_fun_real_a, I2 : nat]: (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, I2), K2)) => pp(aa_fun_real_a_bool(aa_set565305185a_bool(aa_set297177414a_bool(aa_set735229831a_bool(aa_set966414334a_bool(top1_t193675959real_a, top1_t1808349867terval), top1_t1361226682pology), X), TX), aa_nat_fun_real_a(aa_lis794516969real_a(nth_fun_real_a, Ps), I2))))))).

tff(conj_14, hypothesis,
    ((![A : $i, K2 : nat, Ps : list_fun_real_a, X0 : a, I2 : nat]: (pp(aa_nat_bool(aa_nat_fun_nat_bool(ord_less_nat, I2), K2)) => (((I2 = zero_zero_nat) => (aa_real_a(aa_nat_fun_real_a(aa_lis794516969real_a(nth_fun_real_a, Ps), I2), zero_zero_real) = X0)) & ((I2 != zero_zero_nat) => (aa_real_a(aa_nat_fun_real_a(aa_lis794516969real_a(nth_fun_real_a, Ps), I2), zero_zero_real) = aa_real_a(aa_nat_fun_real_a(aa_lis794516969real_a(nth_fun_real_a, Ps), aa_nat_nat(aa_nat_fun_nat_nat(minus_minus_nat, I2), one_one_nat)), one_one_real)))))))).

tff(conj_15, hypothesis,
    ((![A : $i, Ps : list_fun_real_a, K2 : nat, X0 : a]: (aa_real_a(aa_nat_fun_real_a(aa_lis794516969real_a(nth_fun_real_a, Ps), aa_nat_nat(aa_nat_fun_nat_nat(minus_minus_nat, K2), one_one_nat)), one_one_real) = X0)))).

tff(conj_16, conjecture,
    ((![A : $i, X : set_a, TX : set_set_a, X0 : a, Ps : list_fun_real_a, H : set_set_fun_real_a]: pp(aa_set25805382a_bool(aa_set2046342210a_bool(member234694068real_a, aa_fun2143400618real_a(collect_fun_real_a, aa_fun1449139684a_bool(aa_a_f1220162559a_bool(aa_set777295790a_bool(aa_set1130400275a_bool(top1_C1365662694v_on_a, X), TX), X0), aa_fun964359948real_a(aa_lis1561326464real_a(aa_fun1222027692real_a(foldr_149499255real_a, top1_C2124551647duct_a), Ps), aa_a_fun_real_a(top1_C339327026path_a, X0))))), H))))).

